[[webflux-oauth2-client]]
= OAuth2 Client

Spring Security's OAuth Support allows obtaining an access token without authenticating.
A basic configuration with Spring Boot can be seen below:

[source,yml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: replace-with-client-id
            client-secret: replace-with-client-secret
            scope: read:user,public_repo
----

You will need to replace the `client-id` and `client-secret` with values registered with GitHub.

The next step is to instruct Spring Security that you wish to act as an OAuth2 Client so that you can obtain an access token.

[source,java]
----
@Bean
SecurityWebFilterChain configure(ServerHttpSecurity http) throws Exception {
	http
		// ...
		.oauth2Client(withDefaults());
	return http.build();
}
----

You can now leverage Spring Security's <<webclient>> or <<webflux-roac,@RegisteredOAuth2AuthorizedClient>> support to obtain and use the access token.

== BearerTokenResolver

With interface BearerTokenResolver you can provide a strategy to resolve a bearer token.

The interface provides the next method:

[source,java]
----
/**
* Resolve any <a href="https://tools.ietf.org/html/rfc6750#section-1.2" target="_blank">Bearer Token</a>
* value from the request.
*
* @param request the request
* @return the Bearer Token value or {@code null} if none found
* @throws OAuth2AuthenticationException if the found token is invalid
*/
String resolve(HttpServletRequest request);
----

In code base, you can find two implementation of this interface:
HeaderBearerTokenResolver and DefaultBearerTokenResolver (based on RFC 6750).

Below you can see HeaderBearerTokenResolver, it takes a bearer token from request by header
which was passed in constructor

[source,java]
----
public class HeaderBearerTokenResolver implements BearerTokenResolver {

	private String header;

	public HeaderBearerTokenResolver(String header) {
		Assert.hasText(header, "header cannot be empty");
		this.header = header;
	}

	@Override
	public String resolve(HttpServletRequest request) {
		return request.getHeader(this.header);
	}
}
----
