[[appendix-namespace]]
== 安全名称空间
本附录提供了对安全性命名空间中可用元素的引用以及他们创建的底层bean的信息（假定了解各个类以及它们如何一起工作 - 您可以在项目Javadoc和本文档中的其他地方找到更多信息）。
如果您之前没有使用过命名空间，请阅读命名空间配置上的<<ns-config,introductory chapter>>，因为这是对此处信息的补充。
建议在编辑基于模式的配置时使用高质量的XML编辑器，因为这将提供关于哪些元素和属性可用的上下文信息以及解释其用途的注释。
命名空间是用 http://www.relaxng.org/[RELAX NG]压缩格式编写的，后来转换为XSD模式。
如果您熟悉这种格式，您可能希望查看https://raw.githubusercontent.com/spring-projects/spring-security/master/config/src/main/resources/org/springframework/security/config/ spring-security-4.1.rnc [模式文件]直接。

[[nsa-web]]
===  Web应用程序安全性

[[nsa-debug]]
==== <debug>
启用S​​pring Security调试基础架构。
这将提供可读的（多行）调试信息来监视进入安全过滤器的请求。
这可能包括敏感信息，如请求参数或标题，并且只能在开发环境中使用。

[[nsa-http]]
==== <http>
如果您在应用程序中使用`<http>`元素，则会创建一个名为"springSecurityFilterChain"的`FilterChainProxy` bean，并使用元素内的配置在内部构建过滤器链
`FilterChainProxy`.
从Spring Security 3.1开始，可以使用额外的`http`元素添加额外的过滤器链脚注：[请参阅pass：specialcharacters，宏[<<ns-web-xml,introductory chapter>>]了解如何设置来自{{2 }}]。
一些核心过滤器总是在过滤器链中创建，而其他核心过滤器将根据存在的属性和子元素添加到堆栈中。
标准过滤器的位置是固定的（请参阅
命名空间简介中的<<filter-stack,the filter order table>>），当用户必须显式配置过滤器链时，用以前版本的框架消除常见的错误来源
`FilterChainProxy` bean。
当然，如果您需要完全控制配置，您仍然可以这样做。


所有需要引用`AuthenticationManager`的过滤器将自动注入由命名空间配置创建的内部实例（有关`AuthenticationManager`的更多信息，请参阅<<ns-auth-manager,introductory chapter>>）。

每个`<http>`命名空间块始终创建一个`SecurityContextPersistenceFilter`，一个`ExceptionTranslationFilter`和一个`FilterSecurityInterceptor`。
这些是固定的，不能用替代品替代。


[[nsa-http-attributes]]
=====  <http>属性
`<http>`元素上的属性控制核心过滤器的一些属性。


[[nsa-http-access-decision-manager-ref]]
* **access-decision-manager-ref**
可选属性，指定应用于授权HTTP请求的`AccessDecisionManager`实现的ID。
默认情况下，`AffirmativeBased`实现用于`RoleVoter`和`AuthenticatedVoter`。


[[nsa-http-authentication-manager-ref]]
* **authentication-manager-ref**
对由此http元素创建的`FilterChain`使用的`AuthenticationManager`的引用。


[[nsa-http-auto-config]]
* **auto-config**
自动注册登录表单，BASIC认证，注销服务。
如果设置为"true"，则会添加所有这些功能（尽管您仍然可以通过提供相应的元素来自定义每个功能的配置）。
如果未指定，则默认为"false"。
不建议使用此属性。
使用显式配置元素来避免混淆。


[[nsa-http-create-session]]
* **create-session**
控制Spring安全类创建HTTP会话的热切程度。
选项包括：

**  `always`  - 如果Spring Security不存在，Spring会主动创建一个会话。
**  `ifRequired`  -  Spring Security只会在需要时创建一个会话（默认值）。
**  `never`  -  Spring Security永远不会创建一个会话，但如果应用程序会使用一个会话。
**  `stateless`  -  Spring Security不会创建会话并忽略会话以获取Spring `Authentication`。

[[nsa-http-disable-url-rewriting]]
* **disable-url-rewriting**
防止将会话ID附加到应用程序中的URL上。
如果此属性设置为`true`，则客户端必须使用Cookie。
默认值是`true`。


[[nsa-http-entry-point-ref]]
* **entry-point-ref**
通常，所使用的`AuthenticationEntryPoint`将根据已配置的认证机制进行设置。
此属性允许通过定义将启动身份验证过程的自定义`AuthenticationEntryPoint` bean来覆盖此行为。


[[nsa-http-jaas-api-provision]]
* **jaas-api-provision**
如果可用，请将请求作为从`JaasAuthenticationToken`获取的`Subject`来运行，该`JaasAuthenticationToken`通过将`JaasApiIntegrationFilter` bean添加到堆栈来实现。
默认为`false`。


[[nsa-http-name]]
* **name**
一个bean标识符，用于在上下文中的其他地方引用bean。


[[nsa-http-once-per-request]]
* **once-per-request**
对应于`FilterSecurityInterceptor`的{​​{0}}属性。
默认为`true`。


[[nsa-http-pattern]]
* **pattern**
为<<nsa-http,http>>元素定义模式控制将通过其定义的过滤器列表进行过滤的请求。
解释取决于配置的<<nsa-http-request-matcher,request-matcher>>。
如果未定义模式，则所有请求都将匹配，因此应首先声明最具体的模式。


[[nsa-http-realm]]
* **realm**
设置用于基本身份验证的领域名称（如果启用）。
对应`BasicAuthenticationEntryPoint`上的`realmName`属性。


[[nsa-http-request-matcher]]
* **request-matcher**
定义`FilterChainProxy`中使用的`RequestMatcher`策略和`intercept-url`创建的bean匹配传入请求。
对于Spring MVC，ant，正则表达式和不区分大小写的正则表达式，选项分别为`mvc`，`ant`，`regex`和`ciRegex`。
使用其<<nsa-intercept-url-pattern,pattern>>，<<nsa-intercept-url-method,method>>和<<nsa-intercept-url-servlet-path,servlet-path>>属性为每个<<nsa-intercept-url,intercept-url>>元素创建单独的实例。
使用`AntPathRequestMatcher`匹配Ant路径，使用`RegexRequestMatcher`匹配正则表达式，并使用匹配`MvcRequestMatcher`的Spring MVC路径。
有关这些类的详细信息，请参阅Javadoc以了解如何执行匹配。
Ant路径是默认策略。


[[nsa-http-request-matcher-ref]]
* **request-matcher-ref**
对实现`RequestMatcher`的bean的引用，它将确定是否应使用此`FilterChain`。
这是<<nsa-http-pattern,pattern>>的更强大替代方案。


[[nsa-http-security]]
* **security**
通过将此属性设置为`none`，可将请求模式映射到空的过滤器链。
没有安全性将被应用，Spring Security的功能都不可用。


[[nsa-http-security-context-repository-ref]]
* **security-context-repository-ref**
允许在`SecurityContextPersistenceFilter`中注入自定义`SecurityContextRepository`。


[[nsa-http-servlet-api-provision]]
* **servlet-api-provision**
提供`HttpServletRequest`安全方法的版本，例如`isUserInRole()`和`getPrincipal()`，这些方法通过在堆栈中添加一个`SecurityContextHolderAwareRequestFilter` bean来实现。
默认为`true`。


[[nsa-http-use-expressions]]
* **use-expressions**
如<<el-access-web,expression-based access-control>>一章所述，在`access`属性中启用EL表达式。
默认值是true。


[[nsa-http-children]]
<http>的{​​{0}}子元素
* <<nsa-access-denied-handler,access-denied-handler>>
* <<nsa-anonymous,anonymous>>
* <<nsa-cors,cors>>
* <<nsa-csrf,csrf>>
* <<nsa-custom-filter,custom-filter>>
* <<nsa-expression-handler,expression-handler>>
* <<nsa-form-login,form-login>>
* <<nsa-headers,headers>>
* <<nsa-http-basic,http-basic>>
* <<nsa-intercept-url,intercept-url>>
* <<nsa-jee,jee>>
* <<nsa-logout,logout>>
* <<nsa-openid-login,openid-login>>
* <<nsa-port-mappings,port-mappings>>
* <<nsa-remember-me,remember-me>>
* <<nsa-request-cache,request-cache>>
* <<nsa-session-management,session-management>>
* <<nsa-x509,x509>>


[[nsa-access-denied-handler]]
==== <access-denied-handler>
此元素允许您使用<<nsa-access-denied-handler-error-page,error-page>>属性为`ExceptionTranslationFilter`使用的默认`AccessDeniedHandler`设置`errorPage`属性，或者使用{{4 }}属性。
这在<<access-denied-handler,ExceptionTranslationFilter>>的部分有更详细的讨论。


[[nsa-access-denied-handler-parents]]
<access-denied-handler>的{​​{0}}父元素

* <<nsa-http,http>>

[[nsa-access-denied-handler-attributes]]
=====  <access-denied-handler>属性


[[nsa-access-denied-handler-error-page]]
* **error-page**
访问被拒绝的页面，认证用户将被重定向到，如果他们请求他们没有权限访问的页面。


[[nsa-access-denied-handler-ref]]
* **ref**
定义对`AccessDeniedHandler`类型的Spring bean的引用。


[[nsa-cors]]
==== <cors>
该元素允许配置`CorsFilter`。
如果未指定`CorsFilter`或`CorsConfigurationSource`，并且Spring MVC位于类路径中，则`HandlerMappingIntrospector`将用作`CorsConfigurationSource`。

[[nsa-cors-attributes]]
=====  <cors>属性
`<cors>`元素上的属性控制标题元素。

[[nsa-cors-ref]]
* **ref**
可选属性，指定`CorsFilter`的bean名称。

[[nsa-cors-configuration-source-ref]]
* **cors-configuration-source-ref**
可选属性，指定要注入到由XML命名空间创建的`CorsFilter`中的`CorsConfigurationSource`的bean名称。

[[nsa-cors-parents]]
<cors>的{​​{0}}父元素

* <<nsa-http,http>>

[[nsa-headers]]
==== <headers>
该元素允许配置附加（安全）头与响应一起发送。
它可以轻松配置多个标题，还可以通过<<nsa-header,header>>元素设置自定义标题。
其他信息可以在参考文献的<<headers,Security Headers>>部分找到。

**  `Cache-Control`，`Pragma`和`Expires`  - 可以使用<<nsa-cache-control,cache-control>>元素进行设置。
这可确保浏览器不会缓存受保护的页面。
**  `Strict-Transport-Security`  - 可以使用<<nsa-hsts,hsts>>元素进行设置。
这可确保浏览器自动为未来的请求请求HTTPS。
**  `X-Frame-Options`  - 可以使用<<nsa-frame-options,frame-options>>元素进行设置。
http://en.wikipedia.org/wiki/Clickjacking#X-Frame-Options[X-框架，选项]标头可用于防止点击劫持攻击。
**  `X-XSS-Protection`  - 可以使用<<nsa-xss-protection,xss-protection>>元素进行设置。
浏览器可以使用 http://en.wikipedia.org/wiki/Cross-site_scripting[X-XSS-保护]标题进行基本控制。
**  `X-Content-Type-Options`  - 可以使用<<nsa-content-type-options,content-type-options>>元素进行设置。
http://blogs.msdn.com/b/ie/archive/2008/09/02/ie8-security-part-vi-beta-2-update.aspx[X-Content-Type的选项]标题阻止Internet Explorer从MIME中嗅探到已声明的内容类型的响应。
在下载扩展程序时，这也适用于Google Chrome。
**  `Public-Key-Pinning`或`Public-Key-Pinning-Report-Only`  - 可以使用<<nsa-hpkp,hpkp>>元素进行设置。
这使得HTTPS网站能够抵御攻击者使用错误发布或其他欺诈性证书的冒充行为。
**  `Content-Security-Policy`或`Content-Security-Policy-Report-Only`  - 可以使用<<nsa-content-security-policy,content-security-policy>>元素进行设置。
https://www.w3.org/TR/CSP2/ [内容安全策略（CSP）]是Web应用程序可以利用的机制来缓解内容注入漏洞，例如跨站点脚本（XSS）。
**  `Referrer-Policy`  - 可以使用<<nsa-referrer-policy,referrer-policy>>元素进行设置，https://www.w3.org/TR/referrer-policy/[Referrer-Policy]是一种Web应用程序可以利用来管理引荐来源字段，其中包含用户所在的最后一页。

[[nsa-headers-attributes]]
=====  <headers>属性
`<headers>`元素上的属性控制标题元素。


[[nsa-headers-defaults-disabled]]
* **defaults-disabled**
可选属性，用于指定禁用默认Spring Security的HTTP响应标头。
默认值为false（包含默认标题）。

[[nsa-headers-disabled]]
* **disabled**
可选属性，指定禁用Spring Security的HTTP响应标头。
默认值为false（标题已启用）。


[[nsa-headers-parents]]
<headers>的{​​{0}}父元素

* <<nsa-http,http>>



[[nsa-headers-children]]
<headers>的{​​{0}}子元素


* <<nsa-cache-control,cache-control>>
* <<nsa-content-security-policy,content-security-policy>>
* <<nsa-content-type-options,content-type-options>>
* <<nsa-frame-options,frame-options>>
* <<nsa-header,header>>
* <<nsa-hpkp,hpkp>>
* <<nsa-hsts,hsts>>
* <<nsa-referrer-policy,referrer-policy>>
* <<nsa-xss-protection,xss-protection>>



[[nsa-cache-control]]
==== <cache-control>
添加`Cache-Control`，`Pragma`和`Expires`标头，以确保浏览器不会缓存受保护的页面。


[[nsa-cache-control-attributes]]
=====  <cache-control>属性

[[nsa-cache-control-disabled]]
* **disabled**
指定是否应禁用缓存控制。
默认为false。


[[nsa-cache-control-parents]]
<cache-control>的{​​{0}}父元素


* <<nsa-headers,headers>>



[[nsa-hsts]]
==== <hsts>
启用后，将 http://tools.ietf.org/html/rfc6797[严格，运输和安全]标头添加到任何安全请求的响应中。
这允许服务器指示浏览器为将来的请求自动使用HTTPS。


[[nsa-hsts-attributes]]
=====  <hsts>属性

[[nsa-hsts-disabled]]
* **disabled**
指定是否应禁用Strict-Transport-Security。
默认为false。

[[nsa-hsts-include-subdomains]]
* **include-sub-domains**
指定是否应包含子域。
默认为true。


[[nsa-hsts-max-age-seconds]]
* **max-age-seconds**
指定主机应被视为已知HSTS主机的最长时间。
默认一年。


[[nsa-hsts-request-matcher-ref]]
* **request-matcher-ref**
RequestMatcher实例用于确定是否应设置标题。
如果HttpServletRequest.isSecure（）为true，则默认为。


[[nsa-hsts-parents]]
<hsts>的{​​{0}}父元素

* <<nsa-headers,headers>>



[[nsa-hpkp]]
==== <hpkp>
启用后，将针对任何安全请求的https://tools.ietf.org/html/rfc7469[Public Key Pinning Extension for HTTP]标头添加到响应中。
这使得HTTPS网站能够抵御攻击者使用错误发布或其他欺诈性证书的冒充行为。


[[nsa-hpkp-attributes]]
=====  <hpkp>属性

[[nsa-hpkp-disabled]]
* **disabled**
指定是否应禁用HTTP公钥关联（HPKP）。
默认为true。

[[nsa-hpkp-include-subdomains]]
* **include-sub-domains**
指定是否应包含子域。
默认为false。


[[nsa-hpkp-max-age-seconds]]
* **max-age-seconds**
设置Public-Key-Pins标头的max-age指令的值。
默认60天。


[[nsa-hpkp-report-only]]
* **report-only**
指定浏览器是否应报告引脚验证失败。
默认为true。


[[nsa-hpkp-report-uri]]
* **report-uri**
指定浏览器应报告引脚验证失败的URI。


[[nsa-hpkp-parents]]
<hpkp>的{​​{0}}父元素

* <<nsa-headers,headers>>


[[nsa-pins]]
==== <pins>
引脚列表


[[nsa-pins-children]]
<pins>的{​​{0}}子元素

* <<nsa-pin,pin>>


[[nsa-pin]]
==== <pin>
使用base64编码的SPKI指纹作为值并将加密散列算法用作属性来指定针脚

[[nsa-pin-attributes]]
=====  <pin>属性

[[nsa-pin-algorithm]]
* **algorithm**
密码散列算法。
默认是SHA256。


[[nsa-pin-parents]]
<pin>的{​​{0}}父元素

* <<nsa-pins,pins>>



[[nsa-content-security-policy]]
==== <content-security-policy>
启用后，将https://www.w3.org/TR/CSP2/ [内容安全策略（CSP）]标头添加到响应中。
CSP是Web应用程序可以利用的机制来缓解内容注入漏洞，例如跨站点脚本（XSS）。

[[nsa-content-security-policy-attributes]]
=====  <content-security-policy>属性

[[nsa-content-security-policy-policy-directives]]
* **policy-directives**
Content-Security-Policy头的安全策略指令或者仅report-only设置为true，则使用Content-Security-Policy-Report-Only头。

[[nsa-content-security-policy-report-only]]
* **report-only**
设置为true，仅启用仅用于报告策略违规的Content-Security-Policy-Report-Only标头。
默认为false。

[[nsa-content-security-policy-parents]]
<content-security-policy>的{​​{0}}父元素

* <<nsa-headers,headers>>



[[nsa-referrer-policy]]
==== <referrer-policy>
启用后，将https://www.w3.org/TR/referrer-policy/[Referrer Policy]标头添加到响应中。

[[nsa-referrer-policy-attributes]]
=====  <referrer-policy>属性

[[nsa-referrer-policy-policy]]
* **policy**
Referrer-Policy标头的策略。
默认"no-referrer"。

[[nsa-referrer-policy-parents]]
<referrer-policy>的{​​{0}}父元素

* <<nsa-headers,headers>>



[[nsa-frame-options]]
==== <frame-options>
启用后，将 http://tools.ietf.org/html/draft-ietf-websec-x-frame-options[X-Frame-Options标题]添加到响应中，这允许较新的浏览器执行一些安全检查并防止 http://en.wikipedia.org/wiki/Clickjacking[点击劫持]攻击。


[[nsa-frame-options-attributes]]
=====  <frame-options>属性

[[nsa-frame-options-disabled]]
* **disabled**
如果禁用，则不包括X-Frame-Options标头。
默认为false。

[[nsa-frame-options-policy]]
* **policy**
**  `DENY`无论站点尝试这样做，页面都不能显示在框架中。
这是指定frame-options-policy时的默认值。
**  `SAMEORIGIN`该页面只能以与页面本身相同的原点显示在框架中
**  `ALLOW-FROM origin`页面只能显示在指定原点的框架中。

+

换句话说，如果你指定了DENY，那么当从其他站点加载时，不仅会尝试在一个框架中加载页面，当从同一站点加载时，尝试这样做将失败。
另一方面，如果指定了SAMEORIGIN，只要网站将其包含在一个框架中，就可以使用该框架中的页面，即可与该页面提供的页面相同。

[[nsa-frame-options-strategy]]
* **strategy**
选择使用ALLOW-FROM策略时要使用的`AllowFromStrategy`。

**  `static`使用单个静态ALLOW-FROM值。
该值可以通过<<nsa-frame-options-value,value>>属性进行设置。
**  `regexp`使用regelur表达式来验证传入的请求，以及它们是否被允许。
正则表达式可以通过<<nsa-frame-options-value,value>>属性设置。
用于检索要验证的值的请求参数可以使用<<nsa-frame-options-from-parameter,from-parameter>>指定。
**  `whitelist`包含允许的域的逗号分隔列表。
逗号分隔列表可以通过<<nsa-frame-options-value,value>>属性设置。
用于检索要验证的值的请求参数可以使用<<nsa-frame-options-from-parameter,from-parameter>>指定。




[[nsa-frame-options-ref]]
* **ref**
也可以使用自定义`AllowFromStrategy`，而不是使用其中一种预定义的策略。
这个bean的引用可以通过这个ref属性来指定。


[[nsa-frame-options-value]]
* **value**
使用ALLOW-FROM时使用的值是<<nsa-frame-options-strategy,strategy>>。


[[nsa-frame-options-from-parameter]]
* **from-parameter**
指定ALLOW-FROM策略使用正则表达式或白名单时要使用的请求参数的名称。


[[nsa-frame-options-parents]]
<frame-options>的{​​{0}}父元素

* <<nsa-headers,headers>>



[[nsa-xss-protection]]
==== <xss-protection>
将 http://blogs.msdn.com/b/ie/archive/2008/07/02/ie8-security-part-iv-the-xss-filter.aspx[X-XSS-Protection头]添加到回复中，以帮助防范 http://en.wikipedia.org/wiki/Cross-site_scripting#Non-Persistent[反射/ Type-1跨站点脚本（XSS）]次攻击。
这绝对不能完全保护XSS攻击！


[[nsa-xss-protection-attributes]]
=====  <xss-protection>属性


[[nsa-xss-protection-disabled]]
* **xss-protection-disabled**
请勿包含 http://en.wikipedia.org/wiki/Cross-site_scripting#Non-Persistent[反射/ Type-1跨站点脚本（XSS）]保护的标题。


[[nsa-xss-protection-enabled]]
* **xss-protection-enabled**
显式启用或禁用 http://en.wikipedia.org/wiki/Cross-site_scripting#Non-Persistent[反射/ Type-1跨站点脚本（XSS）]保护。


[[nsa-xss-protection-block]]
* **xss-protection-block**
当true和xss-protection-enabled为true时，将mode = block添加到标题。
这向浏览器表明该页面不应该被加载。
当false和xss-protection-enabled为真时，当检测到反射攻击时，页面仍将呈现，但响应将被修改以防止攻击。
请注意，有时会绕过此模式，这通常会使页面更加受欢迎。


[[nsa-xss-protection-parents]]
<xss-protection>的{​​{0}}父元素

* <<nsa-headers,headers>>



[[nsa-content-type-options]]
==== <content-type-options>
将值为nosniff的X-Content-Type-Options标头添加到响应中。
http://blogs.msdn.com/b/ie/archive/2008/09/02/ie8-security-part-vi-beta-2-update.aspx[禁用MIME嗅探]适用于IE8 +和Chrome扩展程序。


[[nsa-content-type-options-attributes]]
=====  <content-type-options>属性

[[nsa-content-type-options-disabled]]
* **disabled**
指定是否应禁用内容类型选项。
默认为false。

[[nsa-content-type-options-parents]]
<content-type-options>的{​​{0}}父元素


* <<nsa-headers,headers>>



[[nsa-header]]
==== <header>
将其他标题添加到响应中，需要指定名称和值。


[[nsa-header-attributes]]
=====  <header-attributes>属性


[[nsa-header-name]]
* **header-name**
标题的`name`。


[[nsa-header-value]]
* **value**
要添加的标题的`value`。


[[nsa-header-ref]]
* **ref**
引用`HeaderWriter`界面的自定义实现。


[[nsa-header-parents]]
<header>的{​​{0}}父元素


* <<nsa-headers,headers>>



[[nsa-anonymous]]
==== <anonymous>
将`AnonymousAuthenticationFilter`添加到堆栈并添加`AnonymousAuthenticationProvider`。
如果您使用`IS_AUTHENTICATED_ANONYMOUSLY`属性，则为必需。


[[nsa-anonymous-parents]]
<anonymous>的{​​{0}}父元素


* <<nsa-http,http>>



[[nsa-anonymous-attributes]]
=====  <anonymous>属性


[[nsa-anonymous-enabled]]
* **enabled**
通过默认名称空间设置，匿名"authentication"设施将自动启用。
您可以使用此属性禁用它。


[[nsa-anonymous-granted-authority]]
* **granted-authority**
应该分配给匿名请求的授予权限。
通常这是用来分配匿名请求的特定角色，随后可以用于授权决策。
如果未设置，则默认为`ROLE_ANONYMOUS`。


[[nsa-anonymous-key]]
* **key**
提供者和过滤器之间共享的关键。
这通常不需要设置。
如果未设置，它将默认为安全随机生成的值。
这意味着设置此值可以改善使用匿名功能时的启动时间，因为安全随机值可能需要一段时间才能生成。


[[nsa-anonymous-username]]
* **username**
应分配给匿名请求的用户名。
这样可以识别委托人，这对于记录和审计可能很重要。
如果未设置，则默认为`anonymousUser`。


[[nsa-csrf]]
==== <csrf>
该元素将为应用程序添加 http://en.wikipedia.org/wiki/Cross-site_request_forgery[跨站请求伪造（CSRF）]保护。
它还将默认的RequestCache更新为仅在成功验证后重播"GET"请求。
其他信息可以在参考文献的<<csrf,Cross Site Request Forgery (CSRF)>>部分找到。


[[nsa-csrf-parents]]
<csrf>的{​​{0}}父元素


* <<nsa-http,http>>



[[nsa-csrf-attributes]]
=====  <csrf>属性

[[nsa-csrf-disabled]]
* **disabled**
可选属性，指定禁用Spring Security的CSRF保护。
默认值为false（启用CSRF保护）。
强烈建议启用CSRF保护。

[[nsa-csrf-token-repository-ref]]
* **token-repository-ref**
使用CsrfTokenRepository。
默认值是`HttpSessionCsrfTokenRepository`。


[[nsa-csrf-request-matcher-ref]]
* **request-matcher-ref**
要用来确定是否应用CSRF的RequestMatcher实例。
默认值是除"GET"，"TRACE"，"HEAD"，"OPTIONS"以外的任何HTTP方法。


[[nsa-custom-filter]]
==== <custom-filter>
该元素用于向过滤器链添加过滤器。
它不会创建任何额外的bean，但用​​于选择已在应用程序上下文中定义的`javax.servlet.Filter`类型的bean，并将其添加到由Spring Security维护的过滤器链中的特定位置。
完整的详细信息可以在<<ns-custom-filters, namespace chapter>>中找到。


[[nsa-custom-filter-parents]]
<custom-filter>的{​​{0}}父元素


* <<nsa-http,http>>



[[nsa-custom-filter-attributes]]
=====  <custom-filter>属性


[[nsa-custom-filter-after]]
* **after**
紧随其后的过滤器应放置在链中。
只有希望将自己的过滤器组合到安全过滤器链中并具有标准Spring Security过滤器知识的高级用户才需要此功能。
筛选器名称映射到特定的Spring Security实现筛选器。


[[nsa-custom-filter-before]]
* **before**
自定义过滤器应该放置在链中之前的过滤器


[[nsa-custom-filter-position]]
* **position**
自定义过滤器应放置在链中的显式位置。
如果您要更换标准过滤器，请使用此选项


[[nsa-custom-filter-ref]]
* **ref**
定义对实现`Filter`的Spring bean的引用。


[[nsa-expression-handler]]
==== <expression-handler>
定义如果启用基于表达式的访问控制，将使用的`SecurityExpressionHandler`实例。
如果不提供，将使用默认实现（不支持ACL）。


[[nsa-expression-handler-parents]]
<expression-handler>的{​​{0}}父元素


* <<nsa-global-method-security,global-method-security>>
* <<nsa-http,http>>
* <<nsa-websocket-message-broker,websocket-message-broker>>



[[nsa-expression-handler-attributes]]
=====  <expression-handler>属性


[[nsa-expression-handler-ref]]
* **ref**
定义对实现`SecurityExpressionHandler`的Spring bean的引用。


[[nsa-form-login]]
==== <form-login>
用于将`UsernamePasswordAuthenticationFilter`添加到过滤器堆栈，并将`LoginUrlAuthenticationEntryPoint`添加到应用程序上下文以根据需要提供身份验证。
这将始终优先于其他命名空间创建的入口点。
如果未提供任何属性，则会在URL "/login"脚注中自动生成登录页面：[
此功能实际上只是为了方便而提供的，并不适用于生产（视图技术将被选择并可用于呈现定制登录页面）。
类`DefaultLoginPageGeneratingFilter`负责呈现登录页面，并在必要时为常规表单登录和/或OpenID提供登录表单。
]行为可以使用<<nsa-form-login-attributes, `<form-login>` Attributes>>进行自定义。


[[nsa-form-login-parents]]
<form-login>的{​​{0}}父元素


* <<nsa-http,http>>



[[nsa-form-login-attributes]]
=====  <form-login>属性


[[nsa-form-login-always-use-default-target]]
* **always-use-default-target**
如果设置为`true`，则用户始终以<<nsa-form-login-default-target-url,default-target-url>>给定的值开始，而不管它们是如何到达登录页面的。
映射到`UsernamePasswordAuthenticationFilter`的{​​{0}}属性。
默认值是`false`。


[[nsa-form-login-authentication-details-source-ref]]
* **authentication-details-source-ref**
引用将由认证过滤器使用的`AuthenticationDetailsSource`


[[nsa-form-login-authentication-failure-handler-ref]]
* **authentication-failure-handler-ref**
可以用作<<nsa-form-login-authentication-failure-url,authentication-failure-url>>的替代方法，让您在验​​证失败后完全控制导航流。
该值应该是应用程序上下文中的`AuthenticationFailureHandler` bean的名称。


[[nsa-form-login-authentication-failure-url]]
* **authentication-failure-url**
映射到`UsernamePasswordAuthenticationFilter`的{​​{0}}属性。
定义浏览器在登录失败时将被重定向到的URL。
默认为`/login?error`，将由自动登录页面生成器自动处理，并用错误消息重新呈现登录页面。


[[nsa-form-login-authentication-success-handler-ref]]
* **authentication-success-handler-ref**
这可以用作<<nsa-form-login-default-target-url,default-target-url>>和<<nsa-form-login-always-use-default-target,always-use-default-target>>的替代方案，让您在成功验证后完全控制导航流程。
该值应该是应用程序上下文中的`AuthenticationSuccessHandler` bean的名称。
默认情况下，使用`SavedRequestAwareAuthenticationSuccessHandler`的实现，并使用<<nsa-form-login-default-target-url,default-target-url >>注入。


[[nsa-form-login-default-target-url]]
* **default-target-url**
映射到`UsernamePasswordAuthenticationFilter`的{​​{0}}属性。
如果未设置，则默认值为"/"（应用程序根目录）。
如果用户在尝试访问受保护的资源时没有被要求登录，并将其带到最初请求的URL，则用户将在登录后进入该URL。


[[nsa-form-login-login-page]]
* **login-page**
应该用于呈现登录页面的URL。
映射到`LoginUrlAuthenticationEntryPoint`的{​​{0}}属性。
默认为"/login"。


[[nsa-form-login-login-processing-url]]
* **login-processing-url**
映射到`UsernamePasswordAuthenticationFilter`的{​​{0}}属性。
默认值是"/login"。


[[nsa-form-login-password-parameter]]
* **password-parameter**
包含密码的请求参数的名称。
默认为"password"。


[[nsa-form-login-username-parameter]]
* **username-parameter**
包含用户名的请求参数的名称。
默认为"username"。

[[nsa-form-login-authentication-success-forward-url]]
* **authentication-success-forward-url**
将`ForwardAuthenticationSuccessHandler`映射到`UsernamePasswordAuthenticationFilter`的`authenticationSuccessHandler`属性。


[[nsa-form-login-authentication-failure-forward-url]]
* **authentication-failure-forward-url**
将`ForwardAuthenticationFailureHandler`映射到`UsernamePasswordAuthenticationFilter`的`authenticationFailureHandler`属性。

[[nsa-http-basic]]
==== <http-basic>
向配置添加`BasicAuthenticationFilter`和`BasicAuthenticationEntryPoint`。
如果未启用基于表单的登录，后者将仅用作配置入口点。


[[nsa-http-basic-parents]]
<http-basic>的{​​{0}}父元素


* <<nsa-http,http>>



[[nsa-http-basic-attributes]]
=====  <http-basic>属性


[[nsa-http-basic-authentication-details-source-ref]]
* **authentication-details-source-ref**
引用将由认证过滤器使用的`AuthenticationDetailsSource`


[[nsa-http-basic-entry-point-ref]]
* **entry-point-ref**
设置`BasicAuthenticationFilter`使用的`AuthenticationEntryPoint`。


[[nsa-http-firewall]]
====  <http-firewall>元素
这是一个顶级元素，可用于将`HttpFirewall`的自定义实现注入到名称空间创建的`FilterChainProxy`中。
默认实现应该适用于大多数应用程序。


[[nsa-http-firewall-attributes]]
=====  <http-firewall>属性


[[nsa-http-firewall-ref]]
* **ref**
定义对实现`HttpFirewall`的Spring bean的引用。


[[nsa-intercept-url]]
==== <intercept-url>
此元素用于定义应用程序感兴趣的一组URL模式并配置应该如何处理它们。
它用于构造`FilterSecurityInterceptor`使用的`FilterInvocationSecurityMetadataSource`。
例如，如果特定的URL需要通过HTTPS访问，它还负责配置`ChannelProcessingFilter`。
当针对传入请求匹配指定模式时，匹配按声明元素的顺序完成。
所以最具体的模式应该是第一位的，最普通的模式应该是最后一位。


[[nsa-intercept-url-parents]]
<intercept-url>的{​​{0}}父元素


* <<nsa-filter-security-metadata-source,filter-security-metadata-source>>
* <<nsa-http,http>>



[[nsa-intercept-url-attributes]]
=====  <intercept-url>属性


[[nsa-intercept-url-access]]
* **access**
列出将存储在定义的URL模式/方法组合的`FilterInvocationSecurityMetadataSource`中的访问属性。
这应该是安全配置属性（如角色名称）的以逗号分隔的列表。


[[nsa-intercept-url-filters]]
* **filters**
只能取值"none"。
这将导致任何匹配请求完全绕过Spring Security过滤器链。
`<http>`配置的其余部分都不会对请求产生任何影响，并且在其持续时间内不会有可用的安全上下文。
请求期间访问受保护的方法将失败。

注意：此属性对<<nsa-filter-security-metadata-source,filter-security-metadata-source>>无效

[[nsa-intercept-url-method]]
* **method**
HTTP方法将与模式和servlet路径（可选）结合使用以匹配传入的请求。
如果省略，任何方法都会匹配。
如果使用和不使用方法指定了相同的模式，则特定于方法的匹配将优先。


[[nsa-intercept-url-pattern]]
* **pattern**
定义URL路径的模式。
内容将取决于来自包含http元素的`request-matcher`属性，所以默认为ant路径语法。


[[nsa-intercept-url-request-matcher-ref]]
* **request-matcher-ref**
对`RequestMatcher`的引用，将用于确定是否使用此`<intercept-url>`。


[[nsa-intercept-url-requires-channel]]
* **requires-channel**
可以是"http"或"https"，具体取决于是否应分别通过HTTP或HTTPS访问特定的URL模式。
或者，当没有偏好时，可以使用值"any"。
如果此属性出现在任何`<intercept-url>`元素上，则`ChannelProcessingFilter`将被添加到过滤器堆栈，并将其附加依赖项添加到应用程序上下文中。

如果添加了`<port-mappings>`配置，`SecureChannelProcessor`和`InsecureChannelProcessor` bean将用于确定用于重定向到HTTP / HTTPS的端口。

注意：此属性对<<nsa-filter-security-metadata-source,filter-security-metadata-source>>无效

[[nsa-intercept-url-servlet-path]]
* **servlet-path**
将与模式和HTTP方法结合使用以匹配传入请求的servlet路径。
此属性仅适用于<<nsa-http-request-matcher,request-matcher>>为'mvc'时。
此外，该值仅在以下两种用例中需要：1）`ServletContext`中注册的`HttpServlet`中有2个或更多`HttpServlet`映射的映射以`'/'`开头，且映射不同; 2）该模式以注册`HttpServlet`路径的相同值开始，不包括默认（根）`HttpServlet` `'/'`。

注意：此属性对<<nsa-filter-security-metadata-source,filter-security-metadata-source>>无效


[[nsa-jee]]
==== <jee>
将J2eePreAuthenticatedProcessingFilter添加到过滤器链以提供与容器验证的集成。


[[nsa-jee-parents]]
<jee>的{​​{0}}父元素


* <<nsa-http,http>>



[[nsa-jee-attributes]]
=====  <jee>属性


[[nsa-jee-mappable-roles]]
* **mappable-roles**
在传入的HttpServletRequest中查找的逗号分隔列表。


[[nsa-jee-user-service-ref]]
* **user-service-ref**
对用户服务（或UserDetailsS​​ervice bean）Id的引用


[[nsa-logout]]
==== <logout>
将`LogoutFilter`添加到过滤器堆栈。
这是使用`SecurityContextLogoutHandler`配置的。


[[nsa-logout-parents]]
<logout>的{​​{0}}父元素


* <<nsa-http,http>>



[[nsa-logout-attributes]]
=====  <logout>属性


[[nsa-logout-delete-cookies]]
* **delete-cookies**
用户注销时应删除的Cookie的名称的逗号分隔列表。


[[nsa-logout-invalidate-session]]
* **invalidate-session**
映射到`SecurityContextLogoutHandler`的{​​{0}}。
默认为"true"，所以会话将在注销时失效。


[[nsa-logout-logout-success-url]]
* **logout-success-url**
注销后用户将访问的目标网址。
默认为<form-login-login-page> /？注销（即/ login？注销）

+

设置此属性将为`SessionManagementFilter`注入配置了属性值的`SimpleRedirectInvalidSessionStrategy`。
当提交无效的会话ID时，该策略将被调用，重定向到配置的URL。


[[nsa-logout-logout-url]]
* **logout-url**
将导致注销（即将由过滤器处理）的URL。
默认为"/logout"。


[[nsa-logout-success-handler-ref]]
* **success-handler-ref**
可用于提供`LogoutSuccessHandler`的实例，该实例将在注销后调用以控制导航。


[[nsa-openid-login]]
==== <openid-login>
与`<form-login>`类似，具有相同的属性。
`login-processing-url`的默认值是"/login/openid"。
一个`OpenIDAuthenticationFilter`和`OpenIDAuthenticationProvider`将被注册。
后者需要引用`UserDetailsService`。
再次，这可以使用`user-service-ref`属性由`id`指定，或者将自动定位到应用程序上下文中。


[[nsa-openid-login-parents]]
<openid-login>的{​​{0}}父元素


* <<nsa-http,http>>



[[nsa-openid-login-attributes]]
=====  <openid-login>属性


[[nsa-openid-login-always-use-default-target]]
* **always-use-default-target**
登录后是否应始终将用户重定向到default-target-url。


[[nsa-openid-login-authentication-details-source-ref]]
* **authentication-details-source-ref**
引用将由认证过滤器使用的AuthenticationDetailsS​​ource


[[nsa-openid-login-authentication-failure-handler-ref]]
* **authentication-failure-handler-ref**
引用一个AuthenticationFailureHandler bean，它应该用来处理失败的认证请求。
不应该与authentication-failure-url结合使用，因为实现应始终处理导航到后续目标


[[nsa-openid-login-authentication-failure-url]]
* **authentication-failure-url**
登录失败页面的URL。
如果未指定登录失败URL，则Spring Security将自动在/ login？login_error中创建失败登录URL，并在请求时使用相应的筛选器呈现该登录失败URL。


[[nsa-openid-login-authentication-success-forward-url]]
* **authentication-success-forward-url**
将`ForwardAuthenticationSuccessHandler`映射到`UsernamePasswordAuthenticationFilter`的`authenticationSuccessHandler`属性。


[[nsa-openid-login-authentication-failure-forward-url]]
* **authentication-failure-forward-url**
将`ForwardAuthenticationFailureHandler`映射到`UsernamePasswordAuthenticationFilter`的`authenticationFailureHandler`属性。


[[nsa-openid-login-authentication-success-handler-ref]]
* **authentication-success-handler-ref**
引用应该用于处理成功认证请求的AuthenticationSuccessHandler bean。
不应与<<nsa-openid-login-default-target-url,default-target-url>>（或<<nsa-openid-login-always-use-default-target, always-use-default-target>>）结合使用，因为实施应始终处理导航到后续目标


[[nsa-openid-login-default-target-url]]
* **default-target-url**
如果用户以前的操作无法恢复，则在成功验证后将重定向到的URL。
这通常发生在用户访问登录页面而未首先请求触发认证的安全操作时。
如果未指定，则默认为应用程序的根目录。


[[nsa-openid-login-login-page]]
* **login-page**
登录页面的URL。
如果没有指定登录URL，Spring Security将自动在/ login上创建一个登录URL，并在请求时提供相应的过滤器来呈现该登录URL。


[[nsa-openid-login-login-processing-url]]
* **login-processing-url**
登录表单发布到的URL。
如果未指定，则默认为/ login。


[[nsa-openid-login-password-parameter]]
* **password-parameter**
包含密码的请求参数的名称。
默认为"password"。


[[nsa-openid-login-user-service-ref]]
* **user-service-ref**
对用户服务（或UserDetailsS​​ervice bean）Id的引用


[[nsa-openid-login-username-parameter]]
* **username-parameter**
包含用户名的请求参数的名称。
默认为"username"。


[[nsa-openid-login-children]]
<openid-login>的{​​{0}}子元素
* <<nsa-attribute-exchange,attribute-exchange>>



[[nsa-attribute-exchange]]
==== <attribute-exchange>
`attribute-exchange`元素定义应从身份提供商请求的属性列表。
可以在名称空间配置章节的<<ns-openid,OpenID Support>>部分中找到示例。
可以使用多于一个，在这种情况下，每个都必须具有`identifier-match`属性，其中包含与提供的OpenID标识符相匹配的正则表达式。
这允许从不同的提供者（谷歌，雅虎等）获取不同的属性列表。


[[nsa-attribute-exchange-parents]]
<attribute-exchange>的{​​{0}}父元素


* <<nsa-openid-login,openid-login>>



[[nsa-attribute-exchange-attributes]]
=====  <attribute-exchange>属性


[[nsa-attribute-exchange-identifier-match]]
* **identifier-match**
一个正则表达式，在决定在认证过程中使用哪种属性交换配置时，将与所称身份进行比较。


[[nsa-attribute-exchange-children]]
<attribute-exchange>的{​​{0}}子元素


* <<nsa-openid-attribute,openid-attribute>>



[[nsa-openid-attribute]]
==== <openid-attribute>
制作OpenID AX时使用的属性 http://openid.net/specs/openid-attribute-exchange-1_0.html#fetch_request[ 获取请求]


[[nsa-openid-attribute-parents]]
<openid-attribute>的{​​{0}}父元素


* <<nsa-attribute-exchange,attribute-exchange>>



[[nsa-openid-attribute-attributes]]
=====  <openid-attribute>属性


[[nsa-openid-attribute-count]]
* **count**
指定您希望返回的属性数量。
例如，返回3封电子邮件。
默认值是1。


[[nsa-openid-attribute-name]]
* **name**
指定您希望返回的属性的名称。
例如，电子邮件。


[[nsa-openid-attribute-required]]
* **required**
指定OP是否需要此属性，但如果OP未返回属性，则不会出错。
默认为false。


[[nsa-openid-attribute-type]]
* **type**
指定属性类型。
例如，http://axschema.org/contact/email。
查看您的OP的文档以获取有效的属性类型。


[[nsa-port-mappings]]
==== <port-mappings>
默认情况下，{{}}的实例将被添加到配置中，以用于重定向到安全和不安全的URL。
此元素可以选择用于覆盖该类定义的默认映射。
每个子`<port-mapping>`元素定义一对HTTP：HTTPS端口。
默认映射是80：443和8080：8443。
覆盖这些的示例可以在<<ns-requires-channel,namespace introduction>>中找到。


[[nsa-port-mappings-parents]]
<port-mappings>的{​​{0}}父元素


* <<nsa-http,http>>



[[nsa-port-mappings-children]]
<port-mappings>的{​​{0}}子元素


* <<nsa-port-mapping,port-mapping>>



[[nsa-port-mapping]]
==== <port-mapping>
提供强制重定向时将http端口映射到https端口的方法。


[[nsa-port-mapping-parents]]
<port-mapping>的{​​{0}}父元素


* <<nsa-port-mappings,port-mappings>>



[[nsa-port-mapping-attributes]]
=====  <port-mapping>属性


[[nsa-port-mapping-http]]
* **http**
要使用的http端口。


[[nsa-port-mapping-https]]
* **https**
要使用的https端口。


[[nsa-remember-me]]
==== <remember-me>
将`RememberMeAuthenticationFilter`添加到堆栈。
这反过来会根据属性设置配置为`TokenBasedRememberMeServices`，`PersistentTokenBasedRememberMeServices`或用户指定的实现`RememberMeServices`的bean。


[[nsa-remember-me-parents]]
<remember-me>的{​​{0}}父元素


* <<nsa-http,http>>



[[nsa-remember-me-attributes]]
=====  <remember-me>属性


[[nsa-remember-me-authentication-success-handler-ref]]
* **authentication-success-handler-ref**
如果需要自定义导航，请在`RememberMeAuthenticationFilter`上设置`authenticationSuccessHandler`属性。
该值应该是应用程序上下文中的`AuthenticationSuccessHandler` bean的名称。


[[nsa-remember-me-data-source-ref]]
* **data-source-ref**
对`DataSource` bean的引用。
如果已设置，将使用`PersistentTokenBasedRememberMeServices`并使用`JdbcTokenRepositoryImpl`实例进行配置。


[[nsa-remember-me-remember-me-parameter]]
* **remember-me-parameter**
切换记住我身份验证的请求参数的名称。
默认为"remember-me"。
映射到`AbstractRememberMeServices`的{​​{0}}属性。


[[nsa-remember-me-remember-me-cookie]]
* **remember-me-cookie**
存储记忆我认证令牌的cookie的名称。
默认为"remember-me"。
映射到`AbstractRememberMeServices`的{​​{0}}属性。


[[nsa-remember-me-key]]
* **key**
映射到`AbstractRememberMeServices`的{​​{0}}属性。
应设置为唯一值以确保记忆我的Cookie仅在一个应用程序脚注中有效：[
这不会影响使用`PersistentTokenBasedRememberMeServices`，其中令牌存储在服务器端。
].
如果未设置，则会生成安全随机值。
由于生成安全随机值可能需要一段时间，因此使用记忆功能时，明确设置此值可帮助改善启动时间。


[[nsa-remember-me-services-alias]]
* **services-alias**
将内部定义的`RememberMeServices`作为bean别名导出，使其可以被应用程序上下文中的其他bean使用。


[[nsa-remember-me-services-ref]]
* **services-ref**
允许完整控制过滤器将使用的`RememberMeServices`实施。
该值应该是应用程序上下文中实现此接口的bean的`id`。
如果正在使用注销过滤器，还应该实现`LogoutHandler`。


[[nsa-remember-me-token-repository-ref]]
* **token-repository-ref**
配置`PersistentTokenBasedRememberMeServices`，但允许使用自定义`PersistentTokenRepository` bean。


[[nsa-remember-me-token-validity-seconds]]
* **token-validity-seconds**
映射到`AbstractRememberMeServices`的{​​{0}}属性。
指定remember-me Cookie应该有效的时间段（以秒为单位）。
默认情况下，它将在14天内有效。


[[nsa-remember-me-use-secure-cookie]]
* **use-secure-cookie**
建议记住我的cookies仅通过HTTPS提交，因此应该标记为"secure"。
默认情况下，如果进行登录请求的连接安全（应该是），将使用安全cookie。
如果您将此属性设置为`false`，则不会使用安全cookie。
将其设置为`true`将始终在cookie上设置安全标志。
该属性映射到`AbstractRememberMeServices`的{​​{0}}属性。


[[nsa-remember-me-user-service-ref]]
* **user-service-ref**
Remember-me服务实现需要访问`UserDetailsService`，因此必须在应用程序上下文中定义一个。
如果只有一个，它将被命名空间配置自动选择和使用。
如果存在多个实例，则可以使用此属性显式指定一个bean `id`。


[[nsa-request-cache]]
====  <request-cache>元素
在调用`AuthenticationEntryPoint`之前，设置将`ExceptionTranslationFilter`用于存储请求信息的`RequestCache`实例。


[[nsa-request-cache-parents]]
<request-cache>的{​​{0}}父元素

* <<nsa-http,http>>

[[nsa-request-cache-attributes]]
=====  <request-cache>属性


[[nsa-request-cache-ref]]
* **ref**
定义对`RequestCache`的Spring bean的引用。


[[nsa-session-management]]
==== <session-management>
会话管理相关功能通过在过滤器堆栈中添加`SessionManagementFilter`来实现。


[[nsa-session-management-parents]]
<session-management>的{​​{0}}父元素


* <<nsa-http,http>>



[[nsa-session-management-attributes]]
=====  <session-management>属性


[[nsa-session-management-invalid-session-url]]
* **invalid-session-url**
设置此属性将为`SessionManagementFilter`注入配置了属性值的`SimpleRedirectInvalidSessionStrategy`。
当提交无效的会话ID时，该策略将被调用，重定向到配置的URL。

[[nsa-session-management-invalid-session-strategy-ref]]
* **invalid-session-url**
允许注入SessionManagementFilter使用的InvalidSessionStrategy实例。
使用这个或`invalid-session-url`属性，但不能同时使用这两个属性。

[[nsa-session-management-session-authentication-error-url]]
* **session-authentication-error-url**
定义在SessionAuthenticationStrategy引发异常时应显示的错误页面的URL。
如果未设置，未经授权的（401）错误代码将返回给客户端。
请注意，如果在基于表单的登录期间发生错误，则此属性不适用，其中用于身份验证失败的URL将优先。


[[nsa-session-management-session-authentication-strategy-ref]]
* **session-authentication-strategy-ref**
允许注入SessionManagementFilter使用的SessionAuthenticationStrategy实例


[[nsa-session-management-session-fixation-protection]]
* **session-fixation-protection**
指示用户验证时如何应用会话修复保护。
如果设置为"none"，则不会应用保护。
"newSession"将创建一个新的空会话，只迁移与Spring Security相关的属性。
"migrateSession"将创建一个新会话并将所有会话属性复制到新会话。
在Servlet 3.1（Java EE 7）和更新的容器中，指定"changeSessionId"将保留现有会话并使用容器提供的会话固定保护（HttpServletRequest＃changeSessionId（））。
在较旧的容器中，Servlet 3.1和较新的容器"migrateSession"中的默认值为"changeSessionId"。
如果在较旧的容器中使用"changeSessionId"，则会引发异常。

+

如果启用会话修复保护，则`SessionManagementFilter`注入适当配置的`DefaultSessionAuthenticationStrategy`。
有关更多详细信息，请参阅此类的Javadoc。


[[nsa-session-management-children]]
<session-management>的{​​{0}}子元素


* <<nsa-concurrency-control,concurrency-control>>



[[nsa-concurrency-control]]
==== <concurrency-control>
增加对并发会话控制的支持，允许限制用户可以拥有的活动会话的数量。
`ConcurrentSessionFilter`将被创建，`ConcurrentSessionControlAuthenticationStrategy`将被用于`SessionManagementFilter`。
如果声明了`form-login`元素，则策略对象也将被注入到创建的认证过滤器中。
`SessionRegistry`（`SessionRegistryImpl`实例的实例，除非用户希望使用自定义bean）将被创建以供策略使用。


[[nsa-concurrency-control-parents]]
<concurrency-control>的{​​{0}}父元素


* <<nsa-session-management,session-management>>



[[nsa-concurrency-control-attributes]]
=====  <concurrency-control>属性


[[nsa-concurrency-control-error-if-maximum-exceeded]]
* **error-if-maximum-exceeded**
如果设置为"true"，则当用户尝试超出允许的最大会话数时，将引发`SessionAuthenticationException`。
默认行为是过期原始会话。


[[nsa-concurrency-control-expired-url]]
* **expired-url**
如果用户尝试使用并发会话控制器中"expired"的会话，则用户将被重定向到的URL，因为用户已超出允许的会话数并已在别处再次登录。
除非`exception-if-maximum-exceeded`被设置，否则应该被设置。
如果没有提供任何值，过期消息将直接写回响应。

[[nsa-concurrency-control-expired-session-strategy-ref]]
* **expired-url**
允许注入由ConcurrentSessionFilter使用的ExpiredSessionStrategy实例

[[nsa-concurrency-control-max-sessions]]
* **max-sessions**
映射到`ConcurrentSessionControlAuthenticationStrategy`的{​​{0}}属性。
指定`-1`作为支持无限制会话的值。


[[nsa-concurrency-control-session-registry-alias]]
* **session-registry-alias**
引用内部会话注册表以便在您自己的Bean或管理界面中使用也很有用。
您可以使用`session-registry-alias`属性公开内部bean，给它一个名称，您可以在配置中的其他位置使用该名称。


[[nsa-concurrency-control-session-registry-ref]]
* **session-registry-ref**
用户可以使用`session-registry-ref`属性提供他们自己的`SessionRegistry`实施。
其他并发会话控制bean将被连接起来使用它。


[[nsa-x509]]
==== <x509>
添加对X.509认证的支持。
一个`X509AuthenticationFilter`将被添加到堆栈中并创建一个`Http403ForbiddenEntryPoint` bean。
只有在没有使用其他身份验证机制时才会使用后者（它的唯一功能是返回HTTP 403错误代码）。
还会创建`PreAuthenticatedAuthenticationProvider`，将用户权限的加载委派给`UserDetailsService`。


[[nsa-x509-parents]]
<x509>的{​​{0}}父元素


* <<nsa-http,http>>



[[nsa-x509-attributes]]
=====  <x509>属性


[[nsa-x509-authentication-details-source-ref]]
* **authentication-details-source-ref**
对`AuthenticationDetailsSource`的引用


[[nsa-x509-subject-principal-regex]]
* **subject-principal-regex**
定义一个正则表达式，用于从证书中提取用户名（用于`UserDetailsService`）。


[[nsa-x509-user-service-ref]]
* **user-service-ref**
在配置多个实例的情况下，允许特定的`UserDetailsService`与X.509一起使用。
如果未设置，则会尝试自动找到合适的实例并使用它。


[[nsa-filter-chain-map]]
==== <filter-chain-map>
用于使用FilterChainMap显式配置FilterChainProxy实例


[[nsa-filter-chain-map-attributes]]
=====  <filter-chain-map>属性


[[nsa-filter-chain-map-request-matcher]]
* **request-matcher**
定义用于匹配传入请求的策略。
目前选项是'ant'（用于蚂蚁路径模式），正则表达式用'regex'，不区分大小写的正则表达式用'ciRegex'。


[[nsa-filter-chain-map-children]]
<filter-chain-map>的{​​{0}}子元素


* <<nsa-filter-chain,filter-chain>>



[[nsa-filter-chain]]
==== <filter-chain>
用于定义特定的URL模式以及适用于与该模式匹配的URL的过滤器列表。
当为了配置FilterChainProxy而在列表中组装多个过滤器链元素时，最具体的模式必须放置在列表的顶部，最常见的模式位于最下面。


[[nsa-filter-chain-parents]]
<filter-chain>的{​​{0}}父元素


* <<nsa-filter-chain-map,filter-chain-map>>



[[nsa-filter-chain-attributes]]
=====  <filter-chain>属性


[[nsa-filter-chain-filters]]
* **filters**
实现`Filter`的Spring bean引用的逗号分隔列表。
值"none"表示不应为此`FilterChain`使用`Filter`。


[[nsa-filter-chain-pattern]]
* **pattern**
与<<nsa-filter-chain-map-request-matcher,request-matcher>>结合创建RequestMatcher的模式


[[nsa-filter-chain-request-matcher-ref]]
* **request-matcher-ref**
对`RequestMatcher`的引用将用于确定是否应该调用`filters`属性中的任何`Filter`。


[[nsa-filter-security-metadata-source]]
==== <filter-security-metadata-source>
用于显式配置FilterSecurityMetadataSource bean以用于FilterSecurityInterceptor。
通常只需要在显式配置FilterChainProxy时使用，而不是使用<http>元素。
所使用的intercept-url元素应该只包含模式，方法和访问属性。
任何其他将导致配置错误。


[[nsa-filter-security-metadata-source-attributes]]
=====  <filter-security-metadata-source>属性


[[nsa-filter-security-metadata-source-id]]
* **id**
一个bean标识符，用于在上下文中的其他地方引用bean。


[[nsa-filter-security-metadata-source-request-matcher]]
* **request-matcher**
定义匹配传入请求的策略用法。
目前选项是'ant'（用于蚂蚁路径模式），正则表达式用'regex'，不区分大小写的正则表达式用'ciRegex'。


[[nsa-filter-security-metadata-source-use-expressions]]
* **use-expressions**
在<intercept-url>元素的“访问”属性中启用表达式，而不是使用传统的配置属性列表。
默认为'true'。
如果启用，每个属性应包含一个布尔表达式。
如果表达式评估为“真”，则将授予访问权限。


[[nsa-filter-security-metadata-source-children]]
<filter-security-metadata-source>的{​​{0}}子元素


* <<nsa-intercept-url,intercept-url>>

[[nsa-websocket-security]]
===  WebSocket安全性

Spring Security 4.0+提供了对授权消息的支持。
其中有用的一个具体示例是在基于WebSocket的应用程序中提供授权。

[[nsa-websocket-message-broker]]
==== <websocket-message-broker>

websocket-message-broker元素有两种不同的模式。
如果没有指定<<nsa-websocket-message-broker-id,websocket-message-broker@id>>，那么它将执行以下操作：

* 确保任何SimpAnnotationMethodMessageHandler都将AuthenticationPrincipalArgumentResolver注册为自定义参数解析器。
这允许使用`@AuthenticationPrincipal`来解析当前`Authentication`的主体
* 确保SecurityContextChannelInterceptor自动注册clientInboundChannel。
这将使用消息中找到的用户填充SecurityContextHolder
* 确保ChannelSecurityInterceptor向clientInboundChannel注册。
这允许为消息指定授权规则。
* 确保CsrfChannelInterceptor向clientInboundChannel注册。
这确保只有来自原始域的请求被启用。
* 确保向WebSocketHttpRequestHandler，TransportHandlingSockJsService或DefaultSockJsService注册CsrfTokenHandshakeInterceptor。
这可确保将来自HttpServletRequest的预期CsrfToken复制到WebSocket会话属性中。

如果需要额外控制，则可以指定id，并将ChannelSecurityInterceptor分配给指定的ID。
Spring的消息传递基础设施的所有接线都可以手动完成。
这比较麻烦，但是可以更好地控制配置。


[[nsa-websocket-message-broker-attributes]]
=====  <websocket-message-broker>属性

[[nsa-websocket-message-broker-id]]
*  **id**一个bean标识符，用于引用上下文中其他位置的ChannelSecurityInterceptor bean。
如果指定，Spring Security需要在Spring Messaging中进行显式配置。
如果未指定，Spring Security将自动与消息传递基础结构集成，如<<nsa-websocket-message-broker>>中所述

[[nsa-websocket-message-broker-same-origin-disabled]]
*  **same-origin-disabled**禁用要求在Stomp头文件中存在CSRF标记（默认为false）。
如果需要允许其他来源进行SockJS连接，则更改默认值很有用。

[[nsa-websocket-message-broker-children]]
<websocket-message-broker>的{​​{0}}子元素


* <<nsa-expression-handler,expression-handler>>
* <<nsa-intercept-message,intercept-message>>

[[nsa-intercept-message]]
==== <intercept-message>

定义消息的授权规则。


[[nsa-intercept-message-parents]]
<intercept-message>的{​​{0}}父元素


* <<nsa-websocket-message-broker,websocket-message-broker>>


[[nsa-intercept-message-attributes]]
=====  <intercept-message>属性

[[nsa-intercept-message-pattern]]
*  **pattern**与消息目标匹配的基于蚂蚁的模式。
例如，"/**"将任何消息与目标匹配; "/admin/**"匹配任何以"/admin/**"开头的消息。

[[nsa-intercept-message-type]]
*  **type**匹配的消息类型。
有效值在SimpMessageType中定义（即CONNECT，CONNECT_ACK，HEARTBEAT，MESSAGE，SUBSCRIBE，UNSUBSCRIBE，DISCONNECT，DISCONNECT_ACK，OTHER）。

[[nsa-intercept-message-access]]
*  **access**用于保护消息的表达式。
例如，"denyAll"将拒绝访问所有匹配的消息; "permitAll"将授予对所有匹配邮件的访问权限; “hasRole（'ADMIN'）要求当前用户具有匹配消息的角色'ROLE_ADMIN'。

[[nsa-authentication]]
=== 身份验证服务
在Spring Security 3.0之前，`AuthenticationManager`在内部自动注册。
现在您必须使用`<authentication-manager>`元素明确注册一个。
这将创建Spring Security的`ProviderManager`类，它需要与一个或多个`AuthenticationProvider`实例列表配置的一个实例。
这些既可以使用由命名空间提供语法元素来创建，或者它们可以是标准的bean定义，标记为除了使用`authentication-provider`元素列表。


[[nsa-authentication-manager]]
==== <authentication-manager>
每个使用名称空间的Spring Security应用程序都必须包含此元素。
它负责注册为应用程序提供认证服务的`AuthenticationManager`。
所有创建`AuthenticationProvider`实例的元素都应该是此元素的子元素。


[[nsa-authentication-manager-attributes]]
=====  <authentication-manager>属性


[[nsa-authentication-manager-alias]]
* **alias**
该属性允许您为内部实例定义一个别名，以便在您自己的配置中使用。
它的使用在<<ns-auth-manager,namespace introduction>>中进行了描述。


[[nsa-authentication-manager-erase-credentials]]
* **erase-credentials**
如果设置为true，将AuthenticationManager会试图清除在返回的认证对象的任何凭证数据，一旦用户通过验证。
从字面上看，它映射到`ProviderManager`的{​​{0}}属性。
这在<<core-services-erasing-credentials,Core Services>>章节中讨论。


[[nsa-authentication-manager-id]]
* **id**
该属性允许您为内部实例定义一个id，以便在您自己的配置中使用。
它与alias元素相同，但对使用id属性的元素提供更一致的体验。


[[nsa-authentication-manager-children]]
<authentication-manager>的{​​{0}}子元素


* <<nsa-authentication-provider,authentication-provider>>
* <<nsa-ldap-authentication-provider,ldap-authentication-provider>>



[[nsa-authentication-provider]]
==== <authentication-provider>
除非与`ref`属性一起使用，否则此元素是配置<<core-services-dao-provider,DaoAuthenticationProvider>>的简写。
`DaoAuthenticationProvider`从`UserDetailsService`加载用户信息，并将用户名/密码组合与登录时提供的值进行比较。
通过使用可用的命名空间元素（`jdbc-user-service`或使用`user-service-ref`属性指向应用程序上下文中定义的其他位置）可以定义`UserDetailsService`实例。
您可以在<<ns-auth-providers,namespace introduction>>中找到这些变体的示例。


[[nsa-authentication-provider-parents]]
<authentication-provider>的{​​{0}}父元素


* <<nsa-authentication-manager,authentication-manager>>



[[nsa-authentication-provider-attributes]]
=====  <authentication-provider>属性


[[nsa-authentication-provider-ref]]
* **ref**
定义对实现`AuthenticationProvider`的Spring bean的引用。

如果您编写了自己的`AuthenticationProvider`实现（或者由于某种原因想要将Spring Security自己的实现配置为传统bean，那么您可以使用以下语法将其添加到{{1} }：

[source,xml]
----

<security:authentication-manager>
<security:authentication-provider ref="myAuthenticationProvider" />
</security:authentication-manager>
<bean id="myAuthenticationProvider" class="com.something.MyAuthenticationProvider"/>

----




[[nsa-authentication-provider-user-service-ref]]
* **user-service-ref**
对实现UserDetailsS​​ervice的bean的引用，可以使用标准bean元素或自定义用户服务元素创建。


[[nsa-authentication-provider-children]]
<authentication-provider>的{​​{0}}子元素


* <<nsa-jdbc-user-service,jdbc-user-service>>
* <<nsa-ldap-user-service,ldap-user-service>>
* <<nsa-password-encoder,password-encoder>>
* <<nsa-user-service,user-service>>



[[nsa-jdbc-user-service]]
==== <jdbc-user-service>
导致创建基于JDBC的UserDetailsS​​ervice。


[[nsa-jdbc-user-service-attributes]]
=====  <jdbc-user-service>属性


[[nsa-jdbc-user-service-authorities-by-username-query]]
* **authorities-by-username-query**
一个SQL语句，用于查询给定用户名的用户授予的权限。

默认是

[source]
----
select username, authority from authorities where username = ?
----




[[nsa-jdbc-user-service-cache-ref]]
* **cache-ref**
定义对用于UserDetailsS​​ervice的缓存的引用。


[[nsa-jdbc-user-service-data-source-ref]]
* **data-source-ref**
提供所需表的DataSource的bean ID。


[[nsa-jdbc-user-service-group-authorities-by-username-query]]
* **group-authorities-by-username-query**
提供用户名的用户组权限查询的SQL语句。
默认是

+

[source]
----
select
g.id, g.group_name, ga.authority
from
groups g, group_members gm, group_authorities ga
where
gm.username = ? and g.id = ga.group_id and g.id = gm.group_id
----




[[nsa-jdbc-user-service-id]]
* **id**
一个bean标识符，用于在上下文中的其他地方引用bean。


[[nsa-jdbc-user-service-role-prefix]]
* **role-prefix**
将添加到从永久存储器加载的角色字符串的非空字符串前缀（缺省值为"ROLE_"）。
在默认值非空的情况下，使用值"none"作为无前缀。


[[nsa-jdbc-user-service-users-by-username-query]]
* **users-by-username-query**
提供用户名的SQL语句，用于查询用户名，密码和启用状态。
默认是

+

[source]
----
select username, password, enabled from users where username = ?
----




[[nsa-password-encoder]]
==== <password-encoder>
如<<ns-password-encoder,namespace introduction>>中所述，身份验证提供程序可以选择配置为使用密码编码器。
这将导致bean被注入适当的`PasswordEncoder`实例。


[[nsa-password-encoder-parents]]
<password-encoder>的{​​{0}}父元素


* <<nsa-authentication-provider,authentication-provider>>
* <<nsa-password-compare,password-compare>>



[[nsa-password-encoder-attributes]]
=====  <password-encoder>属性


[[nsa-password-encoder-hash]]
* **hash**
定义用户密码上使用的哈希算法。
我们强烈建议不要使用MD4，因为它是一个非常弱的哈希算法。


[[nsa-password-encoder-ref]]
* **ref**
定义对实现`PasswordEncoder`的Spring bean的引用。


[[nsa-user-service]]
==== <user-service>
根据属性文件或"user"子元素列表创建内存中的UserDetailsS​​ervice。
用户名在内部转换为小写字母以允许不区分大小写的查找，因此如果需要区分大小写，则不应使用此名称。


[[nsa-user-service-attributes]]
=====  <user-service>属性


[[nsa-user-service-id]]
* **id**
一个bean标识符，用于在上下文中的其他地方引用bean。


[[nsa-user-service-properties]]
* **properties**
属性文件的位置，每行的格式为

+

[source]
----
username=password,grantedAuthority[,grantedAuthority][,enabled|disabled]
----




[[nsa-user-service-children]]
<user-service>的{​​{0}}子元素


* <<nsa-user,user>>



[[nsa-user]]
==== <user>
代表应用程序中的用户。


[[nsa-user-parents]]
<user>的{​​{0}}父元素


* <<nsa-user-service,user-service>>



[[nsa-user-attributes]]
=====  <user>属性


[[nsa-user-authorities]]
* **authorities**
授予用户的更多权限之一。
用逗号分隔当局（但没有空格）。
例如，"ROLE_USER,ROLE_ADMINISTRATOR"


[[nsa-user-disabled]]
* **disabled**
可以设置为"true"将帐户标记为禁用且不可用。


[[nsa-user-locked]]
* **locked**
可以设置为"true"将帐户标记为已锁定且不可用。


[[nsa-user-name]]
* **name**
分配给用户的用户名。


[[nsa-user-password]]
* **password**
分配给用户的密码。
如果相应的身份验证提供程序支持散列，则可能会散列（请记住设置"user-service"元素的"hash"属性）。
在数据不用于认证的情况下，该属性将被省略，但仅用于访问权限。
如果省略，名称空间将生成一个随机值，从而防止意外使用身份验证。
不能为空。


[[nsa-method-security]]
=== 方法安全性


[[nsa-global-method-security]]
==== <global-method-security>
这个元素是添加对Spring Security bean上的方法的支持的主要手段。
通过使用注解（在接口或类级别定义）或通过使用AspectJ语法将一组切入点定义为子元素，可以保护方法。


[[nsa-global-method-security-attributes]]
=====  <global-method-security>属性


[[nsa-global-method-security-access-decision-manager-ref]]
* **access-decision-manager-ref**
方法安全性使用与Web安全性相同的`AccessDecisionManager`配置，但可以使用此属性覆盖此配置。
默认情况下，AffirmativeBased实现用于RoleVoter和AuthenticatedVoter。


[[nsa-global-method-security-authentication-manager-ref]]
* **authentication-manager-ref**
应该用于方法安全性的`AuthenticationManager`的引用。


[[nsa-global-method-security-jsr250-annotations]]
* **jsr250-annotations**
指定是否使用JSR-250样式属性（例如"RolesAllowed"）。
这将需要类路径上的javax.annotation.security类。
将此设置为true还会向`AccessDecisionManager`添加`Jsr250Voter`，因此如果您使用自定义实现并希望使用这些注释，则需要确保您执行此操作。


[[nsa-global-method-security-metadata-source-ref]]
* **metadata-source-ref**
可以提供外部`MethodSecurityMetadataSource`实例，该实例将优先于其他来源（例如默认注释）。


[[nsa-global-method-security-mode]]
* **mode**
该属性可以设置为"aspectj"来指定应该使用AspectJ来代替默认的Spring AOP。
安全方法必须与`spring-security-aspects`模块中的`AnnotationSecurityAspect`交织在一起。

需要注意的是，AspectJ遵循Java的规则，即接口上的注释不会被继承。
这意味着在接口上定义安全注释的方法将不会受到保护。
相反，使用AspectJ时，您必须将安全注释放在类上。


[[nsa-global-method-security-order]]
* **order**
允许为方法安全拦截器设置建议"order"。


[[nsa-global-method-security-pre-post-annotations]]
* **pre-post-annotations**
指定是否应该为此应用程序上下文启用Spring Security的前后调用注释（@PreFilter，@PreAuthorize，@PostFilter，@PostAuthorize）。
默认为"disabled"。


[[nsa-global-method-security-proxy-target-class]]
* **proxy-target-class**
如果为true，则将使用基于类的代理，而不是基于接口的代理。


[[nsa-global-method-security-run-as-manager-ref]]
* **run-as-manager-ref**
对配置的`MethodSecurityInterceptor`将使用的可选`RunAsManager`实现的引用


[[nsa-global-method-security-secured-annotations]]
* **secured-annotations**
指定是否应该为此应用程序上下文启用对Spring Security的@Secured注释的使用。
默认为"disabled"。


[[nsa-global-method-security-children]]
<global-method-security>的{​​{0}}子元素


* <<nsa-after-invocation-provider,after-invocation-provider>>
* <<nsa-expression-handler,expression-handler>>
* <<nsa-pre-post-annotation-handling,pre-post-annotation-handling>>
* <<nsa-protect-pointcut,protect-pointcut>>



[[nsa-after-invocation-provider]]
==== <after-invocation-provider>
此元素可用于修饰由`<global-method-security>`名称空间维护的安全拦截器使用的`AfterInvocationProvider`。
您可以在`global-method-security`元素中定义零个或多个元素，每个元素的`ref`属性指向您的应用程序上下文中的`AfterInvocationProvider` bean实例。


[[nsa-after-invocation-provider-parents]]
<after-invocation-provider>的{​​{0}}父元素


* <<nsa-global-method-security,global-method-security>>



[[nsa-after-invocation-provider-attributes]]
=====  <after-invocation-provider>属性


[[nsa-after-invocation-provider-ref]]
* **ref**
定义对实现`AfterInvocationProvider`的Spring bean的引用。


[[nsa-pre-post-annotation-handling]]
==== <pre-post-annotation-handling>
允许基于表达式的默认机制来处理Spring Security的前后调用注释（@PreFilter，@PreAuthorize，@PostFilter，@PostAuthorize）完全被替换。
仅在启用这些注释时适用。


[[nsa-pre-post-annotation-handling-parents]]
<pre-post-annotation-handling>的{​​{0}}父元素


* <<nsa-global-method-security,global-method-security>>



[[nsa-pre-post-annotation-handling-children]]
<pre-post-annotation-handling>的{​​{0}}子元素


* <<nsa-invocation-attribute-factory,invocation-attribute-factory>>
* <<nsa-post-invocation-advice,post-invocation-advice>>
* <<nsa-pre-invocation-advice,pre-invocation-advice>>



[[nsa-invocation-attribute-factory]]
==== <invocation-attribute-factory>
定义PrePostInvocationAttributeFactory实例，该实例用于从注释的方法中生成前后调用元数据。


[[nsa-invocation-attribute-factory-parents]]
<invocation-attribute-factory>的{​​{0}}父元素


* <<nsa-pre-post-annotation-handling,pre-post-annotation-handling>>



[[nsa-invocation-attribute-factory-attributes]]
=====  <invocation-attribute-factory>属性


[[nsa-invocation-attribute-factory-ref]]
* **ref**
定义对Spring bean Id的引用。


[[nsa-post-invocation-advice]]
==== <post-invocation-advice>
使用ref自定义`PostInvocationAdviceProvider`作为<pre-post-annotation-handling>元素的`PostInvocationAuthorizationAdvice`。


[[nsa-post-invocation-advice-parents]]
<post-invocation-advice>的{​​{0}}父元素


* <<nsa-pre-post-annotation-handling,pre-post-annotation-handling>>



[[nsa-post-invocation-advice-attributes]]
=====  <post-invocation-advice>属性


[[nsa-post-invocation-advice-ref]]
* **ref**
定义对Spring bean Id的引用。


[[nsa-pre-invocation-advice]]
==== <pre-invocation-advice>
使用ref自定义`PreInvocationAuthorizationAdviceVoter`作为<pre-post-annotation-handling>元素的`PreInvocationAuthorizationAdviceVoter`。


[[nsa-pre-invocation-advice-parents]]
<pre-invocation-advice>的{​​{0}}父元素


* <<nsa-pre-post-annotation-handling,pre-post-annotation-handling>>



[[nsa-pre-invocation-advice-attributes]]
=====  <pre-invocation-advice>属性


[[nsa-pre-invocation-advice-ref]]
* **ref**
定义对Spring bean Id的引用。


[[nsa-protect-pointcut]]
==== 使用的安全方法
`<protect-pointcut>`
您可以使用`<protect-pointcut>`元素在服务层中的整套方法和接口中定义横切安全约束，而不是使用`@Secured`批注在单个方法或类基础上定义安全属性。
您可以在<<ns-protect-pointcut,namespace introduction>>中找到示例。


[[nsa-protect-pointcut-parents]]
<protect-pointcut>的{​​{0}}父元素


* <<nsa-global-method-security,global-method-security>>



[[nsa-protect-pointcut-attributes]]
=====  <protect-pointcut>属性


[[nsa-protect-pointcut-access]]
* **access**
访问适用于与切点匹配的所有方法的配置属性列表，例如
"ROLE_A,ROLE_B"


[[nsa-protect-pointcut-expression]]
* **expression**
一个AspectJ表达式，包括'执行'关键字。
例如，'execution（int com.foo.TargetObject.countLength（String））'（不带引号）。


[[nsa-intercept-methods]]
==== <intercept-methods>
可以在bean定义内部使用，将安全拦截器添加到bean中，并为bean的方法设置访问配置属性


[[nsa-intercept-methods-attributes]]
=====  <intercept-methods>属性


[[nsa-intercept-methods-access-decision-manager-ref]]
* **access-decision-manager-ref**
可选的AccessDecisionManager bean ID由创建的方法安全拦截器使用。


[[nsa-intercept-methods-children]]
<intercept-methods>的{​​{0}}子元素


* <<nsa-protect,protect>>



[[nsa-method-security-metadata-source]]
==== <method-security-metadata-source>
创建一个MethodSecurityMetadataSource实例


[[nsa-method-security-metadata-source-attributes]]
=====  <method-security-metadata-source>属性


[[nsa-method-security-metadata-source-id]]
* **id**
一个bean标识符，用于在上下文中的其他地方引用bean。


[[nsa-method-security-metadata-source-use-expressions]]
* **use-expressions**
在<intercept-url>元素的“访问”属性中启用表达式，而不是使用传统的配置属性列表。
默认为'false'。
如果启用，每个属性应包含一个布尔表达式。
如果表达式评估为“真”，则将授予访问权限。


[[nsa-method-security-metadata-source-children]]
<method-security-metadata-source>的{​​{0}}子元素


* <<nsa-protect,protect>>



[[nsa-protect]]
==== <protect>
定义受保护的方法以及应用于其的访问控制配置属性。
我们强烈建议您不要将"protect"声明与提供的任何服务"global-method-security"混合使用。


[[nsa-protect-parents]]
<protect>的{​​{0}}父元素


* <<nsa-intercept-methods,intercept-methods>>
* <<nsa-method-security-metadata-source,method-security-metadata-source>>



[[nsa-protect-attributes]]
=====  <protect>属性


[[nsa-protect-access]]
* **access**
访问适用于该方法的配置属性列表，例如
"ROLE_A,ROLE_B".


[[nsa-protect-method]]
* **method**
方法名称


[[nsa-ldap]]
===  LDAP命名空间选项
<<ldap,its own chapter>>中详细介绍了LDAP。
我们将在这里扩展一些关于命名空间选项如何映射到Spring bean的解释。
LDAP实现广泛使用Spring LDAP，所以熟悉该项目的API可能会有用。


[[nsa-ldap-server]]
==== 使用。定义LDAP服务器
`<ldap-server>`元素
此元素设置一个供其他LDAP Bean使用的Spring LDAP `ContextSource`，定义LDAP服务器的位置和其他信息（如用户名和密码，如果不允许匿名访问）来连接到它。
它也可以用来创建一个用于测试的嵌入式服务器。
<<ldap-server,LDAP chapter>>中介绍了这两种选项的语法细节。
实际的`ContextSource`实现是`DefaultSpringSecurityContextSource`，它扩展了Spring LDAP的`LdapContextSource`类。
`manager-dn`和`manager-password`属性分别映射到后者的`userDn`和`password`属性。

如果您的应用程序上下文中只定义了一个服务器，则其他LDAP名称空间定义的bean将自动使用它。
否则，可以给该元素一个"id"属性，并使用`server-ref`属性从其他名称空间bean中引用该属性。
这实际上是`ContextSource`实例的bean `id`，如果您想在其他传统Spring bean中使用它。


[[nsa-ldap-server-attributes]]
=====  <ldap-server>属性


[[nsa-ldap-server-id]]
* **id**
一个bean标识符，用于在上下文中的其他地方引用bean。


[[nsa-ldap-server-ldif]]
* **ldif**
明确指定要加载到嵌入式LDAP服务器的ldif文件资源。
ldiff应该是一个Spring资源模式（即classpath：init.ldiff）。
缺省值是类路径*:* .ldiff


[[nsa-ldap-server-manager-dn]]
* **manager-dn**
用于认证（非嵌入式）LDAP服务器的"manager"用户身份的用户名（DN）。
如果省略，将使用匿名访问。


[[nsa-ldap-server-manager-password]]
* **manager-password**
经理DN的密码。
如果指定了manager-dn，则这是必需的。


[[nsa-ldap-server-port]]
* **port**
指定一个IP端口号。
例如，用于配置嵌入式LDAP服务器。
默认值是33389。


[[nsa-ldap-server-root]]
* **root**
嵌入式LDAP服务器的可选根后缀。
默认值是"dc=springframework,dc=org"


[[nsa-ldap-server-url]]
* **url**
指定不使用嵌入式LDAP服务器时的ldap服务器URL。


[[nsa-ldap-authentication-provider]]
==== <ldap-authentication-provider>
此元素是创建`LdapAuthenticationProvider`实例的简写。
默认情况下，这将配置一个`BindAuthenticator`实例和一个`DefaultAuthoritiesPopulator`。
与所有名称空间身份验证提供程序一样，它必须作为`authentication-provider`元素的子项包含在内。


[[nsa-ldap-authentication-provider-parents]]
<ldap-authentication-provider>的{​​{0}}父元素


* <<nsa-authentication-manager,authentication-manager>>



[[nsa-ldap-authentication-provider-attributes]]
=====  <ldap-authentication-provider>属性


[[nsa-ldap-authentication-provider-group-role-attribute]]
* **group-role-attribute**
包含将在Spring Security中使用的角色名称的LDAP属性名称。
映射到``DefaultLdapAuthoritiesPopulator``的`groupRoleAttribute`属性。
默认为"cn"。


[[nsa-ldap-authentication-provider-group-search-base]]
* **group-search-base**
搜索基地以查找组成员资格。
映射到``DefaultLdapAuthoritiesPopulator``的`groupSearchBase`构造函数参数。
默认为""（从根目录搜索）。


[[nsa-ldap-authentication-provider-group-search-filter]]
* **group-search-filter**
组搜索过滤器。
映射到``DefaultLdapAuthoritiesPopulator``的`groupSearchFilter`属性。
默认为（uniqueMember = {0}）。
替代参数是用户的DN。


[[nsa-ldap-authentication-provider-role-prefix]]
* **role-prefix**
将添加到从持久性加载的角色字符串的非空字符串前缀。
映射到``DefaultLdapAuthoritiesPopulator``的`rolePrefix`属性。
默认为"ROLE_"。
在默认值非空的情况下，使用值"none"作为无前缀。


[[nsa-ldap-authentication-provider-server-ref]]
* **server-ref**
要使用的可选服务器。
如果省略，并且注册了默认LDAP服务器（使用不带ID的<ldap-server>），则将使用该服务器。


[[nsa-ldap-authentication-provider-user-context-mapper-ref]]
* **user-context-mapper-ref**
允许通过指定一个UserDetailsContextMapper bean明确定制加载的用户对象，该用户对象的目录条目中的上下文信息将被调用


[[nsa-ldap-authentication-provider-user-details-class]]
* **user-details-class**
允许指定用户条目的objectClass。
如果设置，框架将尝试将已定义类的标准属性加载到返回的UserDetails对象中


[[nsa-ldap-authentication-provider-user-dn-pattern]]
* **user-dn-pattern**
如果您的用户位于目录中的固定位置（即，您可以直接从用户名计算出DN而不进行目录搜索），则可以使用此属性直接映射到DN。
它直接映射到`AbstractLdapAuthenticator`的{​​{0}}属性。
该值是用于构建用户DN的特定模式，例如"uid={0},ou=people"。
密钥"{0}"必须存在，并将用用户名代替。


[[nsa-ldap-authentication-provider-user-search-base]]
* **user-search-base**
用户搜索的搜索基地。
默认为""。
仅与“用户搜索过滤器”一起使用。

+

如果您需要执行搜索以在目录中找到用户，则可以设置这些属性来控制搜索。
`BindAuthenticator`将配置为`FilterBasedLdapUserSearch`，属性值直接映射到该bean构造函数的前两个参数。
如果未设置这些属性并且未提供`user-dn-pattern`作为替代，则将使用`user-search-filter="(uid={0})"`和`user-search-base=""`的默认搜索值。


[[nsa-ldap-authentication-provider-user-search-filter]]
* **user-search-filter**
用于搜索用户的LDAP过滤器（可选）。
例如"(uid={0})"。
替换参数是用户的登录名。

+

如果您需要执行搜索以在目录中找到用户，则可以设置这些属性来控制搜索。
`BindAuthenticator`将配置为`FilterBasedLdapUserSearch`，属性值直接映射到该bean构造函数的前两个参数。
如果未设置这些属性并且未提供`user-dn-pattern`作为替代，则将使用`user-search-filter="(uid={0})"`和`user-search-base=""`的默认搜索值。


[[nsa-ldap-authentication-provider-children]]
<ldap-authentication-provider>的{​​{0}}子元素


* <<nsa-password-compare,password-compare>>



[[nsa-password-compare]]
==== <password-compare>
这被用作子元素`<ldap-provider>`，并切换来自所述认证策略`BindAuthenticator`到`PasswordComparisonAuthenticator`。


[[nsa-password-compare-parents]]
<password-compare>的{​​{0}}父元素


* <<nsa-ldap-authentication-provider,ldap-authentication-provider>>



[[nsa-password-compare-attributes]]
=====  <password-compare>属性


[[nsa-password-compare-hash]]
* **hash**
定义用户密码上使用的哈希算法。
我们强烈建议不要使用MD4，因为它是一个非常弱的哈希算法。


[[nsa-password-compare-password-attribute]]
* **password-attribute**
包含用户密码的目录中的属性。
默认为"userPassword"。


[[nsa-password-compare-children]]
<password-compare>的{​​{0}}子元素


* <<nsa-password-encoder,password-encoder>>



[[nsa-ldap-user-service]]
==== <ldap-user-service>
此元件配置一个LDAP `UserDetailsService`。
使用的类是`LdapUserDetailsService`，它是的组合的`FilterBasedLdapUserSearch`和`DefaultLdapAuthoritiesPopulator`。
它支持的属性具有相同的使用如在`<ldap-provider>`。


[[nsa-ldap-user-service-attributes]]
=====  <ldap-user-service>属性


[[nsa-ldap-user-service-cache-ref]]
* **cache-ref**
定义对用于UserDetailsS​​ervice的缓存的引用。


[[nsa-ldap-user-service-group-role-attribute]]
* **group-role-attribute**
包含将在Spring Security中使用的角色名称的LDAP属性名称。
默认为"cn"。


[[nsa-ldap-user-service-group-search-base]]
* **group-search-base**
搜索基地以查找组成员资格。
默认为""（从根目录搜索）。


[[nsa-ldap-user-service-group-search-filter]]
* **group-search-filter**
组搜索过滤器。
默认为（uniqueMember = {0}）。
替代参数是用户的DN。


[[nsa-ldap-user-service-id]]
* **id**
一个bean标识符，用于在上下文中的其他地方引用bean。


[[nsa-ldap-user-service-role-prefix]]
* **role-prefix**
一个非空字符串前缀，将被添加到从永久存储器加载的角色字符串中（例如，
"ROLE_").
在默认值非空的情况下，使用值"none"作为无前缀。


[[nsa-ldap-user-service-server-ref]]
* **server-ref**
要使用的可选服务器。
如果省略，并且注册了默认LDAP服务器（使用不带ID的<ldap-server>），则将使用该服务器。


[[nsa-ldap-user-service-user-context-mapper-ref]]
* **user-context-mapper-ref**
允许通过指定一个UserDetailsContextMapper bean明确定制加载的用户对象，该用户对象的目录条目中的上下文信息将被调用


[[nsa-ldap-user-service-user-details-class]]
* **user-details-class**
允许指定用户条目的objectClass。
如果设置，框架将尝试将已定义类的标准属性加载到返回的UserDetails对象中


[[nsa-ldap-user-service-user-search-base]]
* **user-search-base**
用户搜索的搜索基地。
默认为""。
仅与“用户搜索过滤器”一起使用。


[[nsa-ldap-user-service-user-search-filter]]
* **user-search-filter**
用于搜索用户的LDAP过滤器（可选）。
例如"(uid={0})"。
替换参数是用户的登录名。
