[[servlet-hello-jc]]
= Hello Spring Security (Java Configuration)

In this section we will discuss how to use Spring Security using Java Configuration.
// FIXME: Link to XML and Boot

[[servlet-hello-jc-ews]]
== A Minimal @EnableWebSecurity Configuration

The first step is to create our Spring Security Java Configuration.
The configuration creates a Servlet `Filter` known as the `springSecurityFilterChain` which is responsible for all the security (protecting the application URLs, validating submitted username and passwords, redirecting to the log in form, etc) within your application.
You can find the most basic example of a Spring Security Java Configuration below:

.WebSecurity.java
====
[source,java]
----
import org.springframework.context.annotation.*;
import org.springframework.security.config.annotation.web.configuration.*;
import org.springframework.security.core.userdetails.*;
import org.springframework.security.provisioning.*;

@EnableWebSecurity
public class WebSecurityConfig {

	// @formatter:off
	@Bean
	public UserDetailsService userDetailsService() {
		UserDetails user = User.withDefaultPasswordEncoder()
			.username("user")
			.password("password")
			.roles("USER")
			.build();
		return  new InMemoryUserDetailsManager(user);
	}
	// @formatter:on
}
----
====

There really isn't much to this configuration, but it does a lot.
You can find a summary of the features below:

* Require an authenticated user for any interaction with the application
* Generate a default login form for you
* Allow the user with the *Username* _user_ and the *Password* _password_ to authenticate with form based authentication
* Protects the password storage with BCrypt
* Allow the user to logout
* http://en.wikipedia.org/wiki/Cross-site_request_forgery[CSRF attack] prevention
* http://en.wikipedia.org/wiki/Session_fixation[Session Fixation] protection
* Security Header integration
** http://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security[HTTP Strict Transport Security] for secure requests
** http://msdn.microsoft.com/en-us/library/ie/gg622941(v=vs.85).aspx[X-Content-Type-Options] integration
** Cache Control (can be overridden later by your application to allow caching of your static resources)
** http://msdn.microsoft.com/en-us/library/dd565647(v=vs.85).aspx[X-XSS-Protection] integration
** X-Frame-Options integration to help prevent http://en.wikipedia.org/wiki/Clickjacking[Clickjacking]
* Integrate with the following Servlet API methods
** http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getRemoteUser()[HttpServletRequest#getRemoteUser()]
** http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getUserPrincipal()[HttpServletRequest.html#getUserPrincipal()]
** http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#isUserInRole(java.lang.String)[HttpServletRequest.html#isUserInRole(java.lang.String)]
** http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#login(java.lang.String,%20java.lang.String)[HttpServletRequest.html#login(java.lang.String, java.lang.String)]
** http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#logout()[HttpServletRequest.html#logout()]

// FIXME: After completed rewriting, link to all the sections of doc that this relates to

== AbstractSecurityWebApplicationInitializer

The next step is to register the `springSecurityFilterChain` with the war.
Spring Security provides a base class `AbstractSecurityWebApplicationInitializer` that leverages https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-servlet[Spring's WebApplicationInitializer support].

An example configuration can be seen below:


.SecurityInitializer.java
====
[source,java]
----
import org.springframework.security.web.context.*;

public class SecurityInitializer
	extends AbstractSecurityWebApplicationInitializer {

	public SecurityInitializer() {
		super(WebSecurityConfig.class);
	}
}
----
====

The `SecurityInitializer` will do the following things:

* Add a `ContextLoaderListener` that loads the <<servlet-hello-ews,WebSecurityConfig>>.
* Finds the Bean of type `Filter` named `springSecurityFilterChain` and registers it to process every URL in the application


[NOTE]
====
If you are integrating with a Spring MVC application, be sure to configure the `DispatcherServlet` to load the configuration from the root `ApplicationContext` as shown below:

.MvcInitializer.java
[source,java]
----
public class MvcInitializer extends
		AbstractAnnotationConfigDispatcherServletInitializer {

	// the Root Config is registered in SecurityInitializer
	@Override
	protected Class<?>[] getRootConfigClasses() {
		return null;
	}

	// the Spring MVC configuration should be added to SecurityInitializer constructor
	// i.e.
	// super(MvcConfig.class, WebSecurityConfig.class);
	@Override
	protected Class<?>[] getServletConfigClasses() {
		return null;
	}

	@Override
	protected String[] getServletMappings() {
		return new String[] { "/" };
	}

}

----
====
