

[[introduction]]
== 介绍


[[what-is-acegi-security]]
=== 什么是Spring Security？
Spring Security为基于Java EE的企业软件应用程序提供全面的安全服务。
特别强调支持使用Spring Framework构建的项目，Spring Framework是用于企业软件开发的领先Java EE解决方案。
如果您没有使用Spring开发企业应用程序，我们热烈鼓励您仔细研究它。
对Spring的一些熟悉 - 特别是依赖注入原则 - 将帮助您更轻松地熟悉Spring Security。

人们使用Spring Security的原因有很多，但大多数人在找到Java EE的Servlet规范或EJB规范的安全特性后，都没有深入了解典型企业应用场景所需的深度。
在提到这些标准的同时，重要的是要认识到它们在WAR或EAR级别不可移植。
因此，如果切换服务器环境，在新的目标环境中重新配置应用程序的安全性通常需要很多工作。
使用Spring Security克服了这些问题，并且还为您带来了许多其他有用的，可自定义的安全功能。

您可能知道应用程序安全性的两个主要方面是"authentication"和"authorization"（或"access-control"）。
这是Spring Security的两大主要领域。
"Authentication"是建立委托人的过程是他们声称的（"principal"通常是指可以在您的应用程序中执行操作的用户，设备或其他系统）。
"Authorization"指的是决定是否允许委托人在您的应用程序内执行操作的过程。
为了达到需要授权决定的地步，委托人的身份已经由认证过程确定。
这些概念很常见，并不完全针对Spring Security。

在认证级别，Spring Security支持多种认证模式。
这些认证模式大多由第三方提供，或者由相关标准组织（如互联网工程任务组）开发。
另外，Spring Security还提供了自己的一套认证功能。
具体而言，Spring Security目前支持与所有这些技术的认证集成：


*  HTTP BASIC验证头（基于IETF RFC的标准）

*  HTTP摘要式身份验证标头（基于IETF RFC的标准）

*  HTTP X.509客户端证书交换（基于IETF RFC的标准）

*  LDAP（跨平台认证需求的一种非常常见的方法，特别是在大型环境中）

* 基于表单的身份验证（用于简单的用户界面需求）

*  OpenID身份验证

* 基于预先建立的请求标头的认证（例如Computer Associates Siteminder）

*  Jasig中心身份验证服务（也称为CAS，它是一种流行的开源单点登录系统）

* 远程方法调用（RMI）和HttpInvoker（Spring远程协议）的透明认证上下文传播

* 自动"remember-me"身份验证（因此您可以勾选一个方框以避免在预定时间段内进行重新身份验证）

* 匿名身份验证（允许每个未经身份验证的呼叫自动采用特定的安全身份）

* 运行身份验证（如果一次调用应该使用不同的安全身份进行身份验证，这很有用）

*  Java认证和授权服务（JAAS）

*  Java EE容器认证（如果需要，您仍可以使用容器管理认证）

* 的Kerberos

*  Java开源单一登录（JOSSO）*

*  OpenNMS网络管理平台*

*  AppFuse *

*  AndroMDA *

*  Mule ESB *

* 直接Web请求（DWR）*

*  Grails *

* 挂毯*

*  JTrac *

*  Jasypt *

* 滚筒*

* 弹性路径*

*  Atlassian人群*

* 您自己的身份验证系统（请参阅下文）



（*表示由第三方提供）

许多独立软件供应商（ISV）都采用Spring Security，因为这种灵活的身份验证模型的选择非常重要。
这样做可以让他们快速地将他们的解决方案与他们最终客户需要的任何内容集成起来，而无需进行大量工程或要求客户改变其环境。
如果上述认证机制都不符合您的需求，Spring Security是一个开放平台，编写您自己的认证机制非常简单。
Spring Security的许多企业用户需要与不符合任何特定安全标准的"legacy"系统进行集成，而且Spring Security很高兴能够使用此类系统"play nicely"。

无论身份验证机制如何，Spring Security都提供了一套深层次的授权功能。
有三个主要的感兴趣领域：授权Web请求，授权是否可以调用方法并授权访问单个域对象实例。
为帮助您理解这些差异，请分别考虑Servlet规范Web模式安全性，EJB容器托管安全性和文件系统安全性中的授权功能。
Spring Security在所有这些重要领域提供了深入的功能，我们将在本参考指南的后面部分探讨这些功能。


[[history]]
=== 历史
Spring Security于2003年末开始以"The Acegi Security System for Spring"开始。
Spring Developers的邮件列表上提出了一个问题，询问是否对基于Spring的安全实现给予了任何考虑。
当时Spring社区相对较小（特别是与今天的规模相比），而Spring的确只是从2003年初开始的SourceForge项目。
对这个问题的回应是，这是一个值得的领域，尽管目前缺乏时间阻碍了它的探索。

考虑到这一点，构建了一个简单的安全实现，而不是发布。
几个星期后，Spring社区的另一位成员询问了安全问题，并在当时向他们提供了这些代码。
接下来还有其他几个要求，到2004年1月，大约有20个人在使用这些代码。
这些先锋用户与其他人一起提出了一个建议SourceForge项目是有序的，该项目于2004年3月正式成立。

在那些早期，该项目没有任何自己的认证模块。
集装箱安全管理被用于认证过程，而Acegi Security则专注于授权。
这在一开始就很合适，但随着越来越多的用户请求额外的容器支持，容器特定身份验证领域接口的基本限制变得清晰起来。
还有一个相关的问题，即向容器的类路径添加新的JAR，这是最终用户混淆和错误配置的常见原因。

随后引入了Acegi安全特定的认证服务。
大约一年后，Acegi Security成为Spring Framework的正式子项目。
1。
0.
2006年5月发布了0最终版，经过两年半的积极应用于众多生产软件项目以及数百项改进和社区贡献。

Acegi Security于2007年底成为春季投资组合项目的官方项目，并更名为"Spring Security"。

今天，Spring Security拥有一个强大且活跃的开源社区。
在支持论坛上有数千条关于Spring Security的消息。
有一个积极的核心开发人员从事代码本身的工作，同时也是一个活跃的社区，他们也经常分享补丁和支持他们的同行。


[[release-numbering]]
=== 发布编号
了解Spring Security发行版的工作原理非常有用，因为它可以帮助您确定迁移到项目未来版本所涉及的工作（或缺乏）。
每个版本使用一个标准的整数三元组：MAJOR.MINOR.PATCH。
目的是MAJOR版本不兼容，API的大规模升级。
MINOR版本应该在很大程度上保留与旧版次版本的源代码和二进制兼容性，认为可能会有一些设计更改和不兼容的更新。
PATCH级别应该完全兼容，前后颠倒，可能的例外是修改错误和缺陷的更改。

您受到更改影响的程度取决于您的代码的集成程度。
如果您正在进行大量定制，则与使用简单名称空间配置相比，您可能会受到更多的影响。

在推出新版本之前，您应该始终彻底测试您的应用程序。


[[get-spring-security]]
=== 获得Spring Security
你可以通过几种方式获得Spring Security。
您可以从主http：// spring下载打包发行版。
io / spring-security [Spring Security]页面中，从Maven Central存储库（或Spring Maven存储库中下载快照和里程碑版本）下载各个jar，或者，您可以自己从源代码构建项目。

[[maven]]
==== 使用Maven

最小的Spring Security Maven依赖关系集通常如下所示：

.pom.xml
[source,xml]
[subs="verbatim,attributes"]
----
<dependencies>
<!-- ... other dependency elements ... -->
<dependency>
	<groupId>org.springframework.security</groupId>
	<artifactId>spring-security-web</artifactId>
	<version>{spring-security-version}</version>
</dependency>
<dependency>
	<groupId>org.springframework.security</groupId>
	<artifactId>spring-security-config</artifactId>
	<version>{spring-security-version}</version>
</dependency>
</dependencies>
----

如果您正在使用LDAP，OpenID等附加功能，则还需要包含相应的<<modules>>。

[[maven-repositories]]
=====  Maven仓库
所有GA版本（即以.RELEASE结尾的版本）都将部署到Maven Central，因此您的POM中不需要声明其他Maven存储库。

如果您使用的是SNAPSHOT版本，则需要确保您已经定义了Spring Snapshot存储库，如下所示：

.pom.xml
[source,xml]
----
<repositories>
<!-- ... possibly other repository elements ... -->
<repository>
	<id>spring-snapshot</id>
	<name>Spring Snapshot Repository</name>
	<url>http://repo.spring.io/snapshot</url>
</repository>
</repositories>
----

如果您正在使用里程碑或候选版本，则需要确保您已经定义了Spring Milestone存储库，如下所示：

.pom.xml
[source,xml]
----
<repositories>
<!-- ... possibly other repository elements ... -->
<repository>
	<id>spring-milestone</id>
	<name>Spring Milestone Repository</name>
	<url>http://repo.spring.io/milestone</url>
</repository>
</repositories>
----

[[maven-bom]]
=====  Spring框架

Spring Security针对Spring Framework {spring-version}构建，但应该可以在4.0.x中使用。
许多用户会遇到的问题是Spring Security的传递依赖关系解决了可能导致奇怪类路径问题的Spring Framework {spring-version}。

解决这个问题的一个（单调乏味的）方法是将所有Spring Framework模块包含在你的pom的 http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management[<dependencyManagement>]部分中。
另一种方法是将`spring-framework-bom`包含在`pom.xml`的`<dependencyManagement>`部分中，如下所示：

.pom.xml
[source,xml]
[subs="verbatim,attributes"]
----
<dependencyManagement>
	<dependencies>
	<dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-framework-bom</artifactId>
		<version>{spring-version}</version>
		<type>pom</type>
		<scope>import</scope>
	</dependency>
	</dependencies>
</dependencyManagement>
----

这将确保Spring Security的所有传递依赖使用Spring {spring-version}模块。

注意：此方法使用Maven的"bill of materials"（BOM）概念，并且仅在Maven 2.0.9+中提供。
有关如何解决依赖关系的更多详细信息，请参阅 http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html[Maven的介绍依赖机制文档]。

[[gradle]]
==== 摇篮
最小的Spring Security Gradle依赖关系集通常如下所示：

.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
dependencies {
	compile 'org.springframework.security:spring-security-web:{spring-security-version}'
	compile 'org.springframework.security:spring-security-config:{spring-security-version}'
}
----

如果您正在使用LDAP，OpenID等附加功能，则还需要包含相应的<<modules>>。

[[gradle-repositories]]
=====  Gradle存储库
所有GA版本（即以.RELEASE结尾的版本）都将部署到Maven Central，因此使用mavenCentral（）存储库对于GA版本已足够。

.build.gradle
[source,groovy]
----
repositories {
	mavenCentral()
}
----

如果您使用的是SNAPSHOT版本，则需要确保您已经定义了Spring Snapshot存储库，如下所示：

.build.gradle
[source,groovy]
----
repositories {
	maven { url 'https://repo.spring.io/snapshot' }
}
----

如果您正在使用里程碑或候选版本，则需要确保您已经定义了Spring Milestone存储库，如下所示：

.build.gradle
[source,groovy]
----
repositories {
	maven { url 'https://repo.spring.io/milestone' }
}
----

[[gradle-resolutionStrategy]]
===== 使用Spring 4.0.x和Gradle

默认情况下，Gradle将在解析传递版本时使用最新版本。
这意味着当使用Spring Framework {spring-version}运行Spring Security {spring-security-version}时，通常不需要额外的工作。
但是，有时可能会出现问题，因此最好使用 http://www.gradle.org/docs/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html[Gradle的ResolutionStrategy]来缓解此问题，如下所示：

.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
configurations.all {
	resolutionStrategy.eachDependency { DependencyResolveDetails details ->
		if (details.requested.group == 'org.springframework') {
			details.useVersion '{spring-version}'
		}
	}
}
----

这将确保Spring Security的所有传递依赖使用Spring {spring-version}模块。

注意：本例使用Gradle 1.9，但可能需要修改才能在将来的Gradle版本中使用，因为这是Gradle中的一项孵化功能。

[[modules]]
==== 项目模块
在Spring Security 3.0中，代码库被细分为独立的jar，这些jar更清楚地区分了不同的功能区域和第三方依赖关系。
如果您使用Maven构建项目，那么这些模块将添加到您的`pom.xml`中。
即使您不使用Maven，我们也建议您参考`pom.xml`文件以了解第三方依赖关系和版本。
或者，一个好主意是检查示例应用程序中包含的库。


[[spring-security-core]]
===== 核心 -  spring-security-core.jar
包含核心认证和访问控制类和接口，远程处理支持和基本配置API。
由使用Spring Security的任何应用程序所要求。
支持独立应用程序，远程客户端，方法（服务层）安全性和JDBC用户配置。
包含顶级包：

* `org.springframework.security.core`

* `org.springframework.security.access`

* `org.springframework.security.authentication`

* `org.springframework.security.provisioning`





[[spring-security-remoting]]
===== 远程处理 -  spring-security-remoting.jar
提供与Spring Remoting的集成。
除非你正在编写一个使用Spring Remoting的远程客户端，否则你不需要这个。
主包是`org.springframework.security.remoting`。


[[spring-security-web]]
=====  Web  -  spring-security-web.jar
包含过滤器和相关的网络安全基础架构代码。
任何具有servlet API依赖性的东西。
如果您需要Spring Security Web认证服务和基于URL的访问控制，您将需要它。
主包是`org.springframework.security.web`。


[[spring-security-config]]
=====  Config  -  spring-security-config.jar
包含安全名称空间解析代码和Java配置代码。
如果您使用Spring Security XML名称空间进行配置或Spring Security的Java配置支持，则需要它。
主包是`org.springframework.security.config`。
这些类别都不能直接用于应用程序。


[[spring-security-ldap]]
=====  LDAP  -  spring-security-ldap.jar
LDAP认证和供应代码。
如果您需要使用LDAP身份验证或管理LDAP用户条目，则为必需。
顶级包装是`org.springframework.security.ldap`。


[[spring-security-oauth2-core]]
=====  OAuth 2.0核心 -  spring-security-oauth2-core.jar
`spring-security-oauth2-core.jar`包含为_OAuth 2.0授权框架_和_OpenID Connect Core 1.0_提供支持的核心类和接口。
这是使用_OAuth 2.0_或_OpenID Connect Core 1.0_的应用程序所必需的，例如客户端，资源服务器和授权服务器。
顶级包装是`org.springframework.security.oauth2.core`。


[[spring-security-oauth2-client]]
=====  OAuth 2.0客户端 -  spring-security-oauth2-client.jar
`spring-security-oauth2-client.jar`是Spring Security对_OAuth 2.0授权框架_和_OpenID Connect Core 1.0_的客户端支持。
由利用*OAuth 2.0 Login*和/或OAuth客户端支持的应用程序所需。
顶级包装是`org.springframework.security.oauth2.client`。


[[spring-security-oauth2-jose]]
=====  OAuth 2.0 JOSE  -  spring-security-oauth2-jose.jar
`spring-security-oauth2-jose.jar`包含Spring Security对_JOSE_（Javascript对象签名和加密）框架的支持。
_JOSE_框架旨在提供一种安全地在各方之间传输声明的方法。
它由一系列规格构建而成：

*  JSON Web令牌（JWT）
*  JSON Web签名（JWS）
*  JSON Web加密（JWE）
*  JSON Web密钥（JWK）

它包含顶级软件包：

* `org.springframework.security.oauth2.jwt`
* `org.springframework.security.oauth2.jose`


[[spring-security-acl]]
=====  ACL  -  spring-security-acl.jar
专门的域对象ACL实现。
用于将安全性应用于应用程序内的特定域对象实例。
顶级包装是`org.springframework.security.acls`。


[[spring-security-cas]]
=====  CAS  -  spring-security-cas.jar
Spring Security的CAS客户端集成。
如果您想使用CAS单点登录服务器的Spring Security Web认证。
顶级包装是`org.springframework.security.cas`。


[[spring-security-openid]]
=====  OpenID  -  spring-security-openid.jar
OpenID Web认证支持。
用于对外部OpenID服务器进行身份验证。
`org.springframework.security.openid`.
需要OpenID4Java。


[[spring-security-test]]
===== 测试 -  spring-security-test.jar
支持使用Spring Security进行测试。


[[get-source]]
==== 检出来源
由于Spring Security是一个开源项目，我们强烈建议您使用git来检查源代码。
这将使您可以完全访问所有示例应用程序，并且可以轻松构建项目的最新版本。
拥有项目的源代码对于调试也有很大的帮助。
异常堆栈跟踪不再是晦涩难解的黑盒问题，但您可以直接找到导致问题的线路并计算出发生的情况。
源代码是项目的最终文档，通常是查找实际内容的最简单方式。

要获得项目的源代码，请使用以下git命令：

[source,txt]
----
git clone https://github.com/spring-projects/spring-security.git
----

这将使您可以访问本地计算机上的整个项目历史记录（包括所有版本和分支机构）。
