
[[ns-config]]
== 安全名称空间配置


=== 介绍
名称空间配置自Spring Framework 2.0以来已可用。
它允许您用传统的Spring bean应用程序上下文语法和其他XML模式中的元素进行补充。
您可以在Spring http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/[参考文档]中找到更多信息。
命名空间元素可以简单地用于配置单个Bean的更简洁的方式，或者更有力地定义更接近匹配问题域的替代配置语法，并隐藏用户的底层复杂性。
一个简单的元素可能会隐藏多个bean和处理步骤被添加到应用程序上下文的事实。
例如，将以下元素从安全性名称空间添加到应用程序上下文将启动一个嵌入式LDAP服务器，以在应用程序中测试使用情况：

[source,xml]
----
<security:ldap-server />
----

这比连接相应的Apache Directory Server bean简单得多。
最常见的备选配置要求由`ldap-server`元素上的属性支持，用户不必担心需要创建哪些bean以及哪些bean属性名称。
脚注：[您可以在关于pass的章节中找到更多关于使用`ldap-server`元素的信息：specialcharacters，macros [<<ldap>>]。]。
编辑应用程序上下文文件时使用好的XML编辑器应提供有关可用属性和元素的信息。
我们建议您尝试使用 http://spring.io/tools/sts[Spring工具套件]，因为它具有用于处理标准Spring名称空间的特殊功能。


要开始在您的应用程序上下文中使用安全性命名空间，您需要在您的类路径中包含`spring-security-config` jar。
然后，您需要做的就是将模式声明添加到您的应用程序上下文文件中：

[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
xmlns:security="http://www.springframework.org/schema/security"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.springframework.org/schema/beans
		http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/security
		http://www.springframework.org/schema/security/spring-security.xsd">
	...
</beans>
----

在许多您将看到的示例中（以及示例应用程序中），我们经常会将"security"用作默认名称空间而不是"beans"，这意味着我们可以忽略所有安全名称空间元素上的前缀，使内容更易于阅读。
如果将应用程序上下文划分为单独的文件并在其中一个文件中包含大部分安全配置，则可能还需要执行此操作。
您的安全应用程序上下文文件将会像这样开始

[source,xml]
----
<beans:beans xmlns="http://www.springframework.org/schema/security"
xmlns:beans="http://www.springframework.org/schema/beans"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.springframework.org/schema/beans
		http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/security
		http://www.springframework.org/schema/security/spring-security.xsd">
	...
</beans:beans>
----

我们将假设这章从现在开始使用这个语法。


==== 命名空间的设计
命名空间旨在捕获框架的最常见用途，并提供简化和简洁的语法来在应用程序中启用它们。
该设计基于框架内的大规模依赖关系，可分为以下几个方面：

*  __ Web / HTTP Security__  - 最复杂的部分。
设置用于应用框架认证机制的过滤器和相关服务bean，保护URL，呈现登录和错误页面等等。

*  __业务对象（方法）安全性___  - 保护服务层的选项。

*  __ AuthenticationManager__  - 处理来自框架其他部分的认证请求。

*  __ AccessDecisionManager__  - 为网络和方法安全提供访问决策。
一个默认的将被注册，但你也可以选择使用一个自定义的，使用普通的Spring bean语法声明。

*  __ AuthenticationProvider__s  - 身份验证管理员验证用户身份的机制。
命名空间为几个标准选项提供了支持，同时也提供了添加使用传统语法声明的自定义bean的方法。

*  __ UserDetailsS​​ervice__  - 与身份验证提供程序密切相关，但其他bean通常也需要它。

我们将在下面的章节中看到如何配置这些。

[[ns-getting-started]]
=== 安全名称空间配置入门
在本节中，我们将看看如何构建一个名称空间配置来使用框架的一些主要功能。
假设您最初希望尽快启动并运行，并将身份验证支持和访问控制添加到现有的Web应用程序，并带有一些测试登录名。
然后我们将看看如何切换到对数据库或其他安全存储库进行身份验证。
在后面的章节中，我们将介绍更高级的命名空间配置选项。

[[ns-web-xml]]
====  web.xml配置
您需要做的第一件事是将以下过滤声明添加到您的`web.xml`文件中：

[source,xml]
----
<filter>
<filter-name>springSecurityFilterChain</filter-name>
<filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
</filter>

<filter-mapping>
<filter-name>springSecurityFilterChain</filter-name>
<url-pattern>/*</url-pattern>
</filter-mapping>
----

这为Spring Security Web基础结构提供了一个钩子。
`DelegatingFilterProxy`是一个Spring框架类，它委派一个过滤器实现，它在应用程序上下文中定义为一个Spring bean。
在这种情况下，bean被命名为"springSecurityFilterChain"，它是由命名空间创建的用于处理Web安全性的内部基础设施bean。
请注意，您不应该自己使用这个bean名称。
将这些内容添加到您的`web.xml`后，即可开始编辑您的应用程序上下文文件。
Web安全服务使用`<http>`元素进行配置。

[[ns-minimal]]
==== 最小<http>配置
您只需启用网络安全即可

[source,xml]
----
<http>
<intercept-url pattern="/**" access="hasRole('USER')" />
<form-login />
<logout />
</http>
----

其中说我们希望我们应用程序中的所有URL都受到保护，要求角色`ROLE_USER`能够访问它们，我们希望使用带有用户名和密码的表单登录应用程序，并且我们希望注册注销URL这将允许我们注销应用程序。
`<http>`元素是所有与Web相关的名称空间功能的父项。
`<intercept-url>`元素定义了一个`pattern`，它使用蚂蚁路径样式语法脚注与传入请求的URL匹配：[请参阅关于传递的部分：特殊字符，宏[<<request-matching>>] Web应用程序基础结构一章，了解如何实际执行匹配的更多细节。]。
您也可以使用正则表达式匹配作为替代（有关更多详细信息，请参阅命名空间附录）。
`access`属性定义匹配给定模式的请求的访问要求。
通过默认配置，这通常是逗号分隔的角色列表，其中一个用户必须被允许发出请求。
前缀"ROLE_"是一个标记，表示应该与用户权限进行简单比较。
换句话说，应该使用正常的基于角色的检查。
Spring Security中的访问控制不限于使用简单角色（因此使用前缀来区分不同类型的安全属性）。
我们稍后会看到解释如何变化脚注：[{0}}属性中逗号分隔值的解释取决于pass的实现：specialcharacters，macros [<<ns-access-manager,AccessDecisionManager>>] 。
在Spring Security 3.0中，该属性也可以使用pass：specialcharacters，macros [<<el-access,EL expression>>]来填充。


[NOTE]
====

您可以使用多个`<intercept-url>`元素为不同的网址集定义不同的访问权限要求，但会按列出的顺序对其进行评估，并使用第一个匹配项。
所以你必须把最具体的比赛放在最上面。
您还可以添加`method`属性，以将匹配限制为特定的HTTP方法（`GET`，`POST`，`PUT`）。

====

要添加一些用户，您可以直接在命名空间中定义一组测试数据：

[source,xml]
----
<authentication-manager>
<authentication-provider>
	<user-service>
	<!-- Password is prefixed with {noop} to indicate to DelegatingPasswordEncoder that
	NoOpPasswordEncoder should be used. This is not safe for production, but makes reading
	in samples easier. Normally passwords should be hashed using BCrypt -->
	<user name="jimi" password="{noop}jimispassword" authorities="ROLE_USER, ROLE_ADMIN" />
	<user name="bob" password="{noop}bobspassword" authorities="ROLE_USER" />
	</user-service>
</authentication-provider>
</authentication-manager>
----

这是存储相同密码的安全方式的一个例子。
密码前缀为`{bcrypt}`，用于指示支持任何已配置的`PasswordEncoder`进行匹配的`DelegatingPasswordEncoder`，并使用BCrypt对密码进行散列处理：

[source,xml]
----
<authentication-manager>
<authentication-provider>
	<user-service>
	<user name="jimi" password="{bcrypt}$2a$10$ddEWZUl8aU0GdZPPpy7wbu82dvEw/pBpbRvDQRqA41y6mK1CoH00m"
			authorities="ROLE_USER, ROLE_ADMIN" />
	<user name="bob" password="{bcrypt}$2a$10$/elFpMBnAYYig6KRR5bvOOYeZr1ie1hSogJryg9qDlhza4oCw1Qka"
			authorities="ROLE_USER" />
	<user name="jimi" password="{noop}jimispassword" authorities="ROLE_USER, ROLE_ADMIN" />
	<user name="bob" password="{noop}bobspassword" authorities="ROLE_USER" />
	</user-service>
</authentication-provider>
</authentication-manager>
----



[subs="quotes"]
****
如果你熟悉框架的命名空间版本，你可能已经可以大概猜出这里发生了什么。
`<http>`元素负责创建一个`FilterChainProxy`和它使用的过滤器bean。
由于过滤器位置是预定义的，因此不正确的过滤器排序等常见问题不再是问题。

`<authentication-provider>`元素创建一个`DaoAuthenticationProvider` bean，`<user-service>`元素创建一个`InMemoryDaoImpl`。
所有`authentication-provider`元素必须是`<authentication-manager>`元素的子元素，它会创建一个`ProviderManager`并向其注册身份验证提供程序。
您可以找到有关在<<appendix-namespace,namespace appendix>>中创建的bean的更多详细信息。
如果您想开始了解框架中的重要类以及如何使用这些类，那么值得进行交叉检查，特别是如果您想稍后进行自定义的话。
****

上面的配置定义了两个用户，他们的密码和他们在应用程序中的角色（将用于访问控制）。
也可以使用`user-service`上的`properties`属性从标准属性文件加载用户信息。
有关文件格式的更多详细信息，请参阅<<core-services-in-memory-service,in-memory authentication>>中的部分。
使用`<authentication-provider>`元素意味着用户信息将被认证管理器用于处理认证请求。
您可以有多个`<authentication-provider>`元素来定义不同的身份验证源，并且每个元素都会依次进行查询。

此时您应该能够启动您的应用程序，并且您将需要登录才能继续。
尝试一下，或尝试使用该项目附带的"tutorial"示例应用程序进行试验。


[[ns-form-and-basic]]
==== 表单和基本登录选项
由于我们没有提及任何HTML文件或JSP，因此您可能想知道登录表单从何时被提示登录。
实际上，由于我们没有明确设置登录页面的URL，因此Spring Security会根据启用的功能自动生成一个URL，并使用处理提交的登录的URL的标准值，用户将默认的目标URL在登录后被发送到等等。
但是，命名空间提供了大量的支持来允许您自定义这些选项。
例如，如果您想提供自己的登录页面，则可以使用：

[source,xml]
----
<http>
<intercept-url pattern="/login.jsp*" access="IS_AUTHENTICATED_ANONYMOUSLY"/>
<intercept-url pattern="/**" access="ROLE_USER" />
<form-login login-page='/login.jsp'/>
</http>
----

另请注意，我们已经添加了一个额外的`intercept-url`元素来说明登录页面的任何请求应该可供匿名用户使用脚注：[请参阅关于pass的章节：specialcharacters，macros [<<anonymous>>]]以及关于值`IS_AUTHENTICATED_ANONYMOUSLY`如何处理的更多细节<<authz-authenticated-voter,AuthenticatedVoter>>类。]。
否则，请求将与模式/ **匹配，并且无法访问登录页面本身！
这是一个常见的配置错误，并且会导致应用程序中出现无限循环。
如果您的登录页面似乎受到保护，Spring Security将在日志中发出警告。
通过为模式定义一个单独的`http`元素，也可以让所有匹配特定模式的请求完全绕过安全过滤器链，如下所示：


[source,xml]
----
<http pattern="/css/**" security="none"/>
<http pattern="/login.jsp*" security="none"/>

<http use-expressions="false">
<intercept-url pattern="/**" access="ROLE_USER" />
<form-login login-page='/login.jsp'/>
</http>
----

从Spring Security 3.1开始，现在可以使用多个`http`元素为不同的请求模式定义单独的安全过滤器链配置。
如果从`http`元素中省略`pattern`属性，它将匹配所有请求。
创建一个不安全的模式就是这种语法的一个简单例子，其中模式映射到一个空的过滤器链脚注：[使用多个`<http>`元素是一个重要的特性，允许名称空间同时支持有状态和无状态例如，在同一个应用程序中的路径。
以前使用`intercept-url`元素上的属性`filters="none"`的语法与此更改不兼容，并且在3.1中不再支持。]。
我们将在<<filter-chains-with-ns,Security Filter Chain>>一章中更详细地讨论这种新语法。

认识到这些不安全的请求将完全忽略任何Spring Security Web相关配置或诸如`requires-channel`之类的附加属性是非常重要的，因此您将无法访问当前用户的信息或在请求。
如果您仍希望应用安全筛选器链，请使用`access='IS_AUTHENTICATED_ANONYMOUSLY'`作为替代方案。

如果您想使用基本身份验证而不是表单登录，请将配置更改为

[source,xml]
----
<http use-expressions="false">
<intercept-url pattern="/**" access="ROLE_USER" />
<http-basic />
</http>
----

然后，基本身份验证将优先，并在用户尝试访问受保护资源时用于提示登录。
如果您希望使用此配置，表单登录仍然可用，例如通过嵌入其他网页的登录表单。

[[ns-form-target]]
===== 设置默认的登录后目的地
如果尝试访问受保护资源时未提示表单登录，则`default-target-url`选项会发挥作用。
这是成功登录后用户将访问的网址，默认为"/"。
通过将`always-use-default-target`属性设置为"true"，您还可以配置这些内容，以使用户__always__结束于此页面（无论登录名是"on-demand"还是明确选择登录） 。
如果您的应用程序始终要求用户从"home"页开始，这非常有用，例如：

[source,xml]
----
<http pattern="/login.htm*" security="none"/>
<http use-expressions="false">
<intercept-url pattern='/**' access='ROLE_USER' />
<form-login login-page='/login.htm' default-target-url='/home.htm'
		always-use-default-target='true' />
</http>
----

为了更好地控制目标，您可以使用`authentication-success-handler-ref`属性作为`default-target-url`的替代选项。
被引用的bean应该是`AuthenticationSuccessHandler`的一个实例。
您可以在<<form-login-flow-handling,Core Filters>>章节以及命名空间附录中找到更多信息，以及有关如何在身份验证失败时自定义流的信息。

[[ns-logout]]
==== 注销处理
`logout`元素通过导航到特定的URL添加了对注销的支持。
默认注销网址为`/logout`，但您可以使用`logout-url`属性将其设置为其他内容。
关于其他可用属性的更多信息可以在命名空间附录中找到。

[[ns-auth-providers]]
==== 使用其他身份验证提供程序
在实践中，您将需要一个更可扩展的用户信息来源，而不是添加到应用程序上下文文件中的几个名称。
您很可能希望将您的用户信息存储在数据库或LDAP服务器中。
LDAP命名空间配置在<<ldap,LDAP chapter>>中处理，所以我们不会在这里介绍它。
如果您在应用程序上下文中有一个名为"myUserDetailsService"的Spring Security {0}}的自定义实现，那么您可以使用这种方法进行身份验证

[source,xml]
----

<authentication-manager>
	<authentication-provider user-service-ref='myUserDetailsService'/>
</authentication-manager>

----

如果你想使用数据库，那么你可以使用

[source,xml]
----
<authentication-manager>
<authentication-provider>
	<jdbc-user-service data-source-ref="securityDataSource"/>
</authentication-provider>
</authentication-manager>
----

"securityDataSource"是应用程序上下文中`DataSource` bean的名称，指向包含标准Spring Security <<user-schema,user data tables>>的数据库。
或者，您可以配置Spring Security `JdbcDaoImpl` bean并使用`user-service-ref`属性指向该bean：

[source,xml]
----
<authentication-manager>
<authentication-provider user-service-ref='myUserDetailsService'/>
</authentication-manager>

<beans:bean id="myUserDetailsService"
	class="org.springframework.security.core.userdetails.jdbc.JdbcDaoImpl">
<beans:property name="dataSource" ref="dataSource"/>
</beans:bean>
----

您还可以使用标准的`AuthenticationProvider` bean，如下所示

[source,xml]
----

<authentication-manager>
	<authentication-provider ref='myAuthenticationProvider'/>
</authentication-manager>

----

其中`myAuthenticationProvider`是您的应用程序上下文中实现`AuthenticationProvider`的bean的名称。
您可以使用多个`authentication-provider`元素，在这种情况下，提供程序将按其声明的顺序进行查询。
有关如何使用名称空间配置Spring Security `AuthenticationManager`的更多信息，请参阅<<ns-auth-manager>>。

[[ns-password-encoder]]
===== 添加密码编码器
应该始终使用为此目的而设计的安全哈希算法对密码进行编码（不是像SHA或MD5这样的标准算法）。
这由`<password-encoder>`元素支持。
使用bcrypt编码密码，原始身份验证提供程序配置将如下所示：

[source,xml]
----
<beans:bean name="bcryptEncoder"
	class="org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder"/>

<authentication-manager>
<authentication-provider>
	<password-encoder ref="bcryptEncoder"/>
	<user-service>
	<user name="jimi" password="$2a$10$ddEWZUl8aU0GdZPPpy7wbu82dvEw/pBpbRvDQRqA41y6mK1CoH00m"
			authorities="ROLE_USER, ROLE_ADMIN" />
	<user name="bob" password="$2a$10$/elFpMBnAYYig6KRR5bvOOYeZr1ie1hSogJryg9qDlhza4oCw1Qka"
			authorities="ROLE_USER" />
	</user-service>
</authentication-provider>
</authentication-manager>

----



在大多数情况下，bcrypt是一个不错的选择，除非你有一个遗留系统迫使你使用不同的算法。
如果您使用简单的哈希算法，或者更糟糕的是，存储纯文本密码，那么您应该考虑迁移到更安全的选项，如bcrypt。

[[ns-web-advanced]]
=== 高级网络功能

[[ns-remember-me]]
==== 记住我的身份验证
有关remember-me命名空间配置的信息，请参阅单独的<<remember-me,Remember-Me chapter>>。

[[ns-requires-channel]]
==== 添加HTTP / HTTPS频道安全
如果您的应用程序同时支持HTTP和HTTPS，并且您要求只能通过HTTPS访问特定的URL，则可以使用`<intercept-url>`上的`requires-channel`属性直接支持此功能：

[source,xml]
----
<http>
<intercept-url pattern="/secure/**" access="ROLE_USER" requires-channel="https"/>
<intercept-url pattern="/**" access="ROLE_USER" requires-channel="any"/>
...
</http>
----

使用此配置，如果用户尝试使用HTTP访问任何匹配"/secure/**"模式的内容，则会首先将其重定向到HTTPS URL脚注：[有关如何实现频道处理的更多详细信息，请参阅Javadoc对于`ChannelProcessingFilter`和相关类。]。
可用选项为"http"，"https"或"any"。
使用值"any"表示可以使用HTTP或HTTPS。

如果您的应用程序使用HTTP和/或HTTPS的非标准端口，则可以按如下方式指定端口映射列表：

[source,xml]
----
<http>
...
<port-mappings>
	<port-mapping http="9080" https="9443"/>
</port-mappings>
</http>
----

请注意，为了确保安全，应用程序不应该使用HTTP或在HTTP和HTTPS之间切换。
它应该从HTTPS开始（用户输入HTTPS URL）并始终使用安全连接以避免任何可能的中间人攻击。

[[ns-session-mgmt]]
==== 会话管理

===== 检测超时
您可以配置Spring Security检测提交的无效会话ID并将用户重定向到适当的URL。
这是通过`session-management`元素实现的：

[source,xml]
----
<http>
...
<session-management invalid-session-url="/invalidSession.htm" />
</http>
----

请注意，如果您使用此机制来检测会话超时，那么如果用户注销并重新登录而不关闭浏览器，它可能会错误地报告错误。
这是因为会话cookie在会话无效时不会被清除，即使用户已注销，也会重新提交。
您可以在注销时显式删除JSESSIONID cookie，例如在注销处理程序中使用以下语法：

[source,xml]
----
<http>
<logout delete-cookies="JSESSIONID" />
</http>
----

不幸的是，这不能保证与每个servlet容器一起工作，所以你需要在你的环境中测试它

[NOTE]
====
如果您在代理后运行应用程序，则可以通过配置代理服务器来删除会话cookie。
例如，使用Apache HTTPD的mod_headers，以下指令将通过在对注销请求的响应（假设应用程序部署在`/tutorial`路径下）中删除`JSESSIONID` cookie：

[source,xml]
----
<LocationMatch "/tutorial/logout">
Header always set Set-Cookie "JSESSIONID=;Path=/tutorial;Expires=Thu, 01 Jan 1970 00:00:00 GMT"
</LocationMatch>
----
====


[[ns-concurrent-sessions]]
===== 并发会话控制
如果您希望限制单个用户登录您的应用程序的能力，Spring Security通过以下简单添加支持这种开箱即用的功能。
首先，您需要将以下侦听器添加到您的`web.xml`文件中，以保持Spring Security关于会话生命周期事件的更新：

[source,xml]
----
<listener>
<listener-class>
	org.springframework.security.web.session.HttpSessionEventPublisher
</listener-class>
</listener>
----

然后将以下行添加到您的应用程序上下文中：

[source,xml]
----
<http>
...
<session-management>
	<concurrency-control max-sessions="1" />
</session-management>
</http>
----

这将防止用户多次登录 - 第二次登录会导致第一次登录失效。
通常情况下，您宁愿阻止第二次登录，在这种情况下您可以使用

[source,xml]
----
<http>
...
<session-management>
	<concurrency-control max-sessions="1" error-if-maximum-exceeded="true" />
</session-management>
</http>
----

第二次登录将被拒绝。
通过"rejected"，我们表示如果正在使用基于表单的登录，则用户将被发送到`authentication-failure-url`。
如果第二次认证是通过另一个非交互式机制（例如"remember-me"）发生的，则会向客户端发送一个"unauthorized"（401）错误。
如果您想要使用错误页面，则可以将属性`session-authentication-error-url`添加到`session-management`元素。

如果您使用自定义身份验证过滤器进行基于表单的登录，则必须明确配置并发会话控制支持。
更多详细信息可以在<<session-mgmt,Session Management chapter>>中找到。

[[ns-session-fixation]]
===== 会话固定攻击保护
http://en.wikipedia.org/wiki/Session_fixation[会话固定]攻击是潜在的风险，因为恶意攻击者可能通过访问站点创建会话，然后说服其他用户使用同一会话登录（通过向其发送包含会话标识符的链接作为参数，例如）。
Spring Security通过创建新会话或以其他方式更改用户登录时的会话ID来自动防止此问题。
如果您不需要此保护，或者与其他要求冲突，则可以使用`<session-management>`上的`session-fixation-protection`属性来控制行为，该属性有四个选项

*  `none`  - 不要做任何事情。
原来的会议将被保留。

*  `newSession`  - 创建新的"clean"会话，而不复制现有的会话数据（Spring Security相关的属性仍将被复制）。

*  `migrateSession`  - 创建新会话并将所有现有会话属性复制到新会话。
这是Servlet 3.0或更旧版本容器的默认值。

*  `changeSessionId`  - 不要创建新会话。
而是使用Servlet容器提供的会话固定保护（`HttpServletRequest#changeSessionId()`）。
此选项仅在Servlet 3.1（Java EE 7）和更新的容器中可用。
在较旧的容器中指定它将导致异常。
这是Servlet 3.1和更新的容器中的默认值。


发生会话修复保护时，会导致在应用程序上下文中发布`SessionFixationProtectionEvent`。
如果您使用`changeSessionId`，则此保护将会__also__导致通知任何`javax.servlet.http.HttpSessionIdListener`，因此如果您的代码侦听这两个事件，请谨慎使用。
有关更多信息，请参阅<<session-mgmt,Session Management>>一章。


[[ns-openid]]
====  OpenID支持
命名空间支持 http://openid.net/[OpenID的]登录，而不是普通的基于表单的登录，或者除了普通的基于表单的登录外，还可以进行简单的更改：

[source,xml]
----
<http>
<intercept-url pattern="/**" access="ROLE_USER" />
<openid-login />
</http>
----

然后，您应该向OpenID提供商（例如myopenid.com）注册您自己，并将用户信息添加到您的内存`<user-service>`中：

[source,xml]
----
<user name="http://jimi.hendrix.myopenid.com/" authorities="ROLE_USER" />
----

您应该可以使用`myopenid.com`网站进行身份验证。
通过设置`openid-login`元素上的`user-service-ref`属性，还可以选择特定的`UserDetailsService` bean来使用OpenID。
有关更多信息，请参阅<<ns-auth-providers,authentication providers>>上的上一节。
请注意，我们从上述用户配置中省略了密码属性，因为这组用户数据仅用于为用户加载权限。
随机密码将在内部生成，从而防止您在配置中的其他位置意外地将此用户数据用作身份验证源。


===== 属性交换
支持OpenID http://openid.net/specs/openid-attribute-exchange-1_0.html[属性交换]。
例如，以下配置将尝试从OpenID提供程序中检索电子邮件和全名，供应用程序使用：

[source,xml]
----
<openid-login>
<attribute-exchange>
	<openid-attribute name="email" type="http://axschema.org/contact/email" required="true"/>
	<openid-attribute name="name" type="http://axschema.org/namePerson"/>
</attribute-exchange>
</openid-login>
----

每个OpenID属性的"type"是一个由特定模式确定的URI，在这种情况下为 http://axschema.org/[http://axschema.org/]。
如果必须为成功认证检索属性，则可以设置`required`属性。
支持的确切架构和属性取决于您的OpenID提供者。
属性值作为身份验证过程的一部分返回，并可以使用以下代码进行访问：

[source,java]
----
OpenIDAuthenticationToken token =
	(OpenIDAuthenticationToken)SecurityContextHolder.getContext().getAuthentication();
List<OpenIDAttribute> attributes = token.getAttributes();
----

`OpenIDAttribute`包含属性类型和检索值（或多值属性中的值）。
当我们查看<<core-components,technical overview>>章节中的核心Spring Security组件时，我们将更多地了解如何使用`SecurityContextHolder`类。
如果您希望使用多个身份提供程序，则还支持多个属性交换配置。
您可以使用每个`identifier-matcher`属性提供多个`attribute-exchange`个元素。
这包含一个正则表达式，它将与用户提供的OpenID标识符相匹配。
有关示例配置，请参阅代码库中的OpenID示例应用程序，为Google，Yahoo和MyOpenID提供程序提供不同的属性列表。


[[ns-headers]]
==== 响应标题
有关如何自定义标题元素的其他信息，请参阅参考文献的<<headers>>部分。


[[ns-custom-filters]]
==== 添加您自己的过滤器
如果您以前使用过Spring Security，那么您会知道该框架维护一系列过滤器以应用其服务。
您可能希望将自己的过滤器添加到特定位置的堆栈中，或者使用当前没有命名空间配置选项（例如CAS）的Spring Security过滤器。
或者您可能想要使用标准名称空间过滤器的自定义版本，例如由`<form-login>`元素创建的`UsernamePasswordAuthenticationFilter`，以利用可用的一些额外配置选项显式的bean。
你怎么能用命名空间配置来做到这一点，因为过滤器链不直接暴露？

使用名称空间时，过滤器的顺序始终严格执行。
在创建应用程序上下文时，过滤器bean按名称空间处理代码进行排序，标准Spring Security过滤器在名称空间和知名位置都有一个别名。

[NOTE]
====
在以前的版本中，在应用程序上下文的后处理期间，创建过滤器实例之后进行排序。
在版本3.0+中，现在在bean实例化之前，在bean元数据级完成排序。
这会影响您如何将自己的过滤器添加到堆栈，因为在解析`<http>`元素期间必须知道整个过滤器列表，因此语法在3.0中稍有变化。
====

<<filter-stack>>中显示了创建过滤器的过滤器，别名和命名空间元素/属性。
过滤器按照它们在过滤器链中出现的顺序列出。

[[filter-stack]]
。标准过滤器别名和排序
|===
|别名|过滤器类|名称空间元素或属性

| CHANNEL_FILTER
| `ChannelProcessingFilter`
| `http/intercept-url@requires-channel`

| SECURITY_CONTEXT_FILTER
| `SecurityContextPersistenceFilter`
| `http`

| CONCURRENT_SESSION_FILTER
| `ConcurrentSessionFilter`
| `session-management/concurrency-control`

| HEADERS_FILTER
| `HeaderWriterFilter`
| `http/headers`

| CSRF_FILTER
| `CsrfFilter`
| `http/csrf`

| LOGOUT_FILTER
| `LogoutFilter`
| `http/logout`

| X509_FILTER
| `X509AuthenticationFilter`
| `http/x509`

| PRE_AUTH_FILTER
| `AbstractPreAuthenticatedProcessingFilter`子类
| N / A

| CAS_FILTER
| `CasAuthenticationFilter`
| N / A

| FORM_LOGIN_FILTER
| `UsernamePasswordAuthenticationFilter`
| `http/form-login`

| BASIC_AUTH_FILTER
| `BasicAuthenticationFilter`
| `http/http-basic`

| SERVLET_API_SUPPORT_FILTER
| `SecurityContextHolderAwareRequestFilter`
| `http/@servlet-api-provision`

| JAAS_API_SUPPORT_FILTER
| `JaasApiIntegrationFilter`
| `http/@jaas-api-provision`

| REMEMBER_ME_FILTER
| `RememberMeAuthenticationFilter`
| `http/remember-me`

| ANONYMOUS_FILTER
| `AnonymousAuthenticationFilter`
| `http/anonymous`

| SESSION_MANAGEMENT_FILTER
| `SessionManagementFilter`
| `session-management`

| EXCEPTION_TRANSLATION_FILTER
| `ExceptionTranslationFilter`
| `http`

| FILTER_SECURITY_INTERCEPTOR
| `FilterSecurityInterceptor`
| `http`

| SWITCH_USER_FILTER
| `SwitchUserFilter`
| N / A
|===

您可以使用`custom-filter`元素和其中一个名称来指定您的过滤器应显示在的位置，您可以将自己的过滤器添加到堆栈中：

[source,xml]
----
<http>
<custom-filter position="FORM_LOGIN_FILTER" ref="myFilter" />
</http>

<beans:bean id="myFilter" class="com.mycompany.MySpecialAuthenticationFilter"/>
----

如果您希望将过滤器插入堆栈中另一个过滤器之前或之后，也可以使用`after`或`before`属性。
名称"FIRST"和"LAST"可以与`position`属性一起使用，以指示您希望过滤器分别出现在整个堆栈之前或之后。

。避免过滤器位置冲突
[TIP]
====

如果您插入的自定义过滤器可能与名称空间创建的标准过滤器之一占据相同的位置，请务必不要错误地包含命名空间版本。
删除所有创建要替换其功能的过滤器的元素。

请注意，您无法替换使用`<http>`元素本身创建的过滤器 -  `SecurityContextPersistenceFilter`，`ExceptionTranslationFilter`或`FilterSecurityInterceptor`。
其他一些过滤器默认添加，但您可以禁用它们。
默认情况下会添加`AnonymousAuthenticationFilter`，除非您禁用<<ns-session-fixation,session-fixation protection>>，否则`SessionManagementFilter`也会添加到过滤器链中。

====

如果要替换需要身份验证入口点的名称空间过滤器（即身份验证过程由未经身份验证的用户尝试访问受保护的资源触发），则还需要添加自定义入口点Bean。


[[ns-entry-point-ref]]
===== 设置自定义AuthenticationEntryPoint
如果您没有通过名称空间使用表单登录，OpenID或基本身份验证，则可能需要使用传统的bean语法定义身份验证过滤器和入口点，并将它们链接到名称空间中，就像我们刚刚看到的那样。
可以使用`<http>`元素上的`entry-point-ref`属性来设置相应的`AuthenticationEntryPoint`。

CAS示例应用程序是使用包含此语法的名称空间的自定义Bean的一个很好的示例。
如果您不熟悉身份验证入口点，则会在<<tech-intro-auth-entry-point,technical overview>>一章中讨论它们。


[[ns-method-security]]
=== 方法安全性
从2.0版本开始，Spring Security已经大大改善了对服务层方法的安全性的支持。
它提供对JSR-250注释安全性的支持以及框架的原始`@Secured`注释。
从3.0开始，您还可以使用新的<<el-access,expression-based annotations>>。
您可以使用`intercept-methods`元素来装饰bean声明，也可以将安全性应用于单个bean，也可以使用AspectJ样式切入点在整个服务层中保护多个bean。


[[ns-global-method]]
====  <global-method-security>元素
此元素用于在应用程序中启用基于注释的安全性（通过在元素上设置适当的属性），并将安全性切入点声明分组在一起，这些声明将应用于整个应用程序上下文中。
您应该只声​​明一个`<global-method-security>`元素。
以下声明将支持Spring Security的`@Secured`：

[source,xml]
----
<global-method-security secured-annotations="enabled" />
----

向方法（在类或接口上）添加注释会相应地限制对该方法的访问。
Spring Security的本地注释支持为该方法定义了一组属性。
这些将被传递给`AccessDecisionManager`，以便做出实际的决定：

[source,java]
----
public interface BankService {

@Secured("IS_AUTHENTICATED_ANONYMOUSLY")
public Account readAccount(Long id);

@Secured("IS_AUTHENTICATED_ANONYMOUSLY")
public Account[] findAccounts();

@Secured("ROLE_TELLER")
public Account post(Account account, double amount);
}
----

可以使用支持JSR-250注释

[source,xml]
----
<global-method-security jsr250-annotations="enabled" />
----

这些都是基于标准的，允许应用简单的基于角色的约束，但是没有Spring Security的本地注释的强大功能。
要使用新的基于表达式的语法，您可以使用

[source,xml]
----
<global-method-security pre-post-annotations="enabled" />
----

和等效的Java代码将会是

[source,java]
----
public interface BankService {

@PreAuthorize("isAnonymous()")
public Account readAccount(Long id);

@PreAuthorize("isAnonymous()")
public Account[] findAccounts();

@PreAuthorize("hasAuthority('ROLE_TELLER')")
public Account post(Account account, double amount);
}
----

如果您需要定义简单的规则，而不是根据用户的权限列表检查角色名称，则基于表达式的注释是一个不错的选择。

[NOTE]
====
注释的方法只会对定义为Spring bean的实例（在启用了方法安全性的相同应用程序上下文中）保护。
如果你想确保那些不是由Spring创建的实例（例如使用`new`运算符），那么你需要使用AspectJ。
====

[NOTE]
====
您可以在同一个应用程序中启用多种类型的注释，但只有一种类型应该用于任何界面或类，否则将无法很好地定义行为。
如果找到适用于特定方法的两个注释，则只会应用其中的一个注释。
====

[[ns-protect-pointcut]]
===== 使用protect-pointcut添加安全性切入点

`protect-pointcut`的使用特别强大，因为它允许您仅通过简单的声明就可以将安全性应用于许多bean。
考虑下面的例子：

[source,xml]
----
<global-method-security>
<protect-pointcut expression="execution(* com.mycompany.*Service.*(..))"
	access="ROLE_USER"/>
</global-method-security>
----

这将保护应用程序上下文中声明的bean上的所有方法，这些方法的类位于`com.mycompany`包中，并且其类名以"Service"结尾。
只有具有`ROLE_USER`角色的用户才能够调用这些方法。
与URL匹配一样，最具体的匹配必须在切入点列表中排在第一位，因为将使用第一个匹配表达式。
安全注释优先于切入点。

[[ns-access-manager]]
=== 默认AccessDecisionManager
本节假定您对Spring Security中访问控制的基础体系结构有一定的了解。
如果你不这样做，你可以跳过它并稍后回来，因为这部分内容只对那些需要进行一些定制以便使用不仅仅是基于角色的安全性的人非常相关。

当您使用名称空间配置时，会自动为您注册一个默认实例`AccessDecisionManager`，并将根据您在`intercept-url`中指定的访问属性为方法调用和Web URL访问做出访问决策。 }和`protect-pointcut`声明（如果您使用注释安全方法，则在注释中）。

默认策略是使用带有`RoleVoter`和`AuthenticatedVoter`的`AffirmativeBased` `AccessDecisionManager`。
您可以在<<authz-arch,authorization>>的章节中找到更多关于这些内容的信息。


[[ns-custom-access-mgr]]
==== 自定义AccessDecisionManager
如果您需要使用更复杂的访问控制策略，则很容易为方法和网络安全设置替代方案。

对于方法安全性，您可以通过将`global-method-security`中的`access-decision-manager-ref`属性设置为应用程序上下文中相应的`AccessDecisionManager` bean的`id`来执行此操作：

[source,xml]
----
<global-method-security access-decision-manager-ref="myAccessDecisionManagerBean">
...
</global-method-security>
----

Web安全的语法是相同的，但在`http`元素上：

[source,xml]
----
<http access-decision-manager-ref="myAccessDecisionManagerBean">
...
</http>
----

[[ns-auth-manager]]
=== 验证管理器和名称空间
在Spring Security中提供认证服务的主界面是`AuthenticationManager`。
这通常是Spring Security的`ProviderManager`类的一个实例，如果您之前使用过该框架，您可能已经熟悉了它。
如果没有，稍后将在<<tech-intro-authentication,technical overview chapter>>中进行介绍。
这个bean实例是使用`authentication-manager`命名空间元素注册的。
如果您通过名称空间使用HTTP或方法安全性，则无法使用自定义`AuthenticationManager`，但这不应该成为问题，因为您可以完全控制所使用的`AuthenticationProvider`。

您可能希望使用`ProviderManager`注册其他`AuthenticationProvider` Bean，您可以使用带有`ref`属性的`<authentication-provider>`元素进行此操作，其中属性的值是名称您要添加的提供程序bean的名称。
例如：

[source,xml]
----
<authentication-manager>
<authentication-provider ref="casAuthenticationProvider"/>
</authentication-manager>

<bean id="casAuthenticationProvider"
	class="org.springframework.security.cas.authentication.CasAuthenticationProvider">
...
</bean>
----

另一个常见要求是上下文中的另一个bean可能需要对`AuthenticationManager`的引用。
您可以轻松地为`AuthenticationManager`注册别名，并在您的应用程序上下文的其他地方使用此名称。

[source,xml]
----
<security:authentication-manager alias="authenticationManager">
...
</security:authentication-manager>

<bean id="customizedFormLoginFilter"
	class="com.somecompany.security.web.CustomFormLoginFilter">
<property name="authenticationManager" ref="authenticationManager"/>
...
</bean>
----
