

[[sample-apps]]
== 示例应用程序
有几个示例Web应用程序可用于该项目。
为避免下载量过大，分发zip文件中只包含"tutorial"和"contacts"个样本。
其他人可以直接从您可以获得的来源构建，如<<get-source,the introduction>>中所述。
您可以轻松地自行构建项目，并在项目网站 http://spring.io/spring-security/[http://spring.io/spring-security/]上提供更多信息。
本章中提到的所有路径都与项目源目录有关。


[[tutorial-sample]]
=== 教程示例
教程示例是帮助您入门的一个很好的基本示例。
它始终使用简单的名称空间配置。
已编译的应用程序包含在分发zip文件中，可以部署到您的Web容器（`spring-security-samples-tutorial-3.1.x.war`）中。
<<ns-form-and-basic,form-based>>身份验证机制与常用的<<remember-me,remember-me>>身份验证提供程序结合使用，以便使用Cookie自动记住登录。

我们建议您从教程示例开始，因为XML最小且易于遵循。
最重要的是，您可以轻松地将这一个XML文件（及其相应的`web.xml`条目）添加到您的现有应用程序中。
只有在实现这种基本集成时，我们才建议您尝试添加方法授权或域对象安全性。


[[contacts-sample]]
=== 通讯录
联系人范例是一个高级示例，它说明了除基本应用程序安全性以外，域对象访问控制列表（ACL）的更强大功能。
该应用程序提供了一个用户可以管理联系人简单数据库（域对象）的界面。

要进行部署，只需将Spring Security发行版中的WAR文件复制到您的容器的`webapps`目录中即可。
这场战争应该被称为`spring-security-samples-contacts-3.1.x.war`（附加版本号会因您使用的版本而异）。

启动容器后，检查应用程序是否可以加载。
访问http：// localhost：8080 / contacts（或适用于您的Web容器和您部署的WAR的URL）。

接下来，点击"Debug"。
系统会提示您进行身份验证，并在该页面上建议一系列用户名和密码。
只需对其中任何一个进行身份验证并查看生成的页面。
它应该包含类似于以下内容的成功消息：
----

Security Debug Information

Authentication object is of type:
org.springframework.security.authentication.UsernamePasswordAuthenticationToken

Authentication object as a String:

org.springframework.security.authentication.UsernamePasswordAuthenticationToken@1f127853:
Principal: org.springframework.security.core.userdetails.User@b07ed00: Username: rod; \
Password: [PROTECTED]; Enabled: true; AccountNonExpired: true;
credentialsNonExpired: true; AccountNonLocked: true; \
Granted Authorities: ROLE_SUPERVISOR, ROLE_USER; \
Password: [PROTECTED]; Authenticated: true; \
Details: org.springframework.security.web.authentication.WebAuthenticationDetails@0: \
RemoteIpAddress: 127.0.0.1; SessionId: 8fkp8t83ohar; \
Granted Authorities: ROLE_SUPERVISOR, ROLE_USER

Authentication object holds the following granted authorities:

ROLE_SUPERVISOR (getAuthority(): ROLE_SUPERVISOR)
ROLE_USER (getAuthority(): ROLE_USER)

Success! Your web filters appear to be properly configured!

----


成功收到上述消息后，请返回示例应用程序的主页并单击"Manage"。
然后您可以尝试应用程序。
请注意，只显示当前登录用户可用的联系人，并且只有具有`ROLE_SUPERVISOR`的用户才有权访问以删除其联系人。
在幕后，`MethodSecurityInterceptor`确保业务对象的安全。

该应用程序允许您修改与不同联系人关联的访问控制列表。
请务必通过查看应用程序上下文XML文件来尝试并了解它是如何工作的。


[[ldap-sample]]
===  LDAP示例
LDAP示例应用程序提供基本配置，并使用传统Bean设置名称空间配置和等效配置，这两者都位于同一应用程序上下文文件中。
这意味着实际上在此应用程序中配置了两个相同的认证提供程序


[[openid-sample]]
===  OpenID示例
OpenID示例演示了如何使用名称空间来配置OpenID以及如何为Google，Yahoo和MyOpenID身份提供商设置 http://openid.net/specs/openid-attribute-exchange-1_0.html[属性交换]配置（如果您愿意，可以尝试添加其他人）。
它使用基于JQuery的 http://code.google.com/p/openid-selector/[OpenID的选择]项目来提供用户友好的登录页面，允许用户轻松选择提供者，而不是键入完整的OpenID标识符。

该应用程序不同于正常的身份验证方案，因为它允许任何用户访问该网站（只要其OpenID身份验证成功）。
您第一次登录时，您会收到"Welcome [your name]"“消息。
如果您注销并重新登录（使用相同的OpenID标识），则应该更改为"Welcome Back"。
这是通过使用自定义的`UserDetailsService`为任何用户分配标准角色并将标识内部存储在地图中来实现的。
显然，真正的应用程序会使用数据库。
看看源表格的更多信息。
这个类还考虑到不同的属性可能会从不同的提供者返回，并建立相应的用户名称。


[[cas-sample]]
===  CAS样本
CAS示例要求您同时运行CAS服务器和CAS客户端。
它不包含在发行版中，因此您应该按<<get-source,the introduction>>中所述检出项目代码。
您可以在`sample/cas`目录下找到相关文件。
其中还有一个`Readme.txt`文件，它解释了如何直接从源代码树运行服务器和客户端，并完成SSL支持。


[[jaas-sample]]
===  JAAS示例
JAAS示例是如何在Spring Security中使用JAAS LoginModule的非常简单的示例。
如果用户名等于密码，则所提供的LoginModule将成功认证用户，否则会引发LoginException。
本例中使用的AuthorityGranter总是授予角色ROLE_USER。
示例应用程序还演示了如何通过将<<nsa-http-jaas-api-provision,jaas-api-provision>>设置为等于"true"，作为LoginModule返回的JAAS主体运行。


[[preauth-sample]]
=== 预认证示例
本示例应用程序演示了如何连接来自<<preauth,pre-authentication>>框架的bean以利用来自Java EE容器的登录信息。
用户名和角色是由容器设置的。

代码位于`samples/preauth`。

