
[[el-access]]
== 基于表达式的访问控制
Spring Security 3.0引入了使用Spring EL表达式作为授权机制的能力，以及简单使用以前见过的配置属性和访问决策选项。
基于表达式的访问控制建立在相同的体系结构上，但允许将复杂的布尔逻辑封装在单个表达式中。


=== 概述
Spring Security使用Spring EL进行表达式支持，如果您有兴趣更深入地理解该主题，您应该看看它是如何工作的。
作为评估上下文的一部分，表达式使用"root object"进行评估。
Spring Security使用Web和方法安全性的特定类作为根对象，以便提供内置表达式和对当前主体等值的访问。


[[el-common-built-in]]
==== 常用内置表达式
表达式根对象的基类是`SecurityExpressionRoot`。
这提供了可用于Web和方法安全性的一些常用表达式。

[[common-expressions]]
。常见的内置表达式
|===
|表达式|描述

| `hasRole([role])`
|如果当前主体具有指定的角色，则返回`true`。
默认情况下，如果提供的角色不以“ROLE_”开头，它将被添加。
这可以通过修改`DefaultWebSecurityExpressionHandler`上的`defaultRolePrefix`进行自定义。

| `hasAnyRole([role1,role2])`
|如果当前主体具有任何提供的角色（作为逗号分隔的字符串列表），则返回`true`。
默认情况下，如果提供的角色不以“ROLE_”开头，它将被添加。
这可以通过修改`DefaultWebSecurityExpressionHandler`上的`defaultRolePrefix`进行自定义。

| `hasAuthority([authority])`
|如果当前委托人具有指定的权限，则返回`true`。

| `hasAnyAuthority([authority1,authority2])`
|如果当前主体具有任何提供的角色（作为逗号分隔的字符串列表），则返回`true`;

| `principal`
|允许直接访问表示当前用户的主体对象

| `authentication`
|允许直接访问从`SecurityContext`获取的当前`Authentication`对象

| `permitAll`
|始终评估为`true`

| `denyAll`
|始终评估为`false`

| `isAnonymous()`
|如果当前主体是匿名用户，则返回`true`

| `isRememberMe()`
|如果当前主体是记事本用户，则返回`true`

| `isAuthenticated()`
|如果用户不是匿名的，则返回`true`

| `isFullyAuthenticated()`
|如果用户不是匿名用户或记住我用户，则返回`true`

| `hasPermission(Object target, Object permission)`
|如果用户有权访问为给定权限提供的目标，则返回`true`。
例如，`hasPermission(domainObject, 'read')`

| `hasPermission(Object targetId, String targetType, Object permission)`
|如果用户有权访问为给定权限提供的目标，则返回`true`。
例如，`hasPermission(1, 'com.example.domain.Message', 'read')`
|===



[[el-access-web]]
=== 网络安全表达式
要使用表达式保护单个网址，您首先需要将`<http>`元素中的`use-expressions`属性设置为`true`。
然后，Spring Security将期望`<intercept-url>`元素的`access`属性包含Spring EL表达式。
表达式应评估为布尔值，定义是否允许访问。
例如：

[source,xml]
----

<http>
	<intercept-url pattern="/admin*"
		access="hasRole('admin') and hasIpAddress('192.168.1.0/24')"/>
	...
</http>

----

这里我们已经定义应用程序的"admin"区域（由URL模式定义）应该只对拥有授予权限"admin"并且其IP地址与本地子网匹配的用户可用。
我们已经在上一节中看到了内置的`hasRole`表达式。
表达式`hasIpAddress`是特定于Web安全性的附加内置表达式。
它由`WebSecurityExpressionRoot`类定义，其中的一个实例在评估Web访问表达式时用作表达式根对象。
该对象还直接公开名为`request`的{​​{0}}对象，以便您可以直接在表达式中调用请求。
如果正在使用表达式，则`WebExpressionVoter`将被添加到名称空间所使用的`AccessDecisionManager`。
因此，如果您不使用名称空间并想使用表达式，则必须将其中一个添加到您的配置中。

[[el-access-web-beans]]
==== 在Web安全表达式中引用Beans

如果你想扩展可用的表达式，你可以很容易地引用你公开的任何Spring Bean。
例如，假设您的名称为`webSecurity`的Bean包含以下方法签名：

[source,java]
----
public class WebSecurity {
		public boolean check(Authentication authentication, HttpServletRequest request) {
				...
		}
}
----

你可以参考使用的方法：

[source,xml]
----
<http>
	<intercept-url pattern="/user/**"
		access="@webSecurity.check(authentication,request)"/>
	...
</http>
----

或者在Java配置中


[source,java]
----
http
		.authorizeRequests()
				.antMatchers("/user/**").access("@webSecurity.check(authentication,request)")
				...
----

[[el-access-web-path-variables]]
Web安全表达式中的==== 路径变量

有时能够在URL中引用路径变量是很好的。
例如，考虑一个REST式应用程序，该应用程序通过URL路径以`/user/{userId}`的格式通过id查找用户。

通过将其放入模式中，您可以轻松地引用路径变量。
例如，如果您有名为`webSecurity`的Bean包含以下方法签名：

[source,java]
----
public class WebSecurity {
		public boolean checkUserId(Authentication authentication, int id) {
				...
		}
}
----

你可以参考使用的方法：

[source,xml]
----
<http>
	<intercept-url pattern="/user/{userId}/**"
		access="@webSecurity.checkUserId(authentication,#userId)"/>
	...
</http>
----

或者在Java配置中

[source,java]
----
http
		.authorizeRequests()
				.antMatchers("/user/{userId}/**").access("@webSecurity.checkUserId(authentication,#userId)")
				...
----

在这两种配置中，匹配的URL将传入路径变量（并将其转换为checkUserId方法）。
例如，如果网址为`/user/123/resource`，则传入的ID为`123`。

=== 方法安全表达式
方法安全性比简单的允许或拒绝规则复杂一点。
Spring Security 3.0引入了一些新的注释，以便全面支持表达式的使用。


[[el-pre-post-annotations]]
====  @ Pre和@Post注释
有四个注释支持表达式属性以允许调用前和调用后授权检查，并支持对提交的集合参数或返回值进行过滤。
他们是`@PreAuthorize`，`@PreFilter`，`@PostAuthorize`和`@PostFilter`。
通过`global-method-security`命名空间元素启用它们的使用：

[source,xml]
----
<global-method-security pre-post-annotations="enabled"/>
----

使用@PreAuthorize和@PostAuthorize的===== 访问控制
最明显有用的注释是`@PreAuthorize`，它决定一个方法是否可以被实际调用。
例如（来自"Contacts"示例应用程序）

[source,java]
----
@PreAuthorize("hasRole('USER')")
public void create(Contact contact);
----

这意味着只有具有角色"ROLE_USER"的用户才能访问。
显然，使用传统配置和简单配置属性来实现所需角色可以轻松实现同样的目的。
但是关于：

[source,java]
----
@PreAuthorize("hasPermission(#contact, 'admin')")
public void deletePermission(Contact contact, Sid recipient, Permission permission);
----

这里我们实际上使用方法参数作为表达式的一部分来决定当前用户是否具有给定联系人的"admin"权限。
内置的`hasPermission()`表达式通过应用程序上下文链接到Spring Security ACL模块中，因为我们将<<el-permission-evaluator,see below>>。
您可以按名称访问任何方法参数作为表达式变量。

Spring Security可以通过多种方式来解决方法参数。
Spring Security使用`DefaultSecurityParameterNameDiscoverer`来发现参数名称。
默认情况下，对于整个方法尝试以下选项。

* 如果Spring Security的`@P`注释出现在该方法的单个参数上，则会使用该值。
这对于在JDK 8之前使用JDK编译的接口非常有用，它不包含有关参数名称的任何信息。
例如：

+

[source,java]
----
import org.springframework.security.access.method.P;

...

@PreAuthorize("#c.name == authentication.name")
public void doSomething(@P("c") Contact contact);
----

+

在幕后，使用`AnnotationParameterNameDiscoverer`实现的这种使用可以被自定义为支持任何指定注释的value属性。

* 如果Spring Data的`@Param`注释至少存在于该方法的一个参数中，则将使用该值。
这对于在JDK 8之前使用JDK编译的接口非常有用，它不包含有关参数名称的任何信息。
例如：

+

[source,java]
----
import org.springframework.data.repository.query.Param;

...

@PreAuthorize("#n == authentication.name")
Contact findContactByName(@Param("n") String name);
----

+

在幕后，使用`AnnotationParameterNameDiscoverer`实现的这种使用可以被自定义为支持任何指定注释的value属性。

* 如果使用JDK 8使用-parameters参数编译源文件，并且正在使用Spring 4+，则使用标准的JDK反射API来发现参数名称。
这适用于类和接口。

* 最后，如果代码是使用调试符号编译的，则参数名称将使用调试符号发现。
这对接口不起作用，因为它们没有关于参数名称的调试信息。
对于接口，必须使用注释或JDK 8方法。

[[EL-预后注释-SPEL]]
--
在表达式中可以使用任何Spring-EL功能，因此您也可以访问参数的属性。
例如，如果您希望特定的方法只允许访问其用户名与联系人相匹配的用户，则可以编写
--

[source,java]
----
@PreAuthorize("#contact.name == authentication.name")
public void doSomething(Contact contact);
----

在这里，我们正在访问另一个内置表达式`authentication`，它是存储在安全上下文中的`Authentication`。
您还可以使用表达式`principal`直接访问其"principal"属性。
该值通常是`UserDetails`实例，因此您可以使用表达式`principal.username`或`principal.enabled`。

[[EL-预后注释-交]]
--
通常情况下，您可能希望在调用该方法后执行访问控制检查。
这可以使用`@PostAuthorize`注释来实现。
要从方法访问返回值，请使用表达式中的内置名称`returnObject`。
--

===== 使用@PreFilter和@PostFilter进行过滤
正如您可能已经知道的那样，Spring Security支持对集合和数组进行过滤，现在可以使用表达式来实现这一点。
这通常是对方法的返回值执行的。
例如：

[source,java]
----
@PreAuthorize("hasRole('USER')")
@PostFilter("hasPermission(filterObject, 'read') or hasPermission(filterObject, 'admin')")
public List<Contact> getAll();
----

当使用`@PostFilter`注释时，Spring Security遍历返回的集合并移除提供的表达式为false的所有元素。
名称`filterObject`引用集合中的当前对象。
您也可以在方法调用之前使用`@PreFilter`进行过滤，尽管这是一种不太常见的要求。
语法相同，但如果有多个参数是集合类型，则必须使用此批注的`filterTarget`属性通过名称选择一个参数。

请注意，过滤显然不能替代您的数据检索查询。
如果您要过滤大量集合并删除很多条目，那么这可能效率不高。


[[el-method-built-in]]
==== 内置表达式
有一些特定于方法安全的内置表达式，我们已经在上面看到了这些内置表达式。
`filterTarget`和`returnValue`值非常简单，但使用`hasPermission()`表达式需要仔细观察。


[[el-permission-evaluator]]
=====  PermissionEvaluator接口
`hasPermission()`表达式被委派给`PermissionEvaluator`的一个实例。
它旨在桥接表达式系统和Spring Security的ACL系统，允许您根据抽象权限指定域对象的授权约束。
它对ACL模块没有明确的依赖关系，所以如果需要的话，你可以将它交换出来用于替代实现。
界面有两种方法：

[source,java]
----
boolean hasPermission(Authentication authentication, Object targetDomainObject,
							Object permission);

boolean hasPermission(Authentication authentication, Serializable targetId,
							String targetType, Object permission);
----

它直接映射到表达式的可用版本，但不提供第一个参数（`Authentication`对象）。
第一种用于已经加载访问控制的域对象的情况。
然后，如果当前用户具有该对象的给定权限，表达式将返回true。
第二个版本用于未加载对象但标识符已知的情况。
还需要域对象的抽象"type"说明符，以允许加载正确的ACL权限。
传统上，这是对象的Java类，但不一定要与加载权限的方式一致。

要使用`hasPermission()`表达式，您必须在应用程序上下文中显式配置`PermissionEvaluator`。
这看起来像这样：

[source,xml]
----
<security:global-method-security pre-post-annotations="enabled">
<security:expression-handler ref="expressionHandler"/>
</security:global-method-security>

<bean id="expressionHandler" class=
"org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler">
	<property name="permissionEvaluator" ref="myPermissionEvaluator"/>
</bean>
----

`myPermissionEvaluator`是实现`PermissionEvaluator`的bean。
通常这将是来自名为`AclPermissionEvaluator`的ACL模块的实现。
有关更多详细信息，请参阅"Contacts"示例应用程序配置。

===== 方法安全元注释

您可以使用元注释来进行方法安全性，以使您的代码更具可读性。
如果您发现在整个代码库中重复相同的复杂表达式，这一点尤其方便。
例如，请考虑以下几点：

[source,java]
----
@PreAuthorize("#contact.name == authentication.name")
----

我们可以创建一个可用来代替的元注释，而不是随处重复。

[source,java]
----
@Retention(RetentionPolicy.RUNTIME)
@PreAuthorize("#contact.name == authentication.name")
public @interface ContactPermission {}
----

元注释可用于任何Spring Security方法安全注释。
为了保持与规范兼容，JSR-250注释不支持元注释。

