
[[secure-object-impls]]
== 安全对象实现

[[aop-alliance]]
===  AOP联盟（MethodInvocation）安全拦截器
在Spring Security 2.0之前，安全`MethodInvocation`需要相当多的锅炉配置。
现在推荐的方法安全方法是使用<<ns-method-security,namespace configuration>>。
这样方法安全基础结构bean就会自动为您配置，因此您并不需要了解实现类。
我们只是简单介绍一下这里涉及的类。

使用保证`MethodInvocation`的{​​{0}}实施的方法安全性。
根据配置方法，拦截器可能特定于单个bean或在多个bean之间共享。
拦截器使用`MethodSecurityMetadataSource`实例来获取适用于特定方法调用的配置属性。
`MapBasedMethodSecurityMetadataSource`用于存储由方法名称（可以通配符）键入的配置属性，并且在应用上下文中使用`<intercept-methods>`或`<protect-point>`元素定义属性时将在内部使用。
其他实现将用于处理基于注释的配置。

==== 显式MethodSecurityInterceptor配置
您当然可以在应用程序上下文中直接配置`MethodSecurityIterceptor`，以便与Spring AOP的代理机制一起使用：

[source,xml]
----

<bean id="bankManagerSecurity" class=
	"org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor">
<property name="authenticationManager" ref="authenticationManager"/>
<property name="accessDecisionManager" ref="accessDecisionManager"/>
<property name="afterInvocationManager" ref="afterInvocationManager"/>
<property name="securityMetadataSource">
	<sec:method-security-metadata-source>
	<sec:protect method="com.mycompany.BankManager.delete*" access="ROLE_SUPERVISOR"/>
	<sec:protect method="com.mycompany.BankManager.getBalance" access="ROLE_TELLER,ROLE_SUPERVISOR"/>
	</sec:method-security-metadata-source>
</property>
</bean>
----

[[aspectj]]
===  AspectJ（JoinPoint）安全拦截器
AspectJ安全拦截器与上一节讨论的AOP联盟安全拦截器非常相似。
事实上，我们只会讨论本节的不同之处。

AspectJ拦截器被命名为`AspectJSecurityInterceptor`。
与依靠Spring应用程序上下文通过代理编织安全拦截器的AOP Alliance安全拦截器不同，通过AspectJ编译器编译`AspectJSecurityInterceptor`。
在同一个应用程序中使用两种类型的安全拦截器并不少见，`AspectJSecurityInterceptor`用于域对象实例安全性，而AOP联盟`MethodSecurityInterceptor`用于服务层安全性。

我们首先考虑如何在Spring应用程序上下文中配置`AspectJSecurityInterceptor`：


[source,xml]
----

<bean id="bankManagerSecurity" class=
	"org.springframework.security.access.intercept.aspectj.AspectJMethodSecurityInterceptor">
<property name="authenticationManager" ref="authenticationManager"/>
<property name="accessDecisionManager" ref="accessDecisionManager"/>
<property name="afterInvocationManager" ref="afterInvocationManager"/>
<property name="securityMetadataSource">
	<sec:method-security-metadata-source>
	<sec:protect method="com.mycompany.BankManager.delete*" access="ROLE_SUPERVISOR"/>
	<sec:protect method="com.mycompany.BankManager.getBalance" access="ROLE_TELLER,ROLE_SUPERVISOR"/>
	</sec:method-security-metadata-source>
</property>
</bean>
----


如您所见，除了课程名称外，`AspectJSecurityInterceptor`与AOP Alliance安全拦截器完全相同。
事实上，两个拦截器可以共享`securityMetadataSource`，因为`SecurityMetadataSource`与`java.lang.reflect.Method`协同工作，而不是AOP库特定的类。
当然，您的访问决策可以访问相关的AOP库特定的调用（例如`MethodInvocation`或`JoinPoint`），因此在进行访问决策时可以考虑一系列的附加标准（如方法参数） 。

接下来，您需要定义一个AspectJ `aspect`。
例如：


[source,java]
----

package org.springframework.security.samples.aspectj;

import org.springframework.security.access.intercept.aspectj.AspectJSecurityInterceptor;
import org.springframework.security.access.intercept.aspectj.AspectJCallback;
import org.springframework.beans.factory.InitializingBean;

public aspect DomainObjectInstanceSecurityAspect implements InitializingBean {

	private AspectJSecurityInterceptor securityInterceptor;

	pointcut domainObjectInstanceExecution(): target(PersistableEntity)
		&& execution(public * *(..)) && !within(DomainObjectInstanceSecurityAspect);

	Object around(): domainObjectInstanceExecution() {
		if (this.securityInterceptor == null) {
			return proceed();
		}

		AspectJCallback callback = new AspectJCallback() {
			public Object proceedWithObject() {
				return proceed();
			}
		};

		return this.securityInterceptor.invoke(thisJoinPoint, callback);
	}

	public AspectJSecurityInterceptor getSecurityInterceptor() {
		return securityInterceptor;
	}

	public void setSecurityInterceptor(AspectJSecurityInterceptor securityInterceptor) {
		this.securityInterceptor = securityInterceptor;
	}

	public void afterPropertiesSet() throws Exception {
		if (this.securityInterceptor == null)
			throw new IllegalArgumentException("securityInterceptor required");
		}
	}
}
----


在上面的示例中，安全拦截器将应用于`PersistableEntity`的每个实例，这是一个未显示的抽象类（您可以使用任何其他类或`pointcut`表达式）。
对于那些好奇的人来说，需要`AspectJCallback`，因为`proceed();`语句仅在`around()`正文中具有特殊含义。
`AspectJSecurityInterceptor`在需要目标对象继续时调用这个匿名`AspectJCallback`类。

您将需要配置Spring以加载该方面并将其与`AspectJSecurityInterceptor`连接起来。
下面显示了实现这一点的bean声明：


[source,xml]
----

<bean id="domainObjectInstanceSecurityAspect"
	class="security.samples.aspectj.DomainObjectInstanceSecurityAspect"
	factory-method="aspectOf">
<property name="securityInterceptor" ref="bankManagerSecurity"/>
</bean>
----


而已！
现在，您可以使用您认为合适的任何方式（例如`new Person();`）从应用程序中的任何位置创建bean，并且它们将应用安全拦截器。
