

[[cas]]
==  CAS认证

[[cas-overview]]
=== 概述
JA-SIG在企业范围内生成一个称为CAS的单一登录系统。
与其他举措不同，JA-SIG的中央身份验证服务是开源的，广泛使用，易于理解，独立于平台，并且支持代理功能。
Spring Security完全支持CAS，并提供了从Spring Security的单应用部署到由企业级CAS服务器保护的多应用部署的简单迁移路径。

你可以在http://www.ja-sig.org/cas上了解更多关于CAS的知识。
您还需要访问此网站以下载CAS服务器文件。

[[cas-how-it-works]]
===  CAS的工作原理
虽然CAS网站包含详细介绍CAS体系结构的文档，但我们在Spring Security的上下文中再次提供总体概述。
Spring Security 3.x支持CAS 3。
在撰写本文时，CAS服务器版本为3.4。

您的企业中某处需要安装CAS服务器。
CAS服务器只是一个标准的WAR文件，因此设置服务器没有任何困难。
在WAR文件中，您将自定义向用户显示的页面上的登录和其他单点登录。

部署CAS 3.4服务器时，还需要在CAS中包含的`deployerConfigContext.xml`中指定`AuthenticationHandler`。
`AuthenticationHandler`有一个简单的方法，它返回一个布尔值，以确定给定的一组凭证是否有效。
您的`AuthenticationHandler`实现需要链接到某种类型的后端身份验证存储库，例如LDAP服务器或数据库。
CAS本身包含许多`AuthenticationHandler`来协助完成此操作。
当您下载并部署服务器war文件时，它将被设置为成功验证输入与其用户名相匹配的密码的用户，这对测试非常有用。

除CAS服务器本身之外，其他关键角色当然是在整个企业中部署的安全Web应用程序。
这些Web应用程序被称为"services"。
有三种类型的服务。
那些对服务票据进行身份验证的服务，可以获得代理票据的服务和对代理票据进行身份验证的服务。
验证代理票据的方式不同，因为代理列表必须经过验证，并且通常可以重新使用代理票证。


[[cas-sequence]]
====  Spring Security和CAS交互序列
Web浏览器，CAS服务器和Spring安全保护服务之间的基本交互如下所示：

* 网络用户正在浏览服务的公共页面。
不涉及CAS或Spring Security。
* 用户最终会请求一个安全的页面或者它使用的其中一个安全的页面。
Spring Security的`ExceptionTranslationFilter`将检测`AccessDeniedException`或`AuthenticationException`。
* 由于用户的`Authentication`对象（或缺少）导致`AuthenticationException`，因此`ExceptionTranslationFilter`将调用配置的`AuthenticationEntryPoint`。
如果使用CAS，这将是`CasAuthenticationEntryPoint`类。
*  `CasAuthenticationEntryPoint`将用户的浏览器重定向到CAS服务器。
它还会指示一个`service`参数，它是Spring Security服务（您的应用程序）的回调URL。
例如，浏览器重定向到的URL可能是https://my.company.com/cas/login?service=https%3A%2F%2Fserver3.company.com%2Fwebapp%2Flogin/cas。
* 用户的浏览器重定向到CAS后，系统会提示他们输入用户名和密码。
如果用户提交了一个表明他们以前登录过的会话cookie，他们将不会再被提示重新登录（这个过程有一个例外，我们将在后面介绍）。
如果使用CAS 3.0，CAS将使用`PasswordHandler`（或`AuthenticationHandler`）来决定用户名和密码是否有效。
* 成功登录后，CAS会将用户的浏览器重定向回原始服务。
它还将包含一个`ticket`参数，该参数是代表"service ticket"的不透明字符串。
继续我们前面的例子，浏览器重定向到的URL可能是https://server3.company.com/webapp/login/cas?ticket=ST-0-ER94xMJmn6pha35CQRoZ。
* 回到服务Web应用程序，`CasAuthenticationFilter`始终监听`/login/cas`的请求（这是可配置的，但我们将使用此介绍中的默认值）。
处理过滤器将构建表示服务票证的`UsernamePasswordAuthenticationToken`。
委托人将等于`CasAuthenticationFilter.CAS_STATEFUL_IDENTIFIER`，而凭证将是服务票证不透明值。
此认证请求将交给配置的`AuthenticationManager`。
*  `AuthenticationManager`的实现将是`ProviderManager`，而`ProviderManager`将依次配置`CasAuthenticationProvider`。
`CasAuthenticationProvider`仅响应包含特定于CAS的主体（如`CasAuthenticationFilter.CAS_STATEFUL_IDENTIFIER`）和`CasAuthenticationToken`（稍后讨论）的`UsernamePasswordAuthenticationToken`。
*  `CasAuthenticationProvider`将使用`TicketValidator`实施验证服务票证。
这通常是`Cas20ServiceTicketValidator`，它是包含在CAS客户端库中的类之一。
如果应用程序需要验证代理票证，则使用`Cas20ProxyTicketValidator`。
`TicketValidator`向CAS服务器发出HTTPS请求以验证服务票据。
它也可能包含一个代理回调URL，它包含在此示例中：https://my.company.com/cas/proxyValidate?service=https%3A%2F%2Fserver3.company.com%2Fwebapp%2Flogin/cas&ticket= ST-0-ER94xMJmn6pha35CQRoZ＆pgtUrl = HTTPS：//server3.company.com/webapp/login/cas/proxyreceptor。
* 返回CAS服务器，将收到验证请求。
如果所提供的服务票据与发行票据的服务URL相匹配，则CAS将以XML表示用户名的肯定响应。
如果任何代理参与了身份验证（如下所述），则代理列表也会包含在XML响应中。
*  [可选]如果对CAS验证服务的请求包含代理回调URL（位于`pgtUrl`参数中），CAS将在XML响应中包含一个`pgtIou`字符串。
此`pgtIou`表示代理授予凭单IOU。
然后，CAS服务器将创建自己的HTTPS连接回到`pgtUrl`。
这是为了相互认证CAS服务器和声称的服务URL。
HTTPS连接将用于向原始Web应用程序发送授予票证的代理。
例如，https://server3.company.com/webapp/login/cas/proxyreceptor?pgtIou=PGTIOU-0-R0zlgrl4pdAQwBvJWO3vnNpevwqStbSGcq3vKB2SqSFFRnjPHt&pgtId=PGT-1-si9YkkHLrtACBo64rmsi3v2nf7cpCResXg5MpESZFArbaZiOKH。
*  `Cas20TicketValidator`将解析从CAS服务器收到的XML。
它将返回到`CasAuthenticationProvider` a `TicketResponse`，其中包括用户名（必填），代理列表（如果有任何参与）和代理授予票证IOU（如果请求代理回调）。
* 下一步`CasAuthenticationProvider`将调用配置的`CasProxyDecider`。
`CasProxyDecider`指示服务是否接受`TicketResponse`中的代理列表。
Spring Security提供了几个实现：`RejectProxyTickets`，`AcceptAnyCasProxy`和`NamedCasProxyDecider`。
这些名称在很大程度上不言自明，除了`NamedCasProxyDecider`允许提供`List`个可信代理之外。
接下来*  `CasAuthenticationProvider`将请求`AuthenticationUserDetailsService`加载适用于`Assertion`中包含的用户的`GrantedAuthority`个对象。
* 如果没有问题，`CasAuthenticationProvider`会构建`CasAuthenticationToken`，其中包含`TicketResponse`和``GrantedAuthority``中包含的详细信息。
* 然后控件返回到`CasAuthenticationFilter`，这将创建的`CasAuthenticationToken`放置在安全上下文中。
* 用户的浏览器被重定向到导致`AuthenticationException`（或取决于配置的<<form-login-flow-handling,custom destination>>）的原始页面。

很高兴你仍然在这里！
现在让我们看看这是如何配置的

[[cas-client]]
===  CAS客户端的配置
由于Spring Security的原因，CAS的Web应用程序变得非常简单。
假设你已经知道了使用Spring Security的基础知识，所以下面不再介绍。
我们假设正在使用基于名称空间的配置，并根据需要添加CAS bean。
每节都建立在前一节的基础上。
完整的<<cas-sample,CAS sample application>>可以在Spring Security示例中找到。


[[cas-st]]
==== 服务票据验证
本节介绍如何设置Spring Security来验证服务票证。
通常这都是一个Web应用程序需要的。
您将需要向应用程序上下文添加一个`ServiceProperties` bean。
这代表您的CAS服务：

[source,xml]
----
<bean id="serviceProperties"
	class="org.springframework.security.cas.ServiceProperties">
<property name="service"
	value="https://localhost:8443/cas-sample/login/cas"/>
<property name="sendRenew" value="false"/>
</bean>
----

`service`必须等于由`CasAuthenticationFilter`监控的网址。
`sendRenew`默认为false，但如果您的应用程序特别敏感，则应将其设置为true。
该参数的作用是告诉CAS登录服务，登录时的单一登录是不可接受的。
相反，用户需要重新输入用户名和密码才能访问该服务。

应配置以下bean以启动CAS认证过程（假设您使用的是名称空间配置）：

[source,xml]
----
<security:http entry-point-ref="casEntryPoint">
...
<security:custom-filter position="CAS_FILTER" ref="casFilter" />
</security:http>

<bean id="casFilter"
	class="org.springframework.security.cas.web.CasAuthenticationFilter">
<property name="authenticationManager" ref="authenticationManager"/>
</bean>

<bean id="casEntryPoint"
	class="org.springframework.security.cas.web.CasAuthenticationEntryPoint">
<property name="loginUrl" value="https://localhost:9443/cas/login"/>
<property name="serviceProperties" ref="serviceProperties"/>
</bean>
----

要使CAS运行，`ExceptionTranslationFilter`必须将其`authenticationEntryPoint`属性设置为`CasAuthenticationEntryPoint` bean。
这可以使用<<ns-entry-point-ref,entry-point-ref>>轻松完成，如上例所示。
`CasAuthenticationEntryPoint`必须引用上面讨论的`ServiceProperties` bean，它提供了企业CAS登录服务器的URL。
这是用户的浏览器将被重定向的地方。

`CasAuthenticationFilter`与`UsernamePasswordAuthenticationFilter`（用于基于表单的登录）具有非常相似的属性。
您可以使用这些属性来自定义诸如认证成功和失败的行为。

接下来，您需要添加一个`CasAuthenticationProvider`及其合作者：

[source,xml]
----
<security:authentication-manager alias="authenticationManager">
<security:authentication-provider ref="casAuthenticationProvider" />
</security:authentication-manager>

<bean id="casAuthenticationProvider"
	class="org.springframework.security.cas.authentication.CasAuthenticationProvider">
<property name="authenticationUserDetailsService">
	<bean class="org.springframework.security.core.userdetails.UserDetailsByNameServiceWrapper">
	<constructor-arg ref="userService" />
	</bean>
</property>
<property name="serviceProperties" ref="serviceProperties" />
<property name="ticketValidator">
	<bean class="org.jasig.cas.client.validation.Cas20ServiceTicketValidator">
	<constructor-arg index="0" value="https://localhost:9443/cas" />
	</bean>
</property>
<property name="key" value="an_id_for_this_auth_provider_only"/>
</bean>

<security:user-service id="userService">
<!-- Password is prefixed with {noop} to indicate to DelegatingPasswordEncoder that
NoOpPasswordEncoder should be used.
This is not safe for production, but makes reading
in samples easier.
Normally passwords should be hashed using BCrypt -->
<security:user name="joe" password="{noop}joe" authorities="ROLE_USER" />
...
</security:user-service>
----

`CasAuthenticationProvider`使用`UserDetailsService`实例为用户加载权限，一旦它们通过了CAS的认证。
我们在这里展示了一个简单的内存设置。
请注意，`CasAuthenticationProvider`实际上并未使用密码进行身份验证，但它确实使用了权限。

如果您重新参考<<cas-how-it-works,How CAS Works>>部分，这些bean都是不言自明的。

这完成了CAS的最基本配置。
如果您没有犯任何错误，您的Web应用程序应该在CAS单一登录框架内愉快地工作。
Spring Security的其他部分不需要担心CAS处理身份验证的事实。
在下面的章节中，我们将讨论一些（可选的）更高级的配置。


[[cas-singlelogout]]
==== 单次注销
CAS协议支持Single Logout，可以很容易地添加到Spring Security配置中。
以下是处理Single Logout的Spring Security配置的更新

[source,xml]
----
<security:http entry-point-ref="casEntryPoint">
...
<security:logout logout-success-url="/cas-logout.jsp"/>
<security:custom-filter ref="requestSingleLogoutFilter" before="LOGOUT_FILTER"/>
<security:custom-filter ref="singleLogoutFilter" before="CAS_FILTER"/>
</security:http>

<!-- This filter handles a Single Logout Request from the CAS Server -->
<bean id="singleLogoutFilter" class="org.jasig.cas.client.session.SingleSignOutFilter"/>

<!-- This filter redirects to the CAS Server to signal Single Logout should be performed -->
<bean id="requestSingleLogoutFilter"
	class="org.springframework.security.web.authentication.logout.LogoutFilter">
<constructor-arg value="https://localhost:9443/cas/logout"/>
<constructor-arg>
	<bean class=
		"org.springframework.security.web.authentication.logout.SecurityContextLogoutHandler"/>
</constructor-arg>
<property name="filterProcessesUrl" value="/logout/cas"/>
</bean>
----

`logout`元素将用户从本地应用程序中注销，但不会终止与CAS服务器或任何其他已登录的应用程序的会话。
`requestSingleLogoutFilter`过滤器将允许请求`/spring_security_cas_logout`的URL将应用程序重定向到配置的CAS服务器注销URL。
然后，CAS服务器将向所有登录的服务发送单一注销请求。
`singleLogoutFilter`通过在静态`Map`中查找`HttpSession`处理单一注销请求，然后使其无效。

这可能会令人困惑，为什么需要`logout`元素和`singleLogoutFilter`。
由于`SingleSignOutFilter`仅将`HttpSession`存储在静态`Map`中以便对其调用invalidate，因此首先在本地注销是最佳做法。
使用上面的配置，注销流程将是：

* 用户请求`/logout`将用户登录到本地应用程序，并将用户发送到注销成功页面。
* 注销成功页面`/cas-logout.jsp`应指示用户单击指向`/logout/cas`的链接，以注销所有应用程序。
* 当用户点击链接时，用户被重定向到CAS单一注销URL（https：// localhost：9443 / cas / logout）。
* 在CAS服务器端，CAS单一注销URL然后向所有CAS服务提交单一注销请求。
在CAS服务方面，JASIG的`SingleSignOutFilter`通过使原始会话无效来处理注销请求。



下一步是将以下内容添加到您的web.xml中

[source,xml]
----
<filter>
<filter-name>characterEncodingFilter</filter-name>
<filter-class>
	org.springframework.web.filter.CharacterEncodingFilter
</filter-class>
<init-param>
	<param-name>encoding</param-name>
	<param-value>UTF-8</param-value>
</init-param>
</filter>
<filter-mapping>
<filter-name>characterEncodingFilter</filter-name>
<url-pattern>/*</url-pattern>
</filter-mapping>
<listener>
<listener-class>
	org.jasig.cas.client.session.SingleSignOutHttpSessionListener
</listener-class>
</listener>
----

在使用SingleSignOutFilter时，您可能会遇到一些编码问题。
因此，建议在使用`SingleSignOutFilter`时添加`CharacterEncodingFilter`以确保字符编码正确。
有关详细信息，请再次参阅JASIG的文档。
`SingleSignOutHttpSessionListener`确保当`HttpSession`过期时，用于单次注销的映射将被删除。


[[cas-pt-client]]
==== 使用CAS对无状态服务进行身份验证
本节介绍如何使用CAS对服务进行身份验证。
换句话说，本节讨论如何设置使用CAS认证的服务的客户端。
下一节将介绍如何设置无状态服务以使用CAS进行身份验证。


[[cas-pt-client-config]]
===== 配置CAS以获取代理授予票证
为了向无状态服务进行身份验证，应用程序需要获取代理授予票证（PGT）。
本节介绍如何配置Spring Security以获取PGT构建基于[Service Ticket Authentication]配置。

第一步是在您的Spring Security配置中包含`ProxyGrantingTicketStorage`。
这用于存储由`CasAuthenticationFilter`获得的PGT，以便它们可用于获取代理票证。
示例配置如下所示

[source,xml]
----
<!--
NOTE: In a real application you should not use an in memory implementation.
You will also want to ensure to clean up expired tickets by calling
ProxyGrantingTicketStorage.cleanup()
-->
<bean id="pgtStorage" class="org.jasig.cas.client.proxy.ProxyGrantingTicketStorageImpl"/>
----

下一步是更新`CasAuthenticationProvider`以获取代理票证。
为此，请将`Cas20ServiceTicketValidator`替换为`Cas20ProxyTicketValidator`。
应将`proxyCallbackUrl`设置为该应用程序将收到PGT的URL。
最后，配置还应引用`ProxyGrantingTicketStorage`，以便它可以使用PGT来获取代理票证。
您可以在下面找到一个配置更改的示例。

[source,xml]
----
<bean id="casAuthenticationProvider"
	class="org.springframework.security.cas.authentication.CasAuthenticationProvider">
...
<property name="ticketValidator">
	<bean class="org.jasig.cas.client.validation.Cas20ProxyTicketValidator">
	<constructor-arg value="https://localhost:9443/cas"/>
		<property name="proxyCallbackUrl"
		value="https://localhost:8443/cas-sample/login/cas/proxyreceptor"/>
	<property name="proxyGrantingTicketStorage" ref="pgtStorage"/>
	</bean>
</property>
</bean>
----

最后一步是更新`CasAuthenticationFilter`以接受PGT并将它们存储在`ProxyGrantingTicketStorage`中。
`proxyReceptorUrl`与`Cas20ProxyTicketValidator`的`proxyCallbackUrl`匹配非常重要。
示例配置如下所示。

[source,xml]
----

<bean id="casFilter"
		class="org.springframework.security.cas.web.CasAuthenticationFilter">
	...
	<property name="proxyGrantingTicketStorage" ref="pgtStorage"/>
	<property name="proxyReceptorUrl" value="/login/cas/proxyreceptor"/>
</bean>

----

[[cas-pt-client-sample]]
===== 使用代理票证调用无状态服务
现在Spring Security获得PGT，您可以使用它们来创建可用于向无状态服务进行身份验证的代理票证。
<<cas-sample,CAS sample application>>在`ProxyTicketSampleServlet`中包含一个工作示例。
示例代码可以在下面找到：

[source,java]
----
protected void doGet(HttpServletRequest request, HttpServletResponse response)
	throws ServletException, IOException {
// NOTE: The CasAuthenticationToken can also be obtained using
// SecurityContextHolder.getContext().getAuthentication()
final CasAuthenticationToken token = (CasAuthenticationToken) request.getUserPrincipal();
// proxyTicket could be reused to make calls to the CAS service even if the
// target url differs
final String proxyTicket = token.getAssertion().getPrincipal().getProxyTicketFor(targetUrl);

// Make a remote call using the proxy ticket
final String serviceUrl = targetUrl+"?ticket="+URLEncoder.encode(proxyTicket, "UTF-8");
String proxyResponse = CommonUtils.getResponseFromServer(serviceUrl, "UTF-8");
...
}
----

[[cas-pt]]
==== 代理券验证
`CasAuthenticationProvider`区分有状态客户和无状态客户。
有状态的客户端被认为是提交给`CasAuthenticationFilter`的{​​{0}}的任何客户端。
无状态客户端是指向`filterProcessUrl`以外的网址向`CasAuthenticationFilter`提交身份验证请求的任何客户端。

因为远程协议无法在`HttpSession`的上下文中呈现自己，所以不可能依赖于在请求之间的会话中存储安全上下文的默认实践。
此外，由于CAS服务器在`TicketValidator`验证后使服务器失效，因此在后续请求中呈现相同的代理服务器故障将不起作用。

一个显而易见的选择是远程协议客户端根本不使用CAS。
但是，这将消除CAS的许多理想功能。
作为中间地带，`CasAuthenticationProvider`使用`StatelessTicketCache`。
这仅用于使用等于`CasAuthenticationFilter.CAS_STATELESS_IDENTIFIER`的主体的无状态客户端。
发生什么情况是`CasAuthenticationProvider`将结果`CasAuthenticationToken`存储在`StatelessTicketCache`中，并以代理票据为关键字。
因此，远程协议客户端可以呈现相同的代理票证，`CasAuthenticationProvider`不需要联系CAS服务器进行验证（除第一个请求外）。
一旦通过身份验证，代理票证就可以用于原始目标服务以外的URL。

本部分构建在前面的部分以适应代理票证认证。
第一步是指定验证所有工件，如下所示。

[source,xml]
----
<bean id="serviceProperties"
	class="org.springframework.security.cas.ServiceProperties">
...
<property name="authenticateAllArtifacts" value="true"/>
</bean>
----

下一步是为`CasAuthenticationFilter`指定`serviceProperties`和`authenticationDetailsSource`。
`serviceProperties`属性指示`CasAuthenticationFilter`尝试验证所有工件，而不是只验证`filterProcessUrl`中的工件。
`ServiceAuthenticationDetailsSource`创建一个`ServiceAuthenticationDetails`，以确保基于`HttpServletRequest`的当前URL在验证票证时用作服务URL。
可以通过注入返回自定义`ServiceAuthenticationDetails`的自定义`AuthenticationDetailsSource`来定制生成服务URL的方法。

[source,xml]
----
<bean id="casFilter"
	class="org.springframework.security.cas.web.CasAuthenticationFilter">
...
<property name="serviceProperties" ref="serviceProperties"/>
<property name="authenticationDetailsSource">
	<bean class=
	"org.springframework.security.cas.web.authentication.ServiceAuthenticationDetailsSource">
	<constructor-arg ref="serviceProperties"/>
	</bean>
</property>
</bean>
----

您还需要更新`CasAuthenticationProvider`以处理代理票证。
为此，请将`Cas20ServiceTicketValidator`替换为`Cas20ProxyTicketValidator`。
您需要配置`statelessTicketCache`以及您想要接受的代理。
您可以在下面找到接受所有代理所需更新的示例。

[source,xml]
----

<bean id="casAuthenticationProvider"
	class="org.springframework.security.cas.authentication.CasAuthenticationProvider">
...
<property name="ticketValidator">
	<bean class="org.jasig.cas.client.validation.Cas20ProxyTicketValidator">
	<constructor-arg value="https://localhost:9443/cas"/>
	<property name="acceptAnyProxy" value="true"/>
	</bean>
</property>
<property name="statelessTicketCache">
	<bean class="org.springframework.security.cas.authentication.EhCacheBasedTicketCache">
	<property name="cache">
		<bean class="net.sf.ehcache.Cache"
			init-method="initialise" destroy-method="dispose">
		<constructor-arg value="casTickets"/>
		<constructor-arg value="50"/>
		<constructor-arg value="true"/>
		<constructor-arg value="false"/>
		<constructor-arg value="3600"/>
		<constructor-arg value="900"/>
		</bean>
	</property>
	</bean>
</property>
</bean>
----
