

[[concurrency]]
== 并发支持

在大多数环境中，安全性是按照`Thread`存储的。
这意味着在新的`Thread`上完成工作时，`SecurityContext`将丢失。
Spring Security提供了一些基础设施来帮助用户更容易。
Spring Security在多线程环境中为Spring Security提供低级抽象。
事实上，这就是Spring Security与<<servletapi-start-runnable>>和<<mvc-async>>集成的基础。

===  DelegatingSecurityContextRunnable

Spring Security的并发支持中最基本的构建块之一是`DelegatingSecurityContextRunnable`。
它包装委托`Runnable`，以便为委托初始化具有指定`SecurityContext`的`SecurityContextHolder`。
然后调用委托Runnable，确保事后清除{{0}。
`DelegatingSecurityContextRunnable`看起来像这样：

[source,java]
----
public void run() {
try {
	SecurityContextHolder.setContext(securityContext);
	delegate.run();
} finally {
	SecurityContextHolder.clearContext();
}
}
----

虽然非常简单，但它可以将SecurityContext从一个线程转移到另一个线程。
这很重要，因为在大多数情况下，SecurityContextHolder是以每个线程为基础进行操作的。
例如，您可能使用了Spring Security的<<nsa-global-method-security>>支持来保护您的某项服务。
您现在可以轻松地将当前`Thread`的{​​{0}}传输到调用安全服务的`Thread`。
下面是您可以如何做到这一点的一个例子：

[source,java]
----
Runnable originalRunnable = new Runnable() {
public void run() {
	// invoke secured service
}
};

SecurityContext context = SecurityContextHolder.getContext();
DelegatingSecurityContextRunnable wrappedRunnable =
	new DelegatingSecurityContextRunnable(originalRunnable, context);

new Thread(wrappedRunnable).start();
----

上面的代码执行以下步骤：

* 创建一个将调用我们的安全服务的`Runnable`。
注意它不知道Spring Security
* 获得我们希望从`SecurityContextHolder`使用的`SecurityContext`并初始化`DelegatingSecurityContextRunnable`
* 使用`DelegatingSecurityContextRunnable`创建一个线程
* 开始我们创建的主题

由于从`SecurityContextHolder`创建带有`SecurityContext`的{​​{0}}是很常见的，因此它有一个快捷构造器。
以下代码与上面的代码相同：


[source,java]
----
Runnable originalRunnable = new Runnable() {
public void run() {
	// invoke secured service
}
};

DelegatingSecurityContextRunnable wrappedRunnable =
	new DelegatingSecurityContextRunnable(originalRunnable);

new Thread(wrappedRunnable).start();
----

我们所使用的代码很容易使用，但它仍然需要我们使用Spring Security的知识。
在下一节中，我们将看看如何利用`DelegatingSecurityContextExecutor`来隐藏我们使用Spring Security的事实。

===  DelegatingSecurityContextExecutor

在上一节中，我们发现很容易使用`DelegatingSecurityContextRunnable`，但它并不理想，因为我们必须了解Spring Security才能使用它。
我们来看看`DelegatingSecurityContextExecutor`如何将我们的代码屏蔽掉我们使用Spring Security的任何知识。

`DelegatingSecurityContextExecutor`的设计与`DelegatingSecurityContextRunnable`非常相似，只是它接受委托`Executor`而不是委托`Runnable`。
你可以在下面看到一个如何使用它的例子：


[source,java]
----
SecurityContext context = SecurityContextHolder.createEmptyContext();
Authentication authentication =
	new UsernamePasswordAuthenticationToken("user","doesnotmatter", AuthorityUtils.createAuthorityList("ROLE_USER"));
context.setAuthentication(authentication);

SimpleAsyncTaskExecutor delegateExecutor =
	new SimpleAsyncTaskExecutor();
DelegatingSecurityContextExecutor executor =
	new DelegatingSecurityContextExecutor(delegateExecutor, context);

Runnable originalRunnable = new Runnable() {
public void run() {
	// invoke secured service
}
};

executor.execute(originalRunnable);
----

该代码执行以下步骤：

* 创建`SecurityContext`用于我们的`DelegatingSecurityContextExecutor`。
请注意，在这个例子中，我们只需手工创建`SecurityContext`。
但是，无论我们在何处或如何获得`SecurityContext`（即，如果需要，我们可以从`SecurityContextHolder`获得），都无关紧要。
* 创建一个负责执行提交的``Runnable``的委托执行程序
* 最后，我们创建一个`DelegatingSecurityContextExecutor`，它负责封装用`DelegatingSecurityContextRunnable`传递给execute方法的任何Runnable。
然后它将封装的Runnable传递给delegateExecutor。
在这种情况下，将为提交给我们的`DelegatingSecurityContextExecutor`的每个Runnable使用相同的`SecurityContext`。
如果我们正在运行需要由具有提升权限的用户运行的后台任务，这很好。
* 此时，您可能会问自己"How does this shield my code of any knowledge of Spring Security?"而不是在我们自己的代码中创建`SecurityContext`和`DelegatingSecurityContextExecutor`，我们可以注入一个已经初始化的{{4 }}。

[source,java]
----
@Autowired
private Executor executor; // becomes an instance of our DelegatingSecurityContextExecutor

public void submitRunnable() {
Runnable originalRunnable = new Runnable() {
	public void run() {
	// invoke secured service
	}
};
executor.execute(originalRunnable);
}
----

现在我们的代码不知道`SecurityContext`正在传播到`Thread`，然后`originalRunnable`被执行，然后`SecurityContextHolder`被清除。
在这个例子中，正在使用同一个用户来执行每个线程。
如果我们想在我们调用`executor.execute(Runnable)`时（即当前登录的用户）使用来自`SecurityContextHolder`的用户来处理``originalRunnable``，该怎么办？
这可以通过从我们的`DelegatingSecurityContextExecutor`构造函数中删除`SecurityContext`参数来完成。
例如：


[source,java]
----
SimpleAsyncTaskExecutor delegateExecutor = new SimpleAsyncTaskExecutor();
DelegatingSecurityContextExecutor executor =
	new DelegatingSecurityContextExecutor(delegateExecutor);
----

现在，`executor.execute(Runnable)`随时执行，`SecurityContext`首先由`SecurityContextHolder`获得，然后`SecurityContext`用于创建我们的`DelegatingSecurityContextRunnable`。
这意味着我们使用与调用`executor.execute(Runnable)`代码相同的用户来执行我们的`Runnable`。

===  Spring安全性并发类

请参阅Javadoc以获取与Java并发API和Spring Task抽象的其他集成。
一旦你理解了前面的代码，它们就不言自明了。

*  DelegatingSecurityContextCallable
*  DelegatingSecurityContextExecutor
*  DelegatingSecurityContextExecutorService
*  DelegatingSecurityContextRunnable
*  DelegatingSecurityContextScheduledExecutorService
*  DelegatingSecurityContextSchedulingTaskExecutor
*  DelegatingSecurityContextAsyncTaskExecutor
*  DelegatingSecurityContextTaskExecutor
