[[crypto]]
==  Spring Security加密模块


[[spring-security-crypto-introduction]]
=== 介绍
Spring Security Crypto模块为对称加密，密钥生成和密码编码提供支持。
该代码作为核心模块的一部分进行分发，但不依赖于任何其他Spring Security（或Spring）代码。


[[spring-security-crypto-encryption]]
=== 加密器
Encryptors类提供了构造对称加密器的工厂方法。
使用这个类，您可以创建ByteEncryptors以原始字节[]形式加密数据。
您还可以构造TextEncryptors来加密文本字符串。
加密器是线程安全的。

[[spring-security-crypto-encryption-bytes]]
====  BytesEncryptor
使用Encryptors.standard工厂方法构建一个"standard" BytesEncryptor：

[source,java]
----
Encryptors.standard("password", "salt");
----

"standard"加密方法是使用PKCS＃5的PBKDF2（基于密码的密钥推导函数＃2）的256位AES。
此方法需要Java 6。
用于生成SecretKey的密码应保存在安全的地方，不要共享。
salt用于防止在加密数据被泄露的情况下对字典进行字典攻击。
一个16字节的随机初始化向量也被应用，因此每个加密的消息都是唯一的。

提供的salt应该是以十六进制编码的字符串形式，是随机的，并且长度至少为8个字节。
这种盐可以使用KeyGenerator生成：

[source,java]
----
String salt = KeyGenerators.string().generateKey(); // generates a random 8-byte salt that is then hex-encoded
----

[[spring-security-crypto-encryption-text]]
====  TextEncryptor
使用Encryptors.text工厂方法构建标准的TextEncryptor：

[source,java]
----

Encryptors.text("password", "salt");
----

TextEncryptor使用标准的BytesEncryptor来加密文本数据。
加密结果以十六进制编码字符串的形式返回，以便于在文件系统或数据库中存储。

使用Encryptors.queryableText工厂方法构建一个"queryable" TextEncryptor：

[source,java]
----
Encryptors.queryableText("password", "salt");
----

可查询TextEncryptor和标准TextEncryptor之间的区别与初始化向量（iv）处理有关。
在可查询的TextEncryptor＃encrypt操作中使用的iv是共享的，或者是常量，并且不是随机生成的。
这意味着多次加密的相同文本将始终产生相同的加密结果。
这不太安全，但对于需要查询的加密数据来说是必需的。
可查询加密文本的一个例子是一个OAuth apiKey。

[[spring-security-crypto-keygenerators]]
=== 密钥生成器
KeyGenerators类提供了许多便捷工厂方法来构建不同类型的密钥生成器。
使用这个类，你可以创建一个BytesKeyGenerator来生成byte []键。
你也可以构造一个StringKeyGenerator来生成字符串键。
KeyGenerators是线程安全的。

====  BytesKeyGenerator
使用KeyGenerators.secureRandom工厂方法生成由SecureRandom实例支持的BytesKeyGenerator：

[source,java]
----
BytesKeyGenerator generator = KeyGenerators.secureRandom();
byte[] key = generator.generateKey();
----

默认密钥长度是8个字节。
还有一个可以控制密钥长度的KeyGenerators.secureRandom变体：

[source,java]
----
KeyGenerators.secureRandom(16);
----

使用KeyGenerators.shared工厂方法构造一个BytesKeyGenerator，它总是在每次调用时返回相同的键：

[source,java]
----
KeyGenerators.shared(16);
----

====  StringKeyGenerator
使用KeyGenerators.string工厂方法构造一个8字节的SecureRandom KeyGenerator，它将每个键的字符串编码为一个字符串：

[source,java]
----
KeyGenerators.string();
----

[[spring-security-crypto-passwordencoders]]
=== 密码编码
spring-security-crypto模块的密码包提供对密码编码的支持。
`PasswordEncoder`是中央服务界面，具有以下签名：

[source,java]
----
public interface PasswordEncoder {

String encode(String rawPassword);

boolean matches(String rawPassword, String encodedPassword);
}
----

如果rawPassword一旦编码，就等于encodedPassword，则匹配方法返回true。
此方法旨在支持基于密码的身份验证方案。

`BCryptPasswordEncoder`实现使用广泛支持的"bcrypt"算法对密码进行哈希处理。
Bcrypt使用一个随机的16字节盐值，并且是故意缓慢的算法，以阻止密码破解者。
它所做的工作量可以使用值为4到31的"strength"参数进行调整。
值越高，计算散列的工作就越多。
默认值是10。
您可以在已部署的系统中更改此值，而不会影响现有密码，因为该值也存储在已编码的散列中。

[source,java]
----

// Create an encoder with strength 16
BCryptPasswordEncoder encoder = new BCryptPasswordEncoder(16);
String result = encoder.encode("myPassword");
assertTrue(encoder.matches("myPassword", result));
----

`Pbkdf2PasswordEncoder`实现使用PBKDF2算法来散列密码。
为了破解密码破解PBKDF2是一个故意缓慢的算法，应该调整大约0.5秒来验证系统上的密码。


[source,java]
----

// Create an encoder with all the defaults
Pbkdf2PasswordEncoder encoder = new Pbkdf2PasswordEncoder();
String result = encoder.encode("myPassword");
assertTrue(encoder.matches("myPassword", result));
----
