
[[jaas]]
==  Java认证和授权服务（JAAS）提供程序


=== 概述
Spring Security提供了一个能够将身份验证请求委托给Java身份验证和授权服务（JAAS）的软件包。
这个包在下面详细讨论。


[[jaas-abstractjaasauthenticationprovider]]
===  AbstractJaasAuthenticationProvider
`AbstractJaasAuthenticationProvider`是提供的JAAS `AuthenticationProvider`实现的基础。
子类必须实现一个创建`LoginContext`的方法。
`AbstractJaasAuthenticationProvider`有许多可以注入的依赖关系，下面将对此进行讨论。


[[jaas-callbackhandler]]
====  JAAS CallbackHandler
大多数JAAS `LoginModule`都需要进行某种回调。
这些回调通常用于从用户获取用户名和密码。

在Spring Security部署中，Spring Security负责此用户交互（通过身份验证机制）。
因此，在认证请求委派给JAAS时，Spring Security的认证机制将已经完全填充了`Authentication`对象，其中包含JAAS `LoginModule`所需的全部信息。

因此，Spring Security的JAAS包提供了两个默认回调处理程序`JaasNameCallbackHandler`和`JaasPasswordCallbackHandler`。
每个回调处理程序都实现`JaasAuthenticationCallbackHandler`。
在大多数情况下，这些回调处理程序可以在不理解内部机制的情况下使用。

对于需要完全控制回调行为的用户，内部`AbstractJaasAuthenticationProvider`用`InternalCallbackHandler`包装这些`JaasAuthenticationCallbackHandler`。
`InternalCallbackHandler`是实际实现JAAS普通`CallbackHandler`接口的类。
无论何时使用JAAS `LoginModule`，它都会传递一个配置应用程序上下文的列表`InternalCallbackHandler`。
如果`LoginModule`请求对`InternalCallbackHandler`进行回调，则回调将被传递给被封装的`JaasAuthenticationCallbackHandler`。


[[jaas-authoritygranter]]
JAAS AuthorityGranter ==== 
JAAS与校长合作。
甚至"roles"在JAAS中都被表示为主体。
另一方面，Spring Security使用`Authentication`对象。
每个`Authentication`对象包含一个主体和多个`GrantedAuthority`。
为了促进这些不同概念之间的映射，Spring Security的JAAS包中包含一个`AuthorityGranter`接口。

`AuthorityGranter`负责检查JAAS校长并返回一组`String`，代表分配给校长的当局。
对于每个返回的授权字符串，`AbstractJaasAuthenticationProvider`创建一个`JaasGrantedAuthority`（它实现了Spring Security的`GrantedAuthority`接口），该接口包含授权字符串和`AuthorityGranter`传递的JAAS主体。
`AbstractJaasAuthenticationProvider`通过首先使用JAAS `LoginModule`成功验证用户的凭证，然后访问它返回的`LoginContext`来获取JAAS主体。
对`LoginContext.getSubject().getPrincipals()`进行调用，并将每个结果主体传递给针对`AbstractJaasAuthenticationProvider.setAuthorityGranters(List)`属性定义的每个`AuthorityGranter`。

考虑到每个JAAS主体都具有特定于实现的含义，Spring Security不包括任何生产`AuthorityGranter`。
但是，单元测试中有一个`TestAuthorityGranter`，它演示了一个简单的`AuthorityGranter`实现。


[[jaas-defaultjaasauthenticationprovider]]
===  DefaultJaasAuthenticationProvider
`DefaultJaasAuthenticationProvider`允许将JAAS `Configuration`对象作为依赖注入到该对象中。
然后使用注入的JAAS `Configuration`创建一个`LoginContext`。
这意味着`DefaultJaasAuthenticationProvider`没有像`JaasAuthenticationProvider`那样绑定`Configuration`的任何特定实现。


[[jaas-inmemoryconfiguration]]
====  InMemoryConfiguration
为了便于`Configuration`注入`DefaultJaasAuthenticationProvider`，提供了名为`InMemoryConfiguration`的默认内存中实现。
实现构造函数接受`Map`，其中每个键表示登录配置名称，值表示`AppConfigurationEntry`的`Array`。
`InMemoryConfiguration`还支持`AppConfigurationEntry`对象的默认`Array`，如果未在所提供的`Map`内找到映射，则将使用该对象。
有关详细信息，请参阅`InMemoryConfiguration`的类级别javadoc。


[[jaas-djap-config]]
====  DefaultJaasAuthenticationProvider示例配置
尽管`InMemoryConfiguration`的Spring配置可能比标准JAAS配置文件更详细，但与`DefaultJaasAuthenticationProvider`结合使用会比`JaasAuthenticationProvider`更灵活，因为它不依赖于默认的{{3 }}实现。

下面提供了使用`InMemoryConfiguration`的{​​{0}}的示例配置。
请注意，`Configuration`的自定义实现也可以很容易地注入到`DefaultJaasAuthenticationProvider`中。


[source,xml]
----

<bean id="jaasAuthProvider"
class="org.springframework.security.authentication.jaas.DefaultJaasAuthenticationProvider">
<property name="configuration">
<bean class="org.springframework.security.authentication.jaas.memory.InMemoryConfiguration">
<constructor-arg>
	<map>
	<!--
	SPRINGSECURITY is the default loginContextName
	for AbstractJaasAuthenticationProvider
	-->
	<entry key="SPRINGSECURITY">
	<array>
	<bean class="javax.security.auth.login.AppConfigurationEntry">
		<constructor-arg value="sample.SampleLoginModule" />
		<constructor-arg>
		<util:constant static-field=
			"javax.security.auth.login.AppConfigurationEntry$LoginModuleControlFlag.REQUIRED"/>
		</constructor-arg>
		<constructor-arg>
		<map></map>
		</constructor-arg>
		</bean>
	</array>
	</entry>
	</map>
	</constructor-arg>
</bean>
</property>
<property name="authorityGranters">
<list>
	<!-- You will need to write your own implementation of AuthorityGranter -->
	<bean class="org.springframework.security.authentication.jaas.TestAuthorityGranter"/>
</list>
</property>
</bean>

----



[[jaas-jaasauthenticationprovider]]
===  JaasAuthenticationProvider
`JaasAuthenticationProvider`假定默认`Configuration`是 http://download.oracle.com/javase/1.4.2/docs/guide/security/jaas/spec/com/sun/security/auth/login/ConfigFile.html[ 通过ConfigFile]的一个实例。
这个假设是为了试图更新`Configuration`而做出的。
`JaasAuthenticationProvider`然后使用默认的`Configuration`创建`LoginContext`。

假设我们有一个JAAS登录配置文件`/WEB-INF/login.conf`，其中包含以下内容：

[source,txt]
----
JAASTest {
	sample.SampleLoginModule required;
};
----

像所有Spring Security bean一样，`JaasAuthenticationProvider`通过应用程序上下文进行配置。
以下定义将对应于上述JAAS登录配置文件：

[source,xml]
----

<bean id="jaasAuthenticationProvider"
class="org.springframework.security.authentication.jaas.JaasAuthenticationProvider">
<property name="loginConfig" value="/WEB-INF/login.conf"/>
<property name="loginContextName" value="JAASTest"/>
<property name="callbackHandlers">
<list>
<bean
	class="org.springframework.security.authentication.jaas.JaasNameCallbackHandler"/>
<bean
	class="org.springframework.security.authentication.jaas.JaasPasswordCallbackHandler"/>
</list>
</property>
<property name="authorityGranters">
	<list>
	<bean class="org.springframework.security.authentication.jaas.TestAuthorityGranter"/>
	</list>
</property>
</bean>
----

[[jaas-apiprovision]]
作为主题运行=== 
如果已配置，则`JaasApiIntegrationFilter`将尝试以`JaasAuthenticationToken`上的`Subject`身份运行。
这意味着可以使用以下方式访问`Subject`：

[source,java]
----
Subject subject = Subject.getSubject(AccessController.getContext());
----

这种集成可以使用<<nsa-http-jaas-api-provision,jaas-api-provision>>属性轻松配置。
当与依赖JAAS主题被填充的遗留或外部API集成时，此功能非常有用。
