
[[taglibs]]
==  JSP标记库
Spring Security有自己的taglib，它为访问安全信息和在JSP中应用安全约束提供了基本的支持。


=== 声明Taglib
要使用任何标签，您必须在JSP中声明安全taglib：

[source,xml]
----
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
----

[[taglibs-authorize]]
=== 授权标签
该标签用于确定是否应评估其内容。
在Spring Security 3.0中，它可以以两种方式使用脚注：[
Spring Security 2.0的遗留选项也受到支持，但不鼓励。
].
第一种方法使用在标签的`access`属性中指定的<<el-access-web,web-security expression>>。
表达式评估将委派给应用程序上下文中定义的`SecurityExpressionHandler<FilterInvocation>`（您应该在`<http>`名称空间配置中启用Web表达式以确保此服务可用）。
所以，例如，你可能有

[source,xml]
----
<sec:authorize access="hasRole('supervisor')">

This content will only be visible to users who have the "supervisor" authority in their list of <tt>GrantedAuthority</tt>s.

</sec:authorize>
----

当与Spring Security的PermissionEvaluator结合使用时，该标签也可以用来检查权限。
例如：

[source,xml]
----
<sec:authorize access="hasPermission(#domain,'read') or hasPermission(#domain,'write')">

This content will only be visible to users who have read or write permission to the Object found as a request attribute named "domain".

</sec:authorize>
----

一个常见的要求是只显示特定的链接，如果用户实际上被允许点击它。
我们如何预先确定是否允许某些事情？该标签也可以在另一种模式下运行，该模式允许您将特定的URL定义为属性。
如果用户被允许调用该URL，那么标签主体将被评估，否则它将被跳过。
所以你可能有类似的东西

[source,xml]
----
<sec:authorize url="/admin">

This content will only be visible to users who are authorized to send requests to the "/admin" URL.

</sec:authorize>
----

要使用此标记，您的应用程序上下文中还必须有`WebInvocationPrivilegeEvaluator`的实例。
如果您使用的是名称空间，则会自动注册。
这是`DefaultWebInvocationPrivilegeEvaluator`的一个实例，它为提供的URL创建一个虚拟Web请求，并调用安全拦截器来查看请求是成功还是失败。
这允许您委派到您在`<http>`命名空间配置中使用`intercept-url`声明定义的访问控制设置，并且不必在JSP中复制信息（如所需的角色）。
这种方法还可以与提供HTTP方法的`method`属性相结合，以获得更具体的匹配。

通过将`var`属性设置为变量名称，可以将评估标记的布尔结果（无论是授予还是拒绝访问）存储在页面上下文范围变量中，从而避免需要复制和重新评估条件页面中的其他点。


==== 禁用标签授权以进行测试
在页面中隐藏未授权用户的链接并不妨碍他们访问URL。
例如，他们可以直接将其输入到浏览器中。
作为测试过程的一部分，您可能想要揭示隐藏区域，以检查链接是否真正在后端得到保护。
如果您将系统属性`spring.security.disableUISecurity`设置为`true`，则`authorize`标签仍会运行，但不会隐藏其内容。
默认情况下，它也会用`<span class="securityHiddenUI">...</span>`标签包围内容。
这使您可以显示具有特定CSS样式（例如不同背景颜色）的"hidden"内容。
例如，尝试运行启用了此属性的"tutorial"示例应用程序。

如果要从默认的`span`标签更改周围文本（或使用空字符串将其完全删除），还可以设置属性`spring.security.securedUIPrefix`和`spring.security.securedUISuffix`。


=== 认证标签
该标签允许访问存储在安全上下文中的当前`Authentication`对象。
它直接在JSP中呈现对象的属性。
因此，例如，如果`Authentication`的{​​{0}}属性是Spring Security的`UserDetails`对象的实例，则使用`<sec:authentication property="principal.username" />`将呈现当前用户的名称。

当然，没有必要为这类事情使用JSP标签，而有些人更愿意在视图中尽可能少地使用逻辑。
您可以访问MVC控制器中的`Authentication`对象（通过调用`SecurityContextHolder.getContext().getAuthentication()`）并将数据直接添加到您的模型中，以供视图渲染。


===  accesscontrollist标记
该标签只有在与Spring Security的ACL模块一起使用时才有效。
它检查指定域对象的必需权限的逗号分隔列表。
如果当前用户拥有所有这些权限，则标签正文将被评估。
如果他们不这样做，它将被跳过。
一个例子可能是

小心：一般来说，这个标签应被视为弃用。
请改用<<taglibs-authorize>>。

[source,xml]
----
<sec:accesscontrollist hasPermission="1,2" domainObject="${someObject}">

This will be shown if the user has all of the permissions represented by the values "1" or "2" on the given object.

</sec:accesscontrollist>
----

权限被传递给应用程序上下文中定义的`PermissionFactory`，并将它们转换为ACL `Permission`实例，因此它们可以是工厂支持的任何格式 - 它们不必是整数，它们可以是`READ`或`WRITE`之类的字符串。
如果未找到`PermissionFactory`，则将使用`DefaultPermissionFactory`的实例。
来自应用程序上下文的`AclService`将用于加载提供对象的`Acl`实例。
`Acl`将被调用所需的权限来检查是否所有这些都被授予。

这个标签也支持`var`属性，就像`authorize`标签一样。


===  csrfInput标记
如果启用了CSRF保护，则此标记会为CSRF保护令牌插入一个隐藏表单字段，其中包含正确的名称和值。
如果CSRF保护未启用，则此标记不输出任何内容。

通常，Spring Security会为您使用的任何`<form:form>`标记自动插入CSRF表单字段，但如果由于某种原因您无法使用`<form:form>`，则`csrfInput`是一个方便的替代品。

您应该将此标记置于HTML `<form></form>`块内，您通常会在其中放置其他输入字段。
不要将此标签放置在Spring `<form:form></form:form>`块内。
Spring Security自动处理Spring窗体。

[source,xml]
----
	<form method="post" action="/do/something">
		<sec:csrfInput />
		Name:<br />
		<input type="text" name="name" />
		...
	</form>
----


===  csrfMetaTags标记
如果启用CSRF保护，则此标记会插入包含CSRF保护令牌表单字段和标头名称以及CSRF保护标记值的元标记。
这些元标记对于在应用程序中使用JavaScript中的CSRF保护很有用。

您应该将`csrfMetaTags`放置在HTML `<head></head>`块内，您通常会在其中放置其他元标记。
一旦你使用这个标签，你可以使用JavaScript轻松访问表单字段名称，标题名称和标记值。
在这个例子中使用JQuery使任务更容易。

[source,xml]
----
<!DOCTYPE html>
<html>
	<head>
		<title>CSRF Protected JavaScript Page</title>
		<meta name="description" content="This is the description for this page" />
		<sec:csrfMetaTags />
		<script type="text/javascript" language="javascript">

			var csrfParameter = $("meta[name='_csrf_parameter']").attr("content");
			var csrfHeader = $("meta[name='_csrf_header']").attr("content");
			var csrfToken = $("meta[name='_csrf']").attr("content");

			// using XMLHttpRequest directly to send an x-www-form-urlencoded request
			var ajax = new XMLHttpRequest();
			ajax.open("POST", "http://www.example.org/do/something", true);
			ajax.setRequestHeader("Content-Type", "application/x-www-form-urlencoded data");
			ajax.send(csrfParameter + "=" + csrfToken + "&name=John&...");

			// using XMLHttpRequest directly to send a non-x-www-form-urlencoded request
			var ajax = new XMLHttpRequest();
			ajax.open("POST", "http://www.example.org/do/something", true);
			ajax.setRequestHeader(csrfHeader, csrfToken);
			ajax.send("...");

			// using JQuery to send an x-www-form-urlencoded request
			var data = {};
			data[csrfParameter] = csrfToken;
			data["name"] = "John";
			...
			$.ajax({
				url: "http://www.example.org/do/something",
				type: "POST",
				data: data,
				...
			});

			// using JQuery to send a non-x-www-form-urlencoded request
			var headers = {};
			headers[csrfHeader] = csrfToken;
			$.ajax({
				url: "http://www.example.org/do/something",
				type: "POST",
				headers: headers,
				...
			});

		<script>
	</head>
	<body>
		...
	</body>
</html>
----

如果未启用CSRF保护，则`csrfMetaTags`不输出任何内容。

