[[ldap]]
==  LDAP身份验证


[[ldap-overview]]
=== 概述
LDAP通常被组织用作用户信息和身份验证服务的中央存储库。
它也可以用来存储应用程序用户的角色信息。

LDAP服务器如何配置有很多不同的情况，所以Spring Security的LDAP提供程序是完全可配置的。
它使用单独的策略接口进行身份验证和角色检索，并提供可配置为处理各种情况的默认实现。

在尝试将其用于Spring Security之前，您应该熟悉LDAP。
以下链接提供了有关概念的良好介绍，并提供了使用免费LDAP服务器OpenLDAP设置目录的指南： http://www.zytrax.com/books/ldap/[http://www.zytrax.com/books/ldap/]。
熟悉用于从Java访问LDAP的JNDI API也可能有用。
我们不在LDAP提供程序中使用任何第三方LDAP库（Mozilla，JLDAP等），但广泛使用Spring LDAP，因此如果您计划添加自己的自定义项，对该项目的某些熟悉可能会很有用。

使用LDAP身份验证时，确保正确配置LDAP连接池非常重要。
如果您不熟悉如何操作，可以参考 http://docs.oracle.com/javase/jndi/tutorial/ldap/connect/config.html[Java LDAP文档]。

=== 在Spring Security中使用LDAP
Spring Security中的LDAP认证大致可以分为以下几个阶段。

* 从登录名获取唯一的LDAP "Distinguished Name"或DN。
这通常意味着在目录中执行搜索，除非事先知道用户名到DN的确切映射。
因此，用户在登录时可能会输入名称"joe"，但用于向LDAP进行身份验证的实际名称将是完整的DN，例如`uid=joe,ou=users,dc=spring,dc=io`。

* 以该用户的身份"binding"对用户进行身份验证，或者对DN的目录条目中的password属性执行用户密码的远程"compare"操作。

* 加载用户权限列表。

例外情况是LDAP目录仅用于在本地检索用户信息并进行身份验证。
这可能是不可能的，因为目录通常设置为对用户密码等属性的读访问权限有限。

我们将在下面看一些配置方案。
有关可用配置选项的完整信息，请参阅安全名称空间模式（您的XML编辑器中应该提供哪些信息）。


[[ldap-server]]
=== 配置LDAP服务器
您需要做的第一件事是配置服务器进行身份验证。
这是使用安全名称空间中的`<ldap-server>`元素完成的。
可以使用`url`属性将其配置为指向外部LDAP服务器：

[source,xml]
----
<ldap-server url="ldap://springframework.org:389/dc=springframework,dc=org" />
----

==== 使用嵌入式测试服务器
`<ldap-server>`元素也可用于创建嵌入式服务器，这对于测试和演示可能非常有用。
在这种情况下，您可以不使用`url`属性来使用它：

[source,xml]
----
<ldap-server root="dc=springframework,dc=org"/>
----

这里我们已经指定目录的根目录DIT应该是"dc=springframework,dc=org"，这是默认值。
使用这种方式，命名空间解析器将创建一个嵌入式Apache Directory服务器，并扫描类路径以查找将尝试加载到服务器的任何LDIF文件。
您可以使用定义要加载的LDIF资源的`ldif`属性来自定义此行为：

[source,xml]
----
<ldap-server ldif="classpath:users.ldif" />
----

这使得启动和运行LDAP变得容易很多，因为使用外部服务器可能会很不方便。
它还将用户从连接Apache Directory服务器所需的复杂bean配置中隔离开来。
使用普通的Spring Beans，配置会更加混乱。
您必须拥有必要的Apache目录依赖关系jar供您的应用程序使用。
这些可以从LDAP示例应用程序获得。

==== 使用绑定验证
这是最常见的LDAP身份验证方案。

[source,xml]
----
<ldap-authentication-provider user-dn-pattern="uid={0},ou=people"/>
----

这个简单的例子将通过用所提供的模式中的用户登录名替换用户并获得用户的DN，并尝试将该用户与登录密码绑定。
如果您的所有用户都存储在目录中的单个节点下，这是可以的。
如果您想要配置LDAP搜索过滤器来查找用户，则可以使用以下内容：

[source,xml]
----
<ldap-authentication-provider user-search-filter="(uid={0})"
	user-search-base="ou=people"/>
----

如果与上述服务器定义一起使用，则会使用`user-search-filter`属性的值作为过滤器在DN `ou=people,dc=springframework,dc=org`下执行搜索。
同样，用户登录名将替换过滤器名称中的参数，因此它将搜索`uid`属性等于用户名的条目。
如果未提供`user-search-base`，则将从根目录执行搜索。

==== 加载授权
如何从LDAP目录中的组加载权限是由以下属性控制的。

* `group-search-base`.
定义应在其下执行组搜索的目录树的部分。
* `group-role-attribute`.
包含组条目定义的权限名称的属性。
默认为`cn`
* `group-search-filter`.
用于搜索组成员身份的过滤器。
默认值为`uniqueMember={0}`，对应于`groupOfUniqueNames` LDAP类注脚：[请注意，这与使用`member={0}`的底层`DefaultLdapAuthoritiesPopulator`的默认配置不同）。
在这种情况下，替换参数是用户的完整专有名称。
如果您想过滤登录名称，则可以使用参数`{1}`。

所以如果我们使用下面的配置

[source,xml]
----
<ldap-authentication-provider user-dn-pattern="uid={0},ou=people"
		group-search-base="ou=groups" />
----

并以用户"ben"身份成功进行身份验证，则后续加载权限会在目录条目`ou=groups,dc=springframework,dc=org`下执行搜索，查找包含值`uid=ben,ou=people,dc=springframework,dc=org`的属性`uniqueMember`的条目。
默认情况下，机构名称的前缀是`ROLE_`。
您可以使用`role-prefix`属性进行更改。
如果您不需要任何前缀，请使用`role-prefix="none"`。
有关加载权限的更多信息，请参阅`DefaultLdapAuthoritiesPopulator`类的Javadoc。

=== 实现类
我们上面使用的命名空间配置选项很容易使用，比使用Spring bean明确得多。
有些情况下，您可能需要知道如何直接在应用程序上下文中配置Spring Security LDAP。
例如，您可能希望自定义某些类的行为。
如果您很高兴使用命名空间配置，那么您可以跳过本节和下一节。

主要的LDAP提供者类`LdapAuthenticationProvider`实际上并没有多大作用，而是将工作委托给其他两个bean，`LdapAuthenticator`和`LdapAuthoritiesPopulator`，它们负责验证用户并检索用户的`GrantedAuthority`分别。


[[ldap-ldap-authenticators]]
====  LdapAuthenticator实现
认证者还负责检索任何所需的用户属性。
这是因为对属性的权限可能取决于正在使用的身份验证的类型。
例如，如果作为用户进行绑定，则可能需要使用用户自己的权限读取它们。

目前Spring Security提供了两种身份验证策略：

* 直接向LDAP服务器认证（"bind"认证）。

* 密码比较，其中用户提供的密码与存储库中存储的密码进行比较。
这可以通过检索密码属性的值并在本地进行检查或通过执行LDAP "compare"操作来完成，其中将提供的密码传递给服务器进行比较，并且实际密码值永远不会被检索。

[[ldap-ldap-authenticators-common]]
===== 通用功能
在可以通过任一策略对用户进行身份验证之前，必须从提供给应用程序的登录名中获取专有名称（DN）。
这可以通过简单的模式匹配（通过设置`setUserDnPatterns`数组属性）或通过设置`userSearch`属性来完成。
对于DN模式匹配方法，使用标准的Java模式格式，并且登录名将替换参数`{0}`。
该模式应该与配置的`SpringSecurityContextSource`将绑定到的DN相关（有关此信息的更多信息，请参阅<<ldap-context-source,connecting to the LDAP server>>中的部分）。
例如，如果您使用URL为`ldap://monkeymachine.co.uk/dc=springframework,dc=org`的LDAP服务器，并且模式为`uid={0},ou=greatapes`，则登录名"gorilla"将映射到DN `uid=gorilla,ou=greatapes,dc=springframework,dc=org`。
每个配置的DN模式将依次尝试，直到找到匹配项。
有关使用搜索的信息，请参阅下面的<<ldap-searchobjects,search objects>>部分。
也可以使用两种方法的组合 - 首先检查模式，如果找不到匹配的DN，则将使用搜索。


[[ldap-ldap-authenticators-bind]]
===== 认证者
包`org.springframework.security.ldap.authentication`中的类`BindAuthenticator`实现了绑定认证策略。
它只是试图绑定为用户。


[[ldap-ldap-authenticators-password]]
=====  PasswordComparisonAuthenticator
类`PasswordComparisonAuthenticator`实施密码比较认证策略。


[[ldap-context-source]]
==== 连接到LDAP服务器
上面讨论的bean必须能够连接到服务器。
他们都必须提供`SpringSecurityContextSource`，这是Spring LDAP的`ContextSource`的扩展。
除非您有特殊要求，否则您通常会配置一个`DefaultSpringSecurityContextSource` bean，该bean可以使用您的LDAP服务器的URL进行配置，并且可以使用默认使用的"manager"用户的用户名和密码绑定到服务器时（而不是匿名绑定）。
有关更多信息，请阅读此类的Javadoc和Spring LDAP的`AbstractContextSource`。


[[ldap-searchobjects]]
====  LDAP搜索对象
通常比简单的DN匹配更复杂的策略需要在目录中定位用户条目。
这可以封装在可以提供给验证器实现的`LdapUserSearch`实例中，例如，允许它们定位用户。
提供的实现是`FilterBasedLdapUserSearch`。


[[ldap-searchobjects-filter]]
=====  FilterBasedLdapUserSearch中
这个bean使用LDAP过滤器来匹配目录中的用户对象。
该过程在Javadoc中对 http://java.sun.com/j2se/1.4.2/docs/api/javax/naming/directory/DirContext.html#search(javax.naming.Name%2C%2520java.lang.String%2C%2520java.lang.Object%5B%5D%2C%2520javax.naming.directory.SearchControls)[JDK DirContext类]中的相应搜索方法进行了解释。
如上所述，搜索过滤器可以提供参数。
对于这个类，唯一有效的参数是`{0}`，它将被用户的登录名取代。


[[ldap-authorities]]
====  LdapAuthoritiesPopulator在
在成功验证用户之后，`LdapAuthenticationProvider`将尝试通过调用配置的`LdapAuthoritiesPopulator` Bean来为用户加载一组权限。
`DefaultLdapAuthoritiesPopulator`是一个实现，它将通过在目录中搜索用户所属的组来加载权限（通常这些将是目录中的`groupOfNames`或`groupOfUniqueNames`条目）。
有关它如何工作的更多细节，请咨询本课程的Javadoc。

如果您只想使用LDAP进行身份验证，但是从不同的来源（例如数据库）加载权限，则可以提供您自己的此接口实现，然后插入。

[[ldap-bean-config]]
====  Spring Bean配置
使用我们在此讨论的一些bean的典型配置可能如下所示：

[source,xml]
----
<bean id="contextSource"
		class="org.springframework.security.ldap.DefaultSpringSecurityContextSource">
<constructor-arg value="ldap://monkeymachine:389/dc=springframework,dc=org"/>
<property name="userDn" value="cn=manager,dc=springframework,dc=org"/>
<property name="password" value="password"/>
</bean>

<bean id="ldapAuthProvider"
	class="org.springframework.security.ldap.authentication.LdapAuthenticationProvider">
<constructor-arg>
<bean class="org.springframework.security.ldap.authentication.BindAuthenticator">
	<constructor-arg ref="contextSource"/>
	<property name="userDnPatterns">
	<list><value>uid={0},ou=people</value></list>
	</property>
</bean>
</constructor-arg>
<constructor-arg>
<bean
	class="org.springframework.security.ldap.userdetails.DefaultLdapAuthoritiesPopulator">
	<constructor-arg ref="contextSource"/>
	<constructor-arg value="ou=groups"/>
	<property name="groupRoleAttribute" value="ou"/>
</bean>
</constructor-arg>
</bean>
----

这将设置提供者访问URL为`ldap://monkeymachine:389/dc=springframework,dc=org`的LDAP服务器。
尝试使用DN `uid=<user-login-name>,ou=people,dc=springframework,dc=org`进行绑定来执行身份验证。
验证成功后，角色将通过使用默认过滤器`(member=<user's-DN>)`在DN `ou=groups,dc=springframework,dc=org`下搜索来分配给用户。
角色名称将取自每个匹配的"ou"属性。

要配置使用过滤器`(uid=<user-login-name>)`而不是DN模式（或除此之外）的用户搜索对象，您可以配置以下bean

[source,xml]
----

<bean id="userSearch"
	class="org.springframework.security.ldap.search.FilterBasedLdapUserSearch">
<constructor-arg index="0" value=""/>
<constructor-arg index="1" value="(uid={0})"/>
<constructor-arg index="2" ref="contextSource" />
</bean>
----

并通过设置`BindAuthenticator` bean的`userSearch`属性来使用它。
然后认证者会在尝试以该用户身份进行绑定之前调用搜索对象以获取正确的用户DN。


[[ldap-custom-user-details]]
====  LDAP属性和自定义UserDetails
使用`LdapAuthenticationProvider`进行身份验证的最终结果与使用标准`UserDetailsService`接口的普通Spring Security身份验证相同。
`UserDetails`对象被创建并存储在返回的`Authentication`对象中。
与使用`UserDetailsService`一样，常见的要求是能够自定义此实现并添加额外的属性。
使用LDAP时，这些通常是来自用户条目的属性。
`UserDetails`对象的创建由提供者的`UserDetailsContextMapper`策略控制，该策略负责将用户对象映射到LDAP上下文数据和从LDAP上下文数据映射用户对象：

[source,java]
----
public interface UserDetailsContextMapper {

UserDetails mapUserFromContext(DirContextOperations ctx, String username,
		Collection<GrantedAuthority> authorities);

void mapUserToContext(UserDetails user, DirContextAdapter ctx);
}
----

只有第一种方法与认证有关。
如果您提供此接口的实现并将其注入到`LdapAuthenticationProvider`中，则您可以精确控制如何创建UserDetails对象。
第一个参数是Spring LDAP的`DirContextOperations`实例，它允许您访问在验证期间加载的LDAP属性。
`username`参数是用于认证的名称，最后一个参数是配置的`LdapAuthoritiesPopulator`为用户加载的权限的集合。

根据您使用的身份验证类型，上下文数据加载的方式略有不同。
使用`BindAuthenticator`，绑定操作返回的上下文将用于读取属性，否则将使用从配置的`ContextSource`中获取的标准上下文读取数据（当搜索配置为定位用户，这将是搜索对象返回的数据）。


[[ldap-active-directory]]
===  Active Directory身份验证
Active Directory支持其自身的非标准认证选项，并且正常使用模式不适合标准的`LdapAuthenticationProvider`。
通常使用域用户名（格式为`user@domain`）执行身份验证，而不是使用LDAP专有名称。
为了简化这个过程，Spring Security 3.1有一个为典型Active Directory设置定制的身份验证提供程序。


====  ActiveDirectoryLdapAuthenticationProvider
配置`ActiveDirectoryLdapAuthenticationProvider`非常简单。
您只需提供域名和提供服务器脚注地址的LDAP URL：[也可以使用DNS查找来获取服务器的IP地址。
目前尚未支持，但希望能在未来的版本中。]。
一个示例配置将如下所示：

[source,xml]
----

<bean id="adAuthenticationProvider"
class="org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider">
	<constructor-arg value="mydomain.com" />
	<constructor-arg value="ldap://adserver.mydomain.com/" />
</bean>
}
----

请注意，为了定义服务器位置，不需要指定单独的`ContextSource`  - 该bean是完全独立的。
例如，名为"Sharon"的用户可以通过输入用户名`sharon`或完整的Active Directory `userPrincipalName`进行身份验证，即`sharon@mydomain.com`。
然后定位用户的目录条目，并返回可用于定制创建的`UserDetails`对象（a `UserDetailsContextMapper`）的属性（如上所述）以实现此目的。
与目录的所有交互都与用户本身的身份一致。
没有"manager"用户的概念。

默认情况下，用户权限是从用户条目的`memberOf`属性值中获取的。
分配给用户的权限可以再次使用`UserDetailsContextMapper`进行自定义。
您还可以在提供程序实例中注入`GrantedAuthoritiesMapper`以控制最终位于`Authentication`对象中的权限。

=====  Active Directory错误代码
默认情况下，失败的结果将导致标准的Spring Security `BadCredentialsException`。
如果将属性`convertSubErrorCodesToExceptions`设置为`true`，则将解析异常消息以尝试解压出特定于Active Directory的错误代码并引发更具体的异常。
查看Javadoc课程获取更多信息。
