

[[mvc]]
==  Spring MVC集成

Spring Security提供了许多与Spring MVC的可选集成。
本节将更详细地介绍集成。

[[mvc-enablewebmvcsecurity]]
===  @ EnableWebMvcSecurity

注意：从Spring Security 4.0开始，`@EnableWebMvcSecurity`已被弃用。
替换是`@EnableWebSecurity`，它将确定基于类路径添加Spring MVC功能。

为了使Spring Security与Spring MVC集成，将`@EnableWebSecurity`注释添加到您的配置中。

注意：Spring Security使用Spring MVC的https://docs.spring.io/spring/docs/5.0.0.RELEASE/spring-framework-reference/web.html#mvc-config-customize[WebMvcConfigurer]提供配置。
这意味着如果您使用更高级的选项，如直接与`WebMvcConfigurationSupport`进行集成，则需要手动提供Spring Security配置。

[[mvc-requestmatcher]]
===  MvcRequestMatcher

Spring Security提供了与Spring MVC如何在具有`MvcRequestMatcher`的URL上匹配的深度集成。
这有助于确保您的安全规则与用于处理您的请求的逻辑相匹配。

为了使用`MvcRequestMatcher`，您必须将Spring Security配置放置在与您的`DispatcherServlet`相同的`ApplicationContext`中。
这是非常必要的，因为Spring Security的`MvcRequestMatcher`期望名称为`mvcHandlerMappingIntrospector`的`HandlerMappingIntrospector` bean将被用于执行匹配的Spring MVC配置注册。

对于`web.xml`，这意味着您应该将配置置于`DispatcherServlet.xml`中。

[source,xml]
----
<listener>
  <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
</listener>

<!-- All Spring Configuration (both MVC and Security) are in /WEB-INF/spring/ -->
<context-param>
  <param-name>contextConfigLocation</param-name>
  <param-value>/WEB-INF/spring/*.xml</param-value>
</context-param>

<servlet>
  <servlet-name>spring</servlet-name>
  <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
  <!-- Load from the ContextLoaderListener -->
  <init-param>
    <param-name>contextConfigLocation</param-name>
    <param-value></param-value>
  </init-param>
</servlet>

<servlet-mapping>
  <servlet-name>spring</servlet-name>
  <url-pattern>/</url-pattern>
</servlet-mapping>
----

放置在``DispatcherServlet`` `ApplicationContext`中的`WebSecurityConfiguration`下方。

[source,java]
----
public class SecurityInitializer extends
    AbstractAnnotationConfigDispatcherServletInitializer {

  @Override
  protected Class<?>[] getRootConfigClasses() {
    return null;
  }

  @Override
  protected Class<?>[] getServletConfigClasses() {
    return new Class[] { RootConfiguration.class,
        WebMvcConfiguration.class };
  }

  @Override
  protected String[] getServletMappings() {
    return new String[] { "/" };
  }
}
----

[NOTE]
====
始终建议通过匹配`HttpServletRequest`和方法安全性来提供授权规则。

通过在`HttpServletRequest`上进行匹配提供授权规则是很好的，因为它在代码路径的早期发生并有助于减少https://en.wikipedia.org/wiki/Attack_surface[attack表面]。
方法安全性可确保如果有人绕过了Web授权规则，则您的应用程序仍处于安全状态。
这就是所谓的https://en.wikipedia.org/wiki/Defense_in_depth_(computing）[深度防御]
====

考虑一个映射如下的控制器：

[source,java]
----
@RequestMapping("/admin")
public String admin() {
----

如果我们想限制管理员用户访问此控制器方法，开发人员可以通过将`HttpServletRequest`与以下内容进行匹配来提供授权规则：

[source,java]
----
protected configure(HttpSecurity http) throws Exception {
	http
		.authorizeRequests()
			.antMatchers("/admin").hasRole("ADMIN");
}
----

或以XML格式

[source,xml]
----
<http>
	<intercept-url pattern="/admin" access="hasRole('ADMIN')"/>
</http>
----

无论哪种配置，网址`/admin`都需要经过身份验证的用户成为管理员用户。
但是，根据我们的Spring MVC配置，URL `/admin.html`也将映射到我们的`admin()`方法。
另外，根据我们的Spring MVC配置，URL `/admin/`也会映射到我们的`admin()`方法。

问题是我们的安全规则仅保护`/admin`。
我们可以为Spring MVC的所有排列添加额外的规则，但这将是非常冗长和乏味的。

相反，我们可以利用Spring Security的`MvcRequestMatcher`。
以下配置将通过使用Spring MVC匹配URL来保护Spring MVC将匹配的相同URL。


[source,java]
----
protected configure(HttpSecurity http) throws Exception {
	http
		.authorizeRequests()
			.mvcMatchers("/admin").hasRole("ADMIN");
}
----

或以XML格式

[source,xml]
----
<http request-matcher="mvc">
	<intercept-url pattern="/admin" access="hasRole('ADMIN')"/>
</http>
----

[[mvc-authentication-principal]]
===  @ AuthenticationPrincipal

Spring Security提供了`AuthenticationPrincipalArgumentResolver`，它可以自动解析当前`Authentication.getPrincipal()`的Spring MVC参数。
通过使用`@EnableWebSecurity`，您将自动将它添加到您的Spring MVC配置中。
如果你使用基于XML的配置，你必须自己添加它。
例如：

[source,xml]
----
<mvc:annotation-driven>
		<mvc:argument-resolvers>
				<bean class="org.springframework.security.web.method.annotation.AuthenticationPrincipalArgumentResolver" />
		</mvc:argument-resolvers>
</mvc:annotation-driven>
----

一旦`AuthenticationPrincipalArgumentResolver`被正确配置，您就可以在Spring MVC层完全脱离Spring Security。

考虑一种情况，即自定义`UserDetailsService`返回实现`UserDetails`的`Object`和您自己的`CustomUser` `Object`}。可以使用以下代码访问当前已认证用户的`CustomUser`：

[source,java]
----
@RequestMapping("/messages/inbox")
public ModelAndView findMessagesForUser() {
	Authentication authentication =
	SecurityContextHolder.getContext().getAuthentication();
	CustomUser custom = (CustomUser) authentication == null ? null : authentication.getPrincipal();

	// .. find messages for this user and return them ...
}
----

从Spring Security 3.2开始，我们可以通过添加注释来更直接地解决争论。例如：

[source,java]
----
import org.springframework.security.core.annotation.AuthenticationPrincipal;

// ...

@RequestMapping("/messages/inbox")
public ModelAndView findMessagesForUser(@AuthenticationPrincipal CustomUser customUser) {

	// .. find messages for this user and return them ...
}
----

有时可能需要以某种方式改变校长。
例如，如果`CustomUser`需要是最终的，则无法扩展。
在这种情况下，`UserDetailsService`可能会返回实现`UserDetails`的`Object`，并提供一个名为`getCustomUser`的方法来访问`CustomUser`。
例如，它可能看起来像：

[source,java]
----
public class CustomUserUserDetails extends User {
		// ...
		public CustomUser getCustomUser() {
				return customUser;
		}
}
----

然后，我们可以使用使用`Authentication.getPrincipal()`的https://docs.spring.io/spring/docs/current/spring-framework-reference/html/expressions.html[SpEL表达式]来访问`CustomUser`。作为根对象：

[source,java]
----
import org.springframework.security.core.annotation.AuthenticationPrincipal;

// ...

@RequestMapping("/messages/inbox")
public ModelAndView findMessagesForUser(@AuthenticationPrincipal(expression = "customUser") CustomUser customUser) {

	// .. find messags for this user and return them ...
}
----

我们也可以在我们的SpEL表达式中引用Beans。
例如，如果我们使用JPA来管理用户，并且我们想修改并保存当前用户的属性，可以使用以下内容。

[source,java]
----
import org.springframework.security.core.annotation.AuthenticationPrincipal;

// ...

@PutMapping("/users/self")
public ModelAndView updateName(@AuthenticationPrincipal(expression = "@jpaEntityManager.merge(#this)") CustomUser attachedCustomUser,
		@RequestParam String firstName) {

	// change the firstName on an attached instance which will be persisted to the database
	attachedCustomUser.setFirstName(firstName);

	// ...
}
----

我们可以通过将`@AuthenticationPrincipal`作为我们自己注释中的元注释来进一步消除对Spring Security的依赖。
下面我们演示如何在名为`@CurrentUser`的注释中执行此操作。

注意：认识到为了消除对Spring Security的依赖是很重要的，消费应用程序会创建`@CurrentUser`。
这一步并非严格要求，但有助于将您对Spring Security的依赖隔离到更加中心的位置。

[source,java]
----
@Target({ElementType.PARAMETER, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@AuthenticationPrincipal
public @interface CurrentUser {}
----

现在`@CurrentUser`已经被指定，我们可以用它来发信号来解决我们当前认证用户的`CustomUser`。
我们还将Spring Security的依赖性分离为单个文件。

[source,java]
----
@RequestMapping("/messages/inbox")
public ModelAndView findMessagesForUser(@CurrentUser CustomUser customUser) {

	// .. find messages for this user and return them ...
}
----


[[mvc-async]]
===  Spring MVC异步集成

Spring Web MVC 3.2+对 http://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/mvc.html#mvc-ann-async[异步请求处理]提供了很好的支持。
无需额外配置，Spring Security会自动将`SecurityContext`设置为执行控制器返回的`Callable`的`Thread`。
例如，以下方法会自动将`Callable`与`Callable`创建时可用的`SecurityContext`一起执行：

[source,java]
----
@RequestMapping(method=RequestMethod.POST)
public Callable<String> processUpload(final MultipartFile file) {

return new Callable<String>() {
	public Object call() throws Exception {
	// ...
	return "someView";
	}
};
}
----

[NOTE]
将SecurityContext分配给Callable的
====
从技术上讲，Spring Security与`WebAsyncManager`集成。
用于处理`Callable`的{​​{0}}是调用`SecurityContextHolder`时存在的`SecurityContext`。
====

没有与控制器返回的`DeferredResult`的自动集成。
这是因为`DeferredResult`由用户处理，因此无法自动与它集成。
但是，您仍然可以使用<<concurrency,Concurrency Support>>来提供与Spring Security的透明集成。

[[mvc-csrf]]
===  Spring MVC和CSRF集成

==== 自动令牌包含

Spring Security将在使用 http://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/view.html#view-jsp-formtaglib-formtag[Spring MVC表单标签]的表单中自动<<csrf-include-csrf-token,include the CSRF Token>>。
例如，以下JSP：

[source,xml]
----
<jsp:root xmlns:jsp="http://java.sun.com/JSP/Page"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:form="http://www.springframework.org/tags/form" version="2.0">
	<jsp:directive.page language="java" contentType="text/html" />
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
	<!-- ... -->

	<c:url var="logoutUrl" value="/logout"/>
	<form:form action="${logoutUrl}"
		method="post">
	<input type="submit"
		value="Log out" />
	<input type="hidden"
		name="${_csrf.parameterName}"
		value="${_csrf.token}"/>
	</form:form>

	<!-- ... -->
</html>
</jsp:root>
----

将输出类似于以下内容的HTML：

[source,xml]
----
<!-- ... -->

<form action="/context/logout" method="post">
<input type="submit" value="Log out"/>
<input type="hidden" name="_csrf" value="f81d4fae-7dec-11d0-a765-00a0c91e6bf6"/>
</form>

<!-- ... -->
----

[[mvc-csrf-resolver]]
==== 解析CsrfToken

Spring Security提供了`CsrfTokenArgumentResolver`，它可以自动解析当前`CsrfToken`的Spring MVC参数。
通过使用<<jc-hello-wsca,@EnableWebSecurity>>，您将自动将它添加到您的Spring MVC配置中。
如果你使用基于XML的配置，你必须自己添加它。

`CsrfTokenArgumentResolver`配置正确后，您可以将`CsrfToken`公开给您的基于静态HTML的应用程序。

[source,java]
----
@RestController
public class CsrfController {

	@RequestMapping("/csrf")
	public CsrfToken csrf(CsrfToken token) {
		return token;
	}
}
----

保持`CsrfToken`与其他域的秘密非常重要。
这意味着如果您使用的是https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS[Cross Origin Sharing（CORS）]，则应**NOT**公开`CsrfToken`到任何外部域名。
