

[[oauth2login-advanced]]
==  OAuth 2.0登录 - 高级配置

`HttpSecurity.oauth2Login()`为定制OAuth 2.0登录提供了许多配置选项。
主要配置选项分组到他们的协议端点对应部分。

例如，`oauth2Login().authorizationEndpoint()`允许配置_Authorization Endpoint_，
而`oauth2Login().tokenEndpoint()`允许配置_Token Endpoint_。

以下代码显示了一个示例：

[source,java]
----
@EnableWebSecurity
public class OAuth2LoginSecurityConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.oauth2Login()
				.authorizationEndpoint()
					...
				.redirectionEndpoint()
					...
				.tokenEndpoint()
					...
				.userInfoEndpoint()
					...
	}
}
----

`oauth2Login()` DSL的主要目标是与规范中定义的命名保持一致。

OAuth 2.0授权框架如下定义https://tools.ietf.org/html/rfc6749#section-3[Protocol Endpoints]：

授权过程使用两个授权服务器端点（HTTP资源）：

* 授权端点：客户端用于通过用户代理重定向从资源所有者获取授权。
* 令牌端点：客户端用来为访问令牌交换授权授权，通常使用客户端验证。

以及一个客户端端点：

* 重定向端点：授权服务器用于返回响应
通过资源所有者用户代理向客户端提供授权凭证。

OpenID Connect Core 1.0规范定义了 http://openid.net/specs/openid-connect-core-1_0.html#UserInfo[UserInfo端点]，如下所示：

UserInfo端点是一个OAuth 2.0保护资源，用于返回有关经过身份验证的最终用户的声明。
为了获得有关最终用户的请求声明，客户端向UserInfo端点发出请求
通过使用通过OpenID Connect Authentication获取的访问令牌。
这些声明通常由包含声明的名称/值对集合的JSON对象表示。

以下代码显示了可用于`oauth2Login()` DSL的完整配置选项：

[source,java]
----
@EnableWebSecurity
public class OAuth2LoginSecurityConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.oauth2Login()
				.clientRegistrationRepository(this.clientRegistrationRepository())
				.authorizedClientService(this.authorizedClientService())
				.loginPage("/login")
				.authorizationEndpoint()
					.baseUri(this.authorizationRequestBaseUri())
					.authorizationRequestRepository(this.authorizationRequestRepository())
					.and()
				.redirectionEndpoint()
					.baseUri(this.authorizationResponseBaseUri())
					.and()
				.tokenEndpoint()
					.accessTokenResponseClient(this.accessTokenResponseClient())
					.and()
				.userInfoEndpoint()
					.userAuthoritiesMapper(this.userAuthoritiesMapper())
					.userService(this.oauth2UserService())
					.oidcUserService(this.oidcUserService())
					.customUserType(GitHubOAuth2User.class, "github");
	}
}
----

下面的章节会详细介绍每个可用的配置选项：

* <<oauth2login-advanced-login-page>>
* <<oauth2login-advanced-authorization-endpoint>>
* <<oauth2login-advanced-redirection-endpoint>>
* <<oauth2login-advanced-token-endpoint>>
* <<oauth2login-advanced-userinfo-endpoint>>


[[oauth2login-advanced-login-page]]
===  OAuth 2.0登录页面

默认情况下，OAuth 2.0登录页面由`DefaultLoginPageGeneratingFilter`自动生成。
默认登录页面显示每个配置的OAuth客户端及其`ClientRegistration.clientName`
作为能够启动授权请求（或OAuth 2.0登录）的链接。

每个OAuth客户端的链接目标缺省为以下内容：

`OAuth2AuthorizationRequestRedirectFilter.DEFAULT_AUTHORIZATION_REQUEST_BASE_URI` + "/{registrationId}"

以下行显示一个示例：

[source,html]
----
<a href="/oauth2/authorization/google">Google</a>
----

要覆盖默认的登录页面，
配置`oauth2Login().loginPage()`和（可选）`oauth2Login().authorizationEndpoint().baseUri()`。

以下列表显示了一个示例：

[source,java]
----
@EnableWebSecurity
public class OAuth2LoginSecurityConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.oauth2Login()
				.loginPage("/login/oauth2")
				...
				.authorizationEndpoint()
					.baseUri("/login/oauth2/authorization")
					....
	}
}
----

[IMPORTANT]
您需要提供带有`@RequestMapping("/login/oauth2")`的{​​{0}}，以便呈现自定义登录页面。

[TIP]
====
如前所述，配置`oauth2Login().authorizationEndpoint().baseUri()`是可选的。
但是，如果您选择自定义，请确保每个OAuth客户端的链接都与`authorizationEndpoint().baseUri()`匹配。

以下行显示一个示例：

[source,html]
----
<a href="/login/oauth2/authorization/google">Google</a>
----
====

[[oauth2login-advanced-authorization-endpoint]]
=== 授权端点


[[oauth2login-advanced-authorization-request-repository]]
==== `AuthorizationRequestRepository`

`AuthorizationRequestRepository`负责持续`OAuth2AuthorizationRequest`
从授权请求发起到授权响应的时间
（回调）。

[TIP]
`OAuth2AuthorizationRequest`用于关联和验证授权响应。

`AuthorizationRequestRepository`的默认实现是`HttpSessionOAuth2AuthorizationRequestRepository`，
将`OAuth2AuthorizationRequest`存储在`HttpSession`中。

如果您想提供`AuthorizationRequestRepository`的自定义实施
将`OAuth2AuthorizationRequest`的属性存储在`Cookie`中，
按以下示例中所示进行配置：

[source,java]
----
@EnableWebSecurity
public class OAuth2LoginSecurityConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.oauth2Login()
				.authorizationEndpoint()
					.authorizationRequestRepository(this.cookieAuthorizationRequestRepository())
					...
	}

	private AuthorizationRequestRepository<OAuth2AuthorizationRequest> cookieAuthorizationRequestRepository() {
		return new HttpCookieOAuth2AuthorizationRequestRepository();
	}
}
----

[[oauth2login-advanced-redirection-endpoint]]
=== 重定向端点

授权服务器使用重定向端点来返回授权响应
（包含授权证书）通过资源所有者用户代理发送给客户端。

[TIP]
OAuth 2.0登录利用授权代码授权。
因此，授权凭证是授权代码。

默认的授权响应`baseUri`（重定向端点）为`*/login/oauth2/code/**`，其在`OAuth2LoginAuthenticationFilter.DEFAULT_FILTER_PROCESSES_URI`中定义。

如果您想自定义授权响应`baseUri`，请按照以下示例中所示进行配置：

[source,java]
----
@EnableWebSecurity
public class OAuth2LoginSecurityConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.oauth2Login()
				.redirectionEndpoint()
					.baseUri("/login/oauth2/callback/*")
					....
	}
}
----

[IMPORTANT]
====
您还需要确保`ClientRegistration.redirectUriTemplate`与自定义授权响应`baseUri`匹配。

以下列表显示了一个示例：

[source,java]
----
return CommonOAuth2Provider.GOOGLE.getBuilder("google")
	.clientId("google-client-id")
	.clientSecret("google-client-secret")
	.redirectUriTemplate("{baseUrl}/login/oauth2/callback/{registrationId}")
	.build();
----
====

[[oauth2login-advanced-token-endpoint]]
=== 令牌端点


[[oauth2login-advanced-token-client]]
====  OAuth2AccessTokenResponseClient

`OAuth2AccessTokenResponseClient`负责交换授权授权凭证
获取授权服务器的令牌端点上的访问令牌凭证。

`OAuth2AccessTokenResponseClient`的默认实现是`NimbusAuthorizationCodeTokenResponseClient`，
它在Token端点交换访问令牌的授权代码。

[NOTE]
`NimbusAuthorizationCodeTokenResponseClient`在内部使用https://connect2id.com/products/nimbus-oauth-openid-connect-sdk[Nimbus OAuth 2.0 SDK]。

如果您想提供`OAuth2AccessTokenResponseClient`的自定义实施
它使用Spring Framework 5反应`WebClient`来发起对Token端点的请求，
按以下示例中所示进行配置：

[source,java]
----
@EnableWebSecurity
public class OAuth2LoginSecurityConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.oauth2Login()
				.tokenEndpoint()
					.accessTokenResponseClient(this.accessTokenResponseClient())
					...
	}

	private OAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest> accessTokenResponseClient() {
		return new SpringWebClientAuthorizationCodeTokenResponseClient();
	}
}
----

[[oauth2login-advanced-userinfo-endpoint]]
===  UserInfo端点

UserInfo端点包含许多配置选项，如以下小节所述：

* <<oauth2login-advanced-map-authorities>>
* <<oauth2login-advanced-custom-user>>
* <<oauth2login-advanced-oauth2-user-service>>
* <<oauth2login-advanced-oidc-user-service>>


[[oauth2login-advanced-map-authorities]]
==== 映射用户权限

在用户成功通过OAuth 2.0 Provider进行身份验证后，
可以将`OAuth2User.getAuthorities()`（或`OidcUser.getAuthorities()`）映射到一组新`GrantedAuthority`个实例，
在完成身份验证时将提供给`OAuth2AuthenticationToken`。

[TIP]
`OAuth2AuthenticationToken.getAuthorities()`用于授权请求，如`hasRole('USER')`或`hasRole('ADMIN')`。

映射用户权限时有几个选项可供选择：

* <<oauth2login-advanced-map-authorities-grantedauthoritiesmapper,Using a `GrantedAuthoritiesMapper`>>
* <<oauth2login-advanced-map-authorities-oauth2userservice,Delegation-based strategy with `OAuth2UserService`>>

[[oauth2login-advanced-map-authorities-grantedauthoritiesmapper]]
===== 使用`GrantedAuthoritiesMapper`

提供`GrantedAuthoritiesMapper`的实现并按照以下示例中所示进行配置：

[source,java]
----
@EnableWebSecurity
public class OAuth2LoginSecurityConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.oauth2Login()
				.userInfoEndpoint()
					.userAuthoritiesMapper(this.userAuthoritiesMapper())
					...
	}

	private GrantedAuthoritiesMapper userAuthoritiesMapper() {
		return (authorities) -> {
			Set<GrantedAuthority> mappedAuthorities = new HashSet<>();

			authorities.forEach(authority -> {
				if (OidcUserAuthority.class.isInstance(authority)) {
					OidcUserAuthority oidcUserAuthority = (OidcUserAuthority)authority;

					OidcIdToken idToken = oidcUserAuthority.getIdToken();
					OidcUserInfo userInfo = oidcUserAuthority.getUserInfo();

					// Map the claims found in idToken and/or userInfo
					// to one or more GrantedAuthority's and add it to mappedAuthorities

				} else if (OAuth2UserAuthority.class.isInstance(authority)) {
					OAuth2UserAuthority oauth2UserAuthority = (OAuth2UserAuthority)authority;

					Map<String, Object> userAttributes = oauth2UserAuthority.getAttributes();

					// Map the attributes found in userAttributes
					// to one or more GrantedAuthority's and add it to mappedAuthorities

				}
			});

			return mappedAuthorities;
		};
	}
}
----

或者，您可以注册`GrantedAuthoritiesMapper` `@Bean`以使其自动应用于配置，如以下示例所示：

[source,java]
----
@EnableWebSecurity
public class OAuth2LoginSecurityConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http.oauth2Login();
	}

	@Bean
	public GrantedAuthoritiesMapper userAuthoritiesMapper() {
		...
	}
}
----

[[oauth2login-advanced-map-authorities-oauth2userservice]]
===== 使用`OAuth2UserService`的基于代表团的策略

与使用`GrantedAuthoritiesMapper`相比，此策略更先进，但它也更灵活
因为它使您可以访问`OAuth2UserRequest`和`OAuth2User`（使用OAuth 2.0 UserService时）
或`OidcUserRequest`和`OidcUser`（使用OpenID Connect 1.0 UserService时）。

`OAuth2UserRequest`（和`OidcUserRequest`）可让您访问关联的`OAuth2AccessToken`，
这在_delegator_需要获取权限信息的情况下非常有用
从受保护的资源中映射用户的自定义权限。

以下示例显示如何使用OpenID Connect 1.0 UserService实施和配置基于委派的策略：

[source,java]
----
@EnableWebSecurity
public class OAuth2LoginSecurityConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.oauth2Login()
				.userInfoEndpoint()
					.oidcUserService(this.oidcUserService())
					...
	}

	private OAuth2UserService<OidcUserRequest, OidcUser> oidcUserService() {
		final OidcUserService delegate = new OidcUserService();

		return (userRequest) -> {
			// Delegate to the default implementation for loading a user
			OidcUser oidcUser = delegate.loadUser(userRequest);

			OAuth2AccessToken accessToken = userRequest.getAccessToken();
			Set<GrantedAuthority> mappedAuthorities = new HashSet<>();

			// TODO
			// 1) Fetch the authority information from the protected resource using accessToken
			// 2) Map the authority information to one or more GrantedAuthority's and add it to mappedAuthorities

			// 3) Create a copy of oidcUser but use the mappedAuthorities instead
			oidcUser = new DefaultOidcUser(mappedAuthorities, oidcUser.getIdToken(), oidcUser.getUserInfo());

			return oidcUser;
		};
	}
}
----

[[oauth2login-advanced-custom-user]]
==== 配置自定义OAuth2User

`CustomUserTypesOAuth2UserService`是`OAuth2UserService`的实现
为自定义`OAuth2User`类型提供支持。

如果默认实现（`DefaultOAuth2User`）不符合您的需求，
您可以定义自己的`OAuth2User`实现。

以下代码演示了如何为GitHub注册自定义`OAuth2User`类型：

[source,java]
----
@EnableWebSecurity
public class OAuth2LoginSecurityConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.oauth2Login()
				.userInfoEndpoint()
					.customUserType(GitHubOAuth2User.class, "github")
					...
	}
}
----

以下代码显示了GitHub的自定义`OAuth2User`类型的示例：

[source,java]
----
public class GitHubOAuth2User implements OAuth2User {
	private List<GrantedAuthority> authorities =
		AuthorityUtils.createAuthorityList("ROLE_USER");
	private Map<String, Object> attributes;
	private String id;
	private String name;
	private String login;
	private String email;

	@Override
	public Collection<? extends GrantedAuthority> getAuthorities() {
		return this.authorities;
	}

	@Override
	public Map<String, Object> getAttributes() {
		if (this.attributes == null) {
			this.attributes = new HashMap<>();
			this.attributes.put("id", this.getId());
			this.attributes.put("name", this.getName());
			this.attributes.put("login", this.getLogin());
			this.attributes.put("email", this.getEmail());
		}
		return attributes;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Override
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
}
----

[TIP]
`id`，`name`，`login`和`email`是在GitHub的UserInfo Response中返回的属性。
有关从UserInfo端点返回的详细信息，请参阅API文档
对于https://developer.github.com/v3/users/#get-the-authenticated-user ["Get the authenticated user"]。

[[oauth2login-advanced-oauth2-user-service]]
====  OAuth 2.0 UserService

`DefaultOAuth2UserService`是`OAuth2UserService`的实现
支持标准的OAuth 2.0 Provider。

[NOTE]
`OAuth2UserService`获取用户属性
最终用户（资源所有者）从UserInfo端点（通过使用
在授权流程中授予客户端的访问令牌）
并以`OAuth2User`的形式返回`AuthenticatedPrincipal`。

如果默认实现不适合您的需求，则可以定义您自己的`OAuth2UserService`实现
对于标准的OAuth 2.0 Provider。

以下配置演示了如何配置自定义`OAuth2UserService`：

[source,java]
----
@EnableWebSecurity
public class OAuth2LoginSecurityConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.oauth2Login()
				.userInfoEndpoint()
					.userService(this.oauth2UserService())
					...
	}

	private OAuth2UserService<OAuth2UserRequest, OAuth2User> oauth2UserService() {
		return new CustomOAuth2UserService();
	}
}
----

[[oauth2login-advanced-oidc-user-service]]
====  OpenID Connect 1.0 UserService

`OidcUserService`是`OAuth2UserService`的实现
支持OpenID Connect 1.0 Provider的。

[NOTE]
`OAuth2UserService`负责获取用户属性
最终用户（资源所有者）从UserInfo端点（通过使用
在授权流程中授予客户端的访问令牌）
并以`OidcUser`的形式返回`AuthenticatedPrincipal`。

如果默认实现不适合您的需求，则可以定义您自己的`OAuth2UserService`实现
适用于OpenID Connect 1.0 Provider。

以下配置演示了如何配置自定义OpenID Connect 1.0 `OAuth2UserService`：

[source,java]
----
@EnableWebSecurity
public class OAuth2LoginSecurityConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.oauth2Login()
				.userInfoEndpoint()
					.oidcUserService(this.oidcUserService())
					...
	}

	private OAuth2UserService<OidcUserRequest, OidcUser> oidcUserService() {
		return new CustomOidcUserService();
	}
}
----
