[[preauth]]
== 预认证方案
在某些情况下，您希望使用Spring Security进行授权，但在访问应用程序之前，用户已被某个外部系统可靠地认证。
我们将这些情况称为"pre-authenticated"情景。
示例包括X.509，Siteminder和运行该应用程序的Java EE容器的身份验证。
在使用预认证时，Spring Security必须

* 识别发出请求的用户。

* 获取用户权限。


细节将取决于外部认证机制。
在X.509的情况下，用户可以通过他们的证书信息来标识，或者在Siteminder的情况下通过HTTP请求标头来标识用户。
如果依赖容器身份验证，则将通过调用传入HTTP请求上的`getUserPrincipal()`方法来识别用户。
在某些情况下，外部机制可能会为用户提供角色/权限信息，但在其他情况下，必须从单独的来源获取权限，例如`UserDetailsService`。


=== 预认证框架类
由于大多数预认证机制遵循相同的模式，因此Spring Security具有一组类，它们为实现预认证的认证提供程序提供了一个内部框架。
这消除了重复，并允许以结构化的方式添加新的实现，而无需从头开始编写所有内容。
如果您想使用<<x509,X.509 authentication>>之类的东西，则不需要了解这些类，因为它已经有一个名称空间配置选项，该选项使用起来更简单并且易于使用。
如果您需要使用显式的bean配置或正在计划编写自己的实现，那么了解提供的实现如何工作将会很有用。
您会在`org.springframework.security.web.authentication.preauth`下找到课程。
我们只是在这里提供一个大纲，所以你应该在适当的地方咨询Javadoc和源代码。


====  AbstractPreAuthenticatedProcessingFilter
该类将检查安全上下文的当前内容，如果为空，它将尝试从HTTP请求中提取用户信息并将其提交给`AuthenticationManager`。
子类覆盖以下方法来获取此信息：

[source,java]
----
protected abstract Object getPreAuthenticatedPrincipal(HttpServletRequest request);

protected abstract Object getPreAuthenticatedCredentials(HttpServletRequest request);
----


调用这些后，过滤器将创建一个包含返回数据的`PreAuthenticatedAuthenticationToken`并提交它进行验证。
在"authentication"这里，我们实际上只是意味着可能会加载用户权限的进一步处理，但遵循标准的Spring Security身份验证体系结构。

与其他Spring Security身份验证过滤器一样，身份验证前过滤器也具有`authenticationDetailsSource`属性，默认情况下，该属性将创建一个`WebAuthenticationDetails`对象以将其他信息（如会话标识符和始发IP地址）存储在{{ 2}} `Authentication`对象的属性。
在可以从预认证机制获取用户角色信息的情况下，数据也存储在此属性中，并且具体实现了`GrantedAuthoritiesContainer`接口。
这使验证提供者能够读取外部分配给用户的权限。
接下来我们将看一个具体的例子。


[[j2ee-preauth-details]]
=====  J2eeBasedPreAuthenticatedWebAuthenticationDetailsS​​ource
如果过滤器配置了一个作为该类实例的`authenticationDetailsSource`，则通过为每个预定义的"mappable roles"调用`isUserInRole(String role)`方法来获得权限信息。
该类从配置的`MappableAttributesRetriever`中获取这些信息。
可能的实现包括在应用程序上下文中对列表进行硬编码，并从`web.xml`文件中的`<security-role>`信息中读取角色信息。
预认证示例应用程序使用后一种方法。

还有一个阶段使用配置的`Attributes2GrantedAuthoritiesMapper`将角色（或属性）映射到Spring Security `GrantedAuthority`对象。
默认情况下，只会为名称添加通常的`ROLE_`前缀，但它可以让您完全控制行为。


====  PreAuthenticatedAuthenticationProvider
预先认证的提供者要比为用户加载`UserDetails`对象做更多的事情。
它通过委托给`AuthenticationUserDetailsService`来完成。
后者与标准`UserDetailsService`类似，但采用`Authentication`对象而不仅仅是用户名：

[source,java]
----
public interface AuthenticationUserDetailsService {
	UserDetails loadUserDetails(Authentication token) throws UsernameNotFoundException;
}
----

此接口也可能有其他用途，但通过预认证，它允许访问打包在`Authentication`对象中的权限，如我们在前一节中看到的那样。
`PreAuthenticatedGrantedAuthoritiesUserDetailsService`类执行此操作。
或者，它可以通过`UserDetailsByNameServiceWrapper`实施委托给标准`UserDetailsService`。

====  Http403ForbiddenEntryPoint
<<tech-intro-auth-entry-point,technical overview>>一章讨论了`AuthenticationEntryPoint`。
通常，它负责启动未经身份验证的用户（当他们尝试访问受保护的资源时）的身份验证过程，但在预先验证的情况下，这不适用。
如果您未将预认证与其他认证机制结合使用，那么您只会将`ExceptionTranslationFilter`配置为具有此类的实例。
如果用户被`AbstractPreAuthenticatedProcessingFilter`拒绝，则会被调用，从而导致空身份验证。
如果被调用，它总是返回一个`403`  - 禁止的响应代码。


=== 具体实现
其<<x509,own chapter>>中涵盖了X.509认证。
在这里，我们将看看一些为其他预认证方案提供支持的类。


==== 请求标头认证（Siteminder）
外部认证系统可以通过在HTTP请求上设置特定标头来向应用程序提供信息。
一个众所周知的例子是Siteminder，它在名为`SM_USER`的标头中传递用户名。
该机制由`RequestHeaderAuthenticationFilter`类简单地从头中提取用户名来支持。
它默认使用名称`SM_USER`作为标题名称。
查看Javadoc了解更多详情。

[TIP]
====
请注意，使用这样的系统时，框架完全不执行身份验证检查，而且__extremely__非常重要，因为外部系统已正确配置并保护对应用程序的所有访问。
如果攻击者能够在未检测到原始请求的情况下伪造标头，那么他们可能会选择他们希望的任何用户名。
====

=====  Siteminder示例配置
使用此过滤器的典型配置如下所示：

[source,xml]
----
<security:http>
<!-- Additional http configuration omitted -->
<security:custom-filter position="PRE_AUTH_FILTER" ref="siteminderFilter" />
</security:http>

<bean id="siteminderFilter" class="org.springframework.security.web.authentication.preauth.RequestHeaderAuthenticationFilter">
<property name="principalRequestHeader" value="SM_USER"/>
<property name="authenticationManager" ref="authenticationManager" />
</bean>

<bean id="preauthAuthProvider" class="org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationProvider">
<property name="preAuthenticatedUserDetailsService">
	<bean id="userDetailsServiceWrapper"
		class="org.springframework.security.core.userdetails.UserDetailsByNameServiceWrapper">
	<property name="userDetailsService" ref="userDetailsService"/>
	</bean>
</property>
</bean>

<security:authentication-manager alias="authenticationManager">
<security:authentication-provider ref="preauthAuthProvider" />
</security:authentication-manager>
----

我们在此假设<<ns-config,security namespace>>正用于配置。
还假定您已将`UserDetailsService`（称为"userDetailsService"）添加到您的配置中以加载用户的角色。


====  Java EE容器认证
类`J2eePreAuthenticatedProcessingFilter`将从`HttpServletRequest`的`userPrincipal`属性中提取用户名。
如上所述，<<j2ee-preauth-details>>中使用此过滤器通常会与使用Java EE角色相结合。

在使用这种方法的代码库中有一个示例应用程序，因此如果您有兴趣，可以从github获取代码并查看应用程序上下文文件。
该代码位于`samples/xml/preauth`目录中。
