
[[runas]]
== 运行身份验证替换

[[runas-overview]]
=== 概述
`AbstractSecurityInterceptor`能够在安全对象回调阶段暂时替换`SecurityContext`和`SecurityContextHolder`中的`Authentication`对象。
只有在`AuthenticationManager`和`AccessDecisionManager`成功处理原始`Authentication`对象时才会发生这种情况。
`RunAsManager`将指示应在`SecurityInterceptorCallback`期间使用的替换`Authentication`对象（如果有）。

通过在安全对象回调阶段暂时替换`Authentication`对象，受保护的调用将能够调用需要不同身份验证和授权凭证的其他对象。
它也能够对特定的`GrantedAuthority`对象执行任何内部安全检查。
由于Spring Security提供了许多帮助类，可以根据`SecurityContextHolder`的内容自动配置远程协议，因此这些运行替代在调用远程Web服务时特别有用

[[runas-config]]
=== 配置
Spring Security提供了一个`RunAsManager`接口：

[source,java]
----
Authentication buildRunAs(Authentication authentication, Object object,
	List<ConfigAttribute> config);

boolean supports(ConfigAttribute attribute);

boolean supports(Class clazz);
----



第一种方法返回应在方法调用期间替换现有的`Authentication`对象的`Authentication`对象。
如果该方法返回`null`，则表示不应该进行替换。
第二种方法被`AbstractSecurityInterceptor`用作配置属性启动验证的一部分。
`supports(Class)`方法由安全拦截器实现调用，以确保配置的`RunAsManager`支持安全拦截器将呈现的安全对象的类型。

Spring Security提供了一个`RunAsManager`的具体实现。
如果`ConfigAttribute`以`RUN_AS_`开头，则`RunAsManagerImpl`类将返回替换`RunAsUserToken`。
如果找到任何此类`ConfigAttribute`，则替换`RunAsUserToken`将包含与原始`Authentication`对象相同的委托人，凭据和授予的权限，并为每个`Authentication`对象创建一个新的{{3} {4}} `ConfigAttribute`。
每个新的`SimpleGrantedAuthority`都会以`ROLE_`开头，后面跟`RUN_AS` `ConfigAttribute`。
例如，`RUN_AS_SERVER`将导致包含`ROLE_RUN_AS_SERVER`授权的替换`RunAsUserToken`。

替代`RunAsUserToken`与其他`Authentication`对象一样。
它需要通过`AuthenticationManager`进行身份验证，可能通过委派给合适的`AuthenticationProvider`。
`RunAsImplAuthenticationProvider`执行此类身份验证。
它只是接受任何提供的`RunAsUserToken`有效。

为确保恶意代码不会创建`RunAsUserToken`并将其呈现为`RunAsImplAuthenticationProvider`保证接受，密钥的散列值将存储在所有生成的令牌中。
使用相同的键在bean上下文中创建`RunAsManagerImpl`和`RunAsImplAuthenticationProvider`：

[source,xml]
----

<bean id="runAsManager"
	class="org.springframework.security.access.intercept.RunAsManagerImpl">
<property name="key" value="my_run_as_password"/>
</bean>

<bean id="runAsAuthenticationProvider"
	class="org.springframework.security.access.intercept.RunAsImplAuthenticationProvider">
<property name="key" value="my_run_as_password"/>
</bean>
----



通过使用相同的密钥，每个`RunAsUserToken`都可以验证它是由批准的`RunAsManagerImpl`创建的。
出于安全原因，`RunAsUserToken`在创建之后是不可变的
