
[[x509]]
==  X.509身份验证


[[x509-overview]]
=== 概述
X.509证书认证的最常见用途是验证使用SSL时服务器的身份，最常见的情况是从浏览器使用HTTPS。
浏览器将自动检查由服务器提供的证书是否由其维护的可信证书颁发机构列表中的一个颁发（即数字签名）。

您也可以在"mutual authentication"上使用SSL;服务器将作为SSL握手的一部分向客户端请求有效的证书。
服务器将通过检查其证书是否由可接受的权限进行签名来验证客户端。
如果提供了有效的证书，它可以通过应用程序中的servlet API获取。
Spring Security X.509模块使用过滤器提取证书。
它将证书映射到应用程序用户，并加载该用户的授权权限以供标准Spring Security基础结构使用。

在尝试将它用于Spring Security之前，您应该熟悉使用证书并为您的servlet容器设置客户端身份验证。
大部分工作是创建和安装合适的证书和密钥。
例如，如果您使用Tomcat，请阅读 http://tomcat.apache.org/tomcat-6.0-doc/ssl-howto.html[http://tomcat.apache.org/tomcat-6.0-doc/ssl-howto.html]中的说明。
在使用Spring Security进行试用之前，务必使用它


=== 将X.509身份验证添加到您的Web应用程序中
启用X.509客户端身份验证非常简单。
只需将`<x509/>`元素添加到您的http安全性名称空间配置中即可。

[source,xml]
----
<http>
...
	<x509 subject-principal-regex="CN=(.*?)," user-service-ref="userService"/>;
</http>
----

该元素有两个可选属性：

* `subject-principal-regex`.
正则表达式用于从证书的主题名称中提取用户名。
上面显示了默认值。
这是传递给`UserDetailsService`的用户名，用于为用户加载权限。
* `user-service-ref`.
这是与X.509一起使用的`UserDetailsService`的bean ID。
如果在应用程序上下文中只定义了一个，则不需要。

`subject-principal-regex`应该包含一个组。
例如，默认表达式"CN=(.*?),"与公共名称字段匹配。
因此，如果证书中的主题名称是"CN=Jimi Hendrix, OU=..."，则会给出用户名"Jimi Hendrix"。
这些匹配不区分大小写。
因此，"emailAddress=(.?),"将匹配"EMAILADDRESS=jimi@hendrix.org,CN=..."，并提供用户名"jimi@hendrix.org"。
如果客户端提交证书并且成功提取了有效用户名，则安全上下文中应该有一个有效的`Authentication`对象。
如果没有找到证书，或者找不到相应的用户，那么安全上下文将保持空白。
这意味着您可以使用其他选项（如基于表单的登录）轻松使用X.509身份验证。

[[x509-ssl-config]]
=== 在Tomcat中设置SSL
在Spring Security项目的`samples/certificate`目录中有一些预先生成的证书。
如果您不想生成自己的文件，您可以使用这些文件来启用SSL进行测试。
文件`server.jks`包含服务器证书，私钥和颁发证书颁发机构证书。
还有一些来自示例应用程序的用户的客户端证书文件。
您可以在浏览器中安装这些以启用SSL客户端身份验证。

要运行带有SSL支持的tomcat，请将`server.jks`文件放入tomcat `conf`目录，并将以下连接器添加到`server.xml`文件

[source,xml]
----

<Connector port="8443" protocol="HTTP/1.1" SSLEnabled="true" scheme="https" secure="true"
			clientAuth="true" sslProtocol="TLS"
			keystoreFile="${catalina.home}/conf/server.jks"
			keystoreType="JKS" keystorePass="password"
			truststoreFile="${catalina.home}/conf/server.jks"
			truststoreType="JKS" truststorePass="password"
/>

----

如果即使客户端没有提供证书，仍然希望SSL连接成功，也可以将`clientAuth`设置为`want`。
除非使用非X.509身份验证机制（例如表单身份验证），否则未提供证书的客户将无法访问由Spring Security保护的任何对象。

