[[servlet-authentication-authentication]]
= Authentication

The {security-api-url}org/springframework/security/core/Authentication.html[`Authentication`] interface serves two main purposes within Spring Security:

* An input to <<servlet-authentication-authenticationmanager,`AuthenticationManager`>> to provide the credentials a user has provided to authenticate.
When used in this scenario, `isAuthenticated()` returns `false`.
* Represent the currently authenticated user.
You can obtain the current `Authentication` from the <<servlet-authentication-securitycontext>>.

The `Authentication` contains:

* `principal`: Identifies the user.
When authenticating with a username/password this is often an instance of <<servlet-authentication-userdetails,`UserDetails`>>.
* `credentials`: Often a password.
In many cases, this is cleared after the user is authenticated, to ensure that it is not leaked.
* `authorities`: The <<servlet-authentication-granted-authority,`GrantedAuthority`>> instances are high-level permissions the user is granted.
Two examples are roles and scopes.
