
[[anonymous]]
== 匿名身份验证


[[anonymous-overview]]
=== 概述
通常认为采用"deny-by-default"的安全做法非常好，您可以在其中明确指定允许的内容并拒绝其他所有内容。
定义未经身份验证的用户可访问的内容也是类似的情况，特别是对于Web应用程序。
许多网站要求用户必须通过除少数网址以外的其他任何验证（例如，家庭和登录页面）。
在这种情况下，为这些特定的URL定义访问配置属性是最容易的，而不是针对每个安全资源。
换句话说，有时很高兴地说默认情况下`ROLE_SOMETHING`是必需的，并且只允许某些例外情况，例如登录，注销和应用程序的主页。
您也可以完全忽略过滤器链中的这些页面，从而绕过访问控制检查，但这可能因其他原因而不受欢迎，特别是如果页面对经过身份验证的用户的行为不同。

这就是我们所说的匿名认证。
请注意，"anonymously authenticated"的用户与未经身份验证的用户之间没有真正的概念区别。
Spring Security的匿名身份验证只是为您提供一种更方便的配置访问控制属性的方式。
例如，调用诸如`getCallerPrincipal`的servlet API调用，即使实际上存在`SecurityContextHolder`中的匿名认证对象，仍将返回null。

在其他情况下，匿名身份验证很有用，例如审计拦截器查询`SecurityContextHolder`以确定哪个主体负责给定操作。
如果他们知道`SecurityContextHolder`始终包含`Authentication`对象，并且从不`null`，则可以更强健地编写类。


[[anonymous-config]]
=== 配置
当使用HTTP配置Spring Security 3.0时，会自动提供匿名认证支持，并且可以使用`<anonymous>`元素进行自定义（或禁用）。
除非您使用传统的bean配置，否则不需要配置这里描述的bean。

三个类共同提供匿名身份验证功能。
`AnonymousAuthenticationToken`是`Authentication`的实现，并存储适用于匿名主体的`GrantedAuthority`。
有一个对应的`AnonymousAuthenticationProvider`，链接到`ProviderManager`，以便接受`AnonymousAuthenticationToken`。
最后，还有一个`AnonymousAuthenticationFilter`，它在普通身份验证机制之后被链接，并且如果没有现有的`Authentication`，则会自动向`SecurityContextHolder`添加`AnonymousAuthenticationToken`。
筛选器和身份验证提供程序的定义如下所示：



[source,xml]
----

<bean id="anonymousAuthFilter"
	class="org.springframework.security.web.authentication.AnonymousAuthenticationFilter">
<property name="key" value="foobar"/>
<property name="userAttribute" value="anonymousUser,ROLE_ANONYMOUS"/>
</bean>

<bean id="anonymousAuthenticationProvider"
	class="org.springframework.security.authentication.AnonymousAuthenticationProvider">
<property name="key" value="foobar"/>
</bean>
----



`key`在过滤器和身份验证提供程序之间共享，以便前者创建的令牌可以被后面的脚注接受：[{
不应将`key`属性的使用视为提供任何实际安全性。
这仅仅是一个记账练习。
如果您在验证客户端可能构建`Authentication`对象（例如使用RMI调用）的情况下共享包含`AnonymousAuthenticationProvider`的{​​{0}}，则恶意客户端可以提交自己创建的`AnonymousAuthenticationToken`（使用所选的用户名和权限列表）。
如果`key`是可猜测的或可以发现的，那么该令牌将被匿名提供者接受。
这对正常使用来说并不是问题，但如果您使用RMI，则最好使用自定义`ProviderManager`，省略匿名提供程序，而不是共享您用于HTTP身份验证机制的那个。
].
`userAttribute`以`usernameInTheAuthenticationToken,grantedAuthority[,grantedAuthority]`的形式表示。
这与在`InMemoryDaoImpl`的{​​{0}}属性的等号之后使用的语法相同。

如前所述，匿名身份验证的好处是所有的URI模式都可以应用于它们。
例如：



[source,xml]
----

<bean id="filterSecurityInterceptor"
	class="org.springframework.security.web.access.intercept.FilterSecurityInterceptor">
<property name="authenticationManager" ref="authenticationManager"/>
<property name="accessDecisionManager" ref="httpRequestAccessDecisionManager"/>
<property name="securityMetadata">
	<security:filter-security-metadata-source>
	<security:intercept-url pattern='/index.jsp' access='ROLE_ANONYMOUS,ROLE_USER'/>
	<security:intercept-url pattern='/hello.htm' access='ROLE_ANONYMOUS,ROLE_USER'/>
	<security:intercept-url pattern='/logoff.jsp' access='ROLE_ANONYMOUS,ROLE_USER'/>
	<security:intercept-url pattern='/login.jsp' access='ROLE_ANONYMOUS,ROLE_USER'/>
	<security:intercept-url pattern='/**' access='ROLE_USER'/>
	</security:filter-security-metadata-source>" +
</property>
</bean>
----




[[anonymous-auth-trust-resolver]]
===  AuthenticationTrustResolver
舍弃匿名身份验证讨论的是`AuthenticationTrustResolver`接口及其相应的`AuthenticationTrustResolverImpl`实现。
该接口提供了`isAnonymous(Authentication)`方法，它允许感兴趣的类考虑这种特殊类型的身份验证状态。
`ExceptionTranslationFilter`在处理`AccessDeniedException`时使用此接口。
如果`AccessDeniedException`被抛出，并且身份验证是匿名类型，而不是抛出403（禁止）响应，则过滤器将改为开始`AuthenticationEntryPoint`，以便委托人可以正确进行身份验证。
这是一个必要的区别，否则委托人将始终被视为"authenticated"，永远不会有机会通过表单，基本，摘要或其他正常的身份验证机制进行登录。

您经常会看到上述拦截器配置中的`ROLE_ANONYMOUS`属性被`IS_AUTHENTICATED_ANONYMOUSLY`替代，这在定义访问控制时实际上是同样的事情。
这是使用我们将在<<authz-authenticated-voter,authorization chapter>>中看到的`AuthenticatedVoter`的一个示例。
它使用`AuthenticationTrustResolver`来处理这个特定的配置属性并授予匿名用户访问权限。
`AuthenticatedVoter`方法更强大，因为它允许区分匿名，记住我和完全认证的用户。
如果您不需要此功能，那么您可以坚持使用`ROLE_ANONYMOUS`，这将由Spring Security的标准`RoleVoter`处理。
