
[[basic]]
== 基本和摘要式身份验证
基本和摘要式身份验证是在Web应用程序中流行的备用身份验证机制。
基本身份验证通常用于在每个请求上传递其凭据的无状态客户端。
将它与基于表单的身份验证结合使用是非常常见的，其中通过基于浏览器的用户界面和作为Web服务来使用应用程序。
但是，基本身份验证将密码作为纯文本传输，因此它应该只能用于加密的传输层（如HTTPS）。

[[basic-processing-filter]]
===  BasicAuthenticationFilter一样
`BasicAuthenticationFilter`负责处理HTTP标头中显示的基本认证凭证。
这可以用于验证Spring Remoting协议（例如Hessian和Burlap）以及普通浏览器用户代理（如Firefox和Internet Explorer）所做的调用。
控制HTTP基本认证的标准由RFC 1945第11节定义，`BasicAuthenticationFilter`符合本RFC。
基本身份验证是一种非常有吸引力的身份验证方法，因为它在用户代理中非常广泛地部署，并且实现非常简单（它只是用户名：密码的Base64编码，在HTTP标头中指定）。

[[basic-config]]
==== 配置
要实施HTTP基本认证，您需要将`BasicAuthenticationFilter`添加到您的过滤器链中。
应用程序上下文应包含`BasicAuthenticationFilter`及其所需的协作者：


[source,xml]
----
<bean id="basicAuthenticationFilter"
class="org.springframework.security.web.authentication.www.BasicAuthenticationFilter">
<property name="authenticationManager" ref="authenticationManager"/>
<property name="authenticationEntryPoint" ref="authenticationEntryPoint"/>
</bean>

<bean id="authenticationEntryPoint"
class="org.springframework.security.web.authentication.www.BasicAuthenticationEntryPoint">
<property name="realmName" value="Name Of Your Realm"/>
</bean>
----

配置的`AuthenticationManager`处理每个认证请求。
如果认证失败，则配置的`AuthenticationEntryPoint`将用于重试认证过程。
通常，您将结合`BasicAuthenticationEntryPoint`使用过滤器，该过滤器会返回带有合适标头的401响应，以重试HTTP基本身份验证。
如果认证成功，则像往常一样将生成的`Authentication`对象放入`SecurityContextHolder`。

如果认证事件成功，或者由于HTTP标头不包含支持的认证请求而未尝试认证，则过滤器链将照常继续。
过滤器链将被中断的唯一时间是身份验证失败并调用`AuthenticationEntryPoint`。

[[digest-processing-filter]]
===  DigestAuthenticationFilter
`DigestAuthenticationFilter`能够处理HTTP头中提供的摘要式身份验证凭证。
摘要式身份验证尝试解决许多基本身份验证的弱点，特别是通过确保证书永远不会以明文形式在整个线路上发送。
许多用户代理支持摘要式身份验证，包括Mozilla Firefox和Internet Explorer。
控制HTTP摘要认证的标准由RFC 2617定义，该RFC 2617更新RFC 2069规定的早期版本的摘要认证标准。
大多数用户代理实现RFC 2617。
Spring Security的`DigestAuthenticationFilter`与RFC 2617规定的"`auth`"保护质量（`qop`）兼容，后者也提供与RFC 2069的向后兼容性。
如果您需要使用未加密的HTTP（即无TLS / HTTPS）并希望最大限度地提高身份验证过程的安全性，则摘要式身份验证是一种更具吸引力的选项。
事实上，如RFC 2518第17.1节所述，摘要式身份验证是WebDAV协议的强制性要求。

[NOTE]
====
您不应该在现代应用程序中使用摘要，因为它不被认为是安全的。
最明显的问题是，您必须以明文，加密或MD5格式存储您的密码。
所有这些存储格式都被认为是不安全的。
相反，您应该使用单向自适应密码哈希（即bCrypt，PBKDF2，SCrypt等）。
====

摘要式身份验证的核心是"nonce"。
这是服务器生成的值。
Spring Security的随机数采用以下格式：

[source,txt]
----
base64(expirationTime + ":" + md5Hex(expirationTime + ":" + key))
expirationTime:   The date and time when the nonce expires, expressed in milliseconds
key:              A private key to prevent modification of the nonce token
----

`DigestAuthenticatonEntryPoint`具有一个属性，用于指定用于生成随机标记的`key`以及用于确定到期时间的默认值`nonceValiditySeconds`（默认值300，等于5分钟）。
Whist的nonce有效，摘要是通过连接各种字符串来计算的，包括用户名，密码，nonce，被请求的URI，客户端生成的nonce（仅仅是用户代理生成每个请求的随机值），域名等，然后执行MD5哈希。
服务器和用户代理都执行此摘要计算，如果他们不同意所包含的值（例如密码），则会生成不同的哈希码。
在Spring Security实现中，如果服务器生成的nonce仅仅过期（但摘要本来是有效的），`DigestAuthenticationEntryPoint`将发送一个`"stale=true"`头。
这告诉用户代理不需要打扰用户（因为密码和用户名等是正确的），而只是使用新的随机数再次尝试。

`DigestAuthenticationEntryPoint`的{​​{0}}参数的适当值取决于您的应用程序。
非常安全的应用程序应该注意，可以使用截取的身份验证标头模拟主体，直到达到现时包含的`expirationTime`。
这是选择适当设置时的关键原则，但对于非常安全的应用程序而言，首先不会在TLS / HTTPS上运行，这种情况并不常见。

由于Digest身份验证的实现比较复杂，因此通常会出现用户代理问题。
例如，Internet Explorer无法在同一个会话的后续请求中显示"`opaque`"令牌。
Spring Security过滤器因此将所有状态信息封装到"`nonce`"令牌中。
在我们的测试中，Spring Security的实现可以在Mozilla Firefox和Internet Explorer中可靠地工作，正确处理nonce超时等。


[[digest-config]]
==== 配置
现在我们已经回顾了理论，让我们看看如何使用它。
要实现HTTP摘要认证，有必要在过滤器链中定义`DigestAuthenticationFilter`。
应用程序上下文将需要定义`DigestAuthenticationFilter`及其所需的协作者：

[source,xml]
----
<bean id="digestFilter" class=
	"org.springframework.security.web.authentication.www.DigestAuthenticationFilter">
<property name="userDetailsService" ref="jdbcDaoImpl"/>
<property name="authenticationEntryPoint" ref="digestEntryPoint"/>
<property name="userCache" ref="userCache"/>
</bean>

<bean id="digestEntryPoint" class=
	"org.springframework.security.web.authentication.www.DigestAuthenticationEntryPoint">
<property name="realmName" value="Contacts Realm via Digest Authentication"/>
<property name="key" value="acegi"/>
<property name="nonceValiditySeconds" value="10"/>
</bean>
----

配置的`UserDetailsService`是必需的，因为`DigestAuthenticationFilter`必须能够直接访问用户的明文密码。
如果在DAO脚注中使用编码密码，摘要式身份验证将不起作用：[如果`DigestAuthenticationFilter.passwordAlreadyEncoded`设置为{{}，则可以使用HEX格式（MD5（用户名：realm：password） 1}}。
但是，其他密码编码不适用于摘要式身份验证。]。
DAO协作者和`UserCache`通常直接与`DaoAuthenticationProvider`共享。
`authenticationEntryPoint`属性必须为`DigestAuthenticationEntryPoint`，以便`DigestAuthenticationFilter`可以获取正确的`realmName`和`key`以进行摘要计算。

与`BasicAuthenticationFilter`类似，如果认证成功，`Authentication`请求令牌将被放入`SecurityContextHolder`中。
如果身份验证事件成功，或者由于HTTP头未包含摘要身份验证请求而未尝试身份验证，则过滤器链将照常继续。
过滤器链将被中断的唯一时间是如果验证失败并且调用`AuthenticationEntryPoint`，如前段所述。

摘要式身份验证RFC提供了一系列附加功能以进一步提高安全性。
例如，可以在每个请求中更改随机数。
尽管如此，Spring Security实现的目的是尽量减少实现的复杂性（以及可能出现的无疑的用户代理不兼容），并避免存储服务器端状态。
如果您希望更详细地了解这些功能，请您参阅RFC 2617。
据我们所知，Spring Security的实现符合RFC的最低标准。
