
[[core-web-filters]]
== 核心安全筛选器
在使用Spring Security的Web应用程序中总是会使用一些关键过滤器，所以我们先看看这些及其支持类和接口。
我们不会涵盖每个功能，因此如果您想要获得完整的图片，请务必查看它们的Javadoc。

[[filter-security-interceptor]]
===  FilterSecurityInterceptor
在讨论<<tech-intro-access-control,access-control in general>>时，我们已经简要地看到了`FilterSecurityInterceptor`，并且我们已经将`<intercept-url>`元素的名称空间用于其内部进行配置。
现在我们将看到如何显式配置它以与`FilterChainProxy`一起使用，以及其伴随过滤器`ExceptionTranslationFilter`。
典型配置示例如下所示：

[source,xml]
----
<bean id="filterSecurityInterceptor"
	class="org.springframework.security.web.access.intercept.FilterSecurityInterceptor">
<property name="authenticationManager" ref="authenticationManager"/>
<property name="accessDecisionManager" ref="accessDecisionManager"/>
<property name="securityMetadataSource">
	<security:filter-security-metadata-source>
	<security:intercept-url pattern="/secure/super/**" access="ROLE_WE_DONT_HAVE"/>
	<security:intercept-url pattern="/secure/**" access="ROLE_SUPERVISOR,ROLE_TELLER"/>
	</security:filter-security-metadata-source>
</property>
</bean>
----

`FilterSecurityInterceptor`负责处理HTTP资源的安全性。
它需要引用`AuthenticationManager`和`AccessDecisionManager`。
它还提供了适用于不同HTTP URL请求的配置属性。
请参阅技术介绍中的<<tech-intro-config-attributes,the original discussion on these>>。

`FilterSecurityInterceptor`可以通过两种方式配置配置属性。
上面显示的第一个使用`<filter-security-metadata-source>`命名空间元素。
这与命名空间章节中的`<http>`元素相似，但`<intercept-url>`子元素仅使用`pattern`和`access`属性。
逗号用于分隔适用于每个HTTP URL的不同配置属性。
第二种选择是编写自己的`SecurityMetadataSource`，但这超出了本文的范围。
无论使用何种方法，`SecurityMetadataSource`都负责返回包含与单个安全HTTP URL关联的所有配置属性的`List<ConfigAttribute>`。

应该注意的是`FilterSecurityInterceptor.setSecurityMetadataSource()`方法实际上期望`FilterInvocationSecurityMetadataSource`的一个实例。
这是一个标记接口，其子类`SecurityMetadataSource`。
它仅表示`SecurityMetadataSource`理解`FilterInvocation`。
为了简单起见，我们将继续将`FilterInvocationSecurityMetadataSource`称为`SecurityMetadataSource`，因为区分与大多数用户的关系不大。

通过命名空间语法创建的`SecurityMetadataSource`通过将请求URL与配置的`pattern`属性进行匹配来获取特定`FilterInvocation`的配置属性。
这与命名空间配置的行为方式相同。
默认情况下，将所有表达式视为Apache Ant路径，正则表达式也支持更复杂的情况。
`request-matcher`属性用于指定正在使用的模式的类型。
在相同的定义中混合表达式语法是不可能的。
作为一个例子，使用正则表达式而不是Ant路径的前面的配置将被写成如下：

[source,xml]
----
<bean id="filterInvocationInterceptor"
	class="org.springframework.security.web.access.intercept.FilterSecurityInterceptor">
<property name="authenticationManager" ref="authenticationManager"/>
<property name="accessDecisionManager" ref="accessDecisionManager"/>
<property name="runAsManager" ref="runAsManager"/>
<property name="securityMetadataSource">
	<security:filter-security-metadata-source request-matcher="regex">
	<security:intercept-url pattern="\A/secure/super/.*\Z" access="ROLE_WE_DONT_HAVE"/>
	<security:intercept-url pattern="\A/secure/.*\" access="ROLE_SUPERVISOR,ROLE_TELLER"/>
	</security:filter-security-metadata-source>
</property>
</bean>
----

模式总是按照它们定义的顺序进行评估。
因此，重要的是更多的特定模式在列表中定义得比较不具体的模式更高。
这反映在我们上面的示例中，其中更具体的`/secure/super/`模式显示高于不太具体的`/secure/`模式。
如果它们相反，则`/secure/`模式将始终匹配，并且永远不会评估`/secure/super/`模式。

[[exception-translation-filter]]
=== 的ExceptionTranslationFilter
`ExceptionTranslationFilter`位于安全筛选器堆栈中`FilterSecurityInterceptor`的上方。
它本身并不执行任何实际的安全性实施，但处理安全拦截器引发的异常并提供合适的HTTP响应。

[source,xml]
----

<bean id="exceptionTranslationFilter"
class="org.springframework.security.web.access.ExceptionTranslationFilter">
<property name="authenticationEntryPoint" ref="authenticationEntryPoint"/>
<property name="accessDeniedHandler" ref="accessDeniedHandler"/>
</bean>

<bean id="authenticationEntryPoint"
class="org.springframework.security.web.authentication.LoginUrlAuthenticationEntryPoint">
<property name="loginFormUrl" value="/login.jsp"/>
</bean>

<bean id="accessDeniedHandler"
	class="org.springframework.security.web.access.AccessDeniedHandlerImpl">
<property name="errorPage" value="/accessDenied.htm"/>
</bean>

----

[[auth-entry-point]]
==== 的AuthenticationEntryPoint
如果用户请求安全的HTTP资源，但它们未通过身份验证，则将调用`AuthenticationEntryPoint`。
一个合适的`AuthenticationException`或`AccessDeniedException`将被进一步向下调用堆栈的安全拦截器引发，触发入口点上的`commence`方法。
这可以向用户提供适当的响应，以便开始认证。
我们这里使用的是`LoginUrlAuthenticationEntryPoint`，它将请求重定向到不同的URL（通常是登录页面）。
所使用的实际实现将取决于您希望在应用程序中使用的身份验证机制。


[[access-denied-handler]]
====  AccessDeniedHandler
如果用户已经通过身份验证并且他们尝试访问受保护的资源，会发生什么情况？在正常使用情况下，不应该发生这种情况，因为应用程序工作流程应限制为用户有权访问的操作。
例如，到管理页面的HTML链接可能对没有管理员角色的用户隐藏。
尽管如此，您不能依赖隐藏链接的安全性，因为用户总是可能直接输入URL来尝试绕过限制。
或者他们可能会修改一个RESTful URL来更改一些参数值。
您的应用程序必须受到保护以免出现这些情况，否则它肯定会变得不安全
您通常会使用简单的Web层安全性将约束应用于基本URL，并在您的服务层接口上使用更具体的基于方法的安全性来真正确定允许的内容。

如果`AccessDeniedException`被抛出并且用户已经被认证，那么这意味着已经尝试了他们没有足够权限的操作。
在这种情况下，`ExceptionTranslationFilter`将调用第二个策略`AccessDeniedHandler`。
默认情况下，使用`AccessDeniedHandlerImpl`，仅向客户端发送403（禁止）响应。
或者，您可以显式配置一个实例（如上例），并设置一个错误页面URL，它将把请求转发给脚注：[
我们使用forward，以便SecurityContextHolder仍然包含主体的细节，这对于向用户显示可能是有用的。
在Spring Security的旧版本中，我们依靠servlet容器来处理缺少这种有用上下文信息的403错误消息。
].
这可以是简单的"access denied"页面，如JSP，也可以是更复杂的处理程序，如MVC控制器。
当然，你可以自己实现接口并使用你自己的实现。

当您使用命名空间来配置应用程序时，也可以提供自定义的`AccessDeniedHandler`。
有关更多详情，请参阅<<nsa-access-denied-handler,the namespace appendix>>。


[[request-caching]]
====  SavedRequest和RequestCache接口
`ExceptionTranslationFilter`职责的另一个责任是在调用`AuthenticationEntryPoint`之前保存当前请求。
这允许在用户通过身份验证后恢复请求（请参阅之前的<<tech-intro-web-authentication,web authentication>>概述）。
一个典型的例子是用户使用表单登录，然后通过默认`SavedRequestAwareAuthenticationSuccessHandler`（请参阅<<form-login-flow-handling,below>>）重定向到原始URL。

`RequestCache`封装了存储和检索`HttpServletRequest`实例所需的功能。
默认情况下使用`HttpSessionRequestCache`，将请求存储在`HttpSession`中。
当用户被重定向到原始URL时，`RequestCacheFilter`实际上可以恢复缓存中保存的请求。

在正常情况下，您不需要修改任何此功能，但保存的请求处理是"best-effort"方法，并且可能存在默认配置无法处理的情况。
这些接口的使用使它可以从Spring Security 3.0开始完全插入。


[[security-context-persistence-filter]]
===  SecurityContextPersistenceFilter
我们在<<tech-intro-sec-context-persistence,Technical Overview>>一章中介绍了此重要过滤器的用途，因此您可能需要重新阅读该部分。
我们先来看看如何将它配置为与`FilterChainProxy`一起使用。
基本配置只需要bean本身

[source,xml]
----
<bean id="securityContextPersistenceFilter"
class="org.springframework.security.web.context.SecurityContextPersistenceFilter"/>
----

正如我们以前所见，这个过滤器有两个主要任务。
它负责存储HTTP请求之间的`SecurityContext`内容，并在请求完成时清除`SecurityContextHolder`。
清除存储上下文的`ThreadLocal`是非常重要的，因为否则可能会将一个线程替换到servlet容器的线程池中，同时为特定用户提供安全上下文。
此线程可能会在稍后阶段使用，并使用错误的凭据执行操作。


[[security-context-repository]]
====  SecurityContextRepository
从Spring Security 3.0开始，加载和存储安全上下文的工作现在被委派给一个单独的策略接口：

[source,java]
----
public interface SecurityContextRepository {

SecurityContext loadContext(HttpRequestResponseHolder requestResponseHolder);

void saveContext(SecurityContext context, HttpServletRequest request,
		HttpServletResponse response);
}
----

`HttpRequestResponseHolder`只是传入请求和响应对象的容器，允许实现用包装类替换它们。
返回的内容将被传递给过滤器链。

默认实现是`HttpSessionSecurityContextRepository`，它将安全性上下文存储为`HttpSession`属性脚注：[在Spring Security 2.0及更早版本中，此过滤器被称为`HttpSessionContextIntegrationFilter`并执行所有存储上下文是由过滤器本身执行的。
如果您熟悉此课程，则可以在`HttpSessionSecurityContextRepository`上找到大多数可用的配置选项。]。
此实现的最重要的配置参数是`allowSessionCreation`属性，该属性默认为`true`，因此如果类需要存储经过身份验证的用户的安全上下文，则允许该类创建会话除非进行认证并且安全上下文的内容已经改变，否则不会创建一个）。
如果您不想创建会话，则可以将此属性设置为`false`：

[source,xml]
----
<bean id="securityContextPersistenceFilter"
	class="org.springframework.security.web.context.SecurityContextPersistenceFilter">
<property name='securityContextRepository'>
	<bean class='org.springframework.security.web.context.HttpSessionSecurityContextRepository'>
	<property name='allowSessionCreation' value='false' />
	</bean>
</property>
</bean>
----

或者，您可以提供一个`NullSecurityContextRepository`实例，一个 http://en.wikipedia.org/wiki/Null_Object_pattern[空对象]实现，它将阻止安全上下文被存储，即使在请求期间已经创建了一个会话。


[[form-login-filter]]
===  UsernamePasswordAuthenticationFilter
现在我们已经看到Spring Security web配置中总是存在三种主要的过滤器。
这些也是由名称空间`<http>`元素自动创建的三个元素，不能用替代项替代。
现在唯一缺少的是一种实际的身份验证机制，它允许用户进行身份验证。
这个过滤器是最常用的认证过滤器，也是最经常定制脚注的过滤器：[由于历史原因，在Spring Security 3.0之前，此过滤器被称为`AuthenticationProcessingFilter`，入口点被称为`AuthenticationProcessingFilterEntryPoint` 。
由于框架现在支持许多不同形式的认证，因此它们在3.0中都被赋予了更具体的名称。]。
它还提供名称空间中`<form-login>`元素使用的实现。
配置它需要三个阶段。

* 使用登录页面的网址配置`LoginUrlAuthenticationEntryPoint`，就像我们上面所做的一样，并将其设置在`ExceptionTranslationFilter`上。
* 实现登录页面（使用JSP或MVC控制器）。
* 在应用程序上下文中配置`UsernamePasswordAuthenticationFilter`的实例
* 将过滤器bean添加到您的过滤器链代理中（确保您注意订单）。

登录表单只包含`username`和`password`个输入字段，并发布到由过滤器监控的网址（默认情况下为`/login`）。
基本的过滤器配置如下所示：

[source,xml]
----
<bean id="authenticationFilter" class=
"org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter">
<property name="authenticationManager" ref="authenticationManager"/>
</bean>
----

[[form-login-flow-handling]]
==== 认证成功和失败的应用程序流程
过滤器会调用配置的`AuthenticationManager`来处理每个认证请求。
成功认证或认证失败后的目的地分别由`AuthenticationSuccessHandler`和`AuthenticationFailureHandler`策略接口控制。
该过滤器的属性允许您设置这些属性，以便您可以完全自定义行为脚注：[在3.0之前的版本中，此时的应用程序流已经演变为一个阶段，由此类和策略插件。
该决定是为了重构代码以使这两个策略完全负责。]。
提供了一些标准实现，如`SimpleUrlAuthenticationSuccessHandler`，`SavedRequestAwareAuthenticationSuccessHandler`，`SimpleUrlAuthenticationFailureHandler`，`ExceptionMappingAuthenticationFailureHandler`和`DelegatingAuthenticationFailureHandler`。
查看这些类的Javadoc，并了解`AbstractAuthenticationProcessingFilter`以了解它们如何工作以及支持的功能。

如果认证成功，则生成的`Authentication`对象将被放置到`SecurityContextHolder`中。
然后会调用配置的`AuthenticationSuccessHandler`将用户重定向或转发到适当的目标。
默认情况下使用`SavedRequestAwareAuthenticationSuccessHandler`，这意味着用户在被要求登录之前将被重定向到他们要求的原始目的地。

[NOTE]
====
`ExceptionTranslationFilter`缓存用户所做的原始请求。
当用户进行身份验证时，请求处理程序使用此缓存请求来获取原始URL并将其重定向到它。
原始请求然后被重建并用作替代。
====

如果认证失败，则会调用配置的`AuthenticationFailureHandler`。
