
[[headers]]
== 安全性HTTP响应头
本节讨论Spring Security支持将各种安全头添加到响应中。

=== 默认安全标题
Spring Security允​​许用户轻松地注入默认安全头以帮助保护他们的应用程序。
Spring Security的默认设置是包含以下标题：

[source,http]
----
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
----

注意：仅在HTTPS请求上添加严格传输安全性

有关每个标题的更多详细信息，请参阅相应章节：

* <<headers-cache-control,Cache Control>>
* <<headers-content-type-options,Content Type Options>>
* <<headers-hsts,HTTP Strict Transport Security>>
* <<headers-frame-options,X-Frame-Options>>
* <<headers-xss-protection,X-XSS-Protection>>

虽然这些标题都被认为是最佳实践，但应该指出，并非所有客户都使用标题，因此鼓励进行其他测试。

您可以自定义特定的标题。
例如，假设您希望您的HTTP响应标头如下所示：

[source,http]
----
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
----

具体来说，您需要使用以下自定义设置的所有默认标题：

*  <<headers-frame-options,X-Frame-Options>>允许来自同一个域的任何请求
*  <<headers-hsts,HTTP Strict Transport Security (HSTS)>>不会被添加到响应中

您可以使用以下Java配置轻松完成此操作：

[source,java]
----
@EnableWebSecurity
public class WebSecurityConfig extends
		WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			// ...
			.headers()
				.frameOptions().sameOrigin()
				.httpStrictTransportSecurity().disable();
	}
}
----

或者，如果您使用的是Spring Security XML Configuration，则可以使用以下内容：

[source,xml]
----
<http>
	<!-- ... -->

	<headers>
		<frame-options policy="SAMEORIGIN" />
		<hsts disable="true"/>
	</headers>
</http>
----

如果您不希望添加默认设置并希望明确控制应该使用的内容，则可以禁用默认设置。
下面提供了一个基于Java和XML的配置示例：

如果您使用的是Spring Security的Java配置，以下内容仅会添加<<headers-cache-control,Cache Control>>。

[source,java]
----
@EnableWebSecurity
public class WebSecurityConfig extends
WebSecurityConfigurerAdapter {

@Override
protected void configure(HttpSecurity http) throws Exception {
	http
	// ...
	.headers()
		// do not use any default headers unless explicitly listed
		.defaultsDisabled()
		.cacheControl();
}
}
----

以下XML仅会添加<<headers-cache-control,Cache Control>>。

[source,xml]
----
<http>
	<!-- ... -->

	<headers defaults-disabled="true">
		<cache-control/>
	</headers>
</http>
----


如有必要，可以使用以下Java配置禁用所有HTTP安全响应标头：

[source,java]
----
@EnableWebSecurity
public class WebSecurityConfig extends
WebSecurityConfigurerAdapter {

@Override
protected void configure(HttpSecurity http) throws Exception {
	http
	// ...
	.headers().disable();
}
}
----

如有必要，可以使用下面的XML配置禁用所有HTTP安全响应标头：

[source,xml]
----
<http>
	<!-- ... -->

	<headers disabled="true" />
</http>
----

[[headers-cache-control]]
==== 缓存控制
在过去，Spring Security要求您为您的Web应用程序提供自己的缓存控制。
这在当时似乎是合理的，但浏览器缓存已经发展到包括用于安全连接的缓存。
这意味着用户可以查看已认证的页面并注销，然后恶意用户可以使用浏览器历史记录查看缓存的页面。
为了帮助缓解这个问题，Spring Security增加了缓存控制支持，它将在响应中插入以下头文件。

[source]
----
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
----

简单地添加没有子元素的<<nsa-headers,<headers>>>元素将自动添加缓存控制和其他一些保护。
但是，如果您只需要缓存控制，则可以使用带有<<nsa-cache-control,<cache-control>>>元素和<<nsa-headers-defaults-disabled,headers@defaults-disabled>>属性的Spring Security的XML名称空间启用此功能。

[source,xml]
----
<http>
	<!-- ... -->

	<headers defaults-disable="true">
		<cache-control />
	</headers>
</http>
----

同样，您可以通过以下方式仅启用Java配置中的缓存控制：

[source,java]
----
@EnableWebSecurity
public class WebSecurityConfig extends
WebSecurityConfigurerAdapter {

@Override
protected void configure(HttpSecurity http) throws Exception {
	http
	// ...
	.headers()
		.defaultsDisabled()
		.cacheControl();
}
}
----

如果您真的想缓存特定的响应，您的应用程序可以选择性地调用 http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletResponse.html#setHeader(java.lang.String,java.lang.String)[HttpServletResponse.setHeader（字符串，字符串）]来覆盖Spring Security设置的标头。
这对于确保像CSS，JavaScript和图像等正确缓存很有用。

在使用Spring Web MVC时，通常在您的配置中完成。
例如，以下配置将确保为所有资源设置缓存标头：

[source,java]
----
@EnableWebMvc
public class WebMvcConfiguration implements WebMvcConfigurer {

	@Override
	public void addResourceHandlers(ResourceHandlerRegistry registry) {
		registry
			.addResourceHandler("/resources/**")
			.addResourceLocations("/resources/")
			.setCachePeriod(31556926);
	}

	// ...
}
----

[[headers-content-type-options]]
==== 内容类型选项
历史上，浏览器（包括Internet Explorer）会尝试使用 http://en.wikipedia.org/wiki/Content_sniffing[内容嗅探]来猜测请求的内容类型。
这允许浏览器通过猜测未指定内容类型的资源上的内容类型来改善用户体验。
例如，如果浏览器遇到没有指定内容类型的JavaScript文件，它将能够猜测内容类型并执行它。

[NOTE]
====
在允许上传内容时，应该做很多其他事情（即，仅在不同域中显示文档，确保设置Content-Type标头，清理文档等）。
但是，这些措施超出了Spring Security提供的范围。
指出禁用内容嗅探时，还必须指出内容类型以使事情正常工作。
====

内容嗅探的问题在于，它允许恶意用户使用polyglots（即作为多种内容类型有效的文件）来执行XSS攻击。
例如，某些网站可能允许用户向网站提交有效的postscript文档并查看它。
恶意用户可能会创建 http://webblaze.cs.berkeley.edu/papers/barth-caballero-song.pdf[postscript文件也是一个有效的JavaScript文件]并使用它执行XSS攻击。

内容嗅探可以通过将以下标题添加到我们的响应来禁用：

[source]
----
X-Content-Type-Options: nosniff
----

就像缓存控制元素一样，在没有子元素的情况下使用<headers>元素时，默认添加nosniff指令。
但是，如果您想更多地控制添加哪些标题，则可以使用<<nsa-content-type-options,<content-type-options>>>元素和<<nsa-headers-defaults-disabled,headers@defaults-disabled>>属性，如下所示：

[source,xml]
----
<http>
	<!-- ... -->

	<headers defaults-disabled="true">
		<content-type-options />
	</headers>
</http>
----

默认情况下，Spring Security Java配置会添加X-Content-Type-Options标头。
如果您想更好地控制标题，可以使用以下内容显式指定内容类型选项：

[source,java]
----
@EnableWebSecurity
public class WebSecurityConfig extends
WebSecurityConfigurerAdapter {

@Override
protected void configure(HttpSecurity http) throws Exception {
	http
	// ...
	.headers()
		.defaultsDisabled()
		.contentTypeOptions();
}
}
----

[[headers-hsts]]
====  HTTP严格传输安全性（HSTS）
当您输入银行网站时，您是输入mybank.example.com还是输入https://mybank.example.com []？如果您省略https协议，则可能会受 http://en.wikipedia.org/wiki/Man-in-the-middle_attack[中间人攻击]的影响。
即使网站执行https://mybank.example.com的重定向，恶意用户也可能会拦截最初的HTTP请求并操纵响应（即重定向到https://mibank.example.com并窃取其凭据）。

许多用户省略了https协议，这就是 http://tools.ietf.org/html/rfc6797[HTTP严格传输安全性（HSTS）]创建的原因。
一旦mybank.example.com作为 http://tools.ietf.org/html/rfc6797#section-5.1[HSTS主机]添加，浏览器可以提前知道任何对mybank.example.com的请求应该被解释为https://mybank.example.com。
这大大降低了发生中间人攻击的可能性。

[NOTE]
====
根据{{​​0}}，HSTS标头仅被注入到HTTPS响应中。
为了使浏览器确认标题，浏览器必须首先相信签署用于建立连接的SSL证书的CA（而不仅仅是SSL证书）。
====

将站点标记为HSTS主机的一种方法是将主机预加载到浏览器中。
另一种方法是将"Strict-Transport-Security"标头添加到响应中。
例如，以下内容将指示浏览器将域名视为一年的HSTS主机（一年大约有31536000秒）：

[source]
----
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
----

可选的includeSubDomains指令指示Spring Security将子域（即secure.mybank.example.com）也视为HSTS域。

与其他标题一样，Spring Security默认添加HSTS。
您可以使用<<nsa-hsts,<hsts>>>元素自定义HSTS标头，如下所示：

[source,xml]
----
<http>
	<!-- ... -->

	<headers>
		<hsts
			include-subdomains="true"
			max-age-seconds="31536000" />
	</headers>
</http>
----

同样，您可以只启用带有Java配置的HSTS头文件：

[source,java]
----
@EnableWebSecurity
public class WebSecurityConfig extends
WebSecurityConfigurerAdapter {

@Override
protected void configure(HttpSecurity http) throws Exception {
	http
	// ...
	.headers()
		.httpStrictTransportSecurity()
			.includeSubdomains(true)
			.maxAgeSeconds(31536000);
}
}
----

[[headers-hpkp]]
====  HTTP公钥锁定（HPKP）
HTTP Public Key Pinning（HPKP）是一项安全功能，它告诉Web客户端将特定的加密公钥与特定的Web服务器相关联，以防止伪造的证书对中间人（MITM）的攻击。

为了确保在TLS会话中使用的服务器公钥的真实性，该公钥被封装到通常由证书颁发机构（CA）签署的X.509证书中。
Web客户端（如浏览器）信任很多这些CA，它们都可以为任意域名创建证书。
如果攻击者能够危害单个CA，他们可以对各种TLS连接执行MITM攻击。
HPKP可以通过告诉客户端哪个公钥属于某个Web服务器来规避HTTPS协议的这种威胁。
HPKP是首次使用信托（TOFU）技术。
Web服务器第一次通过特殊的HTTP头告诉客户端公钥属于它时，客户端将这些信息存储一段给定的时间。
当客户端再次访问服务器时，它需要一个包含指纹已经通过HPKP知道的公钥的证书。
如果服务器提供未知的公钥，则客户端应向用户提供警告。

[NOTE]
====
由于用户代理需要根据SSL证书链验证引脚，所以HPKP头只能注入到HTTPS响应中。
====

为您的站点启用此功能非常简单，只需在通过HTTPS访问您的站点时返回Public-Key-Pins HTTP标头即可。
例如，以下内容将指示用户代理仅向指定的URI报告引脚验证失败（通过https://tools.ietf.org/html/rfc7469#section-2.1.4[*_report-uri_*]指令）2个引脚：

[source]
----
Public-Key-Pins-Report-Only: max-age=5184000 ; pin-sha256="d6qzRu9zOECb90Uez27xWltNsj0e1Md7GkYYkVoZWmM=" ; pin-sha256="E9CZ9INDbd+2eRQozYqqbQ2yXLVKB9+xcprMF+44U1g=" ; report-uri="http://example.net/pkp-report" ; includeSubDomains
----

https://tools.ietf.org/html/rfc7469#section-3[*_pin validation failure report_*]是标准的JSON结构，可以通过Web应用程序自己的API或公开托管的HPKP报告服务来捕获，如https://report-uri.io/[*_REPORT-URI_*]。

可选的includeSubDomains指令指示浏览器也使用给定引脚验证子域。

与其他标题相反，Spring Security默认不添加HPKP。
您可以使用<<nsa-hpkp,<hpkp>>>元素自定义HPKP标题，如下所示：

[source,xml]
----
<http>
	<!-- ... -->

	<headers>
		<hpkp
			include-subdomains="true"
			report-uri="http://example.net/pkp-report">
			<pins>
					<pin algorithm="sha256">d6qzRu9zOECb90Uez27xWltNsj0e1Md7GkYYkVoZWmM=</pin>
					<pin algorithm="sha256">E9CZ9INDbd+2eRQozYqqbQ2yXLVKB9+xcprMF+44U1g=</pin>
			</pins>
		</hpkp>
	</headers>
</http>
----

同样，您可以使用Java配置启用HPKP标题：

[source,java]
----
@EnableWebSecurity
public class WebSecurityConfig extends
WebSecurityConfigurerAdapter {

		@Override
		protected void configure(HttpSecurity http) throws Exception {
				http
				// ...
				.headers()
						.httpPublicKeyPinning()
								.includeSubdomains(true)
								.reportUri("http://example.net/pkp-report")
								.addSha256Pins("d6qzRu9zOECb90Uez27xWltNsj0e1Md7GkYYkVoZWmM=", "E9CZ9INDbd+2eRQozYqqbQ2yXLVKB9+xcprMF+44U1g=";
		}
}
----

[[headers-frame-options]]
====  X框-选项
允许将您的网站添加到框架可能是一个安全问题。
例如，使用聪明的CSS样式的用户可能会被欺骗点击他们不想要的东西（ http://www.youtube.com/watch?v=3mk0RySeNsU[视频演示]）。
例如，登录他们银行的用户可能会点击一个按钮，授予对其他用户的访问权限。
这种攻击被称为 http://en.wikipedia.org/wiki/Clickjacking[点击劫持]。

[NOTE]
====
另一种处理点击劫持的现代方法是使用<<headers-csp>>。
====

有多种方法可以缓解点击劫持攻击。
例如，为了保护传统浏览器免受点击劫持攻击，您可以使用https://www.owasp.org/index.php/Clickjacking_Defense_Cheat_Sheet#Best-for-now_Legacy_Browser_Frame_Breaking_Script [框架破解代码]。
虽然不完美，但对于传统浏览器来说，破解代码是最好的选择。

处理点击劫持的更现代的方法是使用https://developer.mozilla.org/en-US/docs/HTTP/X-Frame-Options[X-Frame-Options]标头：

[source]
----
X-Frame-Options: DENY
----

X-Frame-Options响应头指示浏览器阻止响应中的任何站点在帧中呈现。
默认情况下，Spring Security会禁用iframe中的渲染。

您可以使用<<nsa-frame-options,frame-options>>元素自定义X-Frame-Options。
例如，以下内容将指示Spring Security使用允许同一域内的iframe的"X-Frame-Options: SAMEORIGIN"：

[source,xml]
----
<http>
	<!-- ... -->

	<headers>
		<frame-options
		policy="SAMEORIGIN" />
	</headers>
</http>
----

同样，您可以使用以下方法自定义框架选项以在Java配置中使用相同的源：

[source,java]
----
@EnableWebSecurity
public class WebSecurityConfig extends
WebSecurityConfigurerAdapter {

@Override
protected void configure(HttpSecurity http) throws Exception {
	http
	// ...
	.headers()
		.frameOptions()
			.sameOrigin();
}
}
----

[[headers-xss-protection]]
====  X-​​XSS-保护
有些浏览器支持过滤https://www.owasp.org/index.php/Testing_for_Reflected_Cross_site_scripting_(OWASP-DV-001)[reflected XSS attacks]。
这绝不是万无一失的，但有助于XSS保护。

默认情况下，过滤通常处于启用状态，因此添加标头通常会确保启用它并指示浏览器在检测到XSS攻击时该执行什么操作。
例如，该过滤器可能会尝试以最小侵入方式更改内容，以继续呈现所有内容。
有时候，这种类型的替换可能会变成 http://hackademix.net/2009/11/21/ies-xss-filter-creates-xss-vulnerabilities/[XSS漏洞本身]。
相反，最好是阻止内容而不是尝试修复它。
为此，我们可以添加以下标题：

[source]
----
X-XSS-Protection: 1; mode=block
----

该标题默认包含在内。
但是，如果我们想要，我们可以定制它。
例如：

[source,xml]
----
<http>
	<!-- ... -->

	<headers>
		<xss-protection block="false"/>
	</headers>
</http>
----

同样，您可以使用以下方法在Java配置中自定义XSS保护：

[source,java]
----
@EnableWebSecurity
public class WebSecurityConfig extends
WebSecurityConfigurerAdapter {

@Override
protected void configure(HttpSecurity http) throws Exception {
	http
	// ...
	.headers()
		.xssProtection()
			.block(false);
}
}
----

[[headers-csp]]
==== 内容安全策略（CSP）

https://www.w3.org/TR/CSP2/ [内容安全策略（CSP）]是Web应用程序可以利用的机制来缓解内容注入漏洞，例如跨站点脚本（XSS）。
CSP是一种声明性策略，为Web应用程序作者声明并最终通知客户端（用户代理）有关Web应用程序预期从中加载资源的来源提供了便利。

[NOTE]
====
内容安全策略不是为了解决所有内容注入漏洞。
相反，可以利用CSP来帮助减少内容注入攻击造成的危害。
作为第一道防线，Web应用程序作者应验证其输入并对其输出进行编码。
====

Web应用程序可以通过在响应中包含以下HTTP标头之一来使用CSP：

* *_Content-Security-Policy_*
* *_Content-Security-Policy-Report-Only_*

这些标头中的每一个都用作将*_security policy_*交付给客户端的机制。
安全策略包含一组*_security policy directives_*（例如_script-src_和_object-src_），每个负责声明特定资源表示的限制。

例如，Web应用程序可以声明它希望通过在响应中包含以下标题来从特定的可信来源加载脚本：

[source]
----
Content-Security-Policy: script-src https://trustedscripts.example.com
----

尝试从其他来源加载脚本，而不是在_script-src_指令中声明的脚本将被用户代理阻止。
此外，如果在安全策略中声明了https://www.w3.org/TR/CSP2/#directive-report-uri[*_report-uri_*]指令，则该违规将由用户代理报告到声明的URL。

例如，如果Web应用程序违反了声明的安全策略，则以下响应标头将指示用户代理将违规报告发送到策略的_report-uri_指令中指定的URL。

[source]
----
Content-Security-Policy: script-src https://trustedscripts.example.com; report-uri /csp-report-endpoint/
----

https://www.w3.org/TR/CSP2/#violation-reports[*_Violation reports_*]是标准的JSON结构，可以通过Web应用程序自己的API或公开托管的CSP违规报告服务来捕获，如https://report-uri.io/[*_REPORT-URI_*]。

*_Content-Security-Policy-Report-Only_*标头为Web应用程序作者和管理员提供了监控安全策略的功能，而不是强制执行它们。
此标题通常用于为网站试验和/或开发安全策略。
当策略被认为有效时，可以通过使用_Content-Security-Policy_标头字段来强制实施。

给定以下响应头，该策略声明脚本可以从两个可能来源之一加载。

[source]
----
Content-Security-Policy-Report-Only: script-src 'self' https://trustedscripts.example.com; report-uri /csp-report-endpoint/
----

如果站点违反了此策略，则通过尝试从_evil.com_加载脚本，用户代理将向_report-uri_指令指定的声明URL发送违规报告，但仍允许加载违规资源。

[[headers-csp-configure]]
===== 配置内容安全策略

默认情况下需要注意Spring Security *_does not add_*内容安全策略。
Web应用程序作者必须声明安全策略以强制执行和/或监视受保护的资源。

例如，鉴于以下安全策略：

[source]
----
script-src 'self' https://trustedscripts.example.com; object-src https://trustedplugins.example.com; report-uri /csp-report-endpoint/
----

您可以使用带<<nsa-content-security-policy,<content-security-policy>>>元素的XML配置来启用CSP头，如下所示：

[source,xml]
----
<http>
	<!-- ... -->

	<headers>
		<content-security-policy
			policy-directives="script-src 'self' https://trustedscripts.example.com; object-src https://trustedplugins.example.com; report-uri /csp-report-endpoint/" />
	</headers>
</http>
----

要启用CSP _report-only__头，请按如下所示配置元素：

[source,xml]
----
<http>
	<!-- ... -->

	<headers>
		<content-security-policy
			policy-directives="script-src 'self' https://trustedscripts.example.com; object-src https://trustedplugins.example.com; report-uri /csp-report-endpoint/"
			report-only="true" />
	</headers>
</http>
----

同样，您可以使用Java配置启用CSP头，如下所示：

[source,java]
----
@EnableWebSecurity
public class WebSecurityConfig extends
WebSecurityConfigurerAdapter {

@Override
protected void configure(HttpSecurity http) throws Exception {
	http
	// ...
	.headers()
		.contentSecurityPolicy("script-src 'self' https://trustedscripts.example.com; object-src https://trustedplugins.example.com; report-uri /csp-report-endpoint/");
}
}
----

要启用CSP _'report-only'_头，请提供以下Java配置：

[source,java]
----
@EnableWebSecurity
public class WebSecurityConfig extends
WebSecurityConfigurerAdapter {

@Override
protected void configure(HttpSecurity http) throws Exception {
	http
	// ...
	.headers()
		.contentSecurityPolicy("script-src 'self' https://trustedscripts.example.com; object-src https://trustedplugins.example.com; report-uri /csp-report-endpoint/")
		.reportOnly();
}
}
----

[[headers-csp-links]]
===== 其他资源

将内容安全策略应用于Web应用程序通常是一项不重要的任务。
以下资源可能会为您的网站制定有效的安全策略提供进一步的帮助。

http://www.html5rocks.com/en/tutorials/security/content-security-policy/[内容安全策略简介]

https://developer.mozilla.org/en-US/docs/Web/Security/CSP[CSP指南 -  Mozilla开发者网络]

https://www.w3.org/TR/CSP2/[W3C候选推荐]

[[headers-referrer]]
==== 推荐人政策

https://www.w3.org/TR/referrer-policy[Referrer Policy]是Web应用程序可以利用的机制来管理引用者字段，其中包含最后一个
用户所在的页面。

Spring Security的方法是使用https://www.w3.org/TR/referrer-policy/[Referrer Policy]标头，它提供了不同的https://www.w3.org/TR/referrer-policy/#referrer-政策[政策]：

[source]
----
Referrer-Policy: same-origin
----

Referrer-Policy响应头指示浏览器让目的地知道用户以前的来源。

[[headers-referrer-configure]]
===== 配置Referrer策略

Spring Security *_doesn't add_*默认引用策略标头。

您可以使用带<<nsa-referrer-policy,<referrer-policy>>>元素的XML配置启用Referrer-Policy标头，如下所示：

[source,xml]
----
<http>
	<!-- ... -->

	<headers>
		<referrer-policy policy="same-origin" />
	</headers>
</http>
----

同样，您可以使用Java配置启用Referrer Policy标头，如下所示：

[source,java]
----
@EnableWebSecurity
public class WebSecurityConfig extends
WebSecurityConfigurerAdapter {

@Override
protected void configure(HttpSecurity http) throws Exception {
	http
	// ...
	.headers()
		.referrerPolicy(ReferrerPolicy.SAME_ORIGIN);
}
}
----


[[headers-custom]]
=== 自定义标题
Spring Security具有一些机制，可以方便地将更常见的安全性标题添加到应用程序中。
不过，它也提供挂钩来启用添加自定义标题。

[[headers-static]]
==== 静态标头
您可能有时希望将自定义安全标头插入到您的应用程序中，但不支持开箱即用。
例如，给定以下自定义安全标头：

[source]
----
X-Custom-Security-Header: header-value
----

使用XML名称空间时，可以使用<<nsa-header,<header>>>元素将这些头添加到响应中，如下所示：

[source,xml]
----
<http>
	<!-- ... -->

	<headers>
		<header name="X-Custom-Security-Header" value="header-value"/>
	</headers>
</http>
----

同样，可以使用Java Configuration将头添加到响应中，如下所示：

[source,java]
----
@EnableWebSecurity
public class WebSecurityConfig extends
WebSecurityConfigurerAdapter {

@Override
protected void configure(HttpSecurity http) throws Exception {
	http
	// ...
	.headers()
		.addHeaderWriter(new StaticHeadersWriter("X-Custom-Security-Header","header-value"));
}
}
----

[[headers-writer]]
==== 标题作者
如果名称空间或Java配置不支持所需的标题，则可以创建自定义`HeadersWriter`实例，甚至可以提供`HeadersWriter`的自定义实现。

我们来看看使用`XFrameOptionsHeaderWriter`的自定义实例的示例。
也许你想允许为相同的来源制作内容。
通过将<<nsa-frame-options-policy,policy>>属性设置为"SAMEORIGIN"，很容易支持这一点，但让我们来看看使用<<nsa-header-ref,ref>>属性的更明确的示例。

[source,xml]
----
<http>
	<!-- ... -->

	<headers>
		<header ref="frameOptionsWriter"/>
	</headers>
</http>
<!-- Requires the c-namespace.
See http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#beans-c-namespace
-->
<beans:bean id="frameOptionsWriter"
	class="org.springframework.security.web.header.writers.frameoptions.XFrameOptionsHeaderWriter"
	c:frameOptionsMode="SAMEORIGIN"/>
----


我们还可以通过Java配置将内容的框架限制在相同的原始位置：


[source,java]
----
@EnableWebSecurity
public class WebSecurityConfig extends
WebSecurityConfigurerAdapter {

@Override
protected void configure(HttpSecurity http) throws Exception {
	http
	// ...
	.headers()
		.addHeaderWriter(new XFrameOptionsHeaderWriter(XFrameOptionsMode.SAMEORIGIN));
}
}
----



[[headers-delegatingrequestmatcherheaderwriter]]
====  DelegatingRequestMatcherHeaderWriter
有时您可能只想为某些请求编写头文件。
例如，也许你只想保护你的登录页面不被陷害。
您可以使用`DelegatingRequestMatcherHeaderWriter`来执行此操作。
在使用XML名称空间配置时，可以通过以下方式完成此操作：


[source,xml]
----
<http>
	<!-- ... -->

	<headers>
		<frame-options disabled="true"/>
		<header ref="headerWriter"/>
	</headers>
</http>

<beans:bean id="headerWriter"
	class="org.springframework.security.web.header.writers.DelegatingRequestMatcherHeaderWriter">
	<beans:constructor-arg>
		<bean class="org.springframework.security.web.util.matcher.AntPathRequestMatcher"
			c:pattern="/login"/>
	</beans:constructor-arg>
	<beans:constructor-arg>
		<beans:bean
			class="org.springframework.security.web.header.writers.frameoptions.XFrameOptionsHeaderWriter"/>
	</beans:constructor-arg>
</beans:bean>
----


我们还可以使用java配置防止内容成帧到登录页面：


[source,java]
----
@EnableWebSecurity
public class WebSecurityConfig extends
WebSecurityConfigurerAdapter {

@Override
protected void configure(HttpSecurity http) throws Exception {
	RequestMatcher matcher = new AntPathRequestMatcher("/login");
	DelegatingRequestMatcherHeaderWriter headerWriter =
		new DelegatingRequestMatcherHeaderWriter(matcher,new XFrameOptionsHeaderWriter());
	http
	// ...
	.headers()
		.frameOptions().disabled()
		.addHeaderWriter(headerWriter);
}
}
----

