

[[remember-me]]
== 记住我的身份验证


[[remember-me-overview]]
=== 概述
记住我或永久登录身份验证是指网站能够记住会话之间的主体身份。
这通常通过向浏览器发送cookie来完成，在将来的会话中检测到cookie并导致自动登录。
Spring Security为这些操作提供了必要的钩子，并且有两个具体的记住我的实现。
一个使用散列来保存基于cookie的令牌的安全性，另一个使用数据库或其他持久存储机制来存储生成的令牌。

请注意，这两种实现都需要`UserDetailsService`。
如果您使用不使用`UserDetailsService`的身份验证提供程序（例如，LDAP提供程序），那么它将不起作用，除非您的应用程序上下文中还有一个`UserDetailsService` bean。


[[remember-me-hash-token]]
=== 简单的基于哈希的令牌方法
这种方法使用散列来实现有用的记忆我策略。
本质上，cookie在成功交互式验证后发送到浏览器，cookie的组成如下：

[source,txt]
----
base64(username + ":" + expirationTime + ":" +
md5Hex(username + ":" + expirationTime + ":" password + ":" + key))

username:          As identifiable to the UserDetailsService
password:          That matches the one in the retrieved UserDetails
expirationTime:    The date and time when the remember-me token expires, expressed in milliseconds
key:               A private key to prevent modification of the remember-me token
----

因此，记住我记号仅在指定的时间段内有效，并且前提是用户名，密码和密钥不会更改。
值得注意的是，这存在潜在的安全问题，因为捕获的记忆我令牌将可用于任何用户代理直到令牌过期。
这与摘要式身份验证相同。
如果委托人知道令牌已被捕获，他们可以轻松更改其密码，并立即使有问题的所有令牌令牌失效。
如果需要更重要的安全性，则应使用下一节中介绍的方法。
或者，记住我服务应该根本不用。

如果您熟悉<<ns-config,namespace configuration>>一章中讨论的主题，则只需添加`<remember-me>`元素即可启用记事本身份验证：

[source,xml]
----
<http>
...
<remember-me key="myAppKey"/>
</http>
----

通常会自动选择`UserDetailsService`。
如果您的应用程序环境中有多个应用程序，则需要指定哪一个应与`user-service-ref`属性一起使用，其中值是您的`UserDetailsService` bean的名称。

[[remember-me-persistent-token]]
=== 持久令牌方法
此方法基于文章 http://jaspan.com/improved_persistent_login_cookie_best_practice[http://jaspan.com/improved_persistent_login_cookie_best_practice]进行了一些小修改脚注：[基本上，用户名不包含在cookie中，以防止不必要地公开有效的登录名。
本文的评论部分对此进行了讨论。]。
要在命名空间配置中使用这种方法，您需要提供一个数据源参考：

[source,xml]
----
<http>
...
<remember-me data-source-ref="someDataSource"/>
</http>
----

数据库应该包含使用以下SQL（或等价物）创建的`persistent_logins`表：

[source,ddl]
----
create table persistent_logins (username varchar(64) not null,
								series varchar(64) primary key,
								token varchar(64) not null,
								last_used timestamp not null)
----

[[remember-me-impls]]
=== 记住我的接口和实现
Remember-me与`UsernamePasswordAuthenticationFilter`一起使用，并通过`AbstractAuthenticationProcessingFilter`超类中的钩子实现。
它也用于`BasicAuthenticationFilter`。
挂钩将在适当的时候调用具体的`RememberMeServices`。
界面如下所示：

[source,java]
----
Authentication autoLogin(HttpServletRequest request, HttpServletResponse response);

void loginFail(HttpServletRequest request, HttpServletResponse response);

void loginSuccess(HttpServletRequest request, HttpServletResponse response,
	Authentication successfulAuthentication);
----

请参阅Javadoc，详细讨论这些方法的用途，但请注意，在此阶段`AbstractAuthenticationProcessingFilter`仅调用`loginFail()`和`loginSuccess()`方法。
每当`SecurityContextHolder`不包含`Authentication`时，`autoLogin()`方法由`RememberMeAuthenticationFilter`调用。
因此，该接口为潜在的记忆我实现提供了充分的与身份验证相关的事件通知，并在候选Web请求可能包含Cookie并希望被记住时委托实现。
这种设计允许任何数量的记忆我实施策略。
我们在上面看到Spring Security提供了两个实现。
我们将依次查看这些内容。

====  TokenBasedRememberMeServices
此实现支持<<remember-me-hash-token>>中介绍的更简单的方法。
`TokenBasedRememberMeServices`生成`RememberMeAuthenticationToken`，由`RememberMeAuthenticationProvider`处理。
此身份验证提供程序与`TokenBasedRememberMeServices`共享一个`key`。
另外，`TokenBasedRememberMeServices`需要一个UserDetailsS​​ervice，通过它可以检索用户名和密码以进行签名比较，并生成`RememberMeAuthenticationToken`以包含正确的`GrantedAuthority`。
某些注销命令应由应用程序提供，如果用户请求该命令，则会使Cookie无效。
`TokenBasedRememberMeServices`还实现了Spring Security的`LogoutHandler`界面，因此可以与`LogoutFilter`一起使用以自动清除cookie。

在应用程序上下文中启用Remember-me服务所需的bean如下所示：

[source,xml]
----
<bean id="rememberMeFilter" class=
"org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter">
<property name="rememberMeServices" ref="rememberMeServices"/>
<property name="authenticationManager" ref="theAuthenticationManager" />
</bean>

<bean id="rememberMeServices" class=
"org.springframework.security.web.authentication.rememberme.TokenBasedRememberMeServices">
<property name="userDetailsService" ref="myUserDetailsService"/>
<property name="key" value="springRocks"/>
</bean>

<bean id="rememberMeAuthenticationProvider" class=
"org.springframework.security.authentication.RememberMeAuthenticationProvider">
<property name="key" value="springRocks"/>
</bean>
----

不要忘记将您的`RememberMeServices`实施添加到您的`UsernamePasswordAuthenticationFilter.setRememberMeServices()`属性，将`RememberMeAuthenticationProvider`添加到您的`AuthenticationManager.setProviders()`列表中，并将`RememberMeAuthenticationFilter`添加到您的{{5 }}（通常在你的`UsernamePasswordAuthenticationFilter`之后）。


==== 对PersistentTokenBasedRememberMeServices
此类可以与`TokenBasedRememberMeServices`相同的方式使用，但还需要使用`PersistentTokenRepository`配置以存储令牌。
有两种标准实现。

仅用于测试的*  `InMemoryTokenRepositoryImpl`。
*  `JdbcTokenRepositoryImpl`将令牌存储在数据库中。

数据库模式在<<remember-me-persistent-token>>中进行了描述。
