
[[servletapi]]
==  Servlet API集成
本节介绍Spring Security如何与Servlet API集成。
https://github.com/spring-projects/spring-security/tree/master/samples/xml/servletapi[servletapi-xml]示例应用程序演示了每种方法的用法。


[[servletapi-25]]
===  Servlet 2.5+集成


[[servletapi-remote-user]]
====  HttpServletRequest.getRemoteUser（）
http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getRemoteUser()[HttpServletRequest.getRemoteUser（）]将返回通常为当前用户名的`SecurityContextHolder.getContext().getAuthentication().getName()`的结果。
如果您想在应用程序中显示当前用户名，这会很有用。
此外，检查这是否为空可用于指示用户是否已通过身份验证或匿名。
知道用户是否被认证对于确定是否应该显示某些UI元素是有用的（即，仅当用户被认证时才显示注销链接）。


[[servletapi-user-principal]]
====  HttpServletRequest.getUserPrincipal（）
http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getUserPrincipal()[HttpServletRequest.getUserPrincipal（）]将返回`SecurityContextHolder.getContext().getAuthentication()`的结果。
这意味着在使用基于用户名和密码的身份验证时，它是`Authentication`，通常是`UsernamePasswordAuthenticationToken`的实例。
如果您需要有关用户的其他信息，这可能很有用。
例如，您可能已创建一个自定义`UserDetailsService`，返回包含用户姓名和姓氏的自定义`UserDetails`。
您可以通过以下方式获取此信息：


[source,java]
----
Authentication auth = httpServletRequest.getUserPrincipal();
// assume integrated custom UserDetails called MyCustomUserDetails
// by default, typically instance of UserDetails
MyCustomUserDetails userDetails = (MyCustomUserDetails) auth.getPrincipal();
String firstName = userDetails.getFirstName();
String lastName = userDetails.getLastName();
----

[NOTE]
====
应该指出，在整个应用程序中执行如此多的逻辑通常是不好的做法。
相反，应该集中它来减少Spring Security和Servlet API的耦合。
====

[[servletapi-user-in-role]]
====  HttpServletRequest.isUserInRole（字符串）
http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#isUserInRole(java.lang.String)[HttpServletRequest.isUserInRole（字符串）]将确定`SecurityContextHolder.getContext().getAuthentication().getAuthorities()`是否包含传递给`isUserInRole(String)`的角色的`GrantedAuthority`。
通常用户不应将"ROLE_"前缀传入此方法，因为它会自动添加。
例如，如果您要确定当前用户是否具有权限"ROLE_ADMIN"，则可以使用以下内容：

[source,java]
----
boolean isAdmin = httpServletRequest.isUserInRole("ADMIN");
----

这对确定是否显示某些UI组件可能很有用。
例如，只有当前用户是管理员时，才可以显示管理员链接。

[[servletapi-3]]
===  Servlet 3+集成
以下部分描述Spring Security集成的Servlet 3方法。


[[servletapi-authenticate]]
====  HttpServletRequest.authenticate（HttpServletRequest的，HttpServletResponse的）
http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#authenticate%28javax.servlet.http.HttpServletResponse%29[HttpServletRequest.authenticate（HttpServletRequest的，HttpServletResponse的）]方法可用于确保用户通过身份验证。
如果它们未通过身份验证，则配置的AuthenticationEntryPoint将用于请求用户进行身份验证（即重定向到登录页面）。


[[servletapi-login]]
====  HttpServletRequest.login（字符串，字符串）
http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#login%28java.lang.String,%20java.lang.String%29[HttpServletRequest.login（字符串，字符串）]方法可用于使用当前`AuthenticationManager`对用户进行身份验证。
例如，以下内容会尝试使用用户名"user"和密码"password"进行身份验证：

[source,java]
----
try {
httpServletRequest.login("user","password");
} catch(ServletException e) {
// fail to authenticate
}
----

[NOTE]
====
如果您希望Spring Security处理失败的身份验证尝试，则不需要捕获ServletException。
====

[[servletapi-logout]]
====  HttpServletRequest.logout（）
可以使用 http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#logout%28%29[HttpServletRequest.logout（）]方法记录当前用户。

通常这意味着SecurityContextHolder将被清除，HttpSession将失效，任何"Remember Me"认证将被清除，等等。
但是，配置的LogoutHandler实现将根据您的Spring Security配置而有所不同。
请注意，在调用HttpServletRequest.logout（）之后，您仍然负责编写响应。
通常这会涉及重定向到欢迎页面。

[[servletapi-start-runnable]]
====  AsyncContext.start（可运行）
确保您的凭据将传播到新线程的 http://docs.oracle.com/javaee/6/api/javax/servlet/AsyncContext.html#start%28java.lang.Runnable%29[AsynchContext.start（可运行）]方法。
使用Spring Security的并发支持，Spring Security会覆盖AsyncContext.start（Runnable），以确保在处理Runnable时使用当前的SecurityContext。
例如，以下内容会输出当前用户的身份验证：

[source,java]
----
final AsyncContext async = httpServletRequest.startAsync();
async.start(new Runnable() {
	public void run() {
		Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
		try {
			final HttpServletResponse asyncResponse = (HttpServletResponse) async.getResponse();
			asyncResponse.setStatus(HttpServletResponse.SC_OK);
			asyncResponse.getWriter().write(String.valueOf(authentication));
			async.complete();
		} catch(Exception e) {
			throw new RuntimeException(e);
		}
	}
});
----

[[servletapi-async]]
==== 异步Servlet支持
如果您正在使用基于Java的配置，则可以开始使用了。
如果您使用的是XML配置，则需要进行一些更新。
第一步是确保您已更新web.xml以至少使用3.0架构，如下所示：

[source,xml]
----
<web-app xmlns="http://java.sun.com/xml/ns/javaee"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
version="3.0">

</web-app>
----

接下来，您需要确保您的springSecurityFilterChain已设置为处理异步请求。

[source,xml]
----
<filter>
<filter-name>springSecurityFilterChain</filter-name>
<filter-class>
	org.springframework.web.filter.DelegatingFilterProxy
</filter-class>
<async-supported>true</async-supported>
</filter>
<filter-mapping>
<filter-name>springSecurityFilterChain</filter-name>
<url-pattern>/*</url-pattern>
<dispatcher>REQUEST</dispatcher>
<dispatcher>ASYNC</dispatcher>
</filter-mapping>
----

而已！
现在，Spring Security将确保您的SecurityContext也在异步请求上传播。

那么它是怎样工作的？如果你不是真的感兴趣，可以跳过本节的其余部分，否则请继续阅读。
其中大部分都是内置到Servlet规范中的，但是有一点调整，Spring Security确实能够正确地处理异步请求。
在Spring Security 3.2之前，只要提交HttpServletResponse，SecurityContextHolder中的SecurityContext就会自动保存。
这可能会导致异步环境中的问题。
例如，请考虑以下几点：

[source,java]
----
httpServletRequest.startAsync();
new Thread("AsyncThread") {
	@Override
	public void run() {
		try {
			// Do work
			TimeUnit.SECONDS.sleep(1);

			// Write to and commit the httpServletResponse
			httpServletResponse.getOutputStream().flush();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}.start();
----

问题是这个Thread对于Spring Security来说是不知道的，所以SecurityContext不会传播给它。
这意味着当我们提交HttpServletResponse时，没有SecuriytContext。
当Spring Security在提交HttpServletResponse时自动保存SecurityContext时，它会丢失我们的登录用户。

从3.2版本开始，Spring Security足够聪明，只要HttpServletRequest.startAsync（）被调用，就不会再自动保存SecurityContext来提交HttpServletResponse。

[[servletapi-31]]
===  Servlet 3.1+集成
以下部分描述Spring Security集成的Servlet 3.1方法。

[[servletapi-change-session-id]]
==== 的HttpServletRequest＃changeSessionId（）
http://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html#changeSessionId()[HttpServletRequest.changeSessionId（）]是在Servlet 3.1及更高版本中防止<<ns-session-fixation,Session Fixation>>攻击的默认方法。
