[[websocket]]
==  WebSocket安全性

Spring Security 4增加了对保护 http://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html[Spring的WebSocket支持]的支持。
本节介绍如何使用Spring Security的WebSocket支持。

注意：您可以在samples / javaconfig / chat中找到完整的WebSocket安全工作示例。

。直接JSR-356支持
****
Spring Security没有提供直接的JSR-356支持，因为这样做没有多大价值。
这是因为格式未知，所以 http://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html#websocket-intro-sub-protocol[小泉可以做到保证未知格式]。
另外，JSR-356不提供拦截消息的方法，所以安全性会相当侵入。
****

[[websocket-configuration]]
===  WebSocket配置

Spring Security 4.0通过Spring消息抽象为WebSockets引入了授权支持。
要使用Java配置配置授权，只需扩展`AbstractSecurityWebSocketMessageBrokerConfigurer`并配置`MessageSecurityMetadataSourceRegistry`即可。
例如：

[source,java]
----
@Configuration
public class WebSocketSecurityConfig
      extends AbstractSecurityWebSocketMessageBrokerConfigurer { // <1> <2>

    protected void configureInbound(MessageSecurityMetadataSourceRegistry messages) {
        messages
                .simpDestMatchers("/user/*").authenticated() // <3>
    }
}
----

这将确保：

<1>任何入站CONNECT消息都需要一个有效的CSRF令牌来执行<<websocket-sameorigin,Same Origin Policy>>
<2> SecurityContextHolder由simpUser标头属性中的用户填充，用于任何入站请求。
<3>我们的邮件需要获得适当的授权。具体来说，任何以"/user/"开头的入站邮件都需要ROLE_USER。有关授权的更多详细信息，请参阅<<websocket-authorization>>

Spring Security还为保护WebSocket提供<<nsa-websocket-security,XML Namespace>>支持。
可比的基于XML的配置如下所示：

[source,xml]
----
<websocket-message-broker> <!--1--> <!--2-->
    <!--3-->
    <intercept-message pattern="/user/**" access="hasRole('USER')" />
</websocket-message-broker>
----

这将确保：

<1>任何入站CONNECT消息都需要一个有效的CSRF令牌来执行<<websocket-sameorigin,Same Origin Policy>>
<2> SecurityContextHolder由simpUser标头属性中的用户填充，用于任何入站请求。
<3>我们的邮件需要获得适当的授权。具体来说，任何以"/user/"开头的入站邮件都需要ROLE_USER。有关授权的更多详细信息，请参阅<<websocket-authorization>>

[[websocket-authentication]]
===  WebSocket身份验证

当WebSocket连接建立时，WebSocket重复使用与HTTP请求中相同的认证信息。
这意味着`HttpServletRequest`上的`Principal`将被移交给WebSockets。
如果您使用的是Spring Security，则`HttpServletRequest`上的`Principal`会自动覆盖。

更具体地说，为了确保用户已经对WebSocket应用程序进行了身份验证，所有必需的是确保您设置Spring Security来验证您的基于HTTP的Web应用程序。

[[websocket-authorization]]
===  WebSocket授权

Spring Security 4.0通过Spring消息抽象为WebSockets引入了授权支持。
要使用Java配置配置授权，只需扩展`AbstractSecurityWebSocketMessageBrokerConfigurer`并配置`MessageSecurityMetadataSourceRegistry`即可。
例如：

[source,java]
----
@Configuration
public class WebSocketSecurityConfig extends AbstractSecurityWebSocketMessageBrokerConfigurer {

    @Override
    protected void configureInbound(MessageSecurityMetadataSourceRegistry messages) {
        messages
                .nullDestMatcher().authenticated() // <1>
                .simpSubscribeDestMatchers("/user/queue/errors").permitAll() // <2>
                .simpDestMatchers("/app/**").hasRole("USER") // <3>
                .simpSubscribeDestMatchers("/user/**", "/topic/friends/*").hasRole("USER") // <4>
                .simpTypeMatchers(MESSAGE, SUBSCRIBE).denyAll() // <5>
                .anyMessage().denyAll(); // <6>

    }
}
----

这将确保：

<1>没有目标的任何消息（即消息类型为MESSAGE或SUBSCRIBE以外的任何消息）都需要用户进行身份验证
<2>任何人都可以订阅/ user / queue / errors
<3>具有以"/app/"开头的目标的任何消息都将要求用户拥有角色ROLE_USER
<4>任何类型为SUBSCRIBE的以"/user/"或"/topic/friends/"开头的消息都需要ROLE_USER
<5>任何类型为MESSAGE或SUBSCRIBE的消息都会被拒绝。由于6，我们不需要这一步，但它说明了如何匹配特定的消息类型。
<6>其他消息被拒绝。这是确保您不会错过任何消息的好主意。

Spring Security还为保护WebSocket提供<<nsa-websocket-security,XML Namespace>>支持。
可比的基于XML的配置如下所示：

[source,xml]
----
<websocket-message-broker>
    <!--1-->
    <intercept-message type="CONNECT" access="permitAll" />
    <intercept-message type="UNSUBSCRIBE" access="permitAll" />
    <intercept-message type="DISCONNECT" access="permitAll" />

    <intercept-message pattern="/user/queue/errors" type="SUBSCRIBE" access="permitAll" /> <!--2-->
    <intercept-message pattern="/app/**" access="hasRole('USER')" />      <!--3-->

    <!--4-->
    <intercept-message pattern="/user/**" access="hasRole('USER')" />
    <intercept-message pattern="/topic/friends/*" access="hasRole('USER')" />

    <!--5-->
    <intercept-message type="MESSAGE" access="denyAll" />
    <intercept-message type="SUBSCRIBE" access="denyAll" />

    <intercept-message pattern="/**" access="denyAll" /> <!--6-->
</websocket-message-broker>
----

这将确保：

<1>类型为CONNECT，UNSUBSCRIBE或DISCONNECT的任何消息都需要用户进行身份验证
<2>任何人都可以订阅/ user / queue / errors
<3>具有以"/app/"开头的目标的任何消息都将要求用户拥有角色ROLE_USER
<4>任何类型为SUBSCRIBE的以"/user/"或"/topic/friends/"开头的消息都需要ROLE_USER
<5>任何类型为MESSAGE或SUBSCRIBE的消息都会被拒绝。由于6，我们不需要这一步，但它说明了如何匹配特定的消息类型。
<6>任何其他带有目的地的邮件都会被拒绝。这是确保您不会错过任何消息的好主意。

[[websocket-authorization-notes]]
====  WebSocket授权说明

为了正确保护你的应用程序，理解Spring的WebSocket支持是很重要的。

[[websocket-authorization-notes-messagetypes]]
消息类型的=====  WebSocket授权

了解SUBSCRIBE和MESSAGE消息类型之间的区别以及它在Spring中的工作方式非常重要。

考虑一个聊天应用程序。

* 系统可以通过"/topic/system/notifications"的目的地向所有用户发送通知MESSAGE
* 客户可以通过SUBSCRIBE向"/topic/system/notifications"收到通知。

虽然我们希望客户能够订阅"/topic/system/notifications"，但我们不希望让他们向该目的地发送MESSAGE。
如果我们允许发送MESSAGE到"/topic/system/notifications"，则客户端可以直接向该端点发送消息并模拟系统。

一般而言，应用程序通常会拒绝任何发送到以 http://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html#websocket-stomp[经纪人前缀]开头的消息（即"/topic/"或"/queue/"）的消息。

[[websocket-authorization-notes-destinations]]
目的地上的=====  WebSocket授权

了解目的地如何转变也很重要。

考虑一个聊天应用程序。

* 用户可以通过向"/app/chat"的目的地发送消息来向特定用户发送消息。
* 应用程序看到该消息，确保将"from"属性指定为当前用户（我们不能信任客户端）。
* 然后，应用程序使用`SimpMessageSendingOperations.convertAndSendToUser("toUser", "/queue/messages", message)`将消息发送给收件人。
* 邮件转到"/queue/user/messages-<sessionid>"的目的地

通过上面的应用程序，我们希望允许我们的客户端收听转换为"/queue/user/messages-<sessionid>"的{​​{0}}。
但是，我们不希望客户端能够收听"/queue/*"，因为这可以让客户端看到每个用户的消息。

一般来说，应用程序通常拒绝发送给以 http://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html#websocket-stomp[经纪人前缀]开头的消息（即"/topic/"或"/queue/"）的任何SUBSCRIBE。
当然，我们可能会提供例外来解释诸如此类的事情

[[websocket-authorization-notes-outbound]]
==== 出站邮件

Spring包含标题为 http://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html#websocket-stomp-message-flow[消息流]的部分，它描述了消息如何流经系统。
值得注意的是，Spring Security只保护`clientInboundChannel`。
Spring Security不会尝试保护`clientOutboundChannel`。

最重要的原因是性能。
对于每一条消息，通常会有更多消息传出。
我们鼓励确保订阅端点，而不是保护出站消息。

[[websocket-sameorigin]]
=== 实施相同的原产地政策

强调浏览器不强制WebSocket连接的 http://en.wikipedia.org/wiki/Same-origin_policy[同源政策]是非常重要的。
这是一个非常重要的考虑因素。

[[websocket-sameorigin-why]]
==== 为什么同源？

考虑以下情况。
用户访问bank.com并向其帐户进行身份验证。
同一用户在其浏览器中打开另一个选项卡并访问evil.com。
同源策略确保evil.com无法读取或写入bank.com数据。

使用WebSockets相同的来源策略不适用。
事实上，除非bank.com明确禁止它，否则evil.com可以代表用户读取和写入数据。
这意味着用户可以通过webSocket进行任何操作（即转账资金），evil.com可以代表该用户进行操作。

由于SockJS试图模拟WebSockets，它也绕过了同源策略。
这意味着开发人员在使用SockJS时需要明确地保护他们的应用程序免受外部域的攻击

[[websocket-sameorigin-spring]]
====  Spring WebSocket允许的起源

幸运的是，自Spring 4.1.5以来，Spring的WebSocket和SockJS支持限制了对 http://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html#websocket-server-allowed-origins[当前域]的访问。
Spring Security增加了额外的保护层来提供 http://en.wikipedia.org/wiki/Defense_in_depth_%28computing%29[深度防守]。

[[websocket-sameorigin-csrf]]
==== 将CSRF添加到Stomp标题

默认情况下，Spring Security需要任何CONNECT消息类型中的<<csrf,CSRF token>>。
这确保只有可访问CSRF令牌的站点才能连接。
由于只有*Same Origin*可以访问CSRF令牌，因此不允许外部域进行连接。

通常，我们需要将CSRF令牌包含在HTTP标头或HTTP参数中。
但是，SockJS不允许使用这些选项。
相反，我们必须在Stomp标头中包含令牌

通过访问名为_csrf的请求属性，应用程序可以<<csrf-include-csrf-token,obtain a CSRF token>>。
例如，以下将允许访问JSP中的`CsrfToken`：

[source,javascript]
----
var headerName = "${_csrf.headerName}";
var token = "${_csrf.token}";
----

如果您使用静态HTML，则可以在REST端点上公开`CsrfToken`。
例如，以下内容将显示URL / csrf上的`CsrfToken`

[source,java]
----
@RestController
public class CsrfController {

    @RequestMapping("/csrf")
    public CsrfToken csrf(CsrfToken token) {
        return token;
    }
}
----

JavaScript可以对端点进行REST调用，并使用响应填充headerName和令牌。

我们现在可以在Stomp客户端中包含令牌。
例如：

[source,javascript]
----
...
var headers = {};
headers[headerName] = token;
stompClient.connect(headers, function(frame) {
  ...

}
----

[[websocket-sameorigin-disable]]
==== 在WebSockets中禁用CSRF

如果您想允许其他域访问您的网站，可以禁用Spring Security的保护。
例如，在Java配置中，您可以使用以下内容：

[source,java]
----
@Configuration
public class WebSocketSecurityConfig extends AbstractSecurityWebSocketMessageBrokerConfigurer {

    ...

    @Override
    protected boolean sameOriginDisabled() {
        return true;
    }
}
----


[[websocket-sockjs]]
=== 使用SockJS

http://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html#websocket-fallback[SockJS]提供后备传输以支持旧版浏览器。
在使用后备选项时，我们需要放松一些安全约束，以允许SockJS与Spring Security合作。

[[websocket-sockjs-sameorigin]]
====  SockJS和框架选项

SockJS可以使用https://github.com/sockjs/sockjs-client/tree/v0.3.4[transport利用iframe]。
默认情况下，Spring Security将<<headers-frame-options,deny>>站点框起来以防止点击劫持攻击。
为了允许基于SockJS框架的传输工作，我们需要配置Spring Security以允许相同的源来构造内容。

您可以使用<<nsa-frame-options,frame-options>>元素自定义X-Frame-Options。
例如，以下内容将指示Spring Security使用允许同一域内的iframe的"X-Frame-Options: SAMEORIGIN"：

[source,xml]
----
<http>
    <!-- ... -->

    <headers>
        <frame-options
          policy="SAMEORIGIN" />
    </headers>
</http>
----

同样，您可以使用以下方法自定义框架选项以在Java配置中使用相同的源：

[source,java]
----
@EnableWebSecurity
public class WebSecurityConfig extends
   WebSecurityConfigurerAdapter {

  @Override
  protected void configure(HttpSecurity http) throws Exception {
    http
      // ...
      .headers()
        .frameOptions()
            .sameOrigin();
  }
}
----

[[websocket-sockjs-csrf]]
====  SockJS＆Relaxing CSRF

对于任何基于HTTP的传输，SockJS在CONNECT消息上使用POST。
通常，我们需要将CSRF令牌包含在HTTP标头或HTTP参数中。
但是，SockJS不允许使用这些选项。
相反，我们必须按照<<websocket-sameorigin-csrf>>中所述将标记包含在Stomp标头中。

这也意味着我们需要通过Web层来放松我们的CSRF保护。
具体而言，我们希望为我们的连接网址禁用CSRF保护。
我们不希望为每个网址禁用CSRF保护。
否则我们的网站将容易受到CSRF攻击。

我们可以通过提供CSRF RequestMatcher轻松实现此目的。
我们的Java配置使得这非常简单。
例如，如果我们的端点是"/chat"，我们可以仅使用以下配置为仅以"/chat/"开头的URL禁用CSRF保护：

[source,java]
----
@Configuration
@EnableWebSecurity
public class WebSecurityConfig
    extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {

        http
            .csrf()
                // ignore our stomp endpoints since they are protected using Stomp headers
                .ignoringAntMatchers("/chat/**")
                .and()
            .headers()
                // allow same origin to frame our site to support iframe SockJS
                .frameOptions().sameOrigin()
                .and()
            .authorizeRequests()

            ...
----

如果我们使用基于XML的配置，我们可以使用<<nsa-csrf-request-matcher-ref,csrf@request-matcher-ref>>。
例如：

[source,xml]
----
<http ...>
    <csrf request-matcher-ref="csrfMatcher"/>

    <headers>
        <frame-options policy="SAMEORIGIN"/>
    </headers>

    ...
</http>

<b:bean id="csrfMatcher"
    class="AndRequestMatcher">
    <b:constructor-arg value="#{T(org.springframework.security.web.csrf.CsrfFilter).DEFAULT_CSRF_MATCHER}"/>
    <b:constructor-arg>
        <b:bean class="org.springframework.security.web.util.matcher.NegatedRequestMatcher">
          <b:bean class="org.springframework.security.web.util.matcher.AntPathRequestMatcher">
            <b:constructor-arg value="/chat/**"/>
          </b:bean>
        </b:bean>
    </b:constructor-arg>
</b:bean>
----
