[[test-webflux]]
= Reactive Test Support

This section describes how to test reactive applications that use Spring Security.

[[test-erms]]
== Testing Reactive Method Security

For example, we can test our example from <<jc-erms>> by using the same setup and annotations that we used in <<test-method>>.
The following minimal sample shows what we can do:

====
[source,java]
----
@RunWith(SpringRunner.class)
@ContextConfiguration(classes = HelloWebfluxMethodApplication.class)
public class HelloWorldMessageServiceTests {
	@Autowired
	HelloWorldMessageService messages;

	@Test
	public void messagesWhenNotAuthenticatedThenDenied() {
		StepVerifier.create(this.messages.findMessage())
			.expectError(AccessDeniedException.class)
			.verify();
	}

	@Test
	@WithMockUser
	public void messagesWhenUserThenDenied() {
		StepVerifier.create(this.messages.findMessage())
			.expectError(AccessDeniedException.class)
			.verify();
	}

	@Test
	@WithMockUser(roles = "ADMIN")
	public void messagesWhenAdminThenOk() {
		StepVerifier.create(this.messages.findMessage())
			.expectNext("Hello World!")
			.verifyComplete();
	}
}
----
====

[[test-webtestclient]]
== WebTestClientSupport

Spring Security provides integration with `WebTestClient`.
The basic setup looks like this:

====
[source,java]
----
@RunWith(SpringRunner.class)
@ContextConfiguration(classes = HelloWebfluxMethodApplication.class)
public class HelloWebfluxMethodApplicationTests {
	@Autowired
	ApplicationContext context;

	WebTestClient rest;

	@Before
	public void setup() {
		this.rest = WebTestClient
			.bindToApplicationContext(this.context)
			// add Spring Security test Support
			.apply(springSecurity())
			.configureClient()
			.filter(basicAuthentication())
			.build();
	}
	// ...
}
----
====

=== Authentication

After applying the Spring Security support to `WebTestClient`, we can use either annotations or `mutateWith` support -- for example:

====
[source,java]
----
@Test
public void messageWhenNotAuthenticated() throws Exception {
	this.rest
		.get()
		.uri("/message")
		.exchange()
		.expectStatus().isUnauthorized();
}

// --- WithMockUser ---

@Test
@WithMockUser
public void messageWhenWithMockUserThenForbidden() throws Exception {
	this.rest
		.get()
		.uri("/message")
		.exchange()
		.expectStatus().isEqualTo(HttpStatus.FORBIDDEN);
}

@Test
@WithMockUser(roles = "ADMIN")
public void messageWhenWithMockAdminThenOk() throws Exception {
	this.rest
		.get()
		.uri("/message")
		.exchange()
		.expectStatus().isOk()
		.expectBody(String.class).isEqualTo("Hello World!");
}

// --- mutateWith mockUser ---

@Test
public void messageWhenMutateWithMockUserThenForbidden() throws Exception {
	this.rest
		.mutateWith(mockUser())
		.get()
		.uri("/message")
		.exchange()
		.expectStatus().isEqualTo(HttpStatus.FORBIDDEN);
}

@Test
public void messageWhenMutateWithMockAdminThenOk() throws Exception {
	this.rest
		.mutateWith(mockUser().roles("ADMIN"))
		.get()
		.uri("/message")
		.exchange()
		.expectStatus().isOk()
		.expectBody(String.class).isEqualTo("Hello World!");
}
----
====


=== CSRF Support

Spring Security also provides support for CSRF testing with `WebTestClient` -- for example:

====
[source,java]
----
this.rest
	// provide a valid CSRF token
	.mutateWith(csrf())
	.post()
	.uri("/login")
	...
----
====

[[webflux-testing-oauth2]]
=== Testing OAuth 2.0

When it comes to OAuth 2.0, the same principles covered earlier still apply: Ultimately, it depends on what your method under test is expecting to be in the `SecurityContextHolder`.

Consider the following example of a controller:

====
[source,java]
----
@GetMapping("/endpoint")
public Mono<String> foo(Principal user) {
    return Mono.just(user.getName());
}
----
====

Nothing about it is OAuth2-specific, so you can <<test-erms,use `@WithMockUser`>> and be fine.

However, consider a case where your controller is bound to some aspect of Spring Security's OAuth 2.0 support:

====
[source,java]
----
@GetMapping("/endpoint")
public Mono<String> foo(@AuthenticationPrincipal OidcUser user) {
    return Mono.just(user.getIdToken().getSubject());
}
----
====

In that case, Spring Security's test support is handy.

[[webflux-testing-oidc-login]]
=== Testing OIDC Login

Testing the method shown in the <<webflux-testing-oauth2,preceding section>> with `WebTestClient` requires simulating some kind of grant flow with an authorization server.
This is a daunting task, which is why Spring Security ships with support for removing this boilerplate.

For example, we can tell Spring Security to include a default `OidcUser` by using the `SecurityMockServerConfigurers#oidcLogin` method:

====
[source,java]
----
client
    .mutateWith(mockOidcLogin()).get().uri("/endpoint").exchange();
----
====

That line configures the associated `MockServerRequest` with an `OidcUser` that includes a simple `OidcIdToken`, an `OidcUserInfo`, and a `Collection` of granted authorities.

Specifically, it includes an `OidcIdToken` with a `sub` claim set to `user`:

====
[source,json]
----
assertThat(user.getIdToken().getClaim("sub")).isEqualTo("user");
----
====

It also includes an `OidcUserInfo` with no claims set:

====
[source,json]
----
assertThat(user.getUserInfo().getClaims()).isEmpty();
----
====

It also includes a `Collection` of authorities with just one authority, `SCOPE_read`:

====
[source,json]
----
assertThat(user.getAuthorities()).hasSize(1);
assertThat(user.getAuthorities()).containsExactly(new SimpleGrantedAuthority("SCOPE_read"));
----
====

Spring Security makes sure that the `OidcUser` instance is available for <<mvc-authentication-principal,the `@AuthenticationPrincipal` annotation>>.

Further, it also links the `OidcUser` to a simple instance of `OAuth2AuthorizedClient` that it deposits into a mock `ServerOAuth2AuthorizedClientRepository`.
This can be handy if your tests <<webflux-testing-oauth2-client,use the `@RegisteredOAuth2AuthorizedClient` annotation>>..

[[webflux-testing-oidc-login-authorities]]
==== Configuring Authorities

In many circumstances, your method is protected by filter or method security and needs your `Authentication` to have certain granted authorities to allow the request.

In those cases, you can supply what granted authorities you need by using the `authorities()` method:

====
[source,java]
----
client
    .mutateWith(mockOidcLogin()
        .authorities(new SimpleGrantedAuthority("SCOPE_message:read"))
    )
    .get().uri("/endpoint").exchange();
----
====

[[webflux-testing-oidc-login-claims]]
==== Configuring Claims

While granted authorities are common across all of Spring Security, we also have claims in the case of OAuth 2.0.

Suppose, for example, that you have a `user_id` claim that indicates the user's ID in your system.
You might access it as follows in a controller:

====
[source,java]
----
@GetMapping("/endpoint")
public Mono<String> foo(@AuthenticationPrincipal OidcUser oidcUser) {
    String userId = oidcUser.getIdToken().getClaim("user_id");
    // ...
}
----
====

In that case, you can specify that claim with the `idToken()` method:

====
[source,java]
----
client
    .mutateWith(mockOidcLogin()
        .idToken(token -> token.claim("user_id", "1234"))
    )
    .get().uri("/endpoint").exchange();
----
====

That works because `OidcUser` collects its claims from `OidcIdToken`.

[[webflux-testing-oidc-login-user]]
==== Additional Configurations

There are additional methods, too, for further configuring the authentication, depending on what data your controller expects:

* `userInfo(OidcUserInfo.Builder)`: Configures the `OidcUserInfo` instance
* `clientRegistration(ClientRegistration)`: Configures the associated `OAuth2AuthorizedClient` with a given `ClientRegistration`
* `oidcUser(OidcUser)`: Configures the complete `OidcUser` instance

That last one is handy if you:
* Have your own implementation of `OidcUser` or
* Need to change the name attribute

For example, suppose that your authorization server sends the principal name in the `user_name` claim instead of the `sub` claim.
In that case, you can configure an `OidcUser` by hand:

====
[source,java]
----
OidcUser oidcUser = new DefaultOidcUser(
        AuthorityUtils.createAuthorityList("SCOPE_message:read"),
        Collections.singletonMap("user_name", "foo_user"),
        "user_name");

client
    .mutateWith(mockOidcLogin().oidcUser(oidcUser))
    .get().uri("/endpoint").exchange();
----
====

[[webflux-testing-oauth2-login]]
=== Testing OAuth 2.0 Login

As with <<webflux-testing-oidc-login,testing OIDC login>>, testing OAuth 2.0 Login presents a similar challenge: mocking a grant flow.
Because of that, Spring Security also has test support for non-OIDC use cases.

Suppose that we have a controller that gets the logged-in user as an `OAuth2User`:

====
[source,java]
----
@GetMapping("/endpoint")
public Mono<String> foo(@AuthenticationPrincipal OAuth2User oauth2User) {
    return Mono.just(oauth2User.getAttribute("sub"));
}
----
====

In that case, we can tell Spring Security to include a default `OAuth2User` by using the `SecurityMockServerConfigurers#oauth2User` method:

====
[source,java]
----
client
    .mutateWith(mockOAuth2Login())
    .get().uri("/endpoint").exchange();
----
====

The preceding example configures the associated `MockServerRequest` with an `OAuth2User` that includes a simple `Map` of attributes and a `Collection` of granted authorities.

Specifically, it includes a `Map` with a key/value pair of `sub`/`user`:

====
[source,json]
----
assertThat((String) user.getAttribute("sub")).isEqualTo("user");
----
====

It also includes a `Collection` of authorities with just one authority, `SCOPE_read`:

====
[source,json]
----
assertThat(user.getAuthorities()).hasSize(1);
assertThat(user.getAuthorities()).containsExactly(new SimpleGrantedAuthority("SCOPE_read"));
----
====

Spring Security does the necessary work to make sure that the `OAuth2User` instance is available for <<mvc-authentication-principal,the `@AuthenticationPrincipal` annotation>>.

Further, it also links that `OAuth2User` to a simple instance of `OAuth2AuthorizedClient` that it deposits in a mock `ServerOAuth2AuthorizedClientRepository`.
This can be handy if your tests <<webflux-testing-oauth2-client,use the `@RegisteredOAuth2AuthorizedClient` annotation>>.

[[webflux-testing-oauth2-login-authorities]]
==== Configuring Authorities

In many circumstances, your method is protected by filter or method security and needs your `Authentication` to have certain granted authorities to allow the request.

In this case, you can supply the granted authorities you need by using the `authorities()` method:

====
[source,java]
----
client
    .mutateWith(mockOAuth2Login()
        .authorities(new SimpleGrantedAuthority("SCOPE_message:read"))
    )
    .get().uri("/endpoint").exchange();
----
====

[[webflux-testing-oauth2-login-claims]]
==== Configuring Claims

While granted authorities are quite common across all of Spring Security, we also have claims in the case of OAuth 2.0.

Suppose, for example, that you have a `user_id` attribute that indicates the user's ID in your system.
You might access it as follows in a controller:

====
[source,java]
----
@GetMapping("/endpoint")
public Mono<String> foo(@AuthenticationPrincipal OAuth2User oauth2User) {
    String userId = oauth2User.getAttribute("user_id");
    // ...
}
----
====

In that case, you can specify that attribute with the `attributes()` method:

====
[source,java]
----
client
    .mutateWith(mockOAuth2Login()
        .attributes(attrs -> attrs.put("user_id", "1234"))
    )
    .get().uri("/endpoint").exchange();
----
====

[[webflux-testing-oauth2-login-user]]
==== Additional Configurations

There are additional methods, too, for further configuring the authentication, depending on what data your controller expects:

* `clientRegistration(ClientRegistration)`: Configures the associated `OAuth2AuthorizedClient` with a given `ClientRegistration`
* `oauth2User(OAuth2User)`: Configures the complete `OAuth2User` instance

That last one is handy if you:
* Have your own implementation of `OAuth2User` or
* Need to change the name attribute

For example, suppose that your authorization server sends the principal name in the `user_name` claim instead of the `sub` claim.
In that case, you can configure an `OAuth2User` by hand:

====
[source,java]
----
OAuth2User oauth2User = new DefaultOAuth2User(
        AuthorityUtils.createAuthorityList("SCOPE_message:read"),
        Collections.singletonMap("user_name", "foo_user"),
        "user_name");

client
    .mutateWith(mockOAuth2Login().oauth2User(oauth2User))
    .get().uri("/endpoint").exchange();
----
====

[[webflux-testing-oauth2-client]]
=== Testing OAuth 2.0 Clients

Independent of how your user authenticates, you may have other tokens and client registrations that are in play for the request you are testing.
For example, your controller may rely on the client credentials grant to get a token that is not associated with the user at all:

====
[source,java]
----
@GetMapping("/endpoint")
public Mono<String> foo(@RegisteredOAuth2AuthorizedClient("my-app") OAuth2AuthorizedClient authorizedClient) {
    return this.webClient.get()
        .attributes(oauth2AuthorizedClient(authorizedClient))
        .retrieve()
        .bodyToMono(String.class);
}
----
====

Simulating this handshake with the authorization server can be cumbersome.
Instead, you can use `SecurityMockServerConfigurers#oauth2Client` to add a `OAuth2AuthorizedClient` to a mock `ServerOAuth2AuthorizedClientRepository`:

====
[source,java]
----
client
    .mutateWith(mockOAuth2Client("my-app"))
    .get().uri("/endpoint").exchange();
----
====

This creates an `OAuth2AuthorizedClient` that has a simple `ClientRegistration`, a `OAuth2AccessToken`, and a resource owner name.

Specifically, it includes a `ClientRegistration` with a client ID of `test-client` and a client secret of `test-secret`:

====
[source,json]
----
assertThat(authorizedClient.getClientRegistration().getClientId()).isEqualTo("test-client");
assertThat(authorizedClient.getClientRegistration().getClientSecret()).isEqualTo("test-secret");
----
====

It also includes a resource owner name of `user`:

====
[source,json]
----
assertThat(authorizedClient.getPrincipalName()).isEqualTo("user");
----
====

It also includes an `OAuth2AccessToken` with one scope, `read`:

====
[source,json]
----
assertThat(authorizedClient.getAccessToken().getScopes()).hasSize(1);
assertThat(authorizedClient.getAccessToken().getScopes()).containsExactly("read");
----
====

You can then retrieve the client as usual by using `@RegisteredOAuth2AuthorizedClient` in a controller method.

[[webflux-testing-oauth2-client-scopes]]
==== Configuring Scopes

In many circumstances, the OAuth 2.0 access token comes with a set of scopes.
Consider the following example of how a controller can inspect the scopes:

====
[source,java]
----
@GetMapping("/endpoint")
public Mono<String> foo(@RegisteredOAuth2AuthorizedClient("my-app") OAuth2AuthorizedClient authorizedClient) {
    Set<String> scopes = authorizedClient.getAccessToken().getScopes();
    if (scopes.contains("message:read")) {
        return this.webClient.get()
            .attributes(oauth2AuthorizedClient(authorizedClient))
            .retrieve()
            .bodyToMono(String.class);
    }
    // ...
}
----
====

Given a controller that inspects scopes, you can configure the scope by using the `accessToken()` method:

====
[source,java]
----
client
    .mutateWith(mockOAuth2Client("my-app")
        .accessToken(new OAuth2AccessToken(BEARER, "token", null, null, Collections.singleton("message:read"))))
    )
    .get().uri("/endpoint").exchange();
----
====

[[webflux-testing-oauth2-client-registration]]
==== Additional Configurations

You can also use additional methods to further configure the authentication depending on what data your controller expects:

* `principalName(String)`; Configures the resource owner name
* `clientRegistration(Consumer<ClientRegistration.Builder>)`: Configures the associated `ClientRegistration`
* `clientRegistration(ClientRegistration)`: Configures the complete `ClientRegistration`

That last one is handy if you want to use a real `ClientRegistration`

For example, suppose that you want to use one of your application's `ClientRegistration` definitions, as specified in your `application.yml`.

In that case, your test can autowire the `ReactiveClientRegistrationRepository` and look up the one your test needs:

====
[source,java]
----
@Autowired
ReactiveClientRegistrationRepository clientRegistrationRepository;

// ...

client
    .mutateWith(mockOAuth2Client()
        .clientRegistration(this.clientRegistrationRepository.findByRegistrationId("facebook"))
    )
    .get().uri("/exchange").exchange();
----
====

[[webflux-testing-jwt]]
=== Testing JWT Authentication

To make an authorized request on a resource server, you need a bearer token.
If your resource server is configured for JWTs, the bearer token needs to be signed and then encoded according to the JWT specification.
All of this can be quite daunting, especially when this is not the focus of your test.

Fortunately, there are a number of simple ways in which you can overcome this difficulty and let your tests focus on authorization and not on representing bearer tokens.
We look at two of them in the next two subsections.

==== `mockJwt() WebTestClientConfigurer`

The first way is with a `WebTestClientConfigurer`.
The simplest of these would look something like this:

====
[source,java]
----
client
    .mutateWith(mockJwt()).get().uri("/endpoint").exchange();
----
====

This example creates a mock `Jwt` and passes it through any authentication APIs so that it is available for your authorization mechanisms to verify.

By default, the `JWT` that it creates has the following characteristics:

====
[source,json]
----
{
  "headers" : { "alg" : "none" },
  "claims" : {
    "sub" : "user",
    "scope" : "read"
  }
}
----
====

The resulting `Jwt`, were it tested, would pass in the following way:

====
[source,java]
----
assertThat(jwt.getTokenValue()).isEqualTo("token");
assertThat(jwt.getHeaders().get("alg")).isEqualTo("none");
assertThat(jwt.getSubject()).isEqualTo("sub");
GrantedAuthority authority = jwt.getAuthorities().iterator().next();
assertThat(authority.getAuthority()).isEqualTo("read");
----
====

Note that you configure these values.

You can also configure any headers or claims with their corresponding methods:

====
[source,java]
----
client
	.mutateWith(mockJwt().jwt(jwt -> jwt.header("kid", "one")
		.claim("iss", "https://idp.example.org")))
	.get().uri("/endpoint").exchange();
----

[source,java]
----
client
	.mutateWith(mockJwt().jwt(jwt -> jwt.claims(claims -> claims.remove("scope"))))
	.get().uri("/endpoint").exchange();
----
====

The `scope` and `scp` claims are processed the same way here as they are in a normal bearer token request.
However, this can be overridden simply by providing the list of `GrantedAuthority` instances that you need for your test:

====
[source,java]
----
client
	.mutateWith(jwt().authorities(new SimpleGrantedAuthority("SCOPE_messages")))
	.get().uri("/endpoint").exchange();
----
====

Alternatively, if you have a custom `Jwt` to `Collection<GrantedAuthority>` converter, you can also use that to derive the authorities:

====
[source,java]
----
client
	.mutateWith(jwt().authorities(new MyConverter()))
	.get().uri("/endpoint").exchange();
----
====

You can also specify a complete `Jwt`, for which `{security-api-url}org/springframework/security/oauth2/jwt/Jwt.Builder.html[Jwt.Builder]` is quite handy:

====
[source,java]
----
Jwt jwt = Jwt.withTokenValue("token")
    .header("alg", "none")
    .claim("sub", "user")
    .claim("scope", "read");

client
	.mutateWith(mockJwt().jwt(jwt))
	.get().uri("/endpoint").exchange();
----
====

==== `authentication()` and `WebTestClientConfigurer`

The second way is by using the `authentication()` `Mutator`.
You can instantiate your own `JwtAuthenticationToken` and provide it in your test:

====
[source,java]
----
Jwt jwt = Jwt.withTokenValue("token")
    .header("alg", "none")
    .claim("sub", "user")
    .build();
Collection<GrantedAuthority> authorities = AuthorityUtils.createAuthorityList("SCOPE_read");
JwtAuthenticationToken token = new JwtAuthenticationToken(jwt, authorities);

client
	.mutateWith(authentication(token))
	.get().uri("/endpoint").exchange();
----
====

Note that, as an alternative to these, you can also mock the `ReactiveJwtDecoder` bean itself with a `@MockBean` annotation.

[[webflux-testing-opaque-token]]
=== Testing Opaque Token Authentication

Similar to <<webflux-testing-jwt,JWTs>>, opaque tokens require an authorization server in order to verify their validity, which can make testing more difficult.
To help with that, Spring Security has test support for opaque tokens.

Suppose you have a controller that retrieves the authentication as a `BearerTokenAuthentication`:

====
[source,java]
----
@GetMapping("/endpoint")
public Mono<String> foo(BearerTokenAuthentication authentication) {
    return Mono.just((String) authentication.getTokenAttributes("sub"));
}
----
====

In that case, you can tell Spring Security to include a default `BearerTokenAuthentication` by using the `SecurityMockServerConfigurers#opaqueToken` method:

====
[source,java]
----
client
    .mutateWith(mockOpaqueToken())
    .get().uri("/endpoint").exchange();
----
====

This example configures the associated `MockHttpServletRequest` with a `BearerTokenAuthentication` that includes a simple `OAuth2AuthenticatedPrincipal`, a `Map` of attributes, and a `Collection` of granted authorities.

Specifically, it includes a `Map` with a key/value pair of `sub`/`user`:

====
[source,json]
----
assertThat((String) token.getTokenAttributes().get("sub")).isEqualTo("user");
----
====

It also includes a `Collection` of authorities with just one authority, `SCOPE_read`:

====
[source,json]
----
assertThat(token.getAuthorities()).hasSize(1);
assertThat(token.getAuthorities()).containsExactly(new SimpleGrantedAuthority("SCOPE_read"));
----
====

Spring Security makes sure that the `BearerTokenAuthentication` instance is available for your controller methods.

[[webflux-testing-opaque-token-authorities]]
==== Configuring Authorities

In many circumstances, your method is protected by filter or method security and needs your `Authentication` to have certain granted authorities to allow the request.

In those cases, you can supply the granted authorities you need by using the `authorities()` method:

====
[source,java]
----
client
    .mutateWith(mockOpaqueToken()
        .authorities(new SimpleGrantedAuthority("SCOPE_message:read"))
    )
    .get().uri("/endpoint").exchange();
----
====

[[webflux-testing-opaque-token-attributes]]
==== Configuring Claims

While granted authorities are quite common across all of Spring Security, we also have attributes in the case of OAuth 2.0.

Suppose, for example, that you have a `user_id` attribute that indicates the user's ID in your system.
You might access it as follows in a controller:

====
[source,java]
----
@GetMapping("/endpoint")
public Mono<String> foo(BearerTokenAuthentication authentication) {
    String userId = (String) authentication.getTokenAttributes().get("user_id");
    // ...
}
----
====

In that case, you can specify that attribute with the `attributes()` method:

====
[source,java]
----
client
    .mutateWith(mockOpaqueToken()
        .attributes(attrs -> attrs.put("user_id", "1234"))
    )
    .get().uri("/endpoint").exchange();
----
====

[[webflux-testing-opaque-token-principal]]
==== Additional Configurations

You can also use additional methods to further configure the authentication, depending on what data your controller expects.

One such method is `principal(OAuth2AuthenticatedPrincipal)`, which you can use to configure the complete `OAuth2AuthenticatedPrincipal` instance that underlies the `BearerTokenAuthentication`.

It is handy if you:
* Have your own implementation of `OAuth2AuthenticatedPrincipal` or
* Want to specify a different principal name

For example, suppose that your authorization server sends the principal name in the `user_name` attribute instead of the `sub` attribute.
In that case, you can configure an `OAuth2AuthenticatedPrincipal` by hand:

====
[source,java]
----
Map<String, Object> attributes = Collections.singletonMap("user_name", "foo_user");
OAuth2AuthenticatedPrincipal principal = new DefaultOAuth2AuthenticatedPrincipal(
        (String) attributes.get("user_name"),
        attributes,
        AuthorityUtils.createAuthorityList("SCOPE_message:read"));

client
    .mutateWith(mockOpaqueToken().principal(principal))
    .get().uri("/endpoint").exchange();
----
====

Note that, as an alternative to using `mockOpaqueToken()` test support, you can also mock the `OpaqueTokenIntrospector` bean itself with a `@MockBean` annotation.
