=  OAuth 2.0登录示例

本指南提供了使用OAuth 2.0提供程序或OpenID Connect 1.0提供程序通过OAuth 2.0登录设置示例应用程序的说明。
示例应用程序使用Spring Boot 2.0.0.M6和Spring Security 5.0中新增的`spring-security-oauth2-client`模块。

以下部分提供了为这些提供商设置OAuth 2.0登录的详细步骤：

* <<google-login, Google>>
* <<github-login, GitHub>>
* <<facebook-login, Facebook>>
* <<okta-login, Okta>>

[[google-login]]
== 使用Google登录

本节介绍如何使用Google作为身份验证提供程序来配置示例应用程序，并涵盖以下主题：

* <<google-initial-setup,Initial setup>>
* <<google-redirect-uri,Setting the redirect URI>>
* <<google-application-config,Configure application.yml>>
* <<google-boot-application,Boot up the application>>

[[google-initial-setup]]
=== 初始设置

要使用Google的OAuth 2.0身份验证系统进行登录，您必须在Google API控制台中设置一个项目以获取OAuth 2.0凭据。

注意：用于身份验证的https://developers.google.com/identity/protocols/OpenIDConnect[Google' OAuth 2.0实现]符合
  http://openid.net/connect/[OpenID Connect 1.0]规范，并且是 http://openid.net/certification/[OpenID认证]。

按照https://developers.google.com/identity/protocols/OpenIDConnect[OpenID Connect]页上的说明操作，从"Setting up OAuth 2.0"部分开始。

完成"Obtain OAuth 2.0 credentials"指示后，您应该拥有一个新的OAuth客户端，其凭据由客户端ID和客户端密钥组成。

[[google-redirect-uri]]
=== 设置重定向URI

重定向URI是应用程序中的路径，终端用户的用户代理在用Google进行身份验证之后将其重定向回
并已授予对Consent页面上的OAuth Client _（在上一步中创建）_的访问权限。

在"Set a redirect URI"小节中，确保*Authorized redirect URIs*字段设置为`http://localhost:8080/login/oauth2/code/google`。

提示：默认重定向URI模板为`{baseUrl}/login/oauth2/code/{registrationId}`。
  *_registrationId_*是`ClientRegistration`的唯一标识符。

[[google-application-config]]
=== 配置application.yml

现在，您已经拥有了一个带有Google的新OAuth客户端，您需要配置该应用程序以使用OAuth客户端作为_authentication flow_。要做到这一点：

. 转到`application.yml`并设置以下配置：
+
[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:	<1>
          google:		<2>
            client-id: google-client-id
            client-secret: google-client-secret
----
+
.OAuth客户端属性
====
<1> `spring.security.oauth2.client.registration`是OAuth客户端属性的基本属性前缀。
<2>基本属性前缀后面是`ClientRegistration`的ID，例如google。
====

. 用您之前创建的OAuth 2.0凭据替换`client-id`和`client-secret`属性中的值。

[[google-boot-application]]
=== 启动应用程序

启动Spring Boot 2.0示例并转至`http://localhost:8080`。
然后，您被重定向到默认的_auto-generated_登录页面，该页面显示Google的链接。

点击Google链接，然后重定向到Google进行身份验证。

在使用Google帐户凭证进行身份验证后，向您呈现的下一页是“同意”屏幕。
“同意”屏幕会要求您允许或拒绝访问之前创建的OAuth客户端。
点击*Allow*，授权OAuth客户端访问您的电子邮件地址和基本配置文件信息。

此时，OAuth客户端将检索您的电子邮件地址和基本配置文件信息
从 http://openid.net/specs/openid-connect-core-1_0.html#UserInfo[UserInfo端点]，并建立一个认证会话。

[[github-login]]
== 使用GitHub登录

本节介绍如何使用GitHub作为身份验证提供程序配置示例应用程序，并涵盖以下主题：

* <<github-register-application,Register OAuth application>>
* <<github-application-config,Configure application.yml>>
* <<github-boot-application,Boot up the application>>

[[github-register-application]]
=== 注册OAuth应用程序

要使用GitHub的OAuth 2.0身份验证系统进行登录，您必须https://github.com/settings/applications/new[注册新的OAuth应用程序]。

注册OAuth应用程序时，请确保*Authorization callback URL*设置为`http://localhost:8080/login/oauth2/code/github`。

授权回调URL（重定向URI）是最终用户的用户代理在使用GitHub进行身份验证后重定向到的应用程序中的路径
并已授予访问_Authorize application_页上的OAuth应用程序的权限。

提示：默认重定向URI模板为`{baseUrl}/login/oauth2/code/{registrationId}`。
  *_registrationId_*是`ClientRegistration`的唯一标识符。

[[github-application-config]]
=== 配置application.yml

现在您已经有了一个带有GitHub的新OAuth应用程序，您需要配置应用程序以使用OAuth应用程序进行_authentication flow_。要做到这一点：

. 转到`application.yml`并设置以下配置：
+
[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:	<1>
          github:		<2>
            client-id: github-client-id
            client-secret: github-client-secret
----
+
.OAuth客户端属性
====
<1> `spring.security.oauth2.client.registration`是OAuth客户端属性的基本属性前缀。
<2>基本属性前缀后面是`ClientRegistration`的ID，例如github。
====

. 用您之前创建的OAuth 2.0凭据替换`client-id`和`client-secret`属性中的值。

[[github-boot-application]]
=== 启动应用程序

启动Spring Boot 2.0示例并转至`http://localhost:8080`。
然后，您将被重定向到默认的_auto-generated_登录页面，该页面显示GitHub的链接。

点击GitHub链接，然后重定向到GitHub进行身份验证。

在使用您的GitHub凭证进行身份验证后，呈现给您的下一页是"Authorize application"。
此页面会要求您在上一步中创建的应用程序*Authorize*。
点击_Authorize application_以允许OAuth应用程序访问您的个人用户数据信息。

此时，OAuth客户端将检索您的个人用户信息
来自UserInfo端点并建立一个认证会话。

[TIP]
有关从UserInfo端点返回的详细信息，请参阅API文档
对于https://developer.github.com/v3/users/#get-the-authenticated-user ["Get the authenticated user"]。

[[facebook-login]]
== 使用Facebook登录

本节介绍如何使用Facebook作为身份验证提供程序配置示例应用程序，并涵盖以下主题：

* <<facebook-register-application,Add a New App>>
* <<facebook-application-config,Configure application.yml>>
* <<facebook-boot-application,Boot up the application>>

[[facebook-register-application]]
=== 添加新的应用程序

要使用Facebook的OAuth 2.0身份验证系统进行登录，您必须先https://developers.facebook.com/apps[Add a New App]。

选择"Create a New App"，然后显示"Create a New App ID"页面。输入显示名称，联系人电子邮件地址，类别，然后点击"Create App ID"。

注：_Category_字段的选择不相关，但它是必填字段 - 选择"Local"。

接下来的页面是"Product Setup"。点击*Facebook Login*产品的"Get Started"按钮。
在左侧边栏的_Products  - > Facebook Login_下，选择_Settings_。

对于字段*Valid OAuth redirect URIs*，输入`http://localhost:8080/login/oauth2/code/facebook`，然后点击_Save Changes_。

OAuth重定向URI是应用程序中的路径，终端用户的用户代理在与Facebook进行身份验证后被重定向回
并已授予访问_Authorize application_页上的应用程序的权限。

提示：默认重定向URI模板为`{baseUrl}/login/oauth2/code/{registrationId}`。
  *_registrationId_*是`ClientRegistration`的唯一标识符。

[[facebook-application-config]]
=== 配置application.yml

现在您已经使用Facebook创建了一个新的应用程序，您需要配置示例应用程序以使用应用程序进行_authentication flow_。要做到这一点：

. 转到`application.yml`并设置以下配置：
+
[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:	<1>
          facebook:		<2>
            client-id: facebook-client-id
            client-secret: facebook-client-secret
----
+
.OAuth客户端属性
====
<1> `spring.security.oauth2.client.registration`是OAuth客户端属性的基本属性前缀。
<2>基本属性前缀后面是`ClientRegistration`的标识，例如facebook。
====

. 用您之前创建的OAuth 2.0凭据替换`client-id`和`client-secret`属性中的值。

[[facebook-boot-application]]
=== 启动应用程序

启动Spring Boot 2.0示例并转至`http://localhost:8080`。
然后，您被重定向到默认的_auto-generated_登录页面，该页面显示Facebook的链接。

点击Facebook链接，然后重定向到Facebook进行身份验证。

使用您的Facebook凭证进行身份验证后，向您展示的下一个页面是"Authorize application"。
此页面会要求您在上一步中创建的应用程序*Authorize*。
点击_Authorize application_允许OAuth应用程序访问您的_public个人资料_和_email地址信息。

此时，OAuth客户端将检索您的个人用户信息
来自UserInfo端点并建立一个认证会话。

[[okta-login]]
== 用Okta登录

本节介绍如何使用Okta作为身份验证提供程序配置示例应用程序，并涵盖以下主题：

* <<okta-register-application,Add Application>>
* <<okta-assign-application-people,Assign Application to People>>
* <<okta-application-config,Configure application.yml>>
* <<okta-boot-application,Boot up the application>>

[[okta-register-application]]
=== 添加应用程序

要使用Okta的OAuth 2.0身份验证系统进行登录，您必须首先https://www.okta.com/developer/signup [创建开发者帐户]。

登录到您的帐户子域并导航到_Applications  - > Applications_，然后选择"Add Application"按钮。
从"Add Application"页面选择"Create New App"按钮并输入以下内容：

*  *Platform:*网络
*  *Sign on method:* OpenID Connect

选择_Create_按钮。
在"General Settings"页面上，输入应用程序名称（例如，"Spring Security Okta Login"），然后选择_Next_按钮。
在"Configure OpenID Connect"页面上，为字段*Redirect URIs*输入`http://localhost:8080/login/oauth2/code/okta`，然后选择_Finish_。

重定向URI是最终用户的用户代理在用Okta进行身份验证后重定向到的应用程序中的路径
并已授予访问_Authorize application_页上的应用程序的权限。

提示：默认重定向URI模板为`{baseUrl}/login/oauth2/code/{registrationId}`。
  *_registrationId_*是`ClientRegistration`的唯一标识符。

[[okta-assign-application-people]]
=== 将应用程序分配给人员

从应用程序的"General"选项卡中，选择"Assignments"选项卡，然后选择_Assign_按钮。
选择_Assign to People_并将您的帐户分配给应用程序。然后选择_Save和Go Back_按钮。

[[okta-application-config]]
=== 配置application.yml

现在您已经使用Okta创建了一个新的应用程序，您需要配置示例应用程序以将该应用程序用于_authentication flow_。要做到这一点：

. 转到`application.yml`并设置以下配置：
+
[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:	<1>
          okta:		<2>
            client-id: okta-client-id
            client-secret: okta-client-secret
        provider:	<3>
          okta:
            authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
            token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys
----
+
.OAuth客户端属性
====
<1> `spring.security.oauth2.client.registration`是OAuth客户端属性的基本属性前缀。
<2>基本属性前缀后面是`ClientRegistration`的ID，例如okta。
<3> `spring.security.oauth2.client.provider`是OAuth提供程序属性的基本属性前缀。
====

. 用您之前创建的OAuth 2.0凭据替换`client-id`和`client-secret`属性中的值。
另外，在注册过程中，将`authorization-uri`，`token-uri`，`user-info-uri`和`jwk-set-uri`中的`https://your-subdomain.oktapreview.com`替换为分配给您帐户的子域。

[[okta-boot-application]]
=== 启动应用程序

启动Spring Boot 2.0示例并转至`http://localhost:8080`。
然后，您将被重定向到默认的_auto-generated_登录页面，该页面显示Okta的链接。

点击Okta链接，然后重定向到Okta进行身份验证。

使用您的Okta帐户凭据进行身份验证后，OAuth客户端将检索您的电子邮件地址和基本配置文件信息
从 http://openid.net/specs/openid-connect-core-1_0.html#UserInfo[UserInfo端点]，并建立一个认证会话。
