= OAuth 2.0 Login Sample

This guide provides instructions on setting up the sample application with OAuth 2.0 Login using an OAuth 2.0 Provider or OpenID Connect 1.0 Provider.
The sample application uses Spring Boot 2.0.0.M6 and the `spring-security-oauth2-client` module which is new in Spring Security 5.0.

The following sections provide detailed steps for setting up OAuth 2.0 Login for these Providers:

* <<google-login, Google>>
* <<github-login, GitHub>>
* <<facebook-login, Facebook>>
* <<okta-login, Okta>>
* <<adfs-login, Microsoft AD FS>>

[[google-login]]
== Login with Google

This section shows how to configure the sample application using Google as the Authentication Provider and covers the following topics:

* <<google-initial-setup,Initial setup>>
* <<google-redirect-uri,Setting the redirect URI>>
* <<google-application-config,Configure application.yml>>
* <<google-boot-application,Boot up the application>>

[[google-initial-setup]]
=== Initial setup

To use Google's OAuth 2.0 authentication system for login, you must set up a project in the Google API Console to obtain OAuth 2.0 credentials.

NOTE: https://developers.google.com/identity/protocols/OpenIDConnect[Google's OAuth 2.0 implementation] for authentication conforms to the
 https://openid.net/connect/[OpenID Connect 1.0] specification and is https://openid.net/certification/[OpenID Certified].

Follow the instructions on the https://developers.google.com/identity/protocols/OpenIDConnect[OpenID Connect] page, starting in the section, "Setting up OAuth 2.0".

After completing the "Obtain OAuth 2.0 credentials" instructions, you should have a new OAuth Client with credentials consisting of a Client ID and a Client Secret.

[[google-redirect-uri]]
=== Setting the redirect URI

The redirect URI is the path in the application that the end-user's user-agent is redirected back to after they have authenticated with Google
and have granted access to the OAuth Client _(created in the previous step)_ on the Consent page.

In the "Set a redirect URI" sub-section, ensure that the *Authorized redirect URIs* field is set to `http://localhost:8080/login/oauth2/code/google`.

TIP: The default redirect URI template is `{baseUrl}/login/oauth2/code/{registrationId}`.
 The *_registrationId_* is a unique identifier for the `ClientRegistration`.

[[google-application-config]]
=== Configure application.yml

Now that you have a new OAuth Client with Google, you need to configure the application to use the OAuth Client for the _authentication flow_. To do so:

. Go to `application.yml` and set the following configuration:
+
[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:	<1>
          google:		<2>
            client-id: google-client-id
            client-secret: google-client-secret
----
+
.OAuth Client properties
====
<1> `spring.security.oauth2.client.registration` is the base property prefix for OAuth Client properties.
<2> Following the base property prefix is the ID for the `ClientRegistration`, such as google.
====

. Replace the values in the `client-id` and `client-secret` property with the OAuth 2.0 credentials you created earlier.

[[google-boot-application]]
=== Boot up the application

Launch the Spring Boot 2.0 sample and go to `http://localhost:8080`.
You are then redirected to the default _auto-generated_ login page, which displays a link for Google.

Click on the Google link, and you are then redirected to Google for authentication.

After authenticating with your Google account credentials, the next page presented to you is the Consent screen.
The Consent screen asks you to either allow or deny access to the OAuth Client you created earlier.
Click *Allow* to authorize the OAuth Client to access your email address and basic profile information.

At this point, the OAuth Client retrieves your email address and basic profile information
from the https://openid.net/specs/openid-connect-core-1_0.html#UserInfo[UserInfo Endpoint] and establishes an authenticated session.

[[github-login]]
== Login with GitHub

This section shows how to configure the sample application using GitHub as the Authentication Provider and covers the following topics:

* <<github-register-application,Register OAuth application>>
* <<github-application-config,Configure application.yml>>
* <<github-boot-application,Boot up the application>>

[[github-register-application]]
=== Register OAuth application

To use GitHub's OAuth 2.0 authentication system for login, you must https://github.com/settings/applications/new[Register a new OAuth application].

When registering the OAuth application, ensure the *Authorization callback URL* is set to `http://localhost:8080/login/oauth2/code/github`.

The Authorization callback URL (redirect URI) is the path in the application that the end-user's user-agent is redirected back to after they have authenticated with GitHub
and have granted access to the OAuth application on the _Authorize application_ page.

TIP: The default redirect URI template is `{baseUrl}/login/oauth2/code/{registrationId}`.
 The *_registrationId_* is a unique identifier for the `ClientRegistration`.

[[github-application-config]]
=== Configure application.yml

Now that you have a new OAuth application with GitHub, you need to configure the application to use the OAuth application for the _authentication flow_. To do so:

. Go to `application.yml` and set the following configuration:
+
[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:	<1>
          github:		<2>
            client-id: github-client-id
            client-secret: github-client-secret
----
+
.OAuth Client properties
====
<1> `spring.security.oauth2.client.registration` is the base property prefix for OAuth Client properties.
<2> Following the base property prefix is the ID for the `ClientRegistration`, such as github.
====

. Replace the values in the `client-id` and `client-secret` property with the OAuth 2.0 credentials you created earlier.

[[github-boot-application]]
=== Boot up the application

Launch the Spring Boot 2.0 sample and go to `http://localhost:8080`.
You are then redirected to the default _auto-generated_ login page, which displays a link for GitHub.

Click on the GitHub link, and you are then redirected to GitHub for authentication.

After authenticating with your GitHub credentials, the next page presented to you is "Authorize application".
This page will ask you to *Authorize* the application you created in the previous step.
Click _Authorize application_ to allow the OAuth application to access your personal user data information.

At this point, the OAuth Client retrieves your personal user information
from the UserInfo Endpoint and establishes an authenticated session.

[TIP]
For detailed information returned from the UserInfo Endpoint, see the API documentation
for https://developer.github.com/v3/users/#get-the-authenticated-user["Get the authenticated user"].

[[facebook-login]]
== Login with Facebook

This section shows how to configure the sample application using Facebook as the Authentication Provider and covers the following topics:

* <<facebook-register-application,Add a New App>>
* <<facebook-application-config,Configure application.yml>>
* <<facebook-boot-application,Boot up the application>>

[[facebook-register-application]]
=== Add a New App

To use Facebook's OAuth 2.0 authentication system for login, you must first https://developers.facebook.com/apps[Add a New App].

Select "Create a New App" and then the "Create a New App ID" page is presented. Enter the Display Name, Contact Email, Category and then click "Create App ID".

NOTE: The selection for the _Category_ field is not relevant but it's a required field - select "Local".

The next page presented is "Product Setup". Click the "Get Started" button for the *Facebook Login* product.
In the left sidebar, under _Products -> Facebook Login_, select _Settings_.

For the field *Valid OAuth redirect URIs*, enter `http://localhost:8080/login/oauth2/code/facebook` then click _Save Changes_.

The OAuth redirect URI is the path in the application that the end-user's user-agent is redirected back to after they have authenticated with Facebook
and have granted access to the application on the _Authorize application_ page.

TIP: The default redirect URI template is `{baseUrl}/login/oauth2/code/{registrationId}`.
 The *_registrationId_* is a unique identifier for the `ClientRegistration`.

[[facebook-application-config]]
=== Configure application.yml

Now that you have created a new application with Facebook, you need to configure the sample application to use the application for the _authentication flow_. To do so:

. Go to `application.yml` and set the following configuration:
+
[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:	<1>
          facebook:		<2>
            client-id: facebook-client-id
            client-secret: facebook-client-secret
----
+
.OAuth Client properties
====
<1> `spring.security.oauth2.client.registration` is the base property prefix for OAuth Client properties.
<2> Following the base property prefix is the ID for the `ClientRegistration`, such as facebook.
====

. Replace the values in the `client-id` and `client-secret` property with the OAuth 2.0 credentials you created earlier.

[[facebook-boot-application]]
=== Boot up the application

Launch the Spring Boot 2.0 sample and go to `http://localhost:8080`.
You are then redirected to the default _auto-generated_ login page, which displays a link for Facebook.

Click on the Facebook link, and you are then redirected to Facebook for authentication.

After authenticating with your Facebook credentials, the next page presented to you is "Authorize application".
This page will ask you to *Authorize* the application you created in the previous step.
Click _Authorize application_ to allow the OAuth application to access your _public profile_ and _email address_ information.

At this point, the OAuth Client retrieves your personal user information
from the UserInfo Endpoint and establishes an authenticated session.

[[okta-login]]
== Login with Okta

This section shows how to configure the sample application using Okta as the Authentication Provider and covers the following topics:

* <<okta-register-application,Add Application>>
* <<okta-assign-application-people,Assign Application to People>>
* <<okta-application-config,Configure application.yml>>
* <<okta-boot-application,Boot up the application>>

[[okta-register-application]]
=== Add Application

To use Okta's OAuth 2.0 authentication system for login, you must first https://www.okta.com/developer/signup[create a developer account].

Sign in to your account sub-domain and navigate to _Applications -> Applications_ and then select the "Add Application" button.
From the "Add Application" page, select the "Create New App" button and enter the following:

* *Platform:* Web
* *Sign on method:* OpenID Connect

Select the _Create_ button.
On the "General Settings" page, enter the Application Name (for example, "Spring Security Okta Login") and then select the _Next_ button.
On the "Configure OpenID Connect" page, enter `http://localhost:8080/login/oauth2/code/okta` for the field *Redirect URIs* and then select _Finish_.

The redirect URI is the path in the application that the end-user's user-agent is redirected back to after they have authenticated with Okta
and have granted access to the application on the _Authorize application_ page.

TIP: The default redirect URI template is `{baseUrl}/login/oauth2/code/{registrationId}`.
 The *_registrationId_* is a unique identifier for the `ClientRegistration`.

[[okta-assign-application-people]]
=== Assign Application to People

From the "General" tab of the application, select the "Assignments" tab and then select the _Assign_ button.
Select _Assign to People_ and assign your account to the application. Then select the _Save and Go Back_ button.

[[okta-application-config]]
=== Configure application.yml

Now that you have created a new application with Okta, you need to configure the sample application to use the application for the _authentication flow_. To do so:

. Go to `application.yml` and set the following configuration:
+
[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:	<1>
          okta:		<2>
            client-id: okta-client-id
            client-secret: okta-client-secret
        provider:	<3>
          okta:
            authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
            token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys
----
+
.OAuth Client properties
====
<1> `spring.security.oauth2.client.registration` is the base property prefix for OAuth Client properties.
<2> Following the base property prefix is the ID for the `ClientRegistration`, such as okta.
<3> `spring.security.oauth2.client.provider` is the base property prefix for OAuth Provider properties.
====

. Replace the values in the `client-id` and `client-secret` property with the OAuth 2.0 credentials you created earlier.
As well, replace `https://your-subdomain.oktapreview.com` in `authorization-uri`, `token-uri`, `user-info-uri` and `jwk-set-uri` with the sub-domain assigned to your account during the registration process.

[[okta-boot-application]]
=== Boot up the application

Launch the Spring Boot 2.0 sample and go to `http://localhost:8080`.
You are then redirected to the default _auto-generated_ login page, which displays a link for Okta.

Click on the Okta link, and you are then redirected to Okta for authentication.

After authenticating with your Okta account credentials, the OAuth Client retrieves your email address and basic profile information
from the https://openid.net/specs/openid-connect-core-1_0.html#UserInfo[UserInfo Endpoint] and establishes an authenticated session.

[[adfs-login]]
== Login with Microsoft AD FS

This section shows how to configure the sample application using Microsoft AD FS 4.0 (and above) as the Authentication Provider and covers the following topics:

* <<adfs-add-application,Add Application Group>>
* <<adfs-application-config,Configure application.yml>>
* <<adfs-boot-application,Boot up the application>>

[[adfs-add-application]]
=== Add Application Group

To use Microsoft AD FS authentication system for login, you must add an Application Group in AD FS Management console.

The following steps describe how to configure the application group in AD FS:
. In AD FS Management, right-click on Application Groups and select Add Application Group. 
. On the Application Group Wizard, for the name enter ADFSSSO and under Client-Server applications select Web browser accessing a web application template. Click Next.
. Copy the Client Identifier value. It will be used later as the value for `client-id` property in the application properties file. 
. Enter the following for Redirect URI: - `http://localhost:8080/login/oauth2/code/adfs`. Click Add. Click Next. 
. On the Apply Access Control Policy screen, click Next.
. On the Summary screen, click Next.
. On the Complete screen, click Close.

The Redirect URI is the path in the application that the end-user's user-agent is redirected back to after they have authenticated with Microsoft AD FS and have granted access to the OAuth application on the _Authorize application_ page.

TIP: The default redirect URI template is `{baseUrl}/login/oauth2/code/{registrationId}`.
 The *_registrationId_* is a unique identifier for the `ClientRegistration`.

[[adfs-application-config]]
=== Configure application.yml

Now that you have created a new application group with Microsof AD FS, you need to configure the sample application to use the application for the _authentication flow_. To do so:

. Go to `application.yml` and set the following configuration:
+
[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:	<1>
          adfs:		<2>
            client-id: your-app-client-id
            scope: openid
            redirect-uri: your-base-url/login/oauth2/code/adfs
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:	<3>
          adfs:
            authorization-uri: https://your-adfs-domain/adfs/oauth2/authorize
            token-uri: https://your-adfs-domain/adfs/oauth2/token
            user-info-authentication-method: query
            jwk-set-uri: https://your-adfs-domain/adfs/discovery/keys
            user-name-attribute: upn
----
+
.OAuth Client properties
====
<1> `spring.security.oauth2.client.registration` is the base property prefix for OAuth Client properties.
<2> Following the base property prefix is the ID for the `ClientRegistration`, such as adfs.
<3> `spring.security.oauth2.client.provider` is the base property prefix for OAuth Provider properties.
====

. Replace the values in the `client-id` property with the OAuth 2.0 credentials you created earlier.
Replace `redirect-uri` with your sample application base url, for example `http://localhost:8080/login/oauth2/code/adfs`.
As well, replace `your-adfs-domain` in `authorization-uri`, `token-uri` and `jwk-set-uri` with the domain assigned to your Microsoft AD FS deployment.

TIP: `client-secret` is not required if setting up an Application Group with a Web application template as shown in <<adfs-add-application,Add Application Group>>. `client-secret` is only required when setting up an Application Group with a Server application template for which you can generate a shared secret during the Application Group Wizard.

[[adfs-boot-application]]
=== Boot up the application

Launch the Spring Boot 2.0 sample and go to `http://localhost:8080`.
You are then redirected to the default _auto-generated_ login page, which displays a link for ADFS.

Click on the ADFS link, and you are then redirected to Microsoft AD FS for authentication.

After authenticating with your Active Directory account credentials, the OAuth Client retrieves your profile information (such as the UPN from Active Directory) and establishes an authenticated session.

