[[core-services-password-encoding]]
= 密码编码

Spring Security的`PasswordEncoder`界面用于执行密码的单向转换，以便安全地存储密码。
鉴于`PasswordEncoder`是单向转换，当密码转换需要两种方式（即存储用于向数据库进行身份验证的凭据）时，它并不适用。
通常`PasswordEncoder`用于存储需要在验证时与用户提供的密码进行比较的密码。

[[pe-history]]
== 密码历史记录

多年来，用于存储密码的标准机制已经发展。
开始时密码以纯文本形式存储。
密码被认为是安全的，因为数据存储密码被保存在所需的凭据中以便访问它。
但是，恶意用户能够通过SQL注入等攻击方式找到获取大量"data dumps"用户名和密码的方法。
随着越来越多的用户凭据成为公安专家意识到我们需要做更多的事情来保护用户的密码。

然后鼓励开发人员在通过单向散列（如SHA-256）运行密码后存储密码。
当用户尝试认证时，散列密码将与他们键入的密码的散列进行比较。
这意味着系统只需要存储密码的单向散列。
如果发生了违规，那么只有密码的单向散列被暴露。
由于哈希是一种方法，并且在计算上很难猜测给定散列的密码，所以在系统中找出每个密码是不值得的。
为了击败这个新系统，恶意用户决定创建名为https://en.wikipedia.org/wiki/Rainbow_table [Rainbow Tables]的查找表。
他们不是每次都在猜测每个密码，而是一次计算密码并将其存储在查找表中。

为了降低彩虹表的有效性，鼓励开发者使用咸味密码。
而不是仅使用密码作为散列函数的输入，将为每个用户的密码生成随机字节（称为salt）。
盐和用户的密码将通过产生唯一散列的散列函数运行。
盐将以明文形式与用户密码一起存储。
然后当用户尝试认证时，散列密码将与存储的盐的哈希以及他们输入的密码进行比较。
独特的盐意味着Rainbow Tables不再有效，因为每种盐和密码组合的散列值都不相同。

在现代，我们意识到密码哈希（如SHA-256）不再安全。
原因是，使用现代硬件，我们可以每秒执行数十亿次哈希计算。
这意味着我们可以轻松破解每个密码。

现在鼓励开发人员利用自适应单向函数来存储密码。
使用自适应单向函数对密码进行验证是有意识的资源（即CPU，内存等）密集型。
自适应单向函数允许配置随着硬件变得越来越好的"work factor"。
建议"work factor"调整大约1秒钟以验证系统上的密码。
这种权衡是为了让攻击者难以破解密码，但并不那么昂贵，它会给你自己的系统带来过大的负担。
Spring Security试图为"work factor"提供良好的起点，但鼓励用户为自己的系统自定义"work factor"，因为不同系统的性能会有很大差异。
应该使用的自适应单向函数的例子包括
https://en.wikipedia.org/wiki/Bcrypt[bcrypt]
https://en.wikipedia.org/wiki/PBKDF2[PBKDF2]
https://en.wikipedia.org/wiki/Scrypt[scrypt]
和https://en.wikipedia.org/wiki/Argon2[Argon2]。

由于自适应单向函数是故意耗费资源的，因此验证每个请求的用户名和密码将显着降低应用程序的性能。
Spring Security（或任何其他库）没有什么能够加速验证密码，因为通过使验证资源密集而获得安全性。
鼓励用户交换短期凭证（即会话，OAuth令牌等）的长期凭证（即用户名和密码）。
短期凭证可以快速验证而不会有任何安全性损失。


[[pe-dpe]]
==  DelegatingPasswordEncoder

在Spring Security 5.0之前，默认的`PasswordEncoder`是`NoOpPasswordEncoder`，它需要纯文本密码。
根据{{​​0}}部分，您可能预计现在默认的`PasswordEncoder`与`BCryptPasswordEncoder`类似。
但是，这忽略了三个现实世界的问题：

- 许多使用旧密码编码的应用程序无法轻松迁移
- 密码存储的最佳做法将再次发生变化。
- 作为一个框架，Spring Security不能经常发生重大更改

相反，Spring Security引入了`DelegatingPasswordEncoder`，它解决了所有的问题：

- 确保使用当前密码存储建议对密码进行编码
- 允许以现代和传统格式验证密码
- 允许将来升级编码

您可以使用`PasswordEncoderFactories`轻松构建`DelegatingPasswordEncoder`的实例。

[source,java]
----
PasswordEncoder passwordEncoder =
    PasswordEncoderFactories.createDelegatingPasswordEncoder();
----

或者，您可以创建自己的自定义实例。例如：

[source,java]
----
String idForEncode = "bcrypt";
Map encoders = new HashMap<>();
encoders.put(idForEncode, new BCryptPasswordEncoder());
encoders.put("noop", NoOpPasswordEncoder.getInstance());
encoders.put("pbkdf2", new Pbkdf2PasswordEncoder());
encoders.put("scrypt", new SCryptPasswordEncoder());
encoders.put("sha256", new StandardPasswordEncoder());

PasswordEncoder passwordEncoder =
    new DelegatingPasswordEncoder(idForEncode, encoders);
----

[[pe-dpe-format]]
=== 密码存储格式

密码的一般格式是：

[source,text]
----
{id}encodedPassword
----

这样`id`是一个标识符，用于查找应该使用哪一个`PasswordEncoder`，`encodedPassword`是所选`PasswordEncoder`的原始编码密码。
`id`必须位于密码的开头，以`{`开头并以`}`结尾。
如果无法找到`id`，则`id`将为空。
例如，以下可能是使用不同`id`编码的密码列表。
所有原始密码均为"password"。


[source,text]
----
{bcrypt}$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG // <1>
{noop}password // <2>
{pbkdf2}5d923b44a6d129f3ddf3e3c8d29412723dcbde72445e8ef6bf3b508fbf17fa4ed4d6b99ca763d8dc // <3>
{scrypt}$e0801$8bWJaSu2IKSn9Z9kM+TPXfOc/9bdYSrN1oD9qfVThWEwdRTnO7re7Ei+fUZRJ68k9lTyuTeUp4of4g24hHnazw==$OAOec05+bXxvuu/1qZ6NUR+xQYvYv7BeL1QxwRpY5Pc=  // <4>
{sha256}97cde38028ad898ebc02e690819fa220e88c62e0699403e94fff291cfffaf8410849f27605abcbc0 // <5>
----

<1>第一个密码的`PasswordEncoder`标识为`bcrypt`，编码密码为`$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG`。
匹配时，它将委托给`BCryptPasswordEncoder`
<2>第二个密码的`PasswordEncoder` ID为`noop`，并且编码密码为`password`。
匹配时，它将委托给`NoOpPasswordEncoder`
<3>第三个密码的`PasswordEncoder`标识为`pbkdf2`，编码密码为`5d923b44a6d129f3ddf3e3c8d29412723dcbde72445e8ef6bf3b508fbf17fa4ed4d6b99ca763d8dc`。
匹配时，它将委托给`Pbkdf2PasswordEncoder`
<4>第四个密码的`PasswordEncoder`编号为`scrypt`，编码密码为`$e0801$8bWJaSu2IKSn9Z9kM+TPXfOc/9bdYSrN1oD9qfVThWEwdRTnO7re7Ei+fUZRJ68k9lTyuTeUp4of4g24hHnazw==$OAOec05+bXxvuu/1qZ6NUR+xQYvYv7BeL1QxwRpY5Pc=`
匹配时，它将委托给`SCryptPasswordEncoder`
<5>最终密码的`PasswordEncoder` ID为`sha256`，encodedPassword为`97cde38028ad898ebc02e690819fa220e88c62e0699403e94fff291cfffaf8410849f27605abcbc0`。
匹配时，它将委托给`StandardPasswordEncoder`

[NOTE]
====
一些用户可能会担心存储格式是为潜在的黑客提供的。
这不是一个问题，因为密码的存储不依赖于算法是一个秘密。
此外，大多数格式都很容易让攻击者找出没有前缀的地方。
例如，BCrypt密码通常以`$2a$`开头。
====

=== 密码编码

传递给构造函数的`idForEncode`将决定使用哪一个`PasswordEncoder`来对密码进行编码。
在我们上面构建的`DelegatingPasswordEncoder`中，这意味着编码`password`的结果将委派给`BCryptPasswordEncoder`并以`{bcrypt}`为前缀。
最终结果如下所示：

[source,text]
----
{bcrypt}$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG
----

=== 密码匹配

匹配是基于`{id}`以及构造函数中提供的`id`到`PasswordEncoder`的映射完成的。
我们在<<Password Storage Format>>中的示例提供了一个如何完成的示例。
默认情况下，使用密码和未映射的`id`调用`matches(CharSequence, String)`的结果（包括空id）将导致`IllegalArgumentException`。
这种行为可以使用`DelegatingPasswordEncoder.setDefaultPasswordEncoderForMatches(PasswordEncoder)`进行自定义。

通过使用`id`，我们可以匹配任何密码编码，但使用最现代的密码编码对密码进行编码。
这很重要，因为与加密不同，密码哈希的设计使得没有简单的方法来恢复明文。
由于无法恢复明文，因此难以迁移密码。
尽管用户迁移`NoOpPasswordEncoder`非常简单，但我们默认选择将其包含在内以简化入门体验。

=== 入门体验

如果您正在制作演示或样本，花时间散列用户的密码会有点麻烦。
有便利的机制可以使这更容易，但这仍然不适用于生产。

[source,java]
----
User user = User.withDefaultPasswordEncoder()
  .username("user")
  .password("password")
  .roles("user")
  .build();
System.out.println(user.getPassword());
// {bcrypt}$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG
----

如果您正在创建多个用户，则还可以重新使用该构建器。

[source,java]
----
UserBuilder users = User.withDefaultPasswordEncoder();
User user = users
  .username("user")
  .password("password")
  .roles("USER")
  .build();
User admin = users
  .username("admin")
  .password("password")
  .roles("USER","ADMIN")
  .build();
----

这确实散列了存储的密码，但密码仍在内存和编译后的源代码中公开。
因此，对于生产环境来说，它仍然不被认为是安全的。
对于生产，你应该在外部散列你的密码。

=== 故障处理

如{0}}中所述，存储的其中一个密码没有标识时会发生以下错误。

----
java.lang.IllegalArgumentException: There is no PasswordEncoder mapped for the id "null"
	at org.springframework.security.crypto.password.DelegatingPasswordEncoder$UnmappedIdPasswordEncoder.matches(DelegatingPasswordEncoder.java:233)
	at org.springframework.security.crypto.password.DelegatingPasswordEncoder.matches(DelegatingPasswordEncoder.java:196)
----

解决错误的最简单方法是切换为明确提供密码编码的`PasswordEncoder`。
解决问题的最简单方法是确定您的密码当前如何存储，并明确提供正确的`PasswordEncoder`。
如果您正在从Spring Security 4.2.x迁移，您可以通过公开`NoOpPasswordEncoder` bean来恢复到以前的行为。
例如，如果您正在使用Java配置，则可以创建如下所示的配置：

[WARNING]
====
恢复到`NoOpPasswordEncoder`不被认为是安全的。
您应该转而使用`DelegatingPasswordEncoder`来支持安全的密码编码。
====

[source,java]
----
@Bean
public static NoOpPasswordEncoder passwordEncoder() {
    return NoOpPasswordEncoder.getInstance();
}
----

如果您使用的是XML配置，则可以公开一个ID为`passwordEncoder`的{​​{0}}：

[source,xml]
----
<b:bean id="passwordEncoder"
        class="org.springframework.security.crypto.password.NoOpPasswordEncoder" factory-method="getInstance"/>
----

或者，您可以使用正确的ID为所有密码加上前缀，并继续使用`DelegatingPasswordEncoder`。
例如，如果您使用的是BCrypt，则可以将密码从以下类似的位置迁移：

----
$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG
----

至

----
{bcrypt}$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG
----

有关映射的完整列表，请参阅Javadoc
https://docs.spring.io/spring-security/site/docs/5.0.x/api/org/springframework/security/crypto/factory/PasswordEncoderFactories.html[PasswordEncoderFactories。

[[pe-bcpe]]
==  BCryptPasswordEncoder

`BCryptPasswordEncoder`实施使用广泛支持的https://en.wikipedia.org/wiki/Bcrypt[bcrypt]算法对密码进行哈希处理。
为了使它对密码破解更具抵抗性，bcrypt故意缓慢。
与其他自适应单向函数一样，应该调整大约1秒以验证系统上的密码。

[source,java]
----
// Create an encoder with strength 16
BCryptPasswordEncoder encoder = new BCryptPasswordEncoder(16);
String result = encoder.encode("myPassword");
assertTrue(encoder.matches("myPassword", result));
----

[[pe-pbkdf2pe]]
==  Pbkdf2PasswordEncoder

`Pbkdf2PasswordEncoder`实施使用https://en.wikipedia.org/wiki/PBKDF2[PBKDF2]算法对密码进行哈希处理。
为了破解密码破解PBKDF2是一个故意缓慢的算法。
与其他自适应单向函数一样，应该调整大约1秒以验证系统上的密码。
当需要FIPS认证时，此算法是一个不错的选择。

[source,java]
----
// Create an encoder with all the defaults
Pbkdf2PasswordEncoder encoder = new Pbkdf2PasswordEncoder();
String result = encoder.encode("myPassword");
assertTrue(encoder.matches("myPassword", result));
----

[[pe-scpe]]
==  SCryptPasswordEncoder

`SCryptPasswordEncoder`实施使用https://en.wikipedia.org/wiki/Scrypt[scrypt]算法对密码进行哈希处理。
为了击败定制硬件上的密码破解scrypt是一个故意缓慢的算法，需要大量的内存。
与其他自适应单向函数一样，应该调整大约1秒以验证系统上的密码。

[source,java]
----
// Create an encoder with all the defaults
SCryptPasswordEncoder encoder = new SCryptPasswordEncoder();
String result = encoder.encode("myPassword");
assertTrue(encoder.matches("myPassword", result));
----

其他PasswordEncoders。== 

有大量其他`PasswordEncoder`实现完全为了向后兼容而存在。
他们都被弃用，表明他们不再被认为是安全的。
但是，由于难以迁移现有的遗留系统，因此没有计划将其删除。
