/*
 * Copyright 2004-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.security.crypto.password;

/**
 * A {@link PasswordEncoder} that appends a server-side pepper to the raw password before
 * delegating to another {@link PasswordEncoder}.
 *
 * <p>
 * A pepper is a shared secret that should be stored separately from the encoded password,
 * for example in an environment variable or secret manager. It is not included in the
 * encoded password and must be available when matching passwords.
 * </p>
 *
 * <p>
 * This encoder does not replace the per-password salt generated by the delegate. It adds
 * a second secret input before the delegate performs its own password encoding.
 * </p>
 *
 * <pre>
 * PasswordEncoder delegate = PasswordEncoderFactories.createDelegatingPasswordEncoder();
 * PasswordEncoder passwordEncoder = new PepperPasswordEncoder(delegate, pepper);
 * </pre>
 *
 * @author KoreaNirsa
 * @since 7.1
 */
public final class PepperPasswordEncoder extends AbstractValidatingPasswordEncoder {

	private final PasswordEncoder passwordEncoder;

	private final String pepper;

	/**
	 * Creates a new instance.
	 * @param passwordEncoder the {@link PasswordEncoder} to delegate to
	 * @param pepper the server-side secret to combine with the raw password
	 */
	public PepperPasswordEncoder(PasswordEncoder passwordEncoder, CharSequence pepper) {
		if (passwordEncoder == null) {
			throw new IllegalArgumentException("passwordEncoder cannot be null");
		}
		if (pepper == null) {
			throw new IllegalArgumentException("pepper cannot be null");
		}
		if (pepper.length() == 0) {
			throw new IllegalArgumentException("pepper cannot be empty");
		}
		this.passwordEncoder = passwordEncoder;
		this.pepper = pepper.toString();
	}

	@Override
	protected String encodeNonNullPassword(String rawPassword) {
		return this.passwordEncoder.encode(appendPepper(rawPassword));
	}

	@Override
	protected boolean matchesNonNull(String rawPassword, String encodedPassword) {
		return this.passwordEncoder.matches(appendPepper(rawPassword), encodedPassword);
	}

	@Override
	protected boolean upgradeEncodingNonNull(String encodedPassword) {
		return this.passwordEncoder.upgradeEncoding(encodedPassword);
	}

	private String appendPepper(String rawPassword) {
		return rawPassword + this.pepper;
	}

}
