name: Merge Dependabot PR

on:
  pull_request:
    branches:
      - main
      - 'docs-build'

run-name: Merge Dependabot PR ${{ github.ref_name }}

jobs:
  merge-dependabot-pr:
    permissions: write-all
    uses: spring-io/spring-github-workflows/.github/workflows/spring-merge-dependabot-pr.yml@359a3523a5a5d5cabbae1eb4f05aa099adf15f20
    with:
      mergeArguments: --auto --rebase
