name: Merge Dependabot PR

on:
  pull_request:
    branches:
      - main
      - 'docs-build'

run-name: Merge Dependabot PR ${{ github.ref_name }}

jobs:
  merge-dependabot-pr:
    permissions: write-all
    uses: spring-io/spring-github-workflows/.github/workflows/spring-merge-dependabot-pr.yml@0c09eb4023e17dd6ca395a0f4e406a4f7506a58d
    with:
      mergeArguments: --auto --rebase
