name: Release Announcements - Stage

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      version:
        description: The version to stage
        required: true
        type: string

permissions:
  contents: read

jobs:
  stage-release-announcements:
    name: Stage Release Announcements
    if: ${{ !github.event.repository.fork }}
    uses: spring-io/spring-security-release-tools/.github/workflows/release-announcements-stage.yml@33d8b6e0a246353d4b659d7676173436a302ab2b # v1.0.18
    with:
      version: ${{ inputs.version || github.ref_name }}
    secrets: inherit
