name: Release Announcements - Stage

on:
  push:
    tags: '**'
  workflow_dispatch:
    inputs:
      version:
        description: The version to stage
        required: true
        type: string

permissions:
  actions: write
  contents: write
  issues: read

jobs:
  stage-release-announcements:
    name: Stage Release Announcements
    uses: spring-io/spring-security-release-tools/.github/workflows/release-announcements-stage.yml@dada80d7c2689772a3d45b36dd491e244ea34c49 # 1.0.x
    with:
      version: ${{ inputs.version || github.ref_name }}
    secrets: inherit
